### ISSUE TITLE
Custom LifoQueue

### ISSUE THREAD

**Issue by Kronuz** [urllib3/urllib3#1087]
During some profiling, I found out one slow operation is `self.pool.get()` in `_get_conn()`.

In urllib3, in `connectionpool.ConnectionPool`, it uses `LifoQueue`:
https://github.com/shazow/urllib3/blob/master/urllib3/connectionpool.py#L65

Which uses a list instead of a much faster deque:
https://github.com/python/cpython/blob/master/Lib/queue.py#L237

My suggestion is one could use a custom LifoQueue that uses the underlying deque, as:
```python
class LifoQueue(Queue):
    def _get(self):
        return self.queue.pop()
```

**Comment by Lukasa** [comment]
Can you provide a benchmark of the two implementations side-by-side to demonstrate the performance difference, please?

**Comment by Lukasa** [comment]
As a further suggestion, there doesn't seem to be any reason the standard library can't use a deque instead of a list. I suggest if there is a performance advantage in this change that you propose the change upstream as well.

**Comment by friscoMad** [comment]
I came across this issue today, and looking around found this benchmark and it seems there are real gains in the switch https://stackoverflow.com/a/20330499/454332

**Comment by nikan1996** [comment]
Hello, I think there is no need to change LifoQueue backend to `deque`.
```

import queue
import time

class LifoQueue(queue.Queue):

    def _qsize(self, len=len):
        return len(self.queue)

    def _put(self, item):
        self.queue.append(item)

    def _get(self):
        return self.queue.pop()
    
size = 500000

start = time.time()
deque_lifo_queue = LifoQueue(size)
for i in range(size):
    deque_lifo_queue.put(i)
for i in range(size):
    deque_lifo_queue.get(i)

print('deque backend cost time: {}'.format(time.time()-start))

start = time.time()
deque_lifo_queue = queue.LifoQueue(size)
for i in range(size):
    deque_lifo_queue.put(i)
for i in range(size):
    deque_lifo_queue.get(i)

print('list backend cost time: {}'.format(time.time() - start))
```
Here is output in my machine:
```
deque backend cost time: 3.1439239978790283
list backend cost time: 3.0481159687042236
```
I use python 3.6.5 and macOS 10.12.6, there is no obvious difference between deque or list backend in `append` and `pop` operation.
`deque` is efficient in appending element to left or popping element from left.
From [https://docs.python.org/2/library/collections.html#collections.deque](https://docs.python.org/2/library/collections.html#collections.deque)
`Though list objects support similar operations, they are optimized for fast fixed-length operations and incur O(n) memory movement costs for pop(0) and insert(0, v) operations which change both the size and position of the underlying data representation.`

@friscoMad , the benchmark gains mostly from `threading.Lock`, I also write an answer in that question several months ago.
