### ISSUE TITLE
Improve support for path-only URLs.

### ISSUE THREAD

**Issue by Lukasa** [urllib3/urllib3#1096]
Encountered while doing a substantial backend rewrite for v2.

Currently, `parse_url` doesn't do well with non-urlencoded URLs that are intended to have no host portion, as frequently used by HTTP Location headers:

```python
>>> from urllib3.util.url import parse_url
>>> parse_url('/redirect?target=http://localhost:61020/')
Url(scheme='/redirect?target=http', auth=None, host='localhost', port=61020, path='/', query=None, fragment=None)
```

As you can see here, the `://` in the URL confuses urllib3's URL handling logic, which means it ends up incorrectly assuming that the scheme is `/redirect?target=http`. This is causing problems in the v2 backend, which uses `parse_url` to attempt to isolate out the request URL to put into the HTTP/1.1 request.

Frustratingly, urlparse gets this right:

```python
>>> from urllib.parse import urlparse
>>> urlparse('/redirect?target=http://localhost:61020/')
ParseResult(scheme='', netloc='', path='/redirect', params='', query='target=http://localhost:61020/', fragment='')
```
It would be good if `parse_url` could spot a URL that is path-only and handle it sensibly.

This is part of a larger problem, which is that `parse_url` and the `Url` class cannot be used to incrementally build up a URL target. This is required to emulate browser logic for redirects if that's a thing that we want to do: it needs to be possible to handle all URLs that could be returned in Location headers, including absolute, scheme-relative, absolute-path, and path-relative, but right now urllib3 can't really do that.

The larger issue doesn't block v2, but this does. It's probably something that @sigmavirus24 could give guidance on if someone wants to pick it up.

**Comment by sigmavirus24** [comment]
The reason urlparse handles this correctly is also the reason why `rfc3986` gets it right:

```
>>> import rfc3986
>>> rfc3986.urlparse('/redirect?target=http://localhost:61020/')
ParseResult(scheme=None, userinfo=None, host=None, port=None, path=u'/redirect', query=u'target=http://localhost:61020/', fragment=None)
```

Our API is just slightly incompatible with the way `parse_url` in urllib3 already works. If we're comfortable breaking that for v2, we can just switch over to a more robust implementation. We still need support for a few things that `parse_url` has grown support for but those should be pretty easy and there are (I think) branches for that work on the repo.

**Comment by Lukasa** [comment]
I certainly have no problem with swapping to a more robust implementation. If you're open to making a patch against the v2 branch that swaps that in, that'd be really cool.
