### ISSUE TITLE
Tests leak FDs which leads to test failures on machines with low ulimits.

### ISSUE THREAD

**Issue by SethMichaelLarson** [urllib3/urllib3#1100]
As was discussed a lot in #1098 many tests open sockets and don't provide a proper clean-up which results in many leaking FDs during a test execution. This leads to problems on machines with low soft ulimits such as Mac OS.

I'll be making an effort to change these tests to not leak FDs such as unclosed connections, pools, etc.

**Comment by alexwlchan** [comment]
One observation from my testing: I’ve seen some FDs that leak intermittently. This can make it harder to tell if a patch succeeded in cleaning it up, or that was just a lucky run.

**Comment by SethMichaelLarson** [comment]
I think this issue is mostly finished. Closing for now. Thanks @alexwlchan!
