### ISSUE TITLE
ImportError during install of urllib3[secure] on Jython

### ISSUE THREAD

**Issue by baztian** [urllib3/urllib3#1133]
I'm getting a ImportError during `pip install urllib3[secure]` with Jython 2.7.0.

    Downloading/unpacking urllib3[secure] Running setup.py egg_info
      for package urllib3
        
        warning: no previously-included files matching '*' found under
      directory 'docs/_build' Installing extra requirements: 'secure'
      Downloading/unpacking pyOpenSSL>=0.14 (from urllib3[secure])
      Running setup.py egg_info for package pyOpenSSL
        
        warning: no previously-included files found matching
        'leakcheck' warning: no previously-included files matching
        '*.py' found under directory 'leakcheck' warning: no
        previously-included files matching '*.pem' found under
        directory 'leakcheck' no previously-included directories found
        matching 'doc/_build' no previously-included directories found
        matching '.travis' no previously-included directories found
        matching '.mention-bot' Downloading/unpacking
        cryptography>=1.3.4 (from urllib3[secure]) Running setup.py
        egg_info for package cryptography
        
        no previously-included directories found matching
        'docs/_build' warning: no previously-included files matching
        '*' found under directory 'vectors' Downloading/unpacking
        idna>=2.0.0 (from urllib3[secure]) Running setup.py egg_info
        for package idna
        
        warning: no previously-included files matching '*.pyc' found
        under directory 'tools' warning: no previously-included files
        matching '*.pyc' found under directory 'tests'
        Downloading/unpacking certifi (from urllib3[secure]) Running
        setup.py egg_info for package certifi
        
    Downloading/unpacking ipaddress (from urllib3[secure]) Downloading
      ipaddress-1.0.18.tar.gz Running setup.py egg_info for package
      ipaddress
        
    Downloading/unpacking six>=1.5.2 (from
      pyOpenSSL>=0.14->urllib3[secure]) Downloading six-1.10.0.tar.gz
      Running setup.py egg_info for package six
        
        no previously-included directories found matching
    'documentation/_build' Downloading/unpacking asn1crypto>=0.21.0
    (from cryptography>=1.3.4->urllib3[secure]) Running setup.py
    egg_info for package asn1crypto
        
    Downloading/unpacking packaging (from
      cryptography>=1.3.4->urllib3[secure]) Running setup.py egg_info
      for package packaging
        
        warning: no previously-included files found matching
        '.travis.yml' warning: no previously-included files found
        matching 'dev-requirements.txt' no previously-included
        directories found matching 'docs/_build' no
        previously-included directories found matching 'tasks'
        Downloading/unpacking setuptools>=11.3 (from
        cryptography>=1.3.4->urllib3[secure]) Running setup.pywhen
        egg_info for package setuptools Traceback (most recent call
        last): File "<string>", line 3, in <module> File
        "setuptools/__init__.py", line 10, in <module> from six.moves
        import filter, map ImportError: No module named six Complete
        output from command python setup.py egg_info: Traceback (most
        recent call last):
    
      File "<string>", line 3, in <module>
    
      File "setuptools/__init__.py", line 10, in <module>
    
        from six.moves import filter, map
    
    ImportError: No module named six
    
    ---------------------------------------- Command python setup.py
    egg_info failed with error code 1 in
    /home/me/dummy/build/setuptools Storing
    complete log in /home/me/.pip/pip.log
    
I'm trying to install `urllib3[secure]` in the hope to resolve a `SNIMissingWarning` which I got when [I ran coveralls](https://travis-ci.org/baztian/jaydebeapi/jobs/209732102). The exception message led me to https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings which further directs me to https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2 that suggests installing `urllib3[secure]`.

**Comment by Lukasa** [comment]
This looks like you have some unresolved dependencies. Try doing `pip install -U setuptools six`.

**Comment by baztian** [comment]
I'm running this on a fresh virtualenv. Anyway I tried to run `pip install -U setuptools six` and am getting this:

    Could not fetch URL https://pypi.python.org/simple/setuptools/: There was a problem confirming the ssl certificate: <urlopen error [Errno 1] Illegal state exception>
    Will skip URL https://pypi.python.org/simple/setuptools/ when looking for download links for setuptools in ./dummy/Lib/site-packages/setuptools-0.6c11-py2.7.egg
    Real name of requirement setuptools is setuptools
    Downloading/unpacking setuptools from https://pypi.python.org/packages/03/79/e56106d77d3d2ae607ba1e1d7f8c3ed61880f7decba1f253feb714b7eafe/setuptools-34.3.1.zip#md5=6d8e87010d72ba3c10a7fce6952dcdb9
      Downloading setuptools-34.3.1.zip (622kB): 622kB downloaded
      Running setup.py egg_info for package setuptools
        Traceback (most recent call last):
          File "<string>", line 3, in <module>
          File "setuptools/__init__.py", line 10, in <module>
            from six.moves import filter, map
        ImportError: No module named six
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
    
      File "<string>", line 3, in <module>
    
      File "setuptools/__init__.py", line 10, in <module>
    
        from six.moves import filter, map
    
    ImportError: No module named six

I can run `pip install six`. But this will just lead me to another error when installing `urllib3[secure]`.

**Comment by Lukasa** [comment]
Sure, but I can't see what that other error is. So we need to go down the chain of errors, fixing them one at a time, until we have resolved them all.

**Comment by baztian** [comment]
I had to install

    pip install six
    pip install appdirs
    pip install packaging

Now when I install `urllib3[secure]` I'm getting this:

     Downloading/unpacking urllib3[secure]
      Downloading urllib3-1.20.tar.gz (201kB): 201kB downloaded
      Running setup.py egg_info for package urllib3
        
        warning: no previously-included files matching '*' found under directory 'docs/_build'
      Installing extra requirements: 'secure'
    Downloading/unpacking pyOpenSSL>=0.14 (from urllib3[secure])
      Downloading pyOpenSSL-16.2.0.tar.gz (167kB): 167kB downloaded
      Running setup.py egg_info for package pyOpenSSL
        
        warning: no previously-included files found matching 'leakcheck'
        warning: no previously-included files matching '*.py' found under directory 'leakcheck'
        warning: no previously-included files matching '*.pem' found under directory 'leakcheck'
        no previously-included directories found matching 'doc/_build'
        no previously-included directories found matching '.travis'
        no previously-included directories found matching '.mention-bot'
    Downloading/unpacking cryptography>=1.3.4 (from urllib3[secure])
      Downloading cryptography-1.8.1.tar.gz (423kB): 423kB downloaded
      Running setup.py egg_info for package cryptography
        
        no previously-included directories found matching 'docs/_build'
        warning: no previously-included files matching '*' found under directory 'vectors'
    Downloading/unpacking idna>=2.0.0 (from urllib3[secure])
      Downloading idna-2.5.tar.gz (130kB): 130kB downloaded
      Running setup.py egg_info for package idna
        
        warning: no previously-included files matching '*.pyc' found under directory 'tools'
        warning: no previously-included files matching '*.pyc' found under directory 'tests'
    Downloading/unpacking certifi (from urllib3[secure])
      Downloading certifi-2017.1.23.tar.gz (380kB): 380kB downloaded
      Running setup.py egg_info for package certifi
        
    Downloading/unpacking ipaddress (from urllib3[secure])
      Downloading ipaddress-1.0.18.tar.gz
      Running setup.py egg_info for package ipaddress
        
    Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2 in ./dummy/Lib/site-packages (from pyOpenSSL>=0.14->urllib3[secure])
    Downloading/unpacking asn1crypto>=0.21.0 (from cryptography>=1.3.4->urllib3[secure])
      Downloading asn1crypto-0.21.1.tar.gz (82kB): 82kB downloaded
      Running setup.py egg_info for package asn1crypto
        
    Requirement already satisfied (use --upgrade to upgrade): packaging in ./dummy/Lib/site-packages (from cryptography>=1.3.4->urllib3[secure])
    Downloading/unpacking setuptools>=11.3 (from cryptography>=1.3.4->urllib3[secure])
      Downloading setuptools-34.3.1.zip (622kB): 622kB downloaded
      Running setup.py egg_info for package setuptools
        warning: no files found matching '*' under directory 'setuptools/_vendor'
    Downloading/unpacking enum34 (from cryptography>=1.3.4->urllib3[secure])
      Downloading enum34-1.1.6.tar.gz (40kB): 40kB downloaded
      Running setup.py egg_info for package enum34
        
    Downloading/unpacking cffi>=1.4.1 (from cryptography>=1.3.4->urllib3[secure])
      Downloading cffi-1.9.1.tar.gz (407kB): 407kB downloaded
      Running setup.py egg_info for package cffi
        Package libffi was not found in the pkg-config search path.
        Perhaps you should add the directory containing `libffi.pc'
        to the PKG_CONFIG_PATH environment variable
        No package 'libffi' found
        Package libffi was not found in the pkg-config search path.
        Perhaps you should add the directory containing `libffi.pc'
        to the PKG_CONFIG_PATH environment variable
        No package 'libffi' found
        Package libffi was not found in the pkg-config search path.
        Perhaps you should add the directory containing `libffi.pc'
        to the PKG_CONFIG_PATH environment variable
        No package 'libffi' found
        Package libffi was not found in the pkg-config search path.
        Perhaps you should add the directory containing `libffi.pc'
        to the PKG_CONFIG_PATH environment variable
        No package 'libffi' found
        Package libffi was not found in the pkg-config search path.
        Perhaps you should add the directory containing `libffi.pc'
        to the PKG_CONFIG_PATH environment variable
        No package 'libffi' found
        Traceback (most recent call last):
          File "<string>", line 16, in <module>
          File "/home/bbowe/Sources/jaydebeapi/dummy/build/cffi/setup.py", line 120, in <module>
            ask_supports_thread()
          File "/home/bbowe/Sources/jaydebeapi/dummy/build/cffi/setup.py", line 63, in ask_supports_thread
            ok = (sys.platform != 'win32' and
          File "/home/bbowe/Software/jython-2.7.0/Lib/distutils/command/config.py", line 232, in try_compile
            self._compile(body, headers, include_dirs, lang)
          File "/home/bbowe/Software/jython-2.7.0/Lib/distutils/command/config.py", line 232, in try_compile
            self._compile(body, headers, include_dirs, lang)
          File "/home/bbowe/Software/jython-2.7.0/Lib/distutils/command/config.py", line 136, in _compile
            (obj,) = self.compiler.object_filenames([src])
          File "/home/bbowe/Software/jython-2.7.0/Lib/distutils/ccompiler.py", line 871, in object_filenames
            if ext not in self.src_extensions:
        TypeError: 'NoneType' object is not iterable
        Complete output from command python setup.py egg_info:
        Package libffi was not found in the pkg-config search path.
    
    Perhaps you should add the directory containing `libffi.pc'
    
    to the PKG_CONFIG_PATH environment variable
    
    No package 'libffi' found
    
    Package libffi was not found in the pkg-config search path.
    
    Perhaps you should add the directory containing `libffi.pc'
    
    to the PKG_CONFIG_PATH environment variable
    
    No package 'libffi' found
    
    Package libffi was not found in the pkg-config search path.
    
    Perhaps you should add the directory containing `libffi.pc'
    
    to the PKG_CONFIG_PATH environment variable
    
    No package 'libffi' found
    
    Package libffi was not found in the pkg-config search path.
    
    Perhaps you should add the directory containing `libffi.pc'
    
    to the PKG_CONFIG_PATH environment variable
    
    No package 'libffi' found
    
    Package libffi was not found in the pkg-config search path.
    
    Perhaps you should add the directory containing `libffi.pc'
    
    to the PKG_CONFIG_PATH environment variable
    
    No package 'libffi' found
    
    Traceback (most recent call last):
    
      File "<string>", line 16, in <module>
    
      File "/home/bbowe/Sources/jaydebeapi/dummy/build/cffi/setup.py", line 120, in <module>
    
        ask_supports_thread()
    
      File "/home/bbowe/Sources/jaydebeapi/dummy/build/cffi/setup.py", line 63, in ask_supports_thread
    
        ok = (sys.platform != 'win32' and
    
      File "/home/bbowe/Software/jython-2.7.0/Lib/distutils/command/config.py", line 232, in try_compile
    
        self._compile(body, headers, include_dirs, lang)
    
      File "/home/bbowe/Software/jython-2.7.0/Lib/distutils/command/config.py", line 232, in try_compile
    
        self._compile(body, headers, include_dirs, lang)
    
      File "/home/bbowe/Software/jython-2.7.0/Lib/distutils/command/config.py", line 136, in _compile
    
        (obj,) = self.compiler.object_filenames([src])
    
      File "/home/bbowe/Software/jython-2.7.0/Lib/distutils/ccompiler.py", line 871, in object_filenames
    
        if ext not in self.src_extensions:
    
    TypeError: 'NoneType' object is not iterable

**Comment by baztian** [comment]
BTW pip freeze shows:

    appdirs==1.4.3
    packaging==16.8
    pyparsing==2.2.0
    six==1.10.0
    wsgiref==0.1.2

**Comment by haikuginger** [comment]
@baztian, it looks like you need to install libffi using the relevant package manager for your system - `brew` or `ports` on MacOS, or `apt`, `pacman`, or something else on the various Linux variants.

**Comment by Lukasa** [comment]
It's not entirely clear to me that cffi will work for Jython.

**Comment by SethMichaelLarson** [comment]
Closing as cffi is not supported on Jython and I don't think our current selector model is either. If Jython starts supporting these things we can reconsider official support for Jython.
