### ISSUE TITLE
sync_connection does not correctly handle SSLWantRead and SSLWantWrite

### ISSUE THREAD

**Issue by haikuginger** [urllib3/urllib3#1149]
If either of `SSLWantRead` or `SSLWantWrite` are raised in the context of `sync_connection._receive_bytes()` on the V2 branch, the error is raised, rather than being interpreted and handled with appropriate action.

**Comment by Lukasa** [comment]
Yup, so this is broader than that. Anywhere we call `socket.recv()` or `socket.send` we need to be able to tolerate getting either of these errors and handling them appropriately. This shouldn't be too hard, but requires some careful refactoring, I think. I'll tackle this by next week if no-one beats me to it.
