### ISSUE TITLE
allow passing of cert chains as namespace rather than file path.

### ISSUE THREAD

**Issue by openfly** [urllib3/urllib3#1210]
looking at:

urllib3/urllib3/contrib/pyopenssl.py:
```python
def load_cert_chain(self, certfile, keyfile=None, password=None):
        self._ctx.use_certificate_file(certfile)
        if password is not None:
            self._ctx.set_passwd_cb(lambda max_length, prompt_twice, userdata: password)
        self._ctx.use_privatekey_file(keyfile or certfile)
```

should probably allow for passing of certs as namespaces as well making use of _ctx.use_certificate context.  same for privkey.  this avoids having to leave unencrypted p12 bundles lying around on filesystem where they can be purloined.

**Comment by Lukasa** [comment]
What does "passing of certs as namespaces" mean? Do you mean "as binary data in memory, rather than from the filesystem?"

**Comment by openfly** [comment]
Or as a string.  I don't really care what the data type is.  I just think having to handle temp files when unpacking a p12 cert is pretty crummy.

**Comment by Lukasa** [comment]
Unfortunately, this is not a thing that is supported by the Python standard library in any form, which makes it difficult for us to support. It can be achieved using APIs in PyOpenSSL if you choose to use that TLS backend, but because there is no stdlib API we can use as a basis for a shim we'd be essentially designing our own TLS API, which we don't really want to do.

My recommendation is that you use the PyOpenSSL TLS backend, call `urllib3.util.ssl_.create_urllib3_context()` to build a brand new PyOpenSSL shim SSLContext object, and then grab the backing context out of it (`._ctx`) and call the relevant [PyOpenSSL APIs](https://pyopenssl.readthedocs.io/en/stable/api/ssl.html#OpenSSL.SSL.Context.use_certificate).

**Comment by openfly** [comment]
there should already be a context for this in pyopenssl.  we just need to handle the object and detect if it's a filehandle or not.

**Comment by Lukasa** [comment]
@openfly I'm not saying PyOpenSSL can't handle it. I just said that it could, and told you where to get the object to call.

What I'm saying is that `urllib3.contrib.pyopenssl` should not grow an API for this, because it does not have any analogue in the standard library. The purpose of that module is to shim the external modules to the standard library and provide equivalent support, not to provide extension points for functionality not provided in the standard library.

**Comment by openfly** [comment]
which standard library are we referring to?  ( having a whose on first moment.. no coffee  etc )

**Comment by Lukasa** [comment]
Python

**Comment by openfly** [comment]
Seems overly complicated tbh.  I kinda get what you are saying.  ( my contextual knowledge of urllib3 is entirely lacking.  I really just want this to work in requests... )  Not sure I'm going to be able to power through that without doing some considerable ramp up on urllib3 itself.  Which frankly, is kind of a time sink for me at the moment.  =/

**Comment by Lukasa** [comment]
I mean, "overly complicated" is entirely a relative term. Requests does not expose anything in its API that is not supported across all TLS backends. PKCS#12 file or data support is not supported in the standard library, therefore we do not support it. We provide a supported way to get at this low-level information via the `SSLContext` API discussed above and outlined [here](https://lukasa.co.uk/2017/02/Configuring_TLS_With_Requests/).

At all points we have a set of rules to prevent us needing to boil the ocean to support all conceivable data types. Hopefully at some point in the future my work on [PEP 543](https://www.python.org/dev/peps/pep-0543/) will bear fruit and we'll be able to allow the TLS backend to concern itself with this, but for now the best I can offer you is to point you at the escape hatches that let you do what you're aiming to do.

**Comment by openfly** [comment]
For clarity.  The goal is not to pass a p12.

The goal is to avoid having to write unpacked cert files to disk to use them in a PKCS authenticated https call.   The current approach is fundamentally less secure.  As it involves forcing users to write unobfuscated, decrypted keys to disk ( usually in tmpfile pathes ).  

So to say this is how TLS should operate is silly from the point of... of course it isn't how it should operate.  But I understand a desire to adhere to base standards.  The problem is, for me ( and lack of education is a big thing here ).  As far as I can tell... TLS has no trouble at all with taking a non filehandle target for this.  It has 3 contexts I've found thus far for this specific cert loading.  So the issue is entirely within either ( as you say ) the python standard library... or within urllib3 and their interpretation of TLS standards.  Which appears to be limited in scope.

**Comment by Lukasa** [comment]
Woah, hang on. We're talking at cross purposes.

> As it involves forcing users to write unobfuscated, decrypted keys to disk ( usually in tmpfile pathes ).

No it does not. As you can see in the function signature above, you can pass a "password" object that is allowed to be a callable to provide the decryption data. This is actually *safer* than decrypting the data in Python code, as you cannot ensure that Python will remove the data from its memory in any kind of timely fashion or at all, while OpenSSL can do so.

I've been answering your questions in the assumption that you didn't want temporary files. If what you don't want in *unencrypted* files then, congratulations, you don't need them: you can convert to encrypted PEM private keys and get what you need. In this case, again, you only need the [SSLContext manipulation code shown here](https://lukasa.co.uk/2017/02/Configuring_TLS_With_Requests/) combined with a call to `load_cert_chain` that provides the password callable.

If you want no files at all, *then* the above discussions apply.

**Comment by openfly** [comment]
I don't want tmp files.  

Encrypting before placing a tmp file is a nice step up for me.  Was unaware that would work.  Kinda surprised actually.  Would still rather keep it all in memory.

**Comment by Lukasa** [comment]
Ok, so I strongly advise you not to put keying material in Python code if you can avoid it. It's vastly better to let you keep it in C code, which can accurately manage the memory. Regardless, your options are as I've laid them out above: either call into PyOpenSSL if you want no files at all, or use the API that lets you provide a password callback.

**Comment by openfly** [comment]
would you be cool with CFFI from a c level perspective?

**Comment by Lukasa** [comment]
CFFI is fine, and indeed PyOpenSSL uses it to delegate the responsibility to OpenSSL.

**Comment by openfly** [comment]
Now that I have had my coffee... thanks for putting up with me and answering questions @Lukasa

**Comment by pquentin** [comment]
As far as I understand, this issue is only an interesting discussion, but there's nothing actionable here that should be done, so I guess it can be closed?

**Comment by SethMichaelLarson** [comment]
I'll close this, if needed it can be reopened.
