### ISSUE TITLE
.coveragerc removes all raise statements from coverage checks

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#1214]
This was discovered in #1211 and affects a few places that ought to have coverage. See #1212 for a full list of modules that are affected. We should aim to remove `raise` from `.coveragerc` and have test coverage for all these places.

As @Lukasa said, this is a great place for a contributor to make a real difference in the quality of this code-base.

**Comment by theodesp** [comment]
So basically we go through the https://codecov.io/gh/urllib3/urllib3/tree/master/src/urllib3 reports and check where the raise statements are not covered and provide test cases for that? If that's OK  I will try to push some PRs.

**Comment by SethMichaelLarson** [comment]
Yeah that's the idea! :) Don't feel like you have to cover them all in one PR either. Committing a few at a time is totally fine.
