### ISSUE TITLE
Timeouts not happening on linux

### ISSUE THREAD

**Issue by eladbitton** [urllib3/urllib3#1271]
Hi guys,

I wanted to check how my code behaves on this slow loading url. I want the ReadTimeoutError error to occur in this situation...

So i made this code to check how urllib handles it:
`from urllib3 import PoolManager, Retry, Timeout`
`p = PoolManager(retries=Retry(0, redirect=0), timeout=Timeout(connect=1.0, read=1.0))`
`r = p.request('get', 'http://kj-art.hs.kr/xboard/board.phpmode=view&number=8306&addUrlQuery=c0NhdD0%5E&page=1&tbnum=77&keyset=&searchword=')`

I ran this code on my Windows PC and on Google Cloud machine running Ubuntu 16.04.

On my Windows I get a ReadTimeoutError real quick.
On the linux i don't get any exceptions. 

On both machines I use python 3.5.2 and urllib3 1.22.

What can cause this problem?

**Comment by Lukasa** [comment]
What *does* happen on Linux? Does it complete, or just block forever?

**Comment by eladbitton** [comment]
Its finished after a minute and a half with status 200.

**Comment by SethMichaelLarson** [comment]
Can you do this on your Linux machine in a Python console:

```python
import urllib3.util.selectors
print(urllib3.util.selectors.DefaultSelector())
```

**Comment by eladbitton** [comment]
Output:
<urllib3.util.selectors.EpollSelector object at 0x7fd69243eb38>

**Comment by Lukasa** [comment]
Is the server just very slow?

**Comment by Lukasa** [comment]
I ask because the timeout isn't a *total* timeout, it applies per socket operation. If the server is constantly drip feeding data, and we are getting each byte within a second of the last, this may never time out.

**Comment by eladbitton** [comment]
Probably my pc's internet is the one that is slow, because probably the interval between drips of data is longer on the PC which cause the timeout to occuer. 

Is there a way to set a total timeout using urllib3 or should i implement it myself?

**Comment by Lukasa** [comment]
You'll need to do it yourself I'm afraid.
