### ISSUE TITLE
Make sure PyOpenSSLContext.load_cert_chain sets password as byte string

### ISSUE THREAD

**Issue by aiguofer** [urllib3/urllib3#1275]
I ran into an issue creating a TransportAdapter using an SSL Context with a passpharse due to the fact that pyopenssl expects a byte string and not unicode (see https://github.com/pyca/pyopenssl/issues/701).

Apparently, they have a reason for not casting it, so it would be nice if `urllib3` did the type check and casting instead. I'd be happy to submit a PR but just wanted to run the idea by you guys first. This could be something as simple as:

```
    def load_cert_chain(self, certfile, keyfile=None, password=None):
        self._ctx.use_certificate_file(certfile)
        if password is not None:
            self._ctx.set_passwd_cb(lambda max_length, prompt_twice, userdata: six.binary_type(password))
        self._ctx.use_privatekey_file(keyfile or certfile)
```

Or it could have a bit more robust type checking.

**Comment by Lukasa** [comment]
Why should the cast come in urllib3 and not in user code? I’m not opposed to adding the cast but the downside of adding it is the possibility of subtle errors due to the encode.

**Comment by aiguofer** [comment]
Mainly for convenience. It works fine passing unicode to the built in SSL library, but not to pyopenssl; it seems a little unexpected to have to worry about what type of string you're passing in to `load_cert_chain` as an end user when the backend is 'magically' chosen for you. It was also kind of hard to debug what was happening since the error was coming from outside of python.
