### ISSUE TITLE
Functions inside `urllib3.util.ssl_` are not using monkeypatched values.

### ISSUE THREAD

**Issue by software-opal** [urllib3/urllib3#1282]
I am experimenting with trying to remove the warnings by monkey-patching `pip` code and I've run into a situation where the library itself is monkey-patched correctly; however `pip` uses both `ssl_.create_urllib3_context` and `ssl_.ssl_wrap_socket` which are using the old, un-monkeypatched values.

To fix this I append a `from urllib3.util.ssl_ import <variable>;` to the start of each line which uses one of the monkeypatched variables.

So far the usages I've encountered are `SSLContext` in `create_urllib3_context` and `HAS_SNI` in `ssl_wrap_socket`.

**Comment by Lukasa** [comment]
I’d be happy to accept a patch to fix this.

**Comment by SethMichaelLarson** [comment]
Hey @leesdolphin, I'd like to fix this issue but I'm having trouble determining what's exactly wrong in those files. Could you provide some more details and help me understand what's going on? Thanks!

**Comment by sethmlarson** [comment]
I believe this is fixed, closing.
