### ISSUE TITLE
timeout does not apply to name resolution

### ISSUE THREAD

**Issue by cancan101** [urllib3/urllib3#1334]
This may be a re-post of https://github.com/shazow/urllib3/issues/423:

Right now it looks like [`timeout` is not applied to name resolution (`getaddrinfo`)](https://github.com/shazow/urllib3/blob/fe918c67359876dc9ff600e10be6103c64b0b7d4/urllib3/util/connection.py#L60). This means that the connection open can hang far FAR longer than timeout.

There is some indication that this requires using a side thread to fix:
https://stackoverflow.com/questions/26857922/pass-timeout-to-socket-getaddrinfo

The current implementation means that the user can get some unexpectedly long hangs when trying to open a connection.

**Comment by njsmith** [comment]
This is actually impossible to fix in any popular OS :-(. The best you can do is to run the `getaddrinfo` in a thread, and then if the timeout occurs, abandon that thread to keep running in the background while your main thread goes back to doing useful work (and hope you don't accumulate too many of these dangling background threads).

**Comment by cancan101** [comment]
Agree that might be best solution. That being said, docs should be updated to reflect this as the current explanation for timeout doesn't capture it.

**Comment by xeruf** [comment]
Is this also why `ping` can hang a long time at name resolution despite low timeout values?

**Comment by cancan101** [comment]
[Here are two implementations](https://github.com/aio-libs/aiohttp/blob/b146766ff709b9b6aa7af6bd50108c49eb4a3840/aiohttp/resolver.py) for hostname resolution that `aiohttp` uses. They use ThreadPool in one and `aiodns` in the other. Issue to be aware of with directly calling `getaddrinfo`  is that the Host header in the HTTP request still should contain the hostname rather than the IP.
