### ISSUE TITLE
Proxying FTP requests

### ISSUE THREAD

**Issue by andyljones** [urllib3/urllib3#1337]
Proxying schemes other than HTTP will return a 400 error.

```python
manager = urllib3.ProxyManager('
resp = manager.request('GET', 'ftp://speedtest.tele2.net/')
print(resp.status) # 400 
```

The code responsible is [here](https://github.com/shazow/urllib3/blob/master/urllib3/poolmanager.py#L318-L321):

```python
        if self.proxy is not None and u.scheme == "http":
            response = conn.urlopen(method, url, **kw)
        else:
            response = conn.urlopen(method, u.request_uri, **kw)
```

where if the URL scheme is other than http, the URI is used instead of the URL. In the case of `ftp://speedtest.tele2.net/` that's simply `/` .

I'd submit a pull request to fix this, but I don't know enough about protocols to say why the code works this way in the first place - it's obviously deliberate, and I assume my naive fix (to strip out the `u.scheme == "http"` test) would break someone else's functionality.

**Comment by sigmavirus24** [comment]
Does urllib3 even handle FTP without proxies? I'd be shocked if it did.

**Comment by haikuginger** [comment]
I would likewise be shocked. IMO, if FTP without a proxy does somehow work, I'd be more inclined to explicitly deprecate it than to add formal support for what's obviously an accidental feature that doesn't have any sort of testing or guarantees.
