### ISSUE TITLE
Support DNS queries over HTTPS (DoH)

### ISSUE THREAD

**Issue by alanhamlett** [urllib3/urllib3#1344]
https://datatracker.ietf.org/doc/draft-hoffman-dispatch-dns-over-https/

**Comment by SethMichaelLarson** [comment]
This would require some re-writing of logic within `create_connection()` into a more abstract construction to accommodate for different DNS-querying methods. It could probably be accomplished already by using Requests and writing your own Adapter class, relying on urllib3 to fetch DNS for the ConnectionPool to bind to and also to complete the HTTP request?
