### ISSUE TITLE
Announcement: @theacodes is the lead maintainer until further notice

### ISSUE THREAD

**Issue by shazow** [urllib3/urllib3#1347]
Hi everyone who watches urllib3 issues. 👋 

As you may recall from #1290, @haikuginger has been the lead maintainer of urllib3 since December. I am very grateful for Jesse's commitment of time and effort. Jesse has left a strong positive mark on the project, and will continue to do so as time permits, but it's time for a new lead maintainer to carry on the torch.

## New maintainer

@theacodes is taking responsibility as the lead maintainer and thus the direction of urllib3 moving forward.

As before, our family of contributors and co-maintainers will continue to support our new leader as needed.

Also, we're adding @SethMichaelLarson to our collection of co-maintainers. Seth will work with Thea to help keep the backlog of issues down and keep things moving forwarding.

## Logistics

- [x] Announcement: https://twitter.com/shazow/status/978299138361184256
- [x] Update README
    - [x] @theacodes' entry should be at the top of the list, can mention that her time is sponsored by Google.
    - [x] @SethMichaelLarson should be added to the list as well (Seth: let us know if someone is sponsoring your work here)
    - [x] Update Sponsors section.
- [x] [Github admin](https://github.com/shazow/urllib3/settings/collaboration)
- [x] [PyPI admin](https://pypi.org/manage/project/urllib3/collaboration/)
- [x] [ReadTheDocs admin](https://readthedocs.org/dashboard/urllib3/users/)
- [x] TravisCI? AppVeyor? (We didn't do these last time, are they needed?)
- [x] Release process documentation? (Did this ever get written up? [Some notes here](https://github.com/shazow/urllib3/issues/1290#issuecomment-351739543), but we should make a wiki or .md file or something)
- [x] Setup alerts:
  - [x] [_Watch_ the `urllib3` repo](https://github.com/shazow/urllib3/subscription)
  - [x] [Subscribe to `urllib3` Stackoverflow tag](https://stackexchange.com/filters/22230/urllib3) (add email alerts or [subscribe to RSS](https://stackoverflow.com/questions/tagged/urllib3))
  - [x] [Join the `python-urllib3` Gitter](https://gitter.im/python-urllib3/Lobby)

Anything else? (Maintainers, please edit the checklist above and check it off as it's completed.)

---

If anyone has questions or concerns, comments here are welcome or email me. ❤️

**Comment by SethMichaelLarson** [comment]
Thank you @haikuginger for your work! Good luck to @jonparrott as lead! :tada:

**Comment by shazow** [comment]
@jonparrott @SethMichaelLarson FYI added a few more suggested items for getting relevant project alerts:

- Setup alerts:
  - [_Watch_ the `urllib3` repo](https://github.com/shazow/urllib3/subscription)
  - [Subscribe to `urllib3` Stackoverflow tag](https://stackoverflow.com/questions/tagged/urllib3) (add email alerts or subscribe to RSS)
  - [Join the `python-urllib3` Gitter](https://gitter.im/python-urllib3/Lobby)

**Comment by shazow** [comment]
Also, one more thing: Please let me know if it would be better to migrate urllib3 to a stand-alone Github org (rather than have it live under my name).

I've offered this with every transition, but so far the sentiment has been that migrating URLs would be a bigger headache than it's worth. I just want to make sure it's clear that this is always on the table. :)

**Comment by jonparrott** [comment]
> Please let me know if it would be better to migrate urllib3 to a stand-alone Github org

I think so. :)

> I've offered this with every transition, but so far the sentiment has been that migrating URLs would be a bigger headache than it's worth.

GitHub should automatically redirect. :)

**Comment by shazow** [comment]
> GitHub should automatically redirect. :)

Will all the build services etc continue working? If you can ping me again after Thursday to remind me, I'll setup a new org.

**Comment by jonparrott** [comment]
> Will all the build services etc continue working?

We'll need to re-enable travis/appveyor but the configs should mostly work. It might take a little tweaking.

**Comment by jonparrott** [comment]
@shazow post-thursday ping about org stuff.

**Comment by shazow** [comment]
Let's do it. https://github.com/python-urllib3 sound good? Any better suggestions?

**Comment by SethMichaelLarson** [comment]
Sounds good to me, the only other alternative IMO is moving under python-hyper?

**Comment by jonparrott** [comment]
@shazow SGTM. plain o' `urllib3/urllib3` would've been fine as well.

**Comment by SethMichaelLarson** [comment]
If @jonparrott's suggestion is available use urllib3/urllib3

**Comment by shazow** [comment]
TIL I already have urllib3/urllib3, off we go.

**Comment by shazow** [comment]
It is done. @jonparrott is an owner of the org, so should be able to do all the necessary remaining configuration. Let me know if you need me for anything!

**Comment by jonparrott** [comment]
\o/ Thanks, @shazow!

**Comment by jonparrott** [comment]
Waiting on Travis and AppVeyor to catch up to github, then I'll enable both services on the new org.

**Comment by jonparrott** [comment]
@shazow can you also make me an admin on ReadTheDocs?

**Comment by jonparrott** [comment]
FYI I have removed all users except @shazow from having direct access to this project, instead, y'all have been added to teams under the urllib3 organization.

**Comment by shazow** [comment]
@jonparrott You're already in the maintainers list for ReadTheDocs. I don't see any options for making someone more admin-ier than that. Could you share instructions?

**Comment by jonparrott** [comment]
Oh no I'm just dumb, I'm sorry. Thanks @shazow!

**Comment by shazow** [comment]
No worries!

**Comment by jonparrott** [comment]
I would just like to call out that @SethMichaelLarson has been doing a great job. Seth, please let me know if you need my attention on anything or if you need me to cut a release. 

I'm going to schedule some time for myself to go through and clean-up some pending pull requests and older issues at some point.

**Comment by shazow** [comment]
Indeed, big thank you to @SethMichaelLarson!

**Comment by SethMichaelLarson** [comment]
The one thing I really want in the next release is #1359 so that Pip 9 can package urllib3 and be on it's merry way with stopping TLS1.0/1.1 on PyPI and still supporting Python 2.9 on macOS. :)

**Comment by jonparrott** [comment]
Cool, I can struggle through the release process when that's merged.

**Comment by SethMichaelLarson** [comment]
Good luck! :) The PR should be in a semi-ready state but it seems @wbond is doing some debugging?

**Comment by theacodes** [comment]
Nope, I need to do that. @SethMichaelLarson would you have some time next friday to walk through a release together?

**Comment by SethMichaelLarson** [comment]
Definitely! Whatever time works for you I should be able to muscle some timein if it's during the day otherwise any time after work is good for me too.

Do we want to release on a Friday and set off everyone's pagers? ;) Maybe a Monday/Tuesday is better for such a large release.

**Comment by theacodes** [comment]
Maybe - let's see then.

**Comment by theacodes** [comment]
I apologize for not getting to this on Friday. @SethMichaelLarson what does your week look like?

**Comment by SethMichaelLarson** [comment]
Don't worry about it! I'm every night at 4PM Central this week. Might be able to put in a an hour or so this week during the workday.

**Comment by nateprewitt** [comment]
Hey @theacodes, @SethMichaelLarson!

I’m looking at cutting a new release of Requests in the near future and was going to start testing against the current urllib3 master branch. Do you foresee any other features being merged before the release or is master about ready?

**Comment by theacodes** [comment]
Should be ready as far as I know.

**Comment by SethMichaelLarson** [comment]
I've stopped adding new features until the new release. There are enough changes already! :)
Speaking of testing Requests, I've been thinking about adding integration tests against pip and requests within our own CI as an `allow_failure` option and then setting `fast_fail: true` too. Would make me feel better for these types of releases. :)

**Comment by theacodes** [comment]
That's a great idea.

**Comment by nateprewitt** [comment]
@SethMichaelLarson I actually started putting something similar together for Requests to automatically test against urllib3 over the weekend. I’m all for more testing, so let me know if I can help at all! I think fortunately pip vendors urllib3 still, so you can rest a bit easier about that.

**Comment by theacodes** [comment]
Okay, I just made my first release and all seems well in the world (fingers crossed). I'm closing this as there's no need to keep this open as I've now *completely taken over the project* (muhahaha).

**Comment by shazow** [comment]
@theacodes Grats! In the past, I kept these announcement threads open for as long as the fact remained, but closing is fine too. :) Probably less confusion now that the library is not under my personal namespace.
