### ISSUE TITLE
Fix AppVeyor CI builds for Organization repository

### ISSUE THREAD

**Issue by SethMichaelLarson** [urllib3/urllib3#1364]
As can be seen in this [AppVeyor build](https://ci.appveyor.com/project/urllib3/urllib3/build/1.0.57/job/j9ja509fylh2c7cy#L29) the latest major release of pip breaks in AppVeyor. This should be fixed along with getting AppVeyor reporting working.

**Comment by jonparrott** [comment]
I'll be investigating this on Friday. It's likely I did something dumb when setting up appveyor for the urllib3 org.

**Comment by SethMichaelLarson** [comment]
@pquentin fixed the Pip 10 issue but the reporting issue still is a thing. We can track that whole activity here. :)

**Comment by jonparrott** [comment]
AppVeyor reporting is back up and running. Also, Python 3.4 build are failing/flaky.

![screen shot 2018-04-20 at 9 41 06 am](https://user-images.githubusercontent.com/250995/39063202-05eb20dc-447f-11e8-98c9-02652e79d8bc.png)
