### ISSUE TITLE
Missing License text on securetransport.py

### ISSUE THREAD

**Issue by wbond** [urllib3/urllib3#1368]
One thing that should happen is adding the license text from https://github.com/urllib3/urllib3/blob/master/urllib3/contrib/_securetransport/bindings.py#L12-L30 to https://github.com/urllib3/urllib3/blob/master/urllib3/contrib/securetransport.py. `securetransport.py` seems to have chunks taken verbatim from https://github.com/wbond/oscrypto/blob/master/oscrypto/_osx/tls.py, along with sections inspired by. No doubt there more differences than similarities, but the exact same variable, function and parameters names, combined with identical control flow in areas would imply to me that at least portions of the code started their life from the oscrypto project.

Some examples:

 - https://github.com/wbond/oscrypto/blob/master/oscrypto/_osx/tls.py#L90
 - https://github.com/urllib3/urllib3/blob/master/urllib3/contrib/securetransport.py#L83

 - https://github.com/wbond/oscrypto/blob/master/oscrypto/_osx/tls.py#L94
 - https://github.com/urllib3/urllib3/blob/master/urllib3/contrib/securetransport.py#L181

 - https://github.com/wbond/oscrypto/blob/master/oscrypto/_osx/tls.py#L144-L149
 - https://github.com/urllib3/urllib3/blob/master/urllib3/contrib/securetransport.py#L218-L223

 - https://github.com/wbond/oscrypto/blob/master/oscrypto/_osx/tls.py#L209
 - https://github.com/urllib3/urllib3/blob/master/urllib3/contrib/securetransport.py#L238

 - https://github.com/wbond/oscrypto/blob/master/oscrypto/_osx/tls.py#L246-L251
 - https://github.com/urllib3/urllib3/blob/master/urllib3/contrib/securetransport.py#L269-L274

 - https://github.com/wbond/oscrypto/blob/master/oscrypto/_osx/tls.py#L264-L265
 - https://github.com/urllib3/urllib3/blob/master/urllib3/contrib/securetransport.py#L291-L292

 -

**Comment by jonparrott** [comment]
HI @wbond, feel free to send a PR to include the exact text you want to be displayed. Thankfully, both projects are MIT-licensed.

**Comment by nateprewitt** [comment]
It looks like Lukasa put the licensing info in urllib3/contrib/_securetransport/bindings.py in #1122.

**Comment by wbond** [comment]
Well, my point is that not just bindings.py is derived, securetransport.py appears to be derived too, so either a `LICENSE` file listing which files are derived should be present, or both individual files should include the copyright notice.

**Comment by SethMichaelLarson** [comment]
Putting licensing information into `urllib3/contrib/securetransport.py` sounds reasonable to me. cc: @Lukasa
