### ISSUE TITLE
PR bankruptcy

### ISSUE THREAD

**Issue by jonparrott** [urllib3/urllib3#1370]
@urllib3/maintainers this project has 46 open pull requests, some of which are several years old.

I am planning on "PR bankruptcy" to bring us back to a reasonable state. I am going to close old/stale PRs and leave a nice message indicating that we are happy to reconsider if the authors still consider them important.

My tentative cutoff is for all PRs older than 6 months. 

Does anyone have any concerns with this?

**Comment by SethMichaelLarson** [comment]
No problems here. :)

**Comment by jonparrott** [comment]
This is done. Sorry for the email spam, but we now only have 2 (!) open PRs. Next, issue bankruptcy.

@njsmith this also makes it much easier to do the v1/v2 split. :)

**Comment by jonparrott** [comment]
For my own reference in the future, this is the script I used to do this: https://gist.github.com/jonparrott/59445db2c1ad3a5e0cd47bfef9138120
