### ISSUE TITLE
Error reading Proxy certificates. (tlsv1 alert unknown ca)

### ISSUE THREAD

**Issue by micafer** [urllib3/urllib3#1384]
I create an issue on the requests library:
https://github.com/requests/requests/issues/4630
They think that the problem is related with urllib3.

**Comment by SethMichaelLarson** [comment]
Thanks for opening this! I'm going to port some information over from the Requests issue to our issue tracker.

**Comment by sigmavirus24** [comment]
@SethMichaelLarson it's the same code-path even in master, FYI

**Comment by micafer** [comment]
FYI: In Requests version 2.11.1 (where the code works as expected) the urllib3 version is 1.16. Then in the version 2.12.0 (where error is raised) version is 1.19 as @SethMichaelLarson commented.

**Comment by micafer** [comment]
Are there any news on this issue?

**Comment by SethMichaelLarson** [comment]
Doesn't appear so. If you'd like to take this issue it'd be a great help. Historically none of the maintainers use proxies and therefore your experience would prove invaluable for this issue.

**Comment by micafer** [comment]
OK, I will try to take a look on it.

**Comment by micafer** [comment]
I have made some tests and in last version 1.23 the issue disappears.
It also seems that last requests version will enable urllib 1.23 so it problem should disappear.
