### ISSUE TITLE
Remove TLS13-* suites from DEFAULT_CIPHERS

### ISSUE THREAD

**Issue by tiran** [urllib3/urllib3#1386]
OpenSSL 1.1.1 changed the name of the TLS 1.3 cipher suites and added a new API to configure them. ``SSL_CTX_set_cipher_list()`` no longer affects TLS 1.3 suites. Therefore the ``TLS13`` suites can be removed from ``DEFAULT_CIPHERS``. The suites are now configured with ``SSL_CTX_set_ciphersuites()``. Neither CPython nor PyOpenSSL expose the feature yet.

https://github.com/openssl/openssl/pull/5392

**Comment by SethMichaelLarson** [comment]
Should we defer removing the TLS 1.3 cipher suites until the `SSL_CTX_set_ciphersuites()` feature is exposed in PyOpenSSL or CPython? Would love your recommendation on how to proceed here. :)
