### ISSUE TITLE
Slow upload on Windows when setting connect timeout

### ISSUE THREAD

**Issue by ivknv** [urllib3/urllib3#1394]
Normally, when I upload files using the `PUT` request I get upload speed of about `100 Mb/s`.
But as soon as I set the connect timeout (read timeout appears to have no effect on the speed), the speed drops to about `4 Mb/s` (can vary depending on the server):

```python
# Running on Windows 10, using Python 3.6.5

from io import BytesIO
import urllib3

def upload(timeout):
    test_file = BytesIO(b"0" * 15 * 1024**2)

    http = urllib3.PoolManager()
    http.request("PUT", "https://httpbin.org/put", body=test_file, timeout=timeout)

upload(urllib3.Timeout(connect=15)) # Painfully slow, about 4 Mb/s
upload(None) # Pretty fast, about 100 Mb/s
```

The problem disappears if I send the request again using the same pool manager, even with the same timeout:

```python
# Running on Windows 10, using Python 3.6.5

from io import BytesIO
import urllib3

test_file = BytesIO(b"0" * 15 * 1024**2)

http = urllib3.PoolManager()
timeout = urllib3.Timeout(connect=15)

print("Request 1")
# Painfully slow, about 4 Mb/S
http.request("PUT", "https://httpbin.org/put", body=test_file, timeout=timeout)

test_file.seek(0)
print("Request 2")
# Pretty fast, about 100 Mb/s
http.request("PUT", "https://httpbin.org/put", body=test_file, timeout=timeout)
```

I tried using different versions of `urllib3`: `1.23`, `1.22`, `1.15`, `1.10`. All of them have this problem.

**Comment by theacodes** [comment]
That is pretty weird! I'm not sure how to debug this. I wonder if the lower-level urllib objects exhibit the same behavior.

**Comment by ivknv** [comment]
I did some more testing. This time I tried to do the same thing with `http.client`, got the same behavior.

```python
from io import BytesIO
import http.client

def upload(timeout=None):
    test_file = BytesIO(b"0" * 15 * 1024**2)

    if timeout is not None:
        conn = http.client.HTTPSConnection("httpbin.org", timeout=timeout)
    else:
        conn = http.client.HTTPSConnection("httpbin.org")

    conn.request("PUT", "/put", body=test_file)

    conn.getresponse().read()

upload(25) # Slow
upload() # Fast
```

So I guess it's something in `http.client`, not `urllib3` specifically.

But using the same pool manager twice removes the problem, maybe there's something relevant in the pool manager class? Perhaps there's a workaround.

**Comment by theacodes** [comment]
Beats me, it seems worthwhile to check bugs.python.org to see if there's an existing one, and if there isn't, file one.

**Comment by ivknv** [comment]
Guess I'll do that.

**Comment by jgstew** [comment]
@ivknv do you have examples that use this?

I am also having this issue and wanting to change the default block size when uploading a large file, but using `requests`

I'm going to have to try this.

Related:
- https://docs.python-requests.org/en/latest/user/advanced/#transport-adapters
- https://docs.python-requests.org/en/master/_modules/requests/adapters/

**Comment by sethmlarson** [comment]
@ivknv Since we allow setting `blocksize` now at least in the `main` branch are we okay to close this issue? Or is there more we need to do?
