### ISSUE TITLE
Version registers as 'dev' in install from source

### ISSUE THREAD

**Issue by AlKult** [urllib3/urllib3#1398]
Hi,

I have no root, no internet and no proxy. Therefore, trying to install urllib3 in venv from source (downloaded as urllib3-master.zip from GitHub).
When I do that, urllib3's version registers to be 'dev', which makes it impossible to intall some packages, plus ones that install complain that urllib3's version is not valid (but work anyway).

Could you please help me make it register with its actual version?

OS RHEL 7.4
Kernel 3.10.0-693.11.1.el7.x86_64
Python 3.5.1

$ pip3 freeze
certifi==2018.4.16
chardet==4.0.0
elasticsearch==6.2.0
idna==2.6
pyOpenSSL==18.1.0.dev0
requests==2.18.4
six==1.11.0
urllib3===dev

> (ingestion) ~/packages/urllib3-master> $ python setup.py install
> /opt/rh/rh-python35/root/usr/lib64/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
>   warnings.warn(msg)
> /home/kult/apps/ingestion/lib64/python3.5/site-packages/setuptools/dist.py:294: UserWarning: The version specified ('dev') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
>   "details." % self.metadata.version
> running install
> running bdist_egg
> running egg_info
> creating urllib3.egg-info
> writing dependency_links to urllib3.egg-info/dependency_links.txt
> writing top-level names to urllib3.egg-info/top_level.txt
> writing urllib3.egg-info/PKG-INFO
> writing requirements to urllib3.egg-info/requires.txt
> writing manifest file 'urllib3.egg-info/SOURCES.txt'
> reading manifest file 'urllib3.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> warning: no previously-included files matching '*' found under directory 'docs/_build'
> writing manifest file 'urllib3.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_py
> creating build
> creating build/lib
> creating build/lib/urllib3
> copying urllib3/__init__.py -> build/lib/urllib3
> copying urllib3/_collections.py -> build/lib/urllib3
> copying urllib3/connection.py -> build/lib/urllib3
> copying urllib3/connectionpool.py -> build/lib/urllib3
> copying urllib3/exceptions.py -> build/lib/urllib3
> copying urllib3/fields.py -> build/lib/urllib3
> copying urllib3/filepost.py -> build/lib/urllib3
> copying urllib3/poolmanager.py -> build/lib/urllib3
> copying urllib3/request.py -> build/lib/urllib3
> copying urllib3/response.py -> build/lib/urllib3
> creating build/lib/urllib3/packages
> copying urllib3/packages/__init__.py -> build/lib/urllib3/packages
> copying urllib3/packages/ordered_dict.py -> build/lib/urllib3/packages
> copying urllib3/packages/six.py -> build/lib/urllib3/packages
> creating build/lib/urllib3/packages/ssl_match_hostname
> copying urllib3/packages/ssl_match_hostname/__init__.py -> build/lib/urllib3/packages/ssl_match_hostname
> copying urllib3/packages/ssl_match_hostname/_implementation.py -> build/lib/urllib3/packages/ssl_match_hostname
> creating build/lib/urllib3/packages/backports
> copying urllib3/packages/backports/__init__.py -> build/lib/urllib3/packages/backports
> copying urllib3/packages/backports/makefile.py -> build/lib/urllib3/packages/backports
> creating build/lib/urllib3/contrib
> copying urllib3/contrib/__init__.py -> build/lib/urllib3/contrib
> copying urllib3/contrib/appengine.py -> build/lib/urllib3/contrib
> copying urllib3/contrib/ntlmpool.py -> build/lib/urllib3/contrib
> copying urllib3/contrib/pyopenssl.py -> build/lib/urllib3/contrib
> copying urllib3/contrib/securetransport.py -> build/lib/urllib3/contrib
> copying urllib3/contrib/socks.py -> build/lib/urllib3/contrib
> creating build/lib/urllib3/contrib/_securetransport
> copying urllib3/contrib/_securetransport/__init__.py -> build/lib/urllib3/contrib/_securetransport
> copying urllib3/contrib/_securetransport/bindings.py -> build/lib/urllib3/contrib/_securetransport
> copying urllib3/contrib/_securetransport/low_level.py -> build/lib/urllib3/contrib/_securetransport
> creating build/lib/urllib3/util
> copying urllib3/util/__init__.py -> build/lib/urllib3/util
> copying urllib3/util/connection.py -> build/lib/urllib3/util
> copying urllib3/util/queue.py -> build/lib/urllib3/util
> copying urllib3/util/request.py -> build/lib/urllib3/util
> copying urllib3/util/response.py -> build/lib/urllib3/util
> copying urllib3/util/retry.py -> build/lib/urllib3/util
> copying urllib3/util/ssl_.py -> build/lib/urllib3/util
> copying urllib3/util/timeout.py -> build/lib/urllib3/util
> copying urllib3/util/url.py -> build/lib/urllib3/util
> copying urllib3/util/wait.py -> build/lib/urllib3/util
> creating build/bdist.linux-x86_64
> creating build/bdist.linux-x86_64/egg
> creating build/bdist.linux-x86_64/egg/urllib3
> copying build/lib/urllib3/__init__.py -> build/bdist.linux-x86_64/egg/urllib3
> copying build/lib/urllib3/_collections.py -> build/bdist.linux-x86_64/egg/urllib3
> copying build/lib/urllib3/connection.py -> build/bdist.linux-x86_64/egg/urllib3
> copying build/lib/urllib3/connectionpool.py -> build/bdist.linux-x86_64/egg/urllib3
> copying build/lib/urllib3/exceptions.py -> build/bdist.linux-x86_64/egg/urllib3
> copying build/lib/urllib3/fields.py -> build/bdist.linux-x86_64/egg/urllib3
> copying build/lib/urllib3/filepost.py -> build/bdist.linux-x86_64/egg/urllib3
> copying build/lib/urllib3/poolmanager.py -> build/bdist.linux-x86_64/egg/urllib3
> copying build/lib/urllib3/request.py -> build/bdist.linux-x86_64/egg/urllib3
> copying build/lib/urllib3/response.py -> build/bdist.linux-x86_64/egg/urllib3
> creating build/bdist.linux-x86_64/egg/urllib3/packages
> copying build/lib/urllib3/packages/__init__.py -> build/bdist.linux-x86_64/egg/urllib3/packages
> copying build/lib/urllib3/packages/ordered_dict.py -> build/bdist.linux-x86_64/egg/urllib3/packages
> copying build/lib/urllib3/packages/six.py -> build/bdist.linux-x86_64/egg/urllib3/packages
> creating build/bdist.linux-x86_64/egg/urllib3/packages/ssl_match_hostname
> copying build/lib/urllib3/packages/ssl_match_hostname/__init__.py -> build/bdist.linux-x86_64/egg/urllib3/packages/ssl_match_hostname
> copying build/lib/urllib3/packages/ssl_match_hostname/_implementation.py -> build/bdist.linux-x86_64/egg/urllib3/packages/ssl_match_hostname
> creating build/bdist.linux-x86_64/egg/urllib3/packages/backports
> copying build/lib/urllib3/packages/backports/__init__.py -> build/bdist.linux-x86_64/egg/urllib3/packages/backports
> copying build/lib/urllib3/packages/backports/makefile.py -> build/bdist.linux-x86_64/egg/urllib3/packages/backports
> creating build/bdist.linux-x86_64/egg/urllib3/contrib
> copying build/lib/urllib3/contrib/__init__.py -> build/bdist.linux-x86_64/egg/urllib3/contrib
> copying build/lib/urllib3/contrib/appengine.py -> build/bdist.linux-x86_64/egg/urllib3/contrib
> copying build/lib/urllib3/contrib/ntlmpool.py -> build/bdist.linux-x86_64/egg/urllib3/contrib
> copying build/lib/urllib3/contrib/pyopenssl.py -> build/bdist.linux-x86_64/egg/urllib3/contrib
> copying build/lib/urllib3/contrib/securetransport.py -> build/bdist.linux-x86_64/egg/urllib3/contrib
> copying build/lib/urllib3/contrib/socks.py -> build/bdist.linux-x86_64/egg/urllib3/contrib
> creating build/bdist.linux-x86_64/egg/urllib3/contrib/_securetransport
> copying build/lib/urllib3/contrib/_securetransport/__init__.py -> build/bdist.linux-x86_64/egg/urllib3/contrib/_securetransport
> copying build/lib/urllib3/contrib/_securetransport/bindings.py -> build/bdist.linux-x86_64/egg/urllib3/contrib/_securetransport
> copying build/lib/urllib3/contrib/_securetransport/low_level.py -> build/bdist.linux-x86_64/egg/urllib3/contrib/_securetransport
> creating build/bdist.linux-x86_64/egg/urllib3/util
> copying build/lib/urllib3/util/__init__.py -> build/bdist.linux-x86_64/egg/urllib3/util
> copying build/lib/urllib3/util/connection.py -> build/bdist.linux-x86_64/egg/urllib3/util
> copying build/lib/urllib3/util/queue.py -> build/bdist.linux-x86_64/egg/urllib3/util
> copying build/lib/urllib3/util/request.py -> build/bdist.linux-x86_64/egg/urllib3/util
> copying build/lib/urllib3/util/response.py -> build/bdist.linux-x86_64/egg/urllib3/util
> copying build/lib/urllib3/util/retry.py -> build/bdist.linux-x86_64/egg/urllib3/util
> copying build/lib/urllib3/util/ssl_.py -> build/bdist.linux-x86_64/egg/urllib3/util
> copying build/lib/urllib3/util/timeout.py -> build/bdist.linux-x86_64/egg/urllib3/util
> copying build/lib/urllib3/util/url.py -> build/bdist.linux-x86_64/egg/urllib3/util
> copying build/lib/urllib3/util/wait.py -> build/bdist.linux-x86_64/egg/urllib3/util
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/__init__.py to __init__.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/_collections.py to _collections.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/connection.py to connection.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/connectionpool.py to connectionpool.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/exceptions.py to exceptions.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/fields.py to fields.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/filepost.py to filepost.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/poolmanager.py to poolmanager.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/request.py to request.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/response.py to response.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/packages/__init__.py to __init__.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/packages/ordered_dict.py to ordered_dict.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/packages/six.py to six.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/packages/ssl_match_hostname/__init__.py to __init__.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/packages/ssl_match_hostname/_implementation.py to _implementation.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/packages/backports/__init__.py to __init__.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/packages/backports/makefile.py to makefile.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/contrib/__init__.py to __init__.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/contrib/appengine.py to appengine.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/contrib/ntlmpool.py to ntlmpool.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/contrib/pyopenssl.py to pyopenssl.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/contrib/securetransport.py to securetransport.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/contrib/socks.py to socks.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/contrib/_securetransport/__init__.py to __init__.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/contrib/_securetransport/bindings.py to bindings.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/contrib/_securetransport/low_level.py to low_level.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/util/__init__.py to __init__.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/util/connection.py to connection.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/util/queue.py to queue.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/util/request.py to request.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/util/response.py to response.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/util/retry.py to retry.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/util/ssl_.py to ssl_.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/util/timeout.py to timeout.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/util/url.py to url.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/util/wait.py to wait.cpython-35.pyc
> creating build/bdist.linux-x86_64/egg/EGG-INFO
> copying urllib3.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying urllib3.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying urllib3.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying urllib3.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying urllib3.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> zip_safe flag not set; analyzing archive contents...
> urllib3.packages.__pycache__.six.cpython-35: module references __path__
> creating dist
> creating 'dist/urllib3-dev-py3.5.egg' and adding 'build/bdist.linux-x86_64/egg' to it
> removing 'build/bdist.linux-x86_64/egg' (and everything under it)
> Processing urllib3-dev-py3.5.egg
> removing '/home/kult/apps/ingestion/lib/python3.5/site-packages/urllib3-dev-py3.5.egg' (and everything under it)
> creating /home/kult/apps/ingestion/lib/python3.5/site-packages/urllib3-dev-py3.5.egg
> Extracting urllib3-dev-py3.5.egg to /home/kult/apps/ingestion/lib/python3.5/site-packages
> urllib3 dev is already the active version in easy-install.pth
> 
> Installed /home/kult/apps/ingestion/lib/python3.5/site-packages/urllib3-dev-py3.5.egg
> Processing dependencies for urllib3===dev
> Finished processing dependencies for urllib3===dev

```
$ python
Python 3.5.1 (default, Sep 15 2016, 08:30:32)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib3
>>> urllib3.__version__
'dev'
>>>
```

Best regards,
Albert.

**Comment by nateprewitt** [comment]
Hi @AlKult, if your zip file contains urllib3 as a git repository, you should be able to navigate to any tag via `git checkout <tag>` (e.g. `git checkout 1.23`). This will have a `__version__` assigned in `__init__.py`.

If you do not have a copy of the git repository, you'll want to download a copy of a released version. You can do this similarly by navigating to "tags" tab under the "branch" dropdown on the UI. Then download a copy.

If all else fails, you can modify the [`__version__`](https://github.com/urllib3/urllib3/blob/6be637268931e100b0d2d15cecd5524323fd4f36/urllib3/__init__.py#L34) yourself to the nearest version. Just realize this version won't be supportable since the urllib3 maintainers won't have context on what version you're actually using.

**Comment by AlKult** [comment]
Hi @nateprewitt! Thanks for the prompt response!
I don't have git on this machine either. I'm on a server wherein almost nothing is installed, therefore I have to operate in this unusual circumstances.
I downloaded the master zip just this morning, therefore I'd think it's 1.23 that I have here.
I've just manually modified urllib3/__init__.py and re-installed the package. It seems to have registered correctly at this time. Not sure how to treat this though. Is it just a one-off issue or something that devs need to further look into?

> $ grep \_\_version\_\_ ./urllib3/__init__.py
> \_\_version\_\_ = '1.23'

> $ python setup.py install
> running install
> running bdist_egg
> running egg_info
> writing top-level names to urllib3.egg-info/top_level.txt
> writing urllib3.egg-info/PKG-INFO
> writing requirements to urllib3.egg-info/requires.txt
> writing dependency_links to urllib3.egg-info/dependency_links.txt
> reading manifest file 'urllib3.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> warning: no previously-included files matching '*' found under directory 'docs/_build'
> writing manifest file 'urllib3.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_py
> copying urllib3/__init__.py -> build/lib/urllib3
> creating build/bdist.linux-x86_64/egg
> creating build/bdist.linux-x86_64/egg/urllib3
> copying build/lib/urllib3/_collections.py -> build/bdist.linux-x86_64/egg/urllib3
> copying build/lib/urllib3/connection.py -> build/bdist.linux-x86_64/egg/urllib3
> copying build/lib/urllib3/connectionpool.py -> build/bdist.linux-x86_64/egg/urllib3
> copying build/lib/urllib3/exceptions.py -> build/bdist.linux-x86_64/egg/urllib3
> copying build/lib/urllib3/fields.py -> build/bdist.linux-x86_64/egg/urllib3
> copying build/lib/urllib3/filepost.py -> build/bdist.linux-x86_64/egg/urllib3
> copying build/lib/urllib3/poolmanager.py -> build/bdist.linux-x86_64/egg/urllib3
> copying build/lib/urllib3/request.py -> build/bdist.linux-x86_64/egg/urllib3
> copying build/lib/urllib3/response.py -> build/bdist.linux-x86_64/egg/urllib3
> creating build/bdist.linux-x86_64/egg/urllib3/packages
> copying build/lib/urllib3/packages/__init__.py -> build/bdist.linux-x86_64/egg/urllib3/packages
> copying build/lib/urllib3/packages/ordered_dict.py -> build/bdist.linux-x86_64/egg/urllib3/packages
> copying build/lib/urllib3/packages/six.py -> build/bdist.linux-x86_64/egg/urllib3/packages
> creating build/bdist.linux-x86_64/egg/urllib3/packages/ssl_match_hostname
> copying build/lib/urllib3/packages/ssl_match_hostname/__init__.py -> build/bdist.linux-x86_64/egg/urllib3/packages/ssl_match_hostname
> copying build/lib/urllib3/packages/ssl_match_hostname/_implementation.py -> build/bdist.linux-x86_64/egg/urllib3/packages/ssl_match_hostname
> creating build/bdist.linux-x86_64/egg/urllib3/packages/backports
> copying build/lib/urllib3/packages/backports/__init__.py -> build/bdist.linux-x86_64/egg/urllib3/packages/backports
> copying build/lib/urllib3/packages/backports/makefile.py -> build/bdist.linux-x86_64/egg/urllib3/packages/backports
> creating build/bdist.linux-x86_64/egg/urllib3/contrib
> copying build/lib/urllib3/contrib/__init__.py -> build/bdist.linux-x86_64/egg/urllib3/contrib
> copying build/lib/urllib3/contrib/appengine.py -> build/bdist.linux-x86_64/egg/urllib3/contrib
> copying build/lib/urllib3/contrib/ntlmpool.py -> build/bdist.linux-x86_64/egg/urllib3/contrib
> copying build/lib/urllib3/contrib/pyopenssl.py -> build/bdist.linux-x86_64/egg/urllib3/contrib
> copying build/lib/urllib3/contrib/securetransport.py -> build/bdist.linux-x86_64/egg/urllib3/contrib
> copying build/lib/urllib3/contrib/socks.py -> build/bdist.linux-x86_64/egg/urllib3/contrib
> creating build/bdist.linux-x86_64/egg/urllib3/contrib/_securetransport
> copying build/lib/urllib3/contrib/_securetransport/__init__.py -> build/bdist.linux-x86_64/egg/urllib3/contrib/_securetransport
> copying build/lib/urllib3/contrib/_securetransport/bindings.py -> build/bdist.linux-x86_64/egg/urllib3/contrib/_securetransport
> copying build/lib/urllib3/contrib/_securetransport/low_level.py -> build/bdist.linux-x86_64/egg/urllib3/contrib/_securetransport
> creating build/bdist.linux-x86_64/egg/urllib3/util
> copying build/lib/urllib3/util/__init__.py -> build/bdist.linux-x86_64/egg/urllib3/util
> copying build/lib/urllib3/util/connection.py -> build/bdist.linux-x86_64/egg/urllib3/util
> copying build/lib/urllib3/util/queue.py -> build/bdist.linux-x86_64/egg/urllib3/util
> copying build/lib/urllib3/util/request.py -> build/bdist.linux-x86_64/egg/urllib3/util
> copying build/lib/urllib3/util/response.py -> build/bdist.linux-x86_64/egg/urllib3/util
> copying build/lib/urllib3/util/retry.py -> build/bdist.linux-x86_64/egg/urllib3/util
> copying build/lib/urllib3/util/ssl_.py -> build/bdist.linux-x86_64/egg/urllib3/util
> copying build/lib/urllib3/util/timeout.py -> build/bdist.linux-x86_64/egg/urllib3/util
> copying build/lib/urllib3/util/url.py -> build/bdist.linux-x86_64/egg/urllib3/util
> copying build/lib/urllib3/util/wait.py -> build/bdist.linux-x86_64/egg/urllib3/util
> copying build/lib/urllib3/__init__.py -> build/bdist.linux-x86_64/egg/urllib3
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/_collections.py to _collections.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/connection.py to connection.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/connectionpool.py to connectionpool.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/exceptions.py to exceptions.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/fields.py to fields.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/filepost.py to filepost.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/poolmanager.py to poolmanager.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/request.py to request.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/response.py to response.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/packages/__init__.py to __init__.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/packages/ordered_dict.py to ordered_dict.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/packages/six.py to six.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/packages/ssl_match_hostname/__init__.py to __init__.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/packages/ssl_match_hostname/_implementation.py to _implementation.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/packages/backports/__init__.py to __init__.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/packages/backports/makefile.py to makefile.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/contrib/__init__.py to __init__.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/contrib/appengine.py to appengine.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/contrib/ntlmpool.py to ntlmpool.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/contrib/pyopenssl.py to pyopenssl.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/contrib/securetransport.py to securetransport.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/contrib/socks.py to socks.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/contrib/_securetransport/__init__.py to __init__.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/contrib/_securetransport/bindings.py to bindings.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/contrib/_securetransport/low_level.py to low_level.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/util/__init__.py to __init__.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/util/connection.py to connection.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/util/queue.py to queue.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/util/request.py to request.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/util/response.py to response.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/util/retry.py to retry.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/util/ssl_.py to ssl_.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/util/timeout.py to timeout.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/util/url.py to url.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/util/wait.py to wait.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/urllib3/__init__.py to __init__.cpython-35.pyc
> creating build/bdist.linux-x86_64/egg/EGG-INFO
> copying urllib3.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying urllib3.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying urllib3.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying urllib3.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying urllib3.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> zip_safe flag not set; analyzing archive contents...
> urllib3.packages.__pycache__.six.cpython-35: module references __path__
> creating 'dist/urllib3-1.23-py3.5.egg' and adding 'build/bdist.linux-x86_64/egg' to it
> removing 'build/bdist.linux-x86_64/egg' (and everything under it)
> Processing urllib3-1.23-py3.5.egg
> creating /home/kult/apps/ingestion/lib/python3.5/site-packages/urllib3-1.23-py3.5.egg
> Extracting urllib3-1.23-py3.5.egg to /home/kult/apps/ingestion/lib/python3.5/site-packages
> Removing urllib3 dev from easy-install.pth file
> Adding urllib3 1.23 to easy-install.pth file
> 
> Installed /home/kult/apps/ingestion/lib/python3.5/site-packages/urllib3-1.23-py3.5.egg
> Processing dependencies for urllib3==1.23
> Finished processing dependencies for urllib3==1.23

```
$ python
Python 3.5.1 (default, Sep 15 2016, 08:30:32)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib3
>>> urllib3.__version__
'1.23'
```

Best regards,
Albert.

**Comment by theacodes** [comment]
It's a pretty niche issue, in my opinion. There are *several* ways to get what you want here:

1. Use git and checkout a specific tag.
2. Use github and download a specific release that corresponds to a tag.
3. Use PyPI and download a `tar.gz` or `whl` that corresponds to a release.

`HEAD` on `master` will always be `dev` and that's intentional. It prevents users actually installing urllib3 from `HEAD` and thinking it's some other released version.

I'm going to go ahead and close this, but happy to keep chatting if you need more help! :)
