### ISSUE TITLE
review request data

### ISSUE THREAD

**Issue by jfindlay** [urllib3/urllib3#1402]
I propose a feature that allows the user to retrieve/review a request object before it is sent similar to [this](https://stackoverflow.com/questions/20658572/python-requests-print-entire-http-request-raw) requests [feature](http://docs.python-requests.org/en/v1.2.3/user/advanced/#prepared-requests).  I have spent some time trying to find a way to do this by:
- reading the documentation
- inspecting urllib3 objects in the python interpreter
- searching the general intarwebz
- searching open issues

This feature could be useful at least for debugging issues with flippant remote servers where it is important to know exactly what headers are sent or how the body is formatted.

I have not yet started looking through the code.  I welcome any advice or direction on how to best phrase this feature request or what the solution should look like or even if I am completely wrong and this is already possible (if so, please tell me :-) ).

**Comment by SethMichaelLarson** [comment]
Unfortunately urllib3's interface is very much married to Pythons urllib interface which doesn't have an idea of a Request "object" which makes it tough to be able to do this without substantial changes.
