### ISSUE TITLE
assert_hostname with non-standard ports is problematic

### ISSUE THREAD

**Issue by JohnOmernik** [urllib3/urllib3#1411]
When using assert_hostname to pass a hostname for SSL verification, if the initial URL containers a non-standard port, there is not a sane way keep connecting to that port and get SSL verification. There is a detailed outline below, however, the TL;DR summary is I am working with a a DNS load balanced server farm, and am trying to "pin" connects to IP in connection. I.e. do a DNS lookup and then connect to only one IP.  The certificates have the DNS name, so the IP address connection doesn't all SSL verification.  The requests toolbelt module eposes an adapter that allows me to use the assert_hostname in urllib3.  This should allow me to connect to an IP address, but specify that a Host name (using hostheaders in request toolbelts) to use as my hostname. 

However, 

if myname.domain becomes 192.168.0.5 and I am using a non standard port, then if I set

https://192.168.0.5:20005 as my connection url, and then use myname.domain as the Hostheader, it I get an error about connection refused to port 443. (It used the default scheme port of 443 instead of port 20005 on the connection URL. 

If I use https://192.168.0.5:20005 as the connection URL, and then myname.domain:20005 as the Hostheader (the assert_hostname) then it makes a connection but myname.domain:20005 doesn't match myname.domain and I get an SSLerror. 

The full details and example usage/code is below in the issue.md.  

While I have an issue both here and in requests toolbelt, I believe the issue to be in urllib3 because all requests toolbelt is doing is calling the assert_hostname. 

Thanks!

John

Detailed Summary of issue: https://github.com/JohnOmernik/jupyter_drill/blob/master/issue.md

Related Issue in requests toolbelt: https://github.com/requests/toolbelt/issues/189

**Comment by SethMichaelLarson** [comment]
Could you post a minimum-verifiable example using only urllib3 as well as a traceback and the HTTP redirect you're receiving when connecting to `myname.domain` to help us diagnose this issue?

Thanks!

**Comment by JohnOmernik** [comment]
So, let me first say that Python at the level of urllib3 is over my head.  Part of the reason I use requests is how much it simplifies things. But in the spirit of open source, I tried to dig into this problem.   I used the test scripts for the asset_hostname, and found that everything, from a test perspective worked as expected. 

My challenge is this:  I tried to follow what requests is doing from a Poolmanager perspective. (This is not represented in the assert_hostname tests).   I honestly got lost, I could not follow the chain that goes from a requests session, to the HTTPHostheader adapter in requests.toolbelt, to what is happening under the hood when a pool manager is created. 

My gut is pointing at an issue when urllib3 pool manager checks to see if a pool item exists based on scheme, host, and port, and assert_hostname was triggered, it doesn't see it, so it, so recreates another pool entry. 

(BTW, this is all in :
https://github.com/urllib3/urllib3/blob/db444ec77836ef1e6aa129bc3507f8e838f1ceb6/urllib3/poolmanager.py)

It uses def _default_key_normalizer(key_class, request_context): on line 57, and in that, it creates a pool item, but only uses host and scheme. (This function doesn't seem to create items based on port) (note lines 79 and 80, while port is part of the tuple, only host and scheme are used here).   But then I realized it's just normalizing (lower casing) the scheme and the host, and since the port is in INT it doesn't do reference that. 

I guess at this point I am lost. I am not trying to deflect work, I've spent hours on this, however, what is happening here is quite over my head.  In the name of completeness, I will likely post this to the requests issues as well.

**Comment by SethMichaelLarson** [comment]
So I may have figured out what your problem is? You're passing the hostname + port combination to the `Host` header but that passes that whole thing to the `assert_hostname` parameter.  You probably shouldn't pass a hostname+port combo to `assert_hostname`, should only be the hostname.

The port needs to be a part of the `url` being used within [`session.post()`](https://github.com/JohnOmernik/jupyter_drill/blob/master/drill_core/drill_base.py#L241).

Sorry if I'm misunderstanding your code, I only took a brief look at the logic and parts I thought were important. Really it would be nice to pick out the necessary parts even if those necessary parts are using requests-toolbelt.

**Comment by JohnOmernik** [comment]
In one test, I did that, because when I only pass the hostname to port, and
the url has IP:port, then the port some how reverts to 443.

**Comment by SethMichaelLarson** [comment]
Could you provide the code doing that along with the HTTP responses you're getting from your server so I can reproduce with httpbin?

**Comment by JohnOmernik** [comment]
Every thing I was able to reproduce is in the issue.md link above.  I tried
to do it with just urllib3 but struggled to replicate exactly what requests
was doing.   Let me know if the issues.md provides enough info ,.if not I
am happy to dig in a different direction but I may need some coaching a
spent hours trying to trace from requests, to urllib3

**Comment by SethMichaelLarson** [comment]
I'm not going to run or read that large amount of code. The most important things that I need to reproduce your issue aren't included in that write-up which are all the HTTP responses (headers and status codes) from your website. Without those I won't be able to help you. You don't need to use urllib3, I just need those responses and the places in your code where you use requests or requests-toolbelt.

**Comment by JohnOmernik** [comment]
@SethMichaelLarson 

Thanks for your insight and prodding.  I tried with just URLLIB3 and couldn't reproduce. I tried with requests and couldn't reproduce.  I was stumped. I was hoping to give a nice chunk of requests only code that showed the problem. 

This made me dig further.  I realized my mistake, I was providing dummy authentication information thinking it didn't matter. However by default, requests follows redirects.  My web server (Apache Drill) on a bad username and password, just provides a single page back.  On success, it does a 303 redirect to a different page, and that's where the issue lies!

I have solved the issue by passing allow_redirects=False in the session.post request. 

The issue is as such: When I make a connection to https://192.168.0.103:20004 but change the host header (as per how requests_toolbelt updates the host used for cert auth, the webserver sees this hostheader, and assumes that the hostheader is the name to include in the 303 redirect.   Since the host header has no port that's what breaks. Essentially, we need a way to provide the host without using the host header.... I am not sure if that is a urllib3 issue, requests issue, or requests toolbelt issue. 

Instead of putting in names or IPs, I will just use the word name and ip

> post('https://ip:port/', headers={'host':'name'])
< HTTP 303 redirect to https://name
> get('https://name:443/')
< Error

**Comment by SethMichaelLarson** [comment]
I had a feeling it had to do with the redirect. :) If your server returned a port number in it's `Location` header it would work properly. Without that port number we assume the standardized HTTPS port number which is 443.

**Comment by JohnOmernik** [comment]
Yep, and I just got word from requests group that they have absolved
urllib3 (as they implement their own redirect logic).  So this one can be
closed  Sorry for the crazy cross posting and I really appreciate the
gentle nudges in the right direction for troubleshooting. I learned tons
here!

**Comment by SethMichaelLarson** [comment]
I'm glad to hear that! :) Good luck with your issue, thanks!
