### ISSUE TITLE
Why the response headers encoding is inconsistent?

### ISSUE THREAD

**Issue by scccboom** [urllib3/urllib3#1416]
* Server
  - Response headers add Content-Disposition=attachment;filename=xxx
  - xxx is not ASCII code, response encoding is utf-8.
* Client:
  - Use urllib response headers Content-Disposition value is base64 string. Decode base64 value is utf-8 encoding bytes, xxx is messy code.
  - Use urllib3 Content-Disposition value is utf-8 string, but xxx is raw_unicode_escape string encode to utf-8.

**Comment by SethMichaelLarson** [comment]
Could you give some more information, specifically code and raw response bytes that you're seeing from the server?

**Comment by SethMichaelLarson** [comment]
I'm guessing that because the filename is UTF-8 and not encoded we're unable to decode it. The filename should not be UTF-8 for highest inter-operability.

**Comment by scccboom** [comment]
Yes, you're right. I urlencode filename on the server. thx!
