### ISSUE TITLE
"idna.core.IDNAError: Empty domain" occurring in getting values for x509.DNSName

### ISSUE THREAD

**Issue by bharathkallurs** [urllib3/urllib3#1421]
In the function call _dnsname_to_stdlib we use name for getting the idna_encoded string. The call happens for name in ext.get_values_for_type(x509.DNSName) in line 228 under the function get_subj_alt_name. If we do not have any X509.DNSName, we hit idna.core.IDNAError.

I guess it is good to check if name is not None and then pass it to _dnsname_to_stdlib. I tried with this fix and it seems to be working fine.

lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 228, in get_subj_alt_name
for name in ext.get_values_for_type(x509.DNSName)

lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 181, in _dnsname_to_stdlib
name = idna_encode(name)
/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 179, in idna_encode
return idna.encode(name)
lib/python2.7/site-packages/idna/core.py", line 356, in encode
raise IDNAError('Empty domain')
idna.core.IDNAError: Empty domain

Fix to be added will be:
names = [ ('DNS', _dnsname_to_stdlib(name)) for name in ext.get_values_for_type(x509.DNSName) if name ]

**Comment by SethMichaelLarson** [comment]
That sounds like a pretty reasonable enhancement, would you be comfortable submitting a PR along with a test to fix this issue?

**Comment by bharathkallurs** [comment]
I can do that. Sorry for the delay but caught up with some other issue on a different library.
Will be sending the PR max by this weekend.

**Comment by bharathkallurs** [comment]
Seth, I see the fix is already in. I just pulled the repo and found it to be fixed. May I know when the version will be upgraded? Any cadence doc that I can refer to?

**Comment by SethMichaelLarson** [comment]
There's been some discussion about revising our release process in issue 1392 to allow for more frequent releases. I might have to take up that issue so we can get towards releasing our nice fixes more often. :)
