### ISSUE TITLE
Fix test_client_no_intermediate flakiness

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#1422]
There are two issues with test_client_no_intermediate: first, the certificates involved here are refused by SecureTransport in macOS 10.13+, and second, the test_client_no_intermediate test is flaky. https://github.com/urllib3/urllib3/issues/1419 was filed for the first problem, and this one is about the flakiness. Here is what test_client_no_intermediate and test_client_intermediate do.

In the test_client_intermediate test, the client connects to the server using SSL but without performing any verification (which is urllib3's default: http://urllib3.readthedocs.io/en/latest/user-guide.html#certificate-verification). However, it sends a certificate, a client certificate, so that the server can verify the client. (Usually, this is done the other way around: the client verifies the server.)

How is this client certificate set up? The root CA (cacert.pem) signed an intermediate CA (the second one in client_intermediate.pem) which signed a leaf certificate (the first one in client_intermediate.pem). The tornado server is configured with the root CA (DEFAULT_CERTS in dummyserver/server.py). The client requests the /certificate endpoint (TestingApp.certificate in dummyserver.py), which returns the client certificate using getpeercert().

If the certificate chain was configured correctly, the server will be able to return the client certificate data. If the intermediate CA is missing, as is the case in test_client_no_intermediate, it's going to fail with an error like "invalid certificate chain". However, in some cases, the failure is different. With SecureTransport, it could be [errSSLClosedAbort](https://developer.apple.com/documentation/security/1503828-secure_transport_result_codes/errsslclosedabort), for example. When looking at https://opensource.apple.com/source/Security/Security-58286.41.2/, it looks like this can happen when the connection on the server side was closed instead of returning the actual error?

However, I don't think trying to understand every possible error case is useful here: what's important is that test_client_intermediate succeeds and test_client_no_intermediate fails, and that the only difference between those tests is a missing intermediate CA.

@SethMichaelLarson Would you accept a patch that accepts any failure in test_client_no_intermediate?

**Comment by SethMichaelLarson** [comment]
The reason I'm not a fan of patching the test to accept any failure is that the test is supposed to be testing a very exact code path (The one you described) and by making the test less specific about the error message we're allowing other code paths to be marked as a "pass" potentially leaving the code path we really care about behind.

However, if you can find something that indicates that `errSSLClosedAbort` can be raised when certificate validation fails I'd accept a patch with such a change.

**Comment by njsmith** [comment]
Isn't the only purpose of this test to double-check that Tornado is actually validating client certificates, so that when `test_client_intermediate` passes we can be confident that it's because we actually sent a valid cert chain, rather than some other fluke? Getting too hung up on the details of exactly how Tornado reports this error seems unnecessary given that this isn't the Tornado project test suite :-).

I dug around a bit in the `Security` docs and code, and there's really no clear indication of what `errSSLClosedAbort` is supposed to mean – it can be raised for issues during the handshake, or as a catchall for transport-level issues... but [this random github comment](https://github.com/couchbase/couchbase-lite-ios/issues/1408#issuecomment-240565630) claims that it can indicate a cert rejection during the handshake. And obviously in this case it *does* indicate a cert problem, we can be confident of that empirically, whatever else it might or might not be documented to mean :-).

**Comment by SethMichaelLarson** [comment]
That sounds like a good enough justification! I'd welcome a pull request that patches test_client_no_intermediate for errSSLClosedAbort :)

**Comment by pquentin** [comment]
An exception that Windows can raise in test_client_no_intermediate is `urllib3.exceptions.SSLError: ("bad handshake: SysCallError(10054, 'WSAECONNRESET')",)`: see https://ci.appveyor.com/project/pquentin/urllib3/build/1.0.115/job/0080swjpfmr96oxv. Just like errSSLClosedAbort, WSAECONNRESET appears to be a catchall for transport-level issues and [can be raised when the certificate is invalid](https://stackoverflow.com/questions/38761166/ssl-bad-handshake-error-10054-wsaeconnreset). I'll likely add this to the list of possible messages in the future.

(I would still prefer to accept any SSLError rather than trying to chase down every possible platform-dependant error message, but that's another debate!)

**Comment by pquentin** [comment]
Another one is `ProtocolError: ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host'))`: https://ci.appveyor.com/project/urllib3/urllib3/build/1.0.199/job/2cb6nfpv8up7t2ah
