### ISSUE TITLE
Timeout isinstance check fails if multiple higher level libs have a different class path

### ISSUE THREAD

**Issue by jhawkinson** [urllib3/urllib3#1426]
Hello,  I'm not sure if this is the right place for this or not, As this is a little bit out of my expertise.  So I have an application I'm developing which makes use of both the jira and docker libraries.  Both use requests which both call in to connectionpool.  

The problem I keep running into is that there are isinstance() checks for the Timeout object and if this check fails, the code assumes that it gets an int:

Here is the code I'm speaking about
   
```
 def _get_timeout(self, timeout):
         Helper that always returns a :class:
        if timeout is _Default:
            return self.timeout.clone()

        if isinstance(timeout, Timeout):
            return timeout.clone()
        else:
            # User passed us an int/float. This is for backwards compatibility,
            # can be removed later
            return Timeout.from_float(timeout)

```
The problem is that in this case while working through these two libraries the class path ends up being different

```
<class 'pip._vendor.requests.packages.urllib3.util.timeout.Timeout'>
<urllib3.util.timeout.Timeout object at 0x7efe059077f0>

```
So this isinstance check fails, and then the code assumes this is an int, and tries to set a Timeout object from float of another Timeout object.

For the time being I've just imported both docker and urllib3 to a private branch on my source tree and modified this isinstance check to a hasattr "clone" so I can keep working.

   
```
 def _get_timeout(self, timeout):
         Helper that always returns a :class:
        if timeout is _Default:
            return self.timeout.clone()

        if hasattr(timeout, clone):
            return timeout.clone()
        else:
            # User passed us an int/float. This is for backwards compatibility,
            # can be removed later
            return Timeout.from_float(timeout)

```
If you guys can tell me the proper way to handle this I'd rather go down that path.

Thanks in advance
-jhawk

**Comment by pquentin** [comment]
@jhawkinson Thanks for the detailed bug report!

See https://github.com/urllib3/urllib3/pull/1391 for a related discussion.

What version of pip and urllib3 are you using?

**Comment by jhawkinson** [comment]
@pquentin Thanks for the additional reading,  Does this mean I should just uninstall all other versions of urllib and requests, update them to the latest and try again?

I don't mind managing packages if that's what's required here.

**Comment by pquentin** [comment]
I honestly don't know, sorry! @sigmavirus24 should be able to help here.

**Comment by jhawkinson** [comment]
@pquentin At least I'm not the only one :)

I'll give it a shot anyways, I'll uninstall all jira, docker, requests, and urllib3 packages, install them at the latest version in order of dependency and see if that helps.  I have a feeling it's the way these things are imported in the children libraries is to blame though.

**Comment by jhawkinson** [comment]
@pquentin Deleting the wheels and upgrading/reinstalling everything worked out in this case :)

**Comment by SethMichaelLarson** [comment]
I'll close this issue for now. If you have additional troubles we can reopen
