### ISSUE TITLE
Any way to skip HeaderParsingError?

### ISSUE THREAD

**Issue by ghostku** [urllib3/urllib3#1433]
Hi
I'm trying to create a request to one site. 

    AUTH_URL = 'https://api.seller.rozetka.com.ua/sites'
    http = urllib3.PoolManager()
    r = http.request('GET', AUTH_URL)

But I get:

`DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.seller.rozetka.com.ua
C:\Users\ghost\Envs\priceman\lib\site-packages\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
DEBUG:urllib3.connectionpool:https://api.seller.rozetka.com.ua:443 "GET /sites HTTP/1.1" 200 None
WARNING:urllib3.connectionpool:Failed to parse headers (url=https://api.seller.rozetka.com.ua:443/sites): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Access-Control-Expose-Headers : X-Pagination-Current-Page\r\nAccess-Control-Expose-Headers : X-Pagination-Page-Count\r\nAccess-Control-Expose-Headers : X-Pagination-Per-Page\r\nAccess-Control-Expose-Headers : X-Pagination-Total-Count\r\n\r\n'
Traceback (most recent call last):
  File "C:\Users\ghost\Envs\priceman\lib\site-packages\urllib3\connectionpool.py", line 399, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "C:\Users\ghost\Envs\priceman\lib\site-packages\urllib3\util\response.py", line 66, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Access-Control-Expose-Headers : X-Pagination-Current-Page\r\nAccess-Control-Expose-Headers : X-Pagination-Page-Count\r\nAccess-Control-Expose-Headers : X-Pagination-Per-Page\r\nAccess-Control-Expose-Headers : X-Pagination-Total-Count\r\n\r\n'`

So as far as I understand server put spaces between name and semicolon in a header, and this is wrong according to RFC. But it is not my server and I can't fix it. Is there any way to suppress this error and get a response from the server (it should be JSON data)?

**Comment by SethMichaelLarson** [comment]
Historically there have been many security issues with accepting HTTP headers that have spaces in non-standard places so I think us parsing headers to spec is the proper thing to do. To allow this we'd have to replace httplib which is something a ways off for this project (I'll note the current candidate for replacing httplib is h11 which would also error on this header).

Unfortunately I'd say your best course of action is to contact the website owners. Sorry!

**Comment by pquentin** [comment]
@SethMichaelLarson 👍 

@ghostku You might find this related requests issue interesting: https://github.com/requests/requests/issues/3098
