### ISSUE TITLE
un-read POST data causes intermittent failure

### ISSUE THREAD

**Issue by mewalig** [urllib3/urllib3#1437]
I have two web components, call them SENDER and RECIPIENT. 

SENDER uses urllib3 to send a POST to RECIPIENT. RECIPIENT sends a response.

The problem is, if RECIPIENT does not bother to read the POST data from SENDER, then SENDER call will hang either on the first call, or if not, on a subsequent call if consecutive calls are made reasonably quickly (and hangs eventually fail via timeout, which is even worse than an immediate fail). More frustrating, the frequency of the hang seems to be impacted by i) the size of the POST, ii) the size of the data returned by RECIPIENT, and iii) the operating system. It probably also depends on the size of the connection pool, etc etc.

For example:

    http = urllib3.PoolManager(cert_reqs=cert_reqs)
    encoded_body, content_type = urllib3.filepost.encode_multipart_formdata(multipart_post)
    response = http.request('POST', url, body=encoded_body, preload_content=False, headers=headers)

The intermittent hang occurs in the last line, either on the first call, or after a few (maybe half a dozen) calls.

My guess is that when the POST data isn't read by RECIPIENT, the connection is not closing, and if the pool cycles through all connections fast enough, then none are left. However, it also seems to be related to the size of POST sent by SENDER _and_ the size of the response by RECIPIENT. Using a SENDER POST size of about 400-500k, if RECIPIENT's response is large enough, even the very first connection will hang-- apparently SENDER is waiting for its POST to get read before it will read any more incoming response. If RECIPIENT sends its data in small packets, initial packets will be sent until some point (in y tests, around 40k if running on Windows, and higher if running on OSX), at which time the SENDER will not read more data.

The workaround that I have found is to ensure that RECIPIENT always reads the entire POST message, if it is there, regardless of whether it wants to. This is obviously not an ideal solution since one does not always have control over RECIPIENT. Perhaps RECIPIENT should just reject POSTs that are not supported (instead of sending 40k of data back), but even if that happened, I'm not sure that the problem would go away-- maybe it would just raise the number of requests within the timeout period that are necessary for the problem to manifest.

Is there any way to ensure that urllib3 doesn't get thrown off track if it POSTs data that doesn't get read?

**Comment by SethMichaelLarson** [comment]
`encode_multipart_formdata` function uses twice as much memory as the amount of data being sent and doesn't perform well on streams of data as you'd expect. Could this be the root of the issue?

**Comment by mewalig** [comment]
I would not expect this to be related, though I haven't reviewed all of the related code enough to rule out that possibility. The reason I would not expect this to be related is that `encode_multipart_formdata` finishes, and yields `encoded_body`, before the request is made, so it should not impact the request. Furthermore, the resulting `encoded_body` doesn't even get read by the other side, so it really doesn't matter if `encode_multipart_formdata` messed up. Lastly, the problem frequency is related to the size of the POST, which suggests that whatever happens in one call is having some side effects that are impacting subsequent calls, and there is really no reason I can think of that `encode_multipart_formdata` would be affected by prior calls made to it (I haven't inspected the code behind `encode_multipart_formdata`, but it would seem to me to be a problem if it in fact had side effects between calls). 

What seems to be happening is that when the POST data isn't read, there is some side effect left over somewhere that needs to be cleared (e.g. some buffer holding the POST data needs to be reset to an empty status)
