### ISSUE TITLE
Content-Encoding with multiple encodings not supported

### ISSUE THREAD

**Issue by jbramleycl** [urllib3/urllib3#1441]
It is possible for a server to respond with a Content-Encoding header like:
`Content-Encoding: deflate, deflate`

From RFC7231:
> If one or more encodings have been applied to a representation, the
> sender that applied the encodings MUST generate a Content-Encoding
> header field that lists the content codings in the order in which
> they were applied.

This can be tested with:

```python
def test_multiple_content_encodings():
    data = zlib.compress(zlib.compress(b'foo'))
    fp = BytesIO(data)
    r = HTTPResponse(fp, headers={'Content-Encoding': 'deflate, deflate'})
    assert r.data == b'foo'
````

Would it make sense to do something like:
````python
if len(self.headers.get('content-encoding').split(',') > 1:
    self._decoder = MultiDecoder(self.headers.get('content-encoding'))
````
where MultiDecoder just iterates through the list applying standard decoders?

**Comment by SethMichaelLarson** [comment]
TIL that `Content-Encoding` allows for nested encodings. Do you have an example site that does this? We haven't hit this problem until now.

I'm open to a PR that implements this behavior.
