### ISSUE TITLE
Creating socket to check if IPv6 is enabled on AppEngine

### ISSUE THREAD

**Issue by apietrzak** [urllib3/urllib3#1446]
Module `urlib3/util/connection.py` executes `_has_ipv6` function while being imported. For checking if IPv6 is enabled this function is creating socket:

            sock = socket.socket(socket.AF_INET6)
            sock.bind((host, 0))
            has_ipv6 = True

From documentation: https://urllib3.readthedocs.io/en/latest/reference/urllib3.contrib.html using socket should be enabled only if `GAE_USE_SOCKETS_HTTPLIB` is set to `true`. So before calling that function there should be check if we want to use sockets on App Engine.

**Comment by theacodes** [comment]
@apietrzak I'm not sure I understand. Can you give me a bit more details? Does this cause failures? Does it incorrectly detect ipv6 support?

**Comment by apietrzak** [comment]
@theacodes 
On appengine you have a daily quota on creating sockets: https://cloud.google.com/appengine/quotas#Sockets 

As you can see in this documentation page:
https://urllib3.readthedocs.io/en/latest/reference/urllib3.contrib.html
there is a way to use urllib3 without sockets. For this purpose  an additional "pool manager" was created which is using URLfetch api:
```
from urllib3.contrib.appengine import AppEngineManager, is_appengine_sandbox
if is_appengine_sandbox():
    # AppEngineManager uses AppEngine's URLFetch API behind the scenes
    http = AppEngineManager()
else:
    # PoolManager uses a socket-level API behind the scenes
    http = PoolManager()

```

The code above always creates a socket. You can check it by adding for example `import pdb;pdb.set_trace()` to util/connections.py code. 
So, unfortunately for us, this is a bug. Additionaly this check is for each machine on app engine (Only import urllib3 runs the checking). App engine is a cloud service, so the machines frequently are spawned and killed.

Example code:
![image](https://user-images.githubusercontent.com/20789218/46474294-c7988d00-c7e2-11e8-8a6a-79059757ef06.png)
And logs:
![image](https://user-images.githubusercontent.com/20789218/46474319-dbdc8a00-c7e2-11e8-947c-dc3d67ad7908.png)

**Comment by theacodes** [comment]
Gotcha, that makes sense. Thank you for clarifying.

**Comment by theacodes** [comment]
I'm not sure if I can do anything here. We make a bit of a mistake in the interface here.

`HAS_IPV6` is a global constant in a public module that has existed for years. We can't make it lazy (because it's a global constant) and we can't really do anything in `contrib.appengine` to interrupt it, as the import for that module happens way before `contrib.appengine` has any say in the process.

We could figure out how to use some of the environment detection logic in `contrib.appengine` within `_is_ipv6()` to short-circuit the socket stuff. But it feels super gross.

**Comment by SethMichaelLarson** [comment]
Now if only we could have module-level `@property`s :)
