### ISSUE TITLE
Error decoding chunked response in _update_chunk_length

### ISSUE THREAD

**Issue by KonMann** [urllib3/urllib3#1452]
Error decoding chunked response in _update_chunk_length: ValueError: invalid literal for int() with base 16: b'HTTP/1.1 200 OK\r\n'
Originally a [Requests-Issue](https://github.com/requests/requests/issues/4248) 
Does the suggested fix, to check for the length, sound okay to you?
If so, I could just create a PR.

**Comment by SethMichaelLarson** [comment]
With proper unit tests I'd accept a PR with those changes.

**Comment by KonMann** [comment]
Actually on second thought, I think it is legit to throw an exception in this situation

**Comment by hixss** [comment]
We temporarily repaired it in this way. I wonder if there will be any problem.

  def _update_chunk_length(self):
        # First, we'll figure out length of a chunk and then
        # we'll try to read it from socket.
        if self.chunk_left is not None:
            return
        line = self._fp.fp.readline()
        line = line.split(b';', 1)[0]
        try:
            self.chunk_left = int(line, 16)
        except ValueError:
            # Invalid chunked protocol response, abort.
            # self.close()
            # raise httplib.IncompleteRead(line)
            self.chunk_left = 0

**Comment by hixss** [comment]
We temporarily repaired it in this way. I wonder if there will be any problem.


    def _update_chunk_length(self):
        # First, we'll figure out length of a chunk and then
        # we'll try to read it from socket.
        if self.chunk_left is not None:
            return
        line = self._fp.fp.readline()
        line = line.split(b';', 1)[0]
        try:
            if len(line) == 0:
                self.chunk_left = 0
            else:
                self.chunk_left = int(line, 16)
        except ValueError:
            # Invalid chunked protocol response, abort.
            self.close()
            raise httplib.IncompleteRead(line)

**Comment by KonMann** [comment]
I just thought it was fine to throw that exception when the connection was just closed and not data is left available. So this would need to be dealt with on a higher level (In this case requests).

**Comment by ddugovic** [comment]
Can a more meaningful exception/error be raised than `Error decoding chunked response in _update_chunk_length: ValueError: invalid literal for int() with base 16: b'HTTP/1.1 200 OK\r\n'`?

**Comment by sethmlarson** [comment]
So is this issue a bug or not? If it's a bug instead of changing the error message I'd rather fix the issue.

Are there any public facing websites that always trigger this issue or do you have an example chunked body that causes it?

**Comment by careless25** [comment]
We use this on Lichess (https://lichess.org/) and all Lichess Bots go down due to this: https://github.com/careless25/lichess-bot/issues/163
