### ISSUE TITLE
Shouldn't urllib3 verify SSL/TLS certificates by default ?

### ISSUE THREAD

**Issue by jerome-nexedi** [urllib3/urllib3#1454]
The README says:

> ... urllib3 brings many critical features that are missing from the Python standard libraries: 
> ...
> Client-side SSL/TLS verification.
> ...

and only in https://urllib3.readthedocs.io/en/latest/user-guide.html#certificate-verification it's explained that 

> By default, urllib3 does not verify HTTPS requests.

Because since [pep-0476](https://www.python.org/dev/peps/pep-0476) (ie python >= 2.7.9 or > 3.4 ) standard libraries verifies SSL certificates by default, nowadays projects switching from urllib2 or httplib to urllib3 without explicitly enabling certificate validation would loose the feature of certificate validation that was provided by standard library.

Of course, this would be an incompatible breaking change, like it was for python at the time, but is it really still a sane default to not verify certificates nowadays ?

**Comment by SethMichaelLarson** [comment]
I think if we were to "do-it-all-over" we'd have TLS verification on by default but to preserve backwards compatibility we'll probably keep the current behavior until v2. Currently a warning is emitted when using an `HTTPSConnection` without TLS verification.

**Comment by jerome-nexedi** [comment]
For the records, see https://github.com/SeleniumHQ/selenium/issues/6534 for a case where switching from httplib to urllib3 accidentally disabled certificate validation ( the change introducing the issue https://github.com/SeleniumHQ/selenium/commit/8d98f3223c3757bac24f779f5d8c1e9e1e8edcfb )

**Comment by theacodes** [comment]
I would personally be totally okay with us changing this behavior in a minor release (Python did it in a patch release, hilariously). I would want some level of consensus with the maintainers of this library and Requests.

**Comment by SethMichaelLarson** [comment]
Knowing Python did this change in a patch makes me feel more comfortable upgrading to verify by default. I have a feeling many of our downstreams already implement this anyways.

**Comment by nateprewitt** [comment]
@theacodes, I believe Requests already has verifying on by default, so I’m fully in support of this. I’m assuming this isn’t an api change beyond changing the default value for the function signature?

**Comment by theacodes** [comment]
Correct.

**Comment by SethMichaelLarson** [comment]
I'd say this is probably ready to go then :)
