### ISSUE TITLE
ImportError: No module named ordered_dict

### ISSUE THREAD

**Issue by william-silversmith** [urllib3/urllib3#1456]
Hi urllib3 team!

I was testing a release of my code on Python 2.7 and I got the following error with urllib3==1.24. It worked on 1.23. I saw that Python 2.6 is EOL, but I figure that means you're still supporting 2.7 for now. Here's my stack trace:

```
ImportError while importing test module '/usr/people/ws9/cloud-volume/test/test_chunks.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.virtualenvs/cv2/local/lib/python2.7/site-packages/six.py:709: in exec_
    exec("""exec _code_ in _globs_, _locs_""")
test/test_chunks.py:7: in <module>
    from cloudvolume.chunks import encode, decode
cloudvolume/__init__.py:1: in <module>
    from .connectionpools import ConnectionPool
cloudvolume/connectionpools.py:6: in <module>
    from google.cloud.storage import Client
../.virtualenvs/cv2/local/lib/python2.7/site-packages/google/cloud/storage/__init__.py:37: in <module>
    from google.cloud.storage.batch import Batch
../.virtualenvs/cv2/local/lib/python2.7/site-packages/google/cloud/storage/batch.py:26: in <module>
    import requests
../.virtualenvs/cv2/local/lib/python2.7/site-packages/requests/__init__.py:112: in <module>
    from . import utils
../.virtualenvs/cv2/local/lib/python2.7/site-packages/requests/utils.py:26: in <module>
    from ._internal_utils import to_native_string
../.virtualenvs/cv2/local/lib/python2.7/site-packages/requests/_internal_utils.py:11: in <module>
    from .compat import is_py2, builtin_str, str
../.virtualenvs/cv2/local/lib/python2.7/site-packages/requests/compat.py:48: in <module>
    from urllib3.packages.ordered_dict import OrderedDict
E   ImportError: No module named ordered_dict
```

Thanks! I'm working around this by using 1.23 for now so no big deal on my end.

**Comment by nateprewitt** [comment]
Hi @william-silversmith, I believe we have specific warnings in Requests stating that urllib3 is only supported up to 1.23.x and that’s also codified in our requirements for the 2.19.1 installer.

We’ll be doing a release within the next week that will resolve these kinds of issues, but until then Requests may not be compatible.

**Comment by william-silversmith** [comment]
Ah sorry for the false alarm then. Thanks for the tip!

**Comment by salvador-bynd** [comment]
Having the same kind of issue.

**Comment by oPromessa** [comment]
* Yup. Here to. Suddenly my travis-ci.org test environment with python 2.7.14 importing flickrapi 2.4.0 is facing this issue.
* With python 3.6.3 and  3.7.0a4+ problem seems not to occur.

**Comment by HadiCS** [comment]
> Having the same kind of issue.
> 
> One of my project dependencies "google-endpoints", depends on "Google Endpoints API Management", which depends on `requests` and `requests` depends on `urllib3`, however the installed `urllib3==1.24` is not supported by `requests`. 🐒
> 
> Enforcing the urllib3 version at the end of my `requirements.txt` file.
> `urllib3==1.23`

Experiencing the same issue with google-endpoints.

**Comment by asottile** [comment]
pip doesn't have proper dependency resolution so if you have a diamond dependency on `urllib3` then `requests`'s restriction will not be honored.  See (for example https://github.com/pypa/pip/issues/4391 https://github.com/pypa/pip/issues/988).  The workaround is to pin `urllib==...` or (more likely) wait for `requests` to follow suit and also drop python2.6

**Comment by nateprewitt** [comment]
Requests v2.20.0 has been released with support for urllib3 1.24

**Comment by SethMichaelLarson** [comment]
Thanks @nateprewitt :tada:

**Comment by Madpentiste** [comment]
I had the same issue, that prevented the menu item "Printers" (System>Administration>Printers) to launch. In a terminal, the command 
_$ printer-config-system_ 
would throw an error similar as above.

The problem was completely solved by issuing in a terminal 
_$ sudo pip install -U requests_

**Comment by skywallger** [comment]
I same problem and  solve it .

 Install  new lib requests . and upgrade urllib3 .
