### ISSUE TITLE
Failure: ImportError (cannot import name certs) ... ERROR

### ISSUE THREAD

**Issue by jacksonKhUA** [urllib3/urllib3#1459]
Hi Team,

I faced today with problem where on CI build was failed for my app
I have investigated problem a part of the day and found that new version urlib3 doesn't supports by requests module = 2.19.1.
So, some log for it:
requests 2.19.1 has requirement urllib3<1.24,>=1.21.1, but you'll have urllib3 1.24 which is incompatible.

So, pip has installed new version but, it doesn't supported, unfortunately.

I solved it with hardcoded version in my requirements.txt file and it works like a charm for now

May be it will help somebody.

Thanks, Evgeniy

**Comment by jacksonKhUA** [comment]
I think need to request support your new version from team who provided 'requests' lib

**Comment by nateprewitt** [comment]
requests/requests#4830
