### ISSUE TITLE
setup.py lacks appropriate metadata for differing python versions

### ISSUE THREAD

**Issue by colemickens** [urllib3/urllib3#1460]
Please see this issue for the full context: https://github.com/NixOS/nixpkgs/issues/46318

Basically, it appears the METADATA in the resulting installation differs depending on the installation method.

I've done some minimal patching to `setup.py` to include the same `python_version` constraints that appear in `setup.cfg` and it appears to fix the issues with regards to METADATA.

However, I'm not very experienced in python packaging and am surprised that no one else has run into this issue before me.

Can anyone confirm that there is a mismatch here and that adding additional constraints to `setup.py` would be appropriate? I'll go ahead and get a PR together in the meantime.

**Comment by SethMichaelLarson** [comment]
There definitely looks to be a discrepency between `setup.cfg` and `setup.py`. I will look into this more, thanks for reporting this.

**Comment by colemickens** [comment]
Any update? I can try my hand at a patch...

**Comment by SethMichaelLarson** [comment]
You're free to do so if you'd like. I'm saving this issue as part of a larger set of packaging updates I'm going to be working on.
