### ISSUE TITLE
urllib3 incorrectly folds/concatenates all HTTP headers (except for `set-cookie`), causing issues with HSTS in particular

### ISSUE THREAD

**Issue by globau** [urllib3/urllib3#1466]
If a site returns multiple HSTS heads:

```
Strict-Transport-Security: max-age=31536000
Strict-Transport-Security: max-age=31536000; includeSubDomains
```

urllib3 folds these into a single header:

```
Strict-Transport-Security: max-age=31536000, max-age=31536000; includeSubDomains
```

http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2 has:

> Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. It MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma. The order in which header fields with the same field-name are received is therefore significant to the interpretation of the combined field value, and thus a proxy MUST NOT change the order of these field values when a message is forwarded

Since the field-value for HSTS is not defined as a comma-separated list and since doing this does change the semantics of the message (by resulting in an invalid HSTS header), this concatenation shouldn't be happening.

https://github.com/mozilla/http-observatory/issues/363#issuecomment-434011250 points to https://github.com/urllib3/urllib3/pull/534/files#diff-01955f24bc4d0d621454698a584ab854R290 as being the problem and proposes some ways to fix this.

**Comment by globau** [comment]
that's my understanding too.  unfortunately handling of spec-violating servers is the nature of the beast.

both chrome and firefox honour only the first header:

https://hg.mozilla.org/integration/autoland/rev/0f8ae1c5e282
> This implements a plaintext reading of RFC 6797, which says to only consider the first, however it slightly conflicts with RFC 7230, which says that sending multiple headers which can't be merged is illegal (except for a specific whitelist which HSTS isn't in). Chrome also implements HSTS using RFC 6797's description of the parsing algorithm.

this behaviour isn't possible to implement with urllib3.

**Comment by sigmavirus24** [comment]
> this behaviour isn't possible to implement with urllib3.

Yes it is. Headers in urllib3 can return the values as a list or as a comma separated string. The behaviour you're seeing is an artefact of old behaviour that was kept for backwards-compatibility. You likely want `headers.getall('strict-transport-security')` which should return a list that looks like `[max-"age=31536000", "max-age=31536000; includeSubDomains"]

**Comment by sigmavirus24** [comment]
Sorry, the method is actually `getlist` (see also: https://github.com/urllib3/urllib3/blob/f8d1c787d9b02a70d66ddbde9c99061d9073d54a/src/urllib3/_collections.py#L251)

**Comment by sigmavirus24** [comment]
Oh and there are other backwards-compatible shims too: https://github.com/urllib3/urllib3/blob/f8d1c787d9b02a70d66ddbde9c99061d9073d54a/src/urllib3/_collections.py#L263..L269

**Comment by SethMichaelLarson** [comment]
I'm going to mark this as closed as there are methods of getting header values without the folding.

**Comment by globau** [comment]
thanks for your time and for pointing me in the right direction.
