### ISSUE TITLE
Session Passing Issues

### ISSUE THREAD

**Issue by ZeldaZach** [urllib3/urllib3#1476]
Hi urllib team!

I seem to have come across a weird race time condition error with your library. I am using the `requests` library to initiate downloads in several processes, but they all state my urllib3 fails in some capacity after a short period of time. Running it in singleton mode, I experience no issue.

Steps I took:
Create a session
Use the session to do some downloads
Call multiprocess.Pool on a function
- This function will then call for downloads using the session created

After a short while, this results in a Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read) error from requests which calls to urllib3. A crashlog can be found at https://pastebin.com/zXfGQc4S

A (temporary) fix can be found at https://github.com/mtgjson/mtgjson4/pull/122, which was to keep resetting the sessions to flush the internal cache (thus creating a new session in each process).

**Comment by sethmlarson** [comment]
Not sure what was causing your issue, the pastebin appears to have expired. Please reopen a new issue if you're still experiencing this.
