### ISSUE TITLE
Standard library

### ISSUE THREAD

**Issue by 1oglop1** [urllib3/urllib3#1482]
I wonder why `urllib` always increment versions as a package instead of contributing to the standard library?

One day we end up with `urllib20` and N other dependencies in requirements file 
`urlib`
`urllib2`
`urllib3`
`urllib3.5`
`urlib17.3`

as and example I'm not the only one who think about it:
https://pypi.org/project/urllib5/

```
Once there was urllib. Then there was urllib2. Then there was urllib3. And if you look at PyPI, you even find urllib4. If you want to have all of them, use urllib5. Or you know, have a nice urllib in the standard library. But that would be too easy. SCNR. HTH. lol
```

So it made me wondering just why?

**Comment by SethMichaelLarson** [comment]
- urllib - Standard library module for opening and handling URLs in Python 3
- urllib2 - Standard library module for opening and handling URLs in Python 2
- urllib3 - Packaged library on PyPI that provides a urllib2/urllib interface for Python 2 and 3 and adds additional functionality found within most HTTP libraries such as Connection pooling, TLS, HTTP redirects, etc
- urllibN - Unrelated to this project and Python standard library.

In the future please reserve our issue tracker for defects in the library.

**Comment by pquentin** [comment]
Related: https://github.com/urllib3/urllib3/issues/1065#issuecomment-265191841
