### ISSUE TITLE
Retry doesn't kick in for DNS errors

### ISSUE THREAD

**Issue by BeyondEvil** [urllib3/urllib3#1488]
I'm not sure if I'm doing something wrong or if I've misinterpreted the documentation.

But I'm trying to handle intermittent issues that I have with AWS and domain failing to resolve.

I'm running a suite of selenium tests, 30 tests to be exact, with lots of moving parts: app hosted on AWS, tests executed by Bitbucket CI (aka pipelines) using docker-in-docker and docker-to-docker.

Intermittently, for a couple of, seemingly random from time to time, tests, I get a failure:

```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pr-5fdb8ad6.dev.dporganizer.com', port=8001): Max retries exceeded with url: /users/login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7feb677b1be0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
```

gistNow I know the app is running and is accessible, because the other tests work fine (they all hit the same endpoint).

I also have a little function that runs before any tests, that makes sure that the app is accessible via all of AWS name servers (for our domain).
https://gist.github.com/BeyondEvil/6f75a446cac23832808c8bbaa8186a90

So, I figured I would look into urllib3's Retry object and logic, to at least solve the symptoms - since troubleshooting this is a nightmare given all the moving parts.

So, this is what I did:

```
from requests.sessions import Session
from requests.adapters import HTTPAdapter, Retry

with Session() as session:
    retry = Retry(connect=5, backoff_factor=1.0)
    session.mount(
        base_url.split(':')[0],  # this will be `https://pr-5fdb8ad6.dev.dporganizer.com`
        HTTPAdapter(
            max_retries=retry
        )
    )
    response = session.request(**signature)
```

Well, the code works, the tests run, but there doesn't seem to be any retries happening. The exception happens, and I'm expecting it to now be wrapped in MaxRetryError, but it's not.

Requests is at 2.20.1 and urllib3 is 1.24.1
python 3.7.0

What am I doing wrong?

How can I validate that retries are actually happening?

**Comment by SethMichaelLarson** [comment]
DNS resolution occurs from [here](https://github.com/urllib3/urllib3/blob/master/src/urllib3/connection.py#L157) within `create_connection()`. From what I'm reading it looks like the `Retry` class checks to see if the exception is a subclass of `ConnectTimeoutError` which `NewConnectionError` is subclassed from so in theory it's accepting that the `NewConnectionError` is retry-able. There may be a test somewhere for this situation.

**Comment by SethMichaelLarson** [comment]
This could also be the problem:

```python
>>> import socket
>>> isinstance(socket.gaierror, socket.error)
False
```

Maybe we should be catching `SocketError` and `socket.gaierror` within `HTTPConnection._new_conn` and transforming both into `NewConnectionError`?

**Comment by BeyondEvil** [comment]
Thanks @SethMichaelLarson !

Any idea how I can test this?

Maybe patch my docker image with a branch of urllib3 that contains changes reflecting catching socket.gaierror as well?

**Comment by SethMichaelLarson** [comment]
Change [this line](https://github.com/urllib3/urllib3/blob/master/src/urllib3/connection.py#L166) to `except (SocketError, socket.gaierror) as e:` and import `socket` up top?

**Comment by BeyondEvil** [comment]
> Change [this line](https://github.com/urllib3/urllib3/blob/master/src/urllib3/connection.py#L166) to `except (SocketError, socket.gaierror) as e:` and import `socket` up top?

Will do!

And I'm I correct in assuming that if Retry is happening, my errors/exceptions should be wrapped by MaxRetryError?

Any other ways of verfiying retry is actually happening?

Is my code correct, btw?

Thanks @SethMichaelLarson

**Comment by SethMichaelLarson** [comment]
Yeah they should be wrapped by that exception. Your code looks correct on first glance.

**Comment by BeyondEvil** [comment]
Cool, thanks!

Quick Q re. `mount()` can the prefix be an empty string? Will that cause the Retry to retry on all URLs?

**Comment by BeyondEvil** [comment]
Changed the except to also catch socket.gaierror (socket was already imported). 

No dice. :(

Here's the test-report: https://dporganizer-test-results.s3.amazonaws.com/e2e/pr_test_report_2018-11-30_15-51-32_firefox.html

Same error, no wrap. :(

Since I'm patching my image, where is a good place to add some debugging?

@SethMichaelLarson

**Comment by SethMichaelLarson** [comment]
I'm going to look at this more closely when I get time. Thanks for trying and providing a result.

**Comment by SethMichaelLarson** [comment]
Also related: #1003, #1008

**Comment by BeyondEvil** [comment]
Thanks! Appreciate it.

I noticed in this run that it looks like Requests might be swallowing the MaxRetryError:

`/usr/local/lib/python3.7/site-packages/requests/adapters.py:513: in send
raise ConnectionError(e, request=request)`

https://github.com/requests/requests/blob/v2.20.1/requests/adapters.py#L500

**Comment by SethMichaelLarson** [comment]
I don't know if you've got time to try but it'd be nice if you could implement what you're attempting to do in a urllib3 `PoolManager`, then we wouldn't get the extra layer or requests obfuscating our exceptions.

**Comment by BeyondEvil** [comment]
I might not have time to do it during the weekend, but I can probably give it a try early next week.

**Comment by BeyondEvil** [comment]
Ok, I'm up and running with a pure urllib3 solution @SethMichaelLarson 

I have a question tho: How can I verify that the retry is actually happening? Logging or is there anything in the retry object I can check? `self.history`?

**Comment by BeyondEvil** [comment]
Thanks for the fast response! @SethMichaelLarson 

I also noticed that whenever a retry is happening, a logging warning is issued.

So, I'm guessing the problem lies with `Requests` and not with urllib3, right?

Here's a test report: https://dporganizer-test-results.s3.amazonaws.com/e2e/pr_test_report_2018-12-03_15-49-05_firefox.html

Check `tests/data_flow_test.py::test_create_data_flow`

There one can see:
```
connectionpool.py 662 WARNING Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fda17edafd0>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /subjects?id=307&populate=all
```

**Comment by SethMichaelLarson** [comment]
Could be! Was this test run with the above patch to that `except` block with `socket.gaierror`? That is the expected warning we'd receive if we couldn't resolve a connection. I'd like to add a test case to our unit tests to ensure the proper code path is being followed as I'm expecting here.

**Comment by BeyondEvil** [comment]
@SethMichaelLarson No, actually it wasn't. This was run using the unpatched version. 🤔

**Comment by BeyondEvil** [comment]
I finally had some time to look into this again @SethMichaelLarson 

It now works as expected. I'm not entirely sure why, but I think it might have to do with the `prefix` argument to the `mount` function of Requests `Session` class. I made sure to set it to the full protocol/scheme `http://` or `https://`.

Thanks for all your help!

**Comment by macfreek** [comment]
Sorry to ask about an older ticket. I'm bumping into the same issue. @BeyondEvil, I'm not clear how you resolved this. Was the issue with urllib3 or with requests? Do you have a pointer to the commit or pull request that fixes this?

**Comment by BeyondEvil** [comment]
@macfreek Unfortunately I can't point to a commit or PR.

But essentially, since I'm using `requests` what I had to do was sure that the `prefix` argument to the `mount` call was correct. (eg. http:// or https://)

Hope that makes sense!
