### ISSUE TITLE
Add support for client key passphrase for SecureTransportContext

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#1490]
Currently we don't use the `_client_key_passphrase` parameter on `SecurityTransportContext` object within `contrib/securetransport`. Currently this would require the following:

- Would probably be best if you have access to a macOS system (Currently I don't have access to one).
- Add support for bindings for the `SecItemImportExportKeyParameters` struct within the @wbond's [`oscrypto`](https://github.com/wbond/oscrypto/blob/master/oscrypto/_osx/_security_ctypes.py#L67) library. Here's the official [documentation for this struct](https://developer.apple.com/documentation/security/secitemimportexportkeyparameters?language=objc).
- Update our `contrib/_securetransport` module with the changes you make upstream.
- Implement the `passphrase` parameter within [urllib3.contrib._securetransport.low_level._load_items_from_file()](https://github.com/urllib3/urllib3/blob/master/src/urllib3/contrib/_securetransport/low_level.py#L238) and pass through the `_client_cert_passphrase` parameter to it within [`urllib3.contrib.WrappedSocket.handshake()`](https://github.com/urllib3/urllib3/blob/master/src/urllib3/contrib/securetransport.py#L479).
- Allow client cert testing within all unit tests for SecureTransport.

**Comment by SethMichaelLarson** [comment]
Pinging @Lukasa as our SecureTransport champion in case you have some additional insights that are missing here.

**Comment by Pradhvan** [comment]
@sethmlarson shouldn't this issue be closed as the #1489 is merged.

**Comment by sethmlarson** [comment]
Yep! Thank you :)

**Comment by sethmlarson** [comment]
Wait no this is still needed. That PR didn't add it for ST.

**Comment by graingert** [comment]
I think this can be closed now that ST is pending deprecation

**Comment by pquentin** [comment]
Thanks, good catch.
