### ISSUE TITLE
Client certificate password?

### ISSUE THREAD

**Issue by lexugax** [urllib3/urllib3#1493]
I am trying to pass a client certificate to my request, but the documentation says nothing about specifying the password for an encrypted certificate:

">>> http = urllib3.PoolManager(
...     cert_file='/path/to/your/client_cert.pem',
...     cert_reqs='CERT_REQUIRED',
...     ca_certs='/path/to/your/certificate_bundle')"

Does this mean that the client cert cannot be encrypted?

**Comment by lexugax** [comment]
Yes, this is what I was looking for. Thanks!

**Comment by sethmlarson** [comment]
@shubsaini09 can you open a separate issue with a full traceback and a filled out issue template?
