### ISSUE TITLE
Create an integration testbed

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#1498]
This issue is being used as a brain dump for me until I create the new repository for this work. This work would be done as part of #1392.

- [ ] Allow testing against versions of Python before and after significant changes were introduced:
  - Python 2.7.8 / 2.7.9 for SSLContext
  - Python 3.4, 3.5, 3.6, 3.7
  - PyPy and PyPy3
  - Dev / RC Python builds
- [ ] Allow testing with a subset of dependencies installed from the various extras.
- [ ] Allow testing with different versions of dependencies we rely on.
  - Cryptography / pyOpenSSL before TLS 1.3 support
  - PySocks
- [ ] Running unit tests for urllib3
- [ ] Running unit tests of our upstream dependents (requests, boto3) with the install of urllib3
- [ ] Running additional customized tests for each environment (e.g. import/inject tests when dependencies are missing)
- [ ] Running with Python installs built against different versions of OpenSSL (focusing on Ubuntu/Debian/macOS environments here)
- [ ] This testbed should be installable and configurable via command line for local runs / development.
- [ ] This testbed should be `git clone`-able into a Travis build and easily configurable using environment variables for our integration tests.
  Thinking along the lines of `URLLIB3_TESTBED=test:urllib3-unittests,python:2.7.9,pyopenssl:14.0`
- [ ] Tracking exactly which tests ran and what their result was so we don't skip/xfail tests we don't expect?

**Comment by SethMichaelLarson** [comment]
FYI currently the repo can be found at https://github.com/SethMichaelLarson/urllib3_test_tool
