### ISSUE TITLE
Can't connect through HTTPS via Proxy

### ISSUE THREAD

**Issue by gleopoldo** [urllib3/urllib3#1513]
Hello!

I have an python 2.7.3 application running with urllib3 1.24.1 and I'm getting an error when attempting to send a request through a proxy. Here is my example:

```
import urllib3
import os

proxy = urllib3.ProxyManager(os.environ['http_proxy'])
proxy.request("GET", "https://google.com")
```

By running the code above, I get:

```
smtp-milter@d3b41adabd1c:~$ pipenv run python test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    proxy.request("GET", "https://google.com")
  File "/smtp-milter/.venv/lib/python2.7/site-packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/smtp-milter/.venv/lib/python2.7/site-packages/urllib3/request.py", line 89, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/smtp-milter/.venv/lib/python2.7/site-packages/urllib3/poolmanager.py", line 446, in urlopen
    return super(ProxyManager, self).urlopen(method, url, redirect=redirect, **kw)
  File "/smtp-milter/.venv/lib/python2.7/site-packages/urllib3/poolmanager.py", line 323, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/smtp-milter/.venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/smtp-milter/.venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/smtp-milter/.venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/smtp-milter/.venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/smtp-milter/.venv/lib/python2.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 403 Forbidden',)))
```

However, if I change the destination address to HTTP instead, I can perform the request successfully.

I've tried different versions of urllib3, from 1.6.0 up to 1.24.1, running into same issue.
Also tried running in different versions of python.
 Any ideas?

**Comment by shazow** [comment]
Is it possible that your proxy is not working with HTTPS connections? Does it work with something like `curl --proxy="<the same proxy>" "https://google.com/"`?

**Comment by gleopoldo** [comment]
Yeah. Nice one! Testing with curl, seems that there is a problem with proxy not accepting requests from my machine :thinking: ...

```
$ curl --proxy "http://proxy.qaservices.locaweb.com.br:8888" "https://google.com/"
curl: (56) Received HTTP code 403 from proxy after CONNECT
```

I'm going to look into this.

Also, I've tried to send a request to google without the HTTPS and, although the request didn't raised an exception, it returned the same 403. Is there any reason to this behavior be so different from the one I've got when sending an HTTPS request?

**Comment by shazow** [comment]
Sounds like it's something related to your proxy configuration--maybe it doesn't like Google's HTTPS certificate for some reason?

Or maybe Google has identified your proxy IP as harbourer of bots (common for shared proxy IPs) and is presenting it with somekind of challenge that the proxy is failing to complete?

Closing this for now, since it's not urllib3's fault, but you're welcome to share the outcome! :)

**Comment by gleopoldo** [comment]
@shazow That seems strange for me, since the response that came back was the same in both cases.... The only difference was that the SSL version raised an exception. Shouldn't the urllib API be consistent in this point and either raising an exception, or returning the error content directly in both scenarios?

**Comment by shazow** [comment]
@gleopoldo Hmm, so are you proposing that a different kind of error should be raised? IIRC this is tricky because ultimately if retries are enabled, `MaxRetryError` is the error you'll get unless it's a whitelisted subset of errors, but it should contain the underlying cause.

Sorry I kinda tried to helicopter help in here without being up to date with the other issues that you're referring to where the error content was returned?

Do you want to open another issue to propose a different behaviour in this case?

**Comment by gleopoldo** [comment]
@shazow I'm don't think that `MaxRetryError` is the problem here... I'm referring to `ProxyError` that is raised when the `403` response returned. It is only raised when I used the HTTPS connection. The HTTP attempt returned the response object correctly.

Since the HTTP request didn't failed at first time, it's never retried and so it never raises the `MaxRetryError`. The other version (using HTTPS) is raising this `ProxyError` when the proxy returned the TUNNEL_REJECT, which leads after some retries to this "outer" error.

**Comment by shazow** [comment]
@gleopoldo Could you please open another issue specifically for what you just described?

**Comment by gleopoldo** [comment]
Yeah. Sure. Tks!
