### ISSUE TITLE
Create a dedicated urllib3 PyPI account.

### ISSUE THREAD

**Issue by theacodes** [urllib3/urllib3#1522]

**Comment by shazow** [comment]
Some questions:

- Do we have a strategy in place for sharing logins/secrets between maintainers? (Should we setup a Keybase group or something?)
- What do we want to do in terms of the email address for shared accounts? (Doesn't look like PyPi has a notion of shared orgs? Should we setup a shared gmail or just use the lead maintainer's email or mine?)

**Comment by theacodes** [comment]
These are all questions I wanted to answer in the process of setting this
up. I'm good with taking this on next week.

**Comment by theacodes** [comment]
I'm going to use [git-secret](https://git-secret.io/) which is just a fancy wrapper on top of `gpg` to store the secret here and share with other maintainers.

**Comment by theacodes** [comment]
@shazow @sethmlarson can y'all share your GPG public keys with me at your convenience?

**Comment by shazow** [comment]
https://keybase.io/shazow/pgp_keys.asc is mine.

**Comment by sethmlarson** [comment]
Just created a keybase. Here's mine: https://keybase.io/sethmlarson/pgp_keys.asc

**Comment by theacodes** [comment]
Ah since we all have keybase I'll just use that. :)

**Comment by theacodes** [comment]
Account created and password is now in Keybase.

@shazow can you add https://pypi.org/user/urllib3/ as a maintainer for urllib3 on PyPI (I don't have the ability).

**Comment by shazow** [comment]
@theacodes Done
