### ISSUE TITLE
Decide on plan for dropping App Engine standard support

### ISSUE THREAD

**Issue by theacodes** [urllib3/urllib3#1523]

**Comment by pquentin** [comment]
@sethmlarson Should we do this as part of 2.0 too?

**Comment by sethmlarson** [comment]
Python App Engine Standard supports Python 3.7 so we'll support this into v2.0 with the help of our friends at Google Cloud :) cc @crwilcox @di

**Comment by crwilcox** [comment]
Thanks @sethmlarson while App Engine Standard is an older way of deploying, folks do still use it. 

If the plan is to maintain v1 after v2 launches, there may be an argument to only support v1 if that would reduce maintainer burden.

Also, do be sure to reach out of if you need assistance on this at all.

**Comment by pquentin** [comment]
@crwilcox The plan is to maintain v1, yes, thanks to [Tidelift support](https://blog.tidelift.com/how-tidelift-helps-urllib3-maintainer-seth-larson-support-more-python-versions-and-release-streams). To be fair, App Engine support isn't that much of a burden, it just makes the code more complex in a few places

**Comment by pquentin** [comment]
It turns out that App Engine does not need any support from urllib3 in Python 3. So we just removed all App Engine code in #2044.

The plan becomes "we'll support App Engine as long as we support 1.x / Python 2.7".

Closing!
