### ISSUE TITLE
Ignore userinfo in request

### ISSUE THREAD

**Issue by Windsooon** [urllib3/urllib3#1530]
I found in the [connection_from_host function](https://github.com/urllib3/urllib3/blob/master/src/urllib3/poolmanager.py#L210), we didn't use userinfo in `request_context`, so 

    r = http.request('GET', 'http://user:1234@httpbin.org/robots.txt')
would be just as same as 

    r = http.request('GET', 'http://httpbin.org/robots.txt')

I wonder why we ignore the userinfo part?

**Comment by sethmlarson** [comment]
Currently we expect our users to handle authentication headers themselves. It's unfortunate that we silently strip this information though. What's the behavior of the standard library for these types of URLs?

**Comment by Windsooon** [comment]
I came from [cpython issue-34628](https://bugs.python.org/issue34628), the standard library didn't handle it correctly. I think we may raise an error there and ignore what RFC standard said right now.

**Comment by sethmlarson** [comment]
Since it matches stdlib behavior I think I'm going to close this issue.
