### ISSUE TITLE
OpenSSL.SSL.Error raised with invalid client cert and cryptography 2.5

### ISSUE THREAD

**Issue by jaraco** [urllib3/urllib3#1537]
In requests/requests#4961, I stumbled onto an issue where it appears that in the right scenario, OpenSSL errors are raised from `urllib.connectionpool.HTTPConnectionPool._make_request`. It happens with these deps

```
asn1crypto==0.24.0
certifi==2018.11.29
cryptography==2.5
ddt==1.2.0
idna==2.8
pyOpenSSL==19.0.0
requests==2.21.0
requests-unixsocket==0.1.5
trustme==0.5.0
urllib3==1.24.1
```

[among others](https://github.com/cherrypy/cheroot/issues/173#issuecomment-460411259) on multiple Pythons and operating systems including Python 3.7.2 on macOS or Python 3.7 on Linux.

Downgrading to pyOpenSSL 18 has no effect, but downgrading to cryptography 2.4 resolves the issue.

I'm still unsure how cryptography 2.5 is relevant to the issue and I've been yet unable to replicate the issue in an isolated environment. One way you can currently replicate the issue is by checking out cherrypy/cheroot@e616c2542d and run `tox -- -k test_tls_client_auth --pdb` (to get a pdb prompt when the exception occurs).

Unfortunately, because an exception was already raised, the `cl_pem` and other state are already cleared out. Let me see if I can't distill that test into a more isolated test that replicates the issue.

**Comment by jaraco** [comment]
[This script](https://gist.github.com/a648d793c847aa3be2ff5186bb8c1dc7) replicates the issue. Download and run with `pip-run -- -m pytest test-ssl.py` (or create an env and install the dependencies manually). This test is a distilled version of the test that cheroot runs. It still relies on cheroot to set up the verifying HTTPS server.

I can distill this more later, but I need to break for now.

**Comment by sethmlarson** [comment]
I'm almost positive this is [post-handshake authentication](https://tools.ietf.org/html/rfc8446#section-4.2.6) of client certificates.
