### ISSUE TITLE
Poolmanager leaves sockets open, causing debug warnings, documentation does not mention clear() function

### ISSUE THREAD

**Issue by hannob** [urllib3/urllib3#1538]
I noticed that python scripts using poolmanager will show warnings when run with PYTHONWARNINGS=d.

Take a simple example (from the docs):
```
from urllib3 import PoolManager
manager = PoolManager(10)
r = manager.request('GET', 'http://google.com/')
```

Save it as example.py, run:
```
PYTHONWARNINGS=d python3 example.py
```
It will cause warnings like this:
```
sys:1: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('[removed]', 41338, 0, 0), raddr=('2a00:1450:400e:809::200e', 80, 0, 0)>
sys:1: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('[removed]', 50384, 0, 0), raddr=('2a00:1450:400e:806::2004', 80, 0, 0)>
```

By looking at what functions the poolmanager object has I found that it supports a clear() function that will close all sockets. However that's not mentioned in the official docs:
https://urllib3.readthedocs.io/en/1.2.1/managers.html

I believe this should be documented and also ideally the code examples should encourage using a pattern that will not cause warnings.

**Comment by sethmlarson** [comment]
The link to documentation you gave it out of date (1.2.1), [this is where our docs are on `PoolManager`](https://urllib3.readthedocs.io/en/latest/reference/index.html#module-urllib3.poolmanager) which mentions `clear()`.

**Comment by hannob** [comment]
It seems the new doc has pretty bad google ranks, the old one is what one always finds. I haven't found that searching for it. But I guess it's okay then. (Not sure if there's a way to do this on readthedocs, but maybe it'd be an idea to have a link on all the old docs "This doc is outdated, go here for the current one".)
