### ISSUE TITLE
HTTPResponse.getheaders() is not backwards compatible

### ISSUE THREAD

**Issue by user234683** [urllib3/urllib3#1543]
The `getheaders()` method of the `HTTPResponse` class returns the dict-like `HTTPHeaderDict`, while the httplib version of that method returns a list of (header, value) tuples. This means that code iterating over the response as in `for header, value in response.getheaders()` will not work with urllib3 response objects unless `.items()` is called on the returned `HTTPHeaderDict` object. A comment near the `getheaders()` method indicates it's supposed to be backwards compatible.

**Comment by sethmlarson** [comment]
You're right, this comment and interface aren't correct. If we were to change this behavior I'm not sure how many people would be impacted but at a minimum that comment either needs to be removed or this interface fixed.

I think the safest bet is to just remove the comment about compatibility, but it still feels kinda bad to pretend to be the same as an `HTTPResponse` object. Thoughts from other @urllib3/maintainers?

**Comment by haikuginger** [comment]
I've been working on type enforcement for `HTTPHeaderDict` the last week or so; in general, it does not fulfill the interfaces it promises (for example, it doesn't meet consistency requirements to actually be the `MutableMapping` ABC it inherits from). I would suggest in this case that, in the near term, we remove comments about compatibility where those are not met, and once we have typechecking in place throughout our codebase, then we can make move towards meaningful compatibility.
