### ISSUE TITLE
invalid escape sequence \*

### ISSUE THREAD

**Issue by damian-sublime** [urllib3/urllib3#1546]
This error is a result of the following comment lines:

>     :param \\**conn_kw:
>         Additional parameters are used to create fresh :class:`urllib3.connection.HTTPConnection`,
>         :class:`urllib3.connection.HTTPSConnection` instances.
>     """

connectionpool.py, line 150

Error thrown:

> Syntax error in module 'app': invalid escape sequence \* (connectionpool.py, line 152)

Peralink: https://github.com/urllib3/urllib3/blob/1e9ab5aee042ff0158d0f443bc600ef3a2e7bf9a/src/urllib3/connectionpool.py#L150

**Comment by sethmlarson** [comment]
Where are you seeing this error?

**Comment by damian-sublime** [comment]
AWS Lambda

**Comment by sethmlarson** [comment]
What version of Python is this? We test Python 2.7 to 3.8 and we're not seeing that error. I need to know what you're doing to get to the bottom of this error.

**Comment by damian-sublime** [comment]
Python 3.6.4
The library simply fails to import at app load

**Comment by sethmlarson** [comment]
I can't reproduce this what you're seeing here so I need as much information about this as you can give me. What's the full output of the error? What version of urllib3 are you using? Are you installing it via pip or vendoring it yourself? Is this code you're using available on GitHub?

**Comment by damian-sublime** [comment]
The deployment is being pushed using AWS Chalice
The code is not available here, our code is privately hosted on BitBucket

The issue can be replicated using both local and BitBucket Pipelines deployment.
Local deploy is being done using virtualenv
Pipelines is using the standard Python image

Both produce the same output when trying to load the library.

**Comment by sethmlarson** [comment]
I just don't know why others aren't seeing this issue, you're definitely not the only one using urllib3 on AWS and we're not seeing a swarm of users opening issues like we would be if this issue impacted everyone.

**Comment by damian-sublime** [comment]
Totally agree.
I don't understand why this is happening.
But given it does and it's only related to a couple of characters in a comment not sure why it's become such a big issue to amend.

**Comment by sethmlarson** [comment]
@damian-sublime Sorry I edited my above comment, can you reply to it?

**Comment by damian-sublime** [comment]
It's 1.24.1

**Comment by sethmlarson** [comment]
What version of pip, requests?

**Comment by damian-sublime** [comment]
19.0.3

**Comment by sethmlarson** [comment]
What version of urllib3? And these are the versions of the libraries that are getting deployed, not the ones in your local virtualenv, correct?

**Comment by damian-sublime** [comment]
The deployment uses a requirements file to pull in latest version of any of the libraries.
So latest version is the one deployed.
As part of the deployment I cache the deployment package for verification.
The deployment indicates correct latest version of the library
![Screen Shot 2019-03-12 at 9 15 18 AM](https://user-images.githubusercontent.com/6157074/54154720-73878800-44a7-11e9-94a8-5e9951e517e7.png)

**Comment by sethmlarson** [comment]
Then I'm all out of ideas unfortunately. :( The escape sequence in the current version is correct, this issue [was fixed over two years ago already](https://github.com/urllib3/urllib3/commit/d9a4d4bc1f900f260dc5dca3a7deda05c2670ec9).

The most help I can give you is that this sounds like somewhere in your dependencies there is a vendored old version of urllib3 (boto, requests, pip, ...).  Try looking there?

**Comment by damian-sublime** [comment]
Hmm
Thanks for looking in this anyway.
I will reply further is I find any resolution or have further findings.
