### ISSUE TITLE
Incorrect ciphersuites order

### ISSUE THREAD

**Issue by ealashwali** [urllib3/urllib3#1550]
I am using `requests ` library. I need  a custom list of ciphersuites in my requests. So I use the following:

```
defaultCiphers = "TLS_AES_128_GCM_SHA256"+":"+"TLS_AES_256_GCM_SHA384"+":"+"TLS_CHACHA20_POLY1305_SHA256"+":"+"ECDHE-ECDSA-AES128-GCM-SHA256"

class TlsAdapter(HTTPAdapter):

  def init_poolmanager(self, *args, **kwargs):
      context = create_urllib3_context(ciphers=defaultCiphers)
      kwargs['ssl_context'] = context
      return super(TlsAdapter, self).init_poolmanager(*args, **kwargs)

  def proxy_manager_for(self, *args, **kwargs):
      context = create_urllib3_context(ciphers=defaultCiphers)
      kwargs['ssl_context'] = context
      return super(TlsAdapter, self).proxy_manager_for(*args, **kwargs)
host = 'https://google.com'
s = requests.Session()
s.mount("https://",TlsAdapter())
response = s.get(host)
```

However, by checking the actual ciphersuites list that is sent in my request using packet analyser it appears in a different order from this order I specify in the code. A correct implementation should respect the order. I have faced similar problem with another SW. It turned to be a function name for TLSv1.3 that is different from that in previous versions. These ciphers that are not ordered correctly are TLSv1.3. This is the OpenSSL devs. response to that issue:
https://github.com/prbinu/tls-scan/issues/21#issuecomment-443795659

Can you please advise me whether it is an issue in `urllib3` code, and if so, can it be fixed any soon?

**Comment by sethmlarson** [comment]
Python does not provide us with a method to reorder or configure TLSv1.3 ciphersuites.  You could try setting `ssl_version = ssl.PROTOCOL_TLSv1_2` to disable TLSv1.3 ciphersuites I believe?

**Comment by ealashwali** [comment]
I need TLSv1.3 ciphersuites in a specific order that's why I create an `adapter` in the code above with `requests` for an experiment.  In python there is  `SSLContext.set_ciphers(ciphers)` See this [link](https://docs.python.org/2/library/ssl.html). I am not sure if this can be of use? But it takes the ciphers in the order the argument `cipher` has.

**Comment by ealashwali** [comment]
Can you please check this post: https://lukasa.co.uk/2017/02/Configuring_TLS_With_Requests/
I have seen it and many other posts that suggest configuring the ciphersuites with requests. using `create_urllib3_context`. Can you clarify please @Lukasa ?

**Comment by sethmlarson** [comment]
Sorry for misunderstanding your original request. If you look at what I mentioned earlier:

> Python does not provide us with a method to reorder or configure TLSv1.3 ciphersuites.

Meaning currently this is not possible for Python, [we don't have access to the required function to configure the order](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.set_ciphers). Basically TLS 1.3 is all-or-nothing in Python until that interface is exposed.

If you don't mind me asking, why are you trying to disable/reorder certain suites? The ciphersuite choice is not controlled by the client anyways.

I'm going to close this issue as we can't do much about this at the moment. Sorry!

**Comment by ealashwali** [comment]
Here is a full example @sethmlarson  @Lukasa :
```
import requests 
import ssl
from requests.adapters import HTTPAdapter
from requests.packages.urllib3.util.ssl_ import create_urllib3_context
requests.packages.urllib3.disable_warnings() # to disable certificate warnings
defaultCiphers = "TLS_AES_128_GCM_SHA256"
class TlsAdapter(HTTPAdapter):
  def init_poolmanager(self, *args, **kwargs):
      context = create_urllib3_context(ciphers=defaultCiphers)
      kwargs['ssl_context'] = context
      return super(TlsAdapter, self).init_poolmanager(*args, **kwargs)

  def proxy_manager_for(self, *args, **kwargs):
      context = create_urllib3_context(ciphers=defaultCiphers)
      kwargs['ssl_context'] = context
      return super(TlsAdapter, self).proxy_manager_for(*args, **kwargs)
host = 'https://gmail.com'

s = requests.Session()
s.mount("https://",TlsAdapter())
response = s.get(host)
responseURL = response.url 
```

Generates this error:```

Traceback (most recent call last):
  File "test_redirection_scanner.py", line 31, in <module>
    s.mount("https://",TlsAdapter())
  File "/home/e/.local/lib/python3.6/site-packages/requests/adapters.py", line 129, in __init__
    self.init_poolmanager(pool_connections, pool_maxsize, block=pool_block)
  File "test_redirection_scanner.py", line 20, in init_poolmanager
    context = create_urllib3_context(ciphers=defaultCiphers)
  File "/home/e/.local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 266, in create_urllib3_context
    context.set_ciphers(ciphers or DEFAULT_CIPHERS)
  File "/home/e/.local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 421, in set_ciphers
    self._ctx.set_cipher_list(ciphers)
  File "/home/e/.local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1186, in set_cipher_list
    _lib.SSL_CTX_set_cipher_list(self._context, cipher_list) == 1
  File "/home/e/.local/lib/python3.6/site-packages/OpenSSL/_util.py", line 67, in openssl_assert
    exception_from_error_queue(error)
  File "/home/e/.local/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'SSL_CTX_set_cipher_list', 'no cipher match')]
```

As I faced similar problem before, the issue turned in `SSL_CTX_set_cipher_list` which should not be used when setting TLS 1.3 ciphers. Instead TLSv1.3 ciphersuites are set using `SSL_CTX_set_ciphersuites()` as pointed by OpenSSL dev https://github.com/prbinu/tls-scan/issues/21#issuecomment-443795659

Can you help please?

**Comment by sethmlarson** [comment]
I'm aware of all the information you're giving me. What you're trying to accomplish is not possible currently in Python. Please read my above responses.

**Comment by ealashwali** [comment]
@sethmlarson Thanks. I read your comment and I am a bit surprised. The reason I need this is to do an experiment. I have done this before with another [tool](https://github.com/prbinu/tls-scan/issues/21). 

So for example, I want to experiment a client with this exact order of ciphersuites:  "TLS_AES_128_GCM_SHA256"+":"+"TLS_AES_256_GCM_SHA384"+":"+"TLS_CHACHA20_POLY1305_SHA256"+":"+"ECDHE-ECDSA-AES128-GCM-SHA256" (the cipher suite is not selected by the client, but the client offered order matters).

**Comment by sethmlarson** [comment]
Unless you're evaluating requests/urllib3 specifically I'd suggest using a different client that has access to the specific required C-level API.

Maybe curl has support? Not sure.

**Comment by ealashwali** [comment]
Thanks. So the bottom line is that if my pyhton utilizes TLS 1.3, it has no control whatsover on the list or order of TLS 1.3 ciphersuites? But does this mean I still can customise the order of TLS 1.2 ciphersuites?

**Comment by sethmlarson** [comment]
You can customize the order of all non-TLSv1.3 ciphersuites (except if you're using SecureTransport on macOS I believe)
