### ISSUE TITLE
Outdated documentation in https://urllib3.readthedocs.io/en/latest/user-guide.html

### ISSUE THREAD

**Issue by tab1tha** [urllib3/urllib3#1557]
On the page linked here: https://urllib3.readthedocs.io/en/latest/user-guide.html, there are a few outdated expected outputs that needs to be updated. Below are a few cases cited;

1. Section [Response content](https://urllib3.readthedocs.io/en/latest/user-guide.html#response-content) output displays `HTTPHeaderDict({'Content-Length': '33', ...})` but in reality as at now, the out of that statement produces `HTTPHeaderDict({'Content-Length': '49', ...})`. I think that should be updated IMHO, I'm afraid.

2. Section [JSON content](https://urllib3.readthedocs.io/en/latest/user-guide.html#json-content) output displays `{'origin': '127.0.0.1'}` however, it should be;
```
{
  "origin": "154.72.170.213, 154.72.170.213"
}
```

This needs updating as well as it seems the current content of the site has changed from what was there before.

NOTE: These are the few that have been mentioned as I have realized, I've not gone through the entire page to see more but I guess there are more of such issues to be addressed.

**Comment by shazow** [comment]
@tab1tha Thank you! Would you be up for opening a pull request with your edits please? :)

**Comment by shazow** [comment]
Keep in mind, the examples using httpbin, the output is specific to the user who is running them (e.g. one of them is "get my IP" which will be different for each person).

For cases like that, we use generic results like 127.0.0.1 (which is a special reserved IP for your own computer).

**Comment by sethmlarson** [comment]
I'm not sure if either of the examples given should be updated, but you're free to check out the rest of our documentation for inconsistencies. The values from those two examples are liable to change any time and aren't really the "point" of that docs section.

**Comment by tab1tha** [comment]
> I'm not sure if either of the examples given should be updated, but you're free to check out the rest of our documentation for inconsistencies. The values from those two examples are liable to change any time and aren't really the "point" of that docs section.

Okay.

**Comment by sethmlarson** [comment]
I'm going to close this issue for now.
