### ISSUE TITLE
Use Azure Pipelines

### ISSUE THREAD

**Issue by kaylangan** [urllib3/urllib3#1559]
I saw that Azure Pipelines was mentioned in #1554 and was wondering if there's any interest in setting it up for CI and PR builds? If so, I'd be happy to submit a PR.

Azure Pipelines offers 10 free pipelines with unlimited minutes for open source projects and supports macOS, Linux, and Windows. Several Python projects are using Azure Pipelines including [cpython](https://dev.azure.com/python/cpython/_build), [pip](https://dev.azure.com/pypa/pip/_build), and [dateutil](https://dev.azure.com/pythondateutilazure/dateutil/_build). Jobs can run for up to 6 hours and there's also rich test reporting:

![image](https://user-images.githubusercontent.com/20052233/55103578-1f7fc480-509f-11e9-8945-031190db9860.png)

Let me know if you're interested or if you have any questions. I'm a Program Manager for Azure Pipelines.

**Comment by sethmlarson** [comment]
cc: @urllib3/maintainers 

I'm interested only if macOS builds are faster than Travis and we have access to macOS 10.13+ and sudo access to turn on SecureTransport support by default. Are these features available in Azure?

IMO our biggest issues for CI right now are spin-up and install time of macOS builders and AppVeyor only having 1 concurrent build for free projects.

**Comment by kaylangan** [comment]
@sethmlarson We will be [releasing support for Mojave](https://devblogs.microsoft.com/devops/hosted-pipelines-announcements-vs-2019-mojave-and-more/) _very_ shortly (next week or two) and also have sudo access. Let me get the Mac builds going on Azure Pipelines so we can compare the build times and go from there. We're still working on caching, so we may be slower.

On the Windows side, I think we'll be able to easily relieve the issues just by having more concurrency.

Not sure about the network timeouts if other CI systems also suffer from the issue; we can give it a go and see what happens. 😃

**Comment by sethmlarson** [comment]
It looks like now that Mojave has been released we can try this out. Will need @shazow's help with creating an organization,project, and setting up the commit status requirements. I can handle the configuration from there. :)

**Comment by shazow** [comment]
@sethmlarson Let me know what we need. @theacodes also has admin privileges on the org.
