### ISSUE TITLE
SNIMissingWarning with Python 2.7.15 and Openssl 1.0.2r

### ISSUE THREAD

**Issue by hashbackup** [urllib3/urllib3#1561]
HashBackup uses requests and so urllib3 also.  I just upgraded requests to 2.21.0 and urllib3 to 1.24.1, and now am getting this warning:

<frozen>:354: SNIMissingWarning: An HTTPS request has been made, but the SNI (Server Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

That page says: "This happens on Python 2 versions older than 2.7.9", but I'm building with Python 2.7.15, so I'm not sure what to do about the warning, other than adding

urllib3.disable_warnings()

Any advice?

**Comment by hashbackup** [comment]
I should have mentioned, this is a "frozen" Python build that uses static libraries.  The system it is running on is indeed old - CentOS 5.5, with an old version of Python and OpenSSL 0.9.8e, but I'm not using those for the build.

**Comment by sethmlarson** [comment]
Are you installing `requests[security]` or just `requests`?

When you run this what do you see?
```python
import ssl
print(ssl.OPENSSL_VERSION)
```

**Comment by hashbackup** [comment]
Only requests.
```
py
Python 2.7.15 (default, Apr 11 2019, 22:16:00) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-55)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> print ssl.OPENSSL_VERSION
OpenSSL 1.0.2r  26 Feb 2019
>>> 
```
Just to make sure this is the version in the executable, I added the OpenSSL version string to the HB version string:
```
[jim@cent5532 opt]$ bin/hb
HashBackup build #2248 Copyright 2009-2019 HashBackup, LLC
OpenSSL 1.0.2r  26 Feb 2019
Usage: hb command options

Commands:

   audit        display audit log
   backup       backup files and directories
   clear        delete all backup data
   compare      compare filesystem to a backup
   config       view and change config options
   dest         secure dest.conf and manipulate remote destinations
   export       export backup database for tech support
   get          get files and directories from backup (restore)
   help         display help summary or help for a command
   init         initialize a new backup directory
   log          run command with logging
   ls           list backup
   mount        mount backup data as a filesystem
   readkey      manage public key / asymmetric encryption
   recover      re-create backup directory from remote server
   rekey        change the encryption key
   rename       rename a path in the backup
   retain       remove old versions of backup files
   rm           remove files and directories from the backup
   selftest     check backup directory
   stats        display backup statistics
   upgrade      upgrade the HashBackup executable
   versions     display backup versions

Use help with a command name for more detailed help.
[jim@cent5532 opt]$ 
```
The SNIMissingWarning message said "frozen" in angle brackets, but that got eaten by GitHub.  Not sure if that matters...

**Comment by sethmlarson** [comment]
It matters, could you post it again or update your comments with the exact message? Maybe put it in a code block. Also is this system installed Python or a virtual environment? If it's system Python can you try making a venv and trying again from there?

**Comment by hashbackup** [comment]
Thanks for taking time to look at this.  The problem happens in the frozen executable and when running from source with the interpreter (2.7.15).  It's easier to manage the interpreter, so I added some prints of the relevant variables in urllib3/.../_ssl.py.  Here's a run of the program to clear backups from Backblaze B2:
```
[jim@cent5532 ~]$ py hbrel/clear.py -c hbb2 --force
Backup directory: /home/jim/hbb2
Using destinations in dest.conf
server_hostname= api.backblazeb2.com
is_ipaddress(server_hostname)= False
IS_SECURETRANSPORT= False
HAS_SNI= False
/home/jim/opt/lib/python2.7/site-packages/urllib3/util/ssl_.py:359: SNIMissingWarning: An HTTPS request has been made, but the SNI (Server Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
server_hostname= api001.backblazeb2.com
is_ipaddress(server_hostname)= False
IS_SECURETRANSPORT= False
HAS_SNI= False
server_hostname= f001.backblazeb2.com
is_ipaddress(server_hostname)= False
IS_SECURETRANSPORT= False
HAS_SNI= False
server_hostname= pod-000-1004-02.backblaze.com
is_ipaddress(server_hostname)= False
IS_SECURETRANSPORT= False
HAS_SNI= False
Warning: destination is disabled: d
Removed dest.db from b2
Removed DESTID from b2
All backups removed
[jim@cent5532 ~]$ 
```
py -m said "No module named pip", same for freeze.  I don't use pip or venvs, but add requests and urllib3 to the Python interpreter environment by copying them to the Python Lib directory and rebuilding Python.  So urllib3 is showing up in site-packages, like in the error message above.

I tried some other stuff that might be relevant:
```
[jim@cent5532 ~]$ py
Python 2.7.15 (default, Apr 11 2019, 22:16:00) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-55)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> from ssl import wrap_socket, CERT_NONE, PROTOCOL_SSLv23
>>> from ssl import HAS_SNI  
>>> from ssl import OP_NO_SSLv2, OP_NO_SSLv3, OP_NO_COMPRESSION
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name OP_NO_COMPRESSION
>>> 
```
Thanks again.

**Comment by sethmlarson** [comment]
So from your above comments it looks like `HAS_SNI` is `False`? Is that correct? If that's the case it's out of our hands, your Python is compiled without SNI. If you're rebuilding Python maybe you need to add a flag or something to get SNI support?

**Comment by hashbackup** [comment]
I built OpenSSL 1.0.2r from source and used the default configuration.  Maybe SNI doesn't get built by default, but is needed?  Here is some info from my OpenSSL build:
```
[jim@cent5532 openssl-1.0.2r]$ apps/openssl version -a
WARNING: can't open config file: /usr/local/ssl/openssl.cnf
OpenSSL 1.0.2r  26 Feb 2019
built on: reproducible build, date unspecified
platform: linux-elf
options:  bn(64,32) rc4(8x,mmx) des(ptr,risc1,16,long) idea(int) blowfish(idx) 
compiler: gcc -I. -I.. -I../include  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -DL_ENDIAN -O3 -fomit-frame-pointer -Wall -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM
OPENSSLDIR: "/usr/local/ssl"

[jim@cent5532 openssl-1.0.2r]$ openssl ciphers -V 'ALL:COMPLEMENTOFALL'
ADH-AES256-SHA:DHE-RSA-AES256-SHA:DHE-DSS-AES256-SHA:AES256-SHA:ADH-AES128-SHA:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA:AES128-SHA:EXP-KRB5-RC4-MD5:EXP-KRB5-RC2-CBC-MD5:EXP-KRB5-DES-CBC-MD5:EXP-KRB5-RC4-SHA:EXP-KRB5-RC2-CBC-SHA:EXP-KRB5-DES-CBC-SHA:KRB5-RC4-MD5:KRB5-DES-CBC3-MD5:KRB5-DES-CBC-MD5:KRB5-RC4-SHA:KRB5-DES-CBC3-SHA:KRB5-DES-CBC-SHA:ADH-DES-CBC3-SHA:ADH-DES-CBC-SHA:EXP-ADH-DES-CBC-SHA:ADH-RC4-MD5:EXP-ADH-RC4-MD5:EDH-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC-SHA:EXP-EDH-RSA-DES-CBC-SHA:EDH-DSS-DES-CBC3-SHA:EDH-DSS-DES-CBC-SHA:EXP-EDH-DSS-DES-CBC-SHA:DES-CBC3-SHA:DES-CBC-SHA:EXP-DES-CBC-SHA:EXP-RC2-CBC-MD5:RC4-SHA:RC4-MD5:EXP-RC4-MD5:DES-CBC3-MD5:DES-CBC-MD5:EXP-RC2-CBC-MD5:RC2-CBC-MD5:EXP-RC4-MD5:RC4-MD5:NULL-SHA:NULL-MD5
```

**Comment by sethmlarson** [comment]
Unfortunately I'm not going to be of much use with compiling Python or OpenSSL. Try googling around? If there's anything else that urllib3 maintainers can do for you either reopen this issue or a new one.

**Comment by hashbackup** [comment]
It turns out that when I used a cp command to copy the openssl include directory somewhere, it is full of symlinks and didn't actually copy the files.  Then cc saw a bunch of broken links and decided to use the system include directory instead and got the old 0.9.8 OpenSSL include, which doesn't have SNI.  Adding -L to the cp command fixed everything.

Thanks again for your help, for steering me, and for having the warning in urllib3.

**Comment by sethmlarson** [comment]
@hashbackup Glad you were able to figure out the issue! :)
