### ISSUE TITLE
requestsdepenencywarning: urllib3 (1.24.2) or chardet (3.0.4) doesn't match a supported version!

### ISSUE THREAD

**Issue by nsperic** [urllib3/urllib3#1571]
I am using a scrip python on ubuntu 18.04.2 LTS, python version 3.6.5.

When I run my script a message of warning is shown for me, but I am not using in my script the urllib3 or others like this.

I try to use **`apt-get install urllib3`** - **`apt-get install -f `** - **`apt-get install urllib3 --upgrade`** and and none solved this problem.

**Comment by sethmlarson** [comment]
Where are you seeing this error? Could you give all your currently installed packages via `python -m pip freeze`?

**Comment by chekroA** [comment]
Hi, I have the same issue on my Django project. 

I work on macOS Mojave 10.14.4 and running Homebrew Python 3.7.3.

I am using a virtualenv, so I deleted it et reinstalled the required packages but still the same warning: `venv/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version! RequestsDependencyWarning)`

Please find the attached [requirements.txt](https://github.com/urllib3/urllib3/files/3130563/requirements.txt) using `python -m pip freeze`

Thank you ^^

**Comment by sethmlarson** [comment]
@chekroA Your issue is because requests 1.21.X doesn't support urllib3 1.25.X. Try downgrading urllib3 via `python -m pip install "urllib3<1.25"`.

**Comment by XuHaoIgeneral** [comment]
> @chekroA Your issue is because requests 1.21.X doesn't support urllib3 1.25.X. Try downgrading urllib3 via `python -m pip install "urllib3<1.25"`.
thanks！！！ its a right approach。

**Comment by EricGPTI** [comment]
Sorry because I delayed to answer... 

@XuHaoIgeneral I did it, but the error remains.

In my code I don't use urllib but, only ubuntu 18.04 LTS, when I run the code this alert is shown, on Windows don't.

@sethmlarson only packages installed are telethon, pymongo, elasticsearch and pytz.
