### ISSUE TITLE
parse_url no longer accepts [] in the URL

### ISSUE THREAD

**Issue by bertjwregeer** [urllib3/urllib3#1585]
With urllib3 1.25.1:

```
>>> parse_url('https://example.com/somevar[]')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/testrunner/testvenv/lib/python2.7/site-packages/urllib3/util/url.py", line 212, in parse_url
    six.raise_from(LocationParseError(url), None)
  File "/home/testrunner/testvenv/lib/python2.7/site-packages/urllib3/packages/six.py", line 718, in raise_from
    raise value
urllib3.exceptions.LocationParseError: Failed to parse: https://example.com/somevar[]
```

Using 1.24.2:

```
>>> parse_url('https://example.com/somevar[]')
Url(scheme='https', auth=None, host='example.com', port=None, path='/somevar[]', query=None, fragment=None)
```

```
>>> parse_url('https://example.com/?somevar["whatever"]')
Url(scheme='https', auth=None, host='example.com', port=None, path='/', query='somevar["whatever"]', fragment=None)
```

This is used by various bits of software (ElasticSearch for instance):

```
>>> parse_url('http://example.com/api/search/?grouping=datasets&q=dontcare&projection=["variables.nonexistingfield"]')
Url(scheme='http', auth=None, host='example.com', port=None, path='/api/search/', query='grouping=datasets&q=dontcare&projection=["variables.nonexistingfield"]', fragment=None)
```

**Comment by sethmlarson** [comment]
Per [RFC 3986 Appendix A](https://tools.ietf.org/html/rfc3986) the only valid characters in the path component are `unreserved`, `pct-encoded`, `sub-delims`, `:`, and `@` which doesn't include `[` or `]`. Can you see if percent-encoding the square braces works as you expect? Maybe we need to do this as a part of normalization?

**Comment by bertjwregeer** [comment]
Okay, this time not in the path:

```
>>> parse_url('http://example.com/api/search/?grouping=datasets&q=dontcare&projection=["variables.nonexistingfield"]')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/testrunner/testvenv/lib/python2.7/site-packages/urllib3/util/url.py", line 212, in parse_url
    six.raise_from(LocationParseError(url), None)
  File "/home/testrunner/testvenv/lib/python2.7/site-packages/urllib3/packages/six.py", line 718, in raise_from
    raise value
urllib3.exceptions.LocationParseError: Failed to parse: http://example.com/api/search/?grouping=datasets&q=dontcare&projection=["variables.nonexistingfield"]
```

You'll find plenty of PHP sites out there that use:

```
>>> parse_url('http://www.example.com/foo.php?bar[]=1&bar[]=2&bar[]=3')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/testrunner/testvenv/lib/python2.7/site-packages/urllib3/util/url.py", line 212, in parse_url
    six.raise_from(LocationParseError(url), None)
  File "/home/testrunner/testvenv/lib/python2.7/site-packages/urllib3/packages/six.py", line 718, in raise_from
    raise value
urllib3.exceptions.LocationParseError: Failed to parse: http://www.example.com/foo.php?bar[]=1&bar[]=2&bar[]=3
```

This creates an array in `$_GET` in PHP for instance.

I understand that this may not be valid as a URL to enter directly, but it is data we have to parse and `parse_url` usually works wonders for that.

How would you recommend I take a user provided string, pull apart the pieces to URL encode the brackets and the like, because `urllib.quote` on the whole thing will create this mess:

```
>>> urllib.quote('http://www.example.com/foo.php?bar[]=1&bar[]=2&bar[]=3')
'http%3A//www.example.com/foo.php%3Fbar%5B%5D%3D1%26bar%5B%5D%3D2%26bar%5B%5D%3D3'
>>> parse_url(urllib.quote('http://www.example.com/foo.php?bar[]=1&bar[]=2&bar[]=3'))
Url(scheme=None, auth=None, host='http%3a', port=None, path='//www.example.com/foo.php%3Fbar%5B%5D%3D1%26bar%5B%5D%3D2%26bar%5B%5D%3D3', query=None, fragment=None)
```

**Comment by sethmlarson** [comment]
If you're looking for an alternative to `parse_url` you can checkout the library we're using for URL parsing ([`rfc3986`](https://github.com/python-hyper/rfc3986)) and then not do any validation on the path or query components?

**Comment by sethmlarson** [comment]
I think we should consider percent-encoding invalid characters in the path, query, and fragment components automatically as a part of normalization though.  Thoughts @urllib3/maintainers?

**Comment by theacodes** [comment]
Do we automatically percent encode any other stuff?

**Comment by sethmlarson** [comment]
No we don't currently. But previously we just passed through whatever the user gave us in the path and query components into the target. We want to do validation at least for control characters at a minimum but I don't know if anything else can hurt us here.

**Comment by bertjwregeer** [comment]
I would like to point out that we found the issue in urllib3 because it was accidentally upgraded by pip and requests just passes the URL through unmodified.

So we would potentially have to intercept the URL before passing it to requests (as well as deal with any `Location` headers/redirects ourselves) just to modify it before passing it to requests which passes it to `urllib3`.

**Comment by theacodes** [comment]
Hrm. I'm okay with being a little lax on path and query validation.
Ultimately it's up to the server to decide if a request is valid or not.

**Comment by sethmlarson** [comment]
Actually scratch that we totally do inside of `IRIReference.from_string(). The path, query and fragment components all receive some percent encoding just not for `[` or `]`.

**Comment by sigmavirus24** [comment]
I think this falls into the "Be conservative in what you send and liberal in what you receive camp".

In other words, let's liberally accept URLs, and then percent-encode (normalize) them before sending them to servers

**Comment by sethmlarson** [comment]
@sigmavirus24 So you're suggesting we should be percent encoding these characters in the path/query before sending them?

**Comment by sigmavirus24** [comment]
Yes

**Comment by bertjwregeer** [comment]
Thanks for getting on this so quickly!

@sigmavirus24 the tables have turned... I'm reporting issues in your project now ;-)
