### ISSUE TITLE
import error http_client

### ISSUE THREAD

**Issue by simplynail** [urllib3/urllib3#1589]
Hi,
I'm having an issue importing urllib3, namely with `http_client` from `six` module
my code:
```
import sys, os, traceback
import __future__

project_path = os.path.join('Python','revit_code','libs')
sys.path.append('C:\\' + project_path)
import urllib3
```

results in:
```
Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "C:\Python\revit_code\libs\urllib3\__init__.py", line 8, in <module>
    from .connectionpool import (
  File "C:\Python\revit_code\libs\urllib3\connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "C:\Python\revit_code\libs\urllib3\exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
ImportError: No module named http_client
```
I'm using IronPython 2.7.4 (bare with me here please, I have no choice :) ) and urllib3 1.12.

**Comment by sethmlarson** [comment]
Unfortunately as I'm sure you're already aware urllib3 1.12 isn't supported any longer. My best guess is that six doesn't support IronPython. [Maybe looking at Google / StackOverflow will help resolve this issue?](https://stackoverflow.com/q/35162177/5763213)

Good luck!
