### ISSUE TITLE
update of urllib3 makes kodi start up much slower

### ISSUE THREAD

**Issue by peno64** [urllib3/urllib3#1590]
Is it normal that the update to version 1.25 makes kodi start up much slower? With version 1.22 it takes about 20 seconds to start up my rpi with kodi and all the add-ons. After the latest update of a couple of says ago to 1.25.1 and also with 1.25.2 which I installed from zip it takes about 45 seconds to start up with all the add-ons.
Is this to be expected and if so will the slow down only in the startup or can it also be in the use of kodi and addons?

Thank you

**Comment by sethmlarson** [comment]
The only things I can think of that would take time to install would be `idna` and `brotli` but urllib3 doesn't specify either of those as mandatory requirements. When you say "start up" do you mean time to import? I'm not familiar with Kodi or how it uses urllib3.

**Comment by peno64** [comment]
In fact 1.24.1 is also still fast (about 25 seconds to startup everything) and from 1.25.1 on it is much slower (about 45 seconds to startup everything).
I don't how this new version makes it slower. When kodi starts up it also starts some addons automatically and they probably use urllib3. If it is the import of it or its usage, I don't know.
Was there some big change between 1.24.1 and 1.25.1 that could explain this?

**Comment by peno64** [comment]
I did a fresh install of kodi on a RPI. Without any addons it starts quickly. From the moment an addon is installed which uses urllib3 it slows down with the newest version. After installing an older version of urllib3 it goes fast again. I don't know if it is just referencing  urllib3 or also using it. Therefore my knowledge of addons is not enough.
Maybe some small python script that can be run from an ssh shell could demonstrate the issue? Can you provide such an example?

**Comment by mikf** [comment]
Regardless its use in Kodi, there is a huge import-time difference (maybe run-time as well) between urllib3 version 1.24 and 1.25, which is largely caused by the `rfc3986` module.

To demonstrate:
```
$ pip install --user urllib3==1.24
$ time python -c 'import urllib3'
real	0m0,218s
user	0m0,184s
sys	0m0,026s

$ pip install --user urllib3==1.25
$ time python -c 'import urllib3'
real	0m0,573s
user	0m0,516s
sys	0m0,053s
```

Taking a look at import-time profiling data shows that basically all the extra time is spent importing `rfc3986.misc`. It should also be noted that the total cumulative import-time for urllib3 increases by **330%**.

```
$ pip install --user urllib3==1.24
$ PYTHONPROFILEIMPORTTIME=1 python -c 'import urllib3' 2>&1 | sort
import time: self [us] | cumulative | imported package
...
import time:      1276 |     157184 | urllib3
...
import time:      8586 |      16352 |                 ssl  # max

$ pip install --user urllib3==1.25
$ PYTHONPROFILEIMPORTTIME=1 python -c 'import urllib3' 2>&1 | sort
import time: self [us] | cumulative | imported package
...
import time:      1213 |     522333 | urllib3
...
import time:    318235 |     318875 |             urllib3.packages.rfc3986.misc  # max

```

**Comment by sethmlarson** [comment]
It's almost certainly all of the regular expressions being compiled then. I wonder if we can delay their compilation until they're used for the first time? Hmm

**Comment by sigmavirus24** [comment]
> It's almost certainly all of the regular expressions being compiled then. I wonder if we can delay their compilation until they're used for the first time? Hmm

I have no idea what Kodi is but that sounds like a different kind of misery

**Comment by sethmlarson** [comment]
@sigmavirus24 Might be worse for RPI because of how small the memory is?

**Comment by sigmavirus24** [comment]
Less memory + slower processor makes sense. Either way it's going to slow something down and I'm not confident that start-up time is the right thing to optimize for in this case. If we defer the import, it'll manifest as a new issue where "My first request is super slooow and then everything else is fast, why does urllib3 suck so much?!"

**Comment by haikuginger** [comment]
I agree with @sigmavirus24; -1 on deferring the compilation.

**Comment by sethmlarson** [comment]
Alright, we'll mark this as a no-fix then.

**Comment by shazow** [comment]
I wonder if it's somehow possible to precompile the regexps during the install step and save it. :thinking:

**Comment by sigmavirus24** [comment]
> I wonder if it's somehow possible to precompile the regexps during the install step and save it. 🤔

That would be amazing but I don't think Python is nearly that smart :/

**Comment by shazow** [comment]
Yea I was trying to figure out if there's a way to serialize the compiled re object and load it after, but didn't find any prior work. :|

**Comment by sethmlarson** [comment]
Probably a great opportunity for a pre-compile regex module to appear. One that will load the precompiled C regexes when packaged as a wheel. :)

**Comment by sigmavirus24** [comment]
I'd be curious to see if there's a way to improve the performance of the rfc3986 library without losing the correctness we have right now. Without something like Go's RangeTables to do effective lookups I'm not sure we have a better option plus I've never liked using the regular expressions for this

**Comment by sethmlarson** [comment]
Almost certainly. The regular expressions are needed primarily for validation. Codifying the ABNF validation rules into subroutines instead of regular expressions should be possible.

**Comment by sethmlarson** [comment]
The `URI_MATCHER` pattern is certainly not breaking anyone's CPU. It's the IP literals and subauthority matcher I'm sure that are hurting the most.

**Comment by mikf** [comment]
I've written a small script that measures the regular expression compile times in `rfc3986.misc`:
https://gist.github.com/mikf/fc29e3e461ddd74e30a9d33fcd01d4ee

`RELATIVE_IRI_MATCHER`, `ABSOLUTE_IRI_MATCHER`, and `IPATH_MATCHER` appear to be the 3 worst offenders here and take over 60% of the total time.

**Comment by peno64** [comment]
The results of this small script on the RPI:

TOTAL                   :  3547.403 ms  100.00 %
RELATIVE_IRI_MATCHER    :  924.956 ms   26.07 %
IPATH_MATCHER           :  915.648 ms   25.81 %
ABSOLUTE_IRI_MATCHER    :  767.717 ms   21.64 %
ISUBAUTHORITY_MATCHER   :  301.554 ms    8.50 %
IHOST_MATCHER           :  167.904 ms    4.73 %
IQUERY_MATCHER          :  144.590 ms    4.08 %
IFRAGMENT_MATCHER       :  128.408 ms    3.62 %
HOST_MATCHER            :   40.204 ms    1.13 %
SUBAUTHORITY_MATCHER    :   39.271 ms    1.11 %
IPv6_MATCHER            :   34.756 ms    0.98 %
IPv6_NO_RFC4007_MATCHER :   30.918 ms    0.87 %
RELATIVE_REF_MATCHER    :   13.466 ms    0.38 %
PATH_MATCHER            :   12.558 ms    0.35 %
ABSOLUTE_URI_MATCHER    :   11.449 ms    0.32 %
URI_MATCHER             :    4.315 ms    0.12 %
IRI_MATCHER             :    3.943 ms    0.11 %
QUERY_MATCHER           :    1.718 ms    0.05 %
FRAGMENT_MATCHER        :    1.708 ms    0.05 %
IPv4_MATCHER            :    1.425 ms    0.04 %
SCHEME_MATCHER          :    0.895 ms    0.03 %

And the following script:

import time

t1 = time.time()
import urllib3.packages.rfc3986.misc
t2 = time.time()

print t2 - t1

Gives: 3.82467889786

**Comment by peno64** [comment]
But surely, the kodi addons don't do
import urllib3.packages.rfc3986.misc
Because everything still works with version 1.22 of urllib3 and there is no rfc3986 in there.
Or is it so that importing something else from urllib3 also automatically imports urllib3.packages.rfc3986.misc?
Only then it can be that rfc3986 is the issue. Correct?

**Comment by peno64** [comment]
I did some extra tests:

import time

t1 = time.time()
from urllib3.util import parse_url

t2 = time.time()

print t2 - t1

When done with version 1.22 this gives 

0.272784948349

When done with version 1.25.2 this gives:

3.80189013481

That is more than 10 times slower...

So although rfc3986 is not explicitly used, it slows down also other import from urllib3 like here util because it also imports rfc3986 ...

And in one of the kodi addons I see for example:

from resources.lib.externals.urllib3.poolmanager import PoolManager, proxy_from_url
from resources.lib.externals.urllib3.response import HTTPResponse
from resources.lib.externals.urllib3.util import parse_url
from resources.lib.externals.urllib3.util import Timeout as TimeoutSauce
from resources.lib.externals.urllib3.util.retry import Retry
from resources.lib.externals.urllib3.exceptions import ClosedPoolError
from resources.lib.externals.urllib3.exceptions import ConnectTimeoutError
from resources.lib.externals.urllib3.exceptions import HTTPError as _HTTPError
from resources.lib.externals.urllib3.exceptions import MaxRetryError
from resources.lib.externals.urllib3.exceptions import NewConnectionError
from resources.lib.externals.urllib3.exceptions import ProxyError as _ProxyError
from resources.lib.externals.urllib3.exceptions import ProtocolError
from resources.lib.externals.urllib3.exceptions import ReadTimeoutError
from resources.lib.externals.urllib3.exceptions import SSLError as _SSLError
from resources.lib.externals.urllib3.exceptions import ResponseError
from resources.lib.externals.urllib3.exceptions import LocationValueError

You can imagine how much slower everything becomes...

**Comment by shazow** [comment]
Once upon a time we also discussed allowing consumers to bring their own URL parser. How do we feel about that? (I imagine it as a property override on one of the lower-level classes, or maybe even module-level.)

**Comment by sethmlarson** [comment]
This issue has been bugging my mind so I'm going to alleviate the problems we're seeing on Raspberry PI and other resource constrained systems.

**Comment by sethmlarson** [comment]
The next release of urllib3 (1.25.3) should have a fix for this issue.

**Comment by sethmlarson** [comment]
@peno64 @mikf If either of you gets any time can you try again using rfc3986 v1.3.2 and comparing against v1.3.1? I think it should be a major reduction while still maintaining functionality.

**Comment by mikf** [comment]
I'm getting a 75% reduction on regex compile time and saving a quarter second is quite substantial.
(These time are from a rather weak Desktop CPU, not a Raspberry PI)

|      | 1.3.1 | 1.3.2 | Diff | Diff Percent
| --- | ---:| ---:| --- |:---:
| `time python -c "import rfc3986"` | 428 ms | 188 ms | 240 ms | 56 %
| [benchmark.py](https://gist.github.com/mikf/fc29e3e461ddd74e30a9d33fcd01d4ee) | 330.528 ms | 87.277 ms |  240 ms | 74 %

**Comment by sethmlarson** [comment]
Raspberry Pi would probably be even more substantial due to the tiny amount of RAM.

**Comment by peno64** [comment]
@sethmlarson I would be glad to test on my RPI but I have no idea where to get these 1.3.1 and 1.3.2 versions...

**Comment by sethmlarson** [comment]
`python -m pip install rfc3986==1.3.1` or `... rfc3986==1.3.2`

Test the import time of that module.

**Comment by peno64** [comment]
@sethmlarson
The shell command:
python -m pip install rfc3986==1.3.1
Gives:
/usr/bin/python: No module named pip

Note that a RPI with libreelec has a very limited OS.
If you can point me to the sources, I can install them myself.

**Comment by peno64** [comment]
@sethmlarson

Note that libreelec also doesn't have apt-get

**Comment by sethmlarson** [comment]
Sources can be grabbed from this repo: https://github.com/python-hyper/rfc3986

1.3.2: https://github.com/python-hyper/rfc3986/archive/1.3.2.tar.gz
1.3.1: https://github.com/python-hyper/rfc3986/archive/1.3.1.tar.gz

**Comment by peno64** [comment]
Ok, I test this with following code:

import time

t1 = time.time()
from urllib3.util import parse_url

t2 = time.time()

print t2 - t1

with urllib3 v1.24 I get in average 0.16 seconds

with urllib3 v1.25.2 I get in average 3.68 seconds

To test with 1.3.x, I took urllib3 v1.25.2 and I copied everything from 1.3.x from the rfc3986 folder over it

with 1.3.1 I get in average 3.68 seconds

with 1.3.2 I get in average 0.71 seconds

Note that I get the same results with following script:

import time

t1 = time.time()
import urllib3.packages.rfc3986.misc

t2 = time.time()

print t2 - t1

But then I can't do the test with urllib3 version 1.24 because it does not have rfc3986

Anyway, 1.3.2 give a very nice improvement!

**Comment by sethmlarson** [comment]
That's excellent news. So this update changes the import time of urllib3 1.25.x on Raspberry Pi from 3.68s -> 0.71s which is a reduction of ~80%. :tada: Still a good deal slower than 1.24.x but much more acceptable.

**Comment by ofek** [comment]
@sethmlarson Hello again! Any idea when 1.25.3 will be out?

**Comment by sethmlarson** [comment]
@ofek I'm trying to get that release prepared today while traveling.

**Comment by dagwieers** [comment]
@sethmlarson I am surprised you are [repeating](https://github.com/urllib3/urllib3/issues/1590#issuecomment-488099404) [here](https://github.com/urllib3/urllib3/issues/1590#issuecomment-491919805) that 1GB of RAM as tiny (wrt. Raspberry Pi). Not sure how much RAM you expect an http library should need ?

**Comment by dagwieers** [comment]
> But then I can't do the test with urllib3 version 1.24 because it does not have rfc3986

@peno64 It means that the overhead of rfc3986 on v1.24 is 0ms :-)

**Comment by sethmlarson** [comment]
@dagwieers I agree that there is an issue with import times on devices that can't hold a lot of RAM for a one-time evaluation of complex regular expressions. We made the decision to use rfc3986 over our existing URL parser due to a lot of vulnerabilities related to URLs and parsers and how they target differences or non-conformities between parsers.

We value correctness and security quite a bit when it comes to networks, unfortunately at the moment at the expense of slower import times. If you'd like to try to improve things the library is open source and I can review changes and help with direction if needed.

**Comment by peno64** [comment]
Where are the times that I had to make programs in a 54 kb memory space... On a Wang minicomputer.
And I still have more than 10 years before I can even think about pension...
;-)

**Comment by dagwieers** [comment]
Now that urllib3 v1.25.3 has been release, we can see that importing urllib3 v1.25.3 takes **about 800ms** on RPi, whereas importing both urllib and urllib2 together only takes 180ms. So IMO this release is still an unacceptable regression on RPi that slows down almost every add-on needlessly.

In comparison, urllib3 v1.24.1 takes **only 260ms** to import, which makes v1.25.3 about **3x slower** to be imported.

**Comment by sethmlarson** [comment]
I'm working on improving the speed while still keeping the correctness. For now urllib3 1.24.3 is safe from the most critical URL vulnerabilities related to CRLF injection.

**Comment by dagwieers** [comment]
urllib3 v1.24.3 is about the same import speed as urllib3 v1.24.1, unfortunately (RPi) Kodi users are now exposed to v1.25.3, slowing down all affected systems :-/

**Comment by sethmlarson** [comment]
Right, I'm aware of Kodi having to re-import modules per-use. I'll see what we can do.

**Comment by dagwieers** [comment]
I have been testing some generic improvements to the regexp that seem to make a difference, but I need to test these on Raspberry Pi this evening to see if I can reproduce the improvements I see. (The variations of multiple runs also makes it hard to objectively see smaller improvements...)

**Comment by dagwieers** [comment]
Version 1.25.4 seems to have dropped the dependency to **rfc3986** which brought performance on Raspberry Pi back to the glory days ;-) Thanks for that!

**Comment by sethmlarson** [comment]
@dagwieers Glad the refactor has brought back some improvements to import time. :)
