### ISSUE TITLE
urllib3 discards valid SSL DNS wildcards because they are invalid IDNA DNS names.

### ISSUE THREAD

**Issue by Kownt** [urllib3/urllib3#1594]
According to [RFC2818](https://tools.ietf.org/html/rfc2818.html) partial wildcards are supported.

> Names may contain the wildcard
   character * which is considered to match any single domain name
   component or component fragment. E.g., \*.a.com matches foo.a.com but
   not bar.foo.a.com. f\*.com matches foo.com but not bar.com.

Due to urllib3's usage of IDNA(namely due to https://github.com/urllib3/urllib3/blob/master/src/urllib3/contrib/pyopenssl.py#L186)  these valid TLS DNS wildcards are discarded before they can be used as a match in SSL hostname matching.

Expected behavior:
The TLS certificate for the DNS address f*.com should be valid for foo.com even though it is not a valid IDNA name, as TLS wildcards are not required to be valid IDNA.

Actual behavior:
f*.com is treated as an invalid IDNA A-Record and is stripped from the Certificates DNS names before the hostname can be matched against under https://github.com/urllib3/urllib3/blob/master/src/urllib3/packages/ssl_match_hostname/_implementation.py#L25.

**Comment by sethmlarson** [comment]
Interesting, it looks like I need to do more investigation for this issue. Are you able to put together a patch with the proper behavior?

**Comment by sethmlarson** [comment]
Also I may be misunderstanding but is this as simple a fix as changing this:
```python
    name = idna_encode(name)
    if name is None:
        return None
    elif sys.version_info >= (3, 0):
```

to this:

```python
    name = idna_encode(name)
    if name is None:
        return name
    elif sys.version_info >= (3, 0):
```

Or maybe we need to be more selective on returning `None` for any `IDNAError`.

**Comment by sethmlarson** [comment]
Some information with how wildcards interact with A-labels and U-labels: https://tools.ietf.org/html/rfc6125#section-7.2
I'm in favor of supporting partial widlcards in the leftmost label as long as it's not puny-encoded. Thoughts @urllib3/maintainers?

**Comment by haikuginger** [comment]
I'm -0; I don't have a strong opinion either way. but would tend towards a thumbs-down. Do we have examples of mainstream CAs issuing certificates of this form? This hasn't come up before, and feels like a feature that's opening a big can of worms as far as potential security-critical bugs.

**Comment by sethmlarson** [comment]
I'm going to close this issue as the code that would need to change comes directly from pyca/cryptography and their code doesn't yet support partial wildcards either which makes me think this is a rare occurrence.
