### ISSUE TITLE
Make a logo for urllib3

### ISSUE THREAD

**Issue by shazow** [urllib3/urllib3#1597]
@sethmlarson had a cute idea: `ur//ib3`, kinda inspired by Mozilla's `moz://a`.

Would be fun to make stickers for future PyCons and whatnot.

Maybe someone is inspired to take a shot at this?

Or maybe we can convince a designer of one of the corporate sponsors to take a stab at it? :D

**Comment by sethmlarson** [comment]
I know @theacodes mentioned asking the individual who created her logos and art. :)

**Comment by theacodes** [comment]
She'd be a great choice if we want a more illustrated logo (like Nox), but a simple typography-based logo would be great as well. I have a graphic designer that could handle that.

**Comment by alexwlchan** [comment]
Okay, so with the disclaimer that my design training comes from the school of MS Paint, I had a quick go at mocking something up this morning:

![Screenshot 2019-05-23 at 08 01 52](https://user-images.githubusercontent.com/301220/58232264-09098880-7d31-11e9-82b2-a9ffe42f398e.png)

The font is Monaco which I don’t think you can license? I think Apple owns it? So you’d have to draw your own letters. But it gives you the idea. (I did tweak the three to have a pointy top rather than a curly top.)

I played with a couple of variants on the slashes – first a solid black, but that’s quite imposing, so I tried doing it in outline – with the thicker weight I kind of dig it? I also poked at putting other colours in the slash because who doesn't want rainbow-pride/trans-pride variants of their logo, right? :D

**Comment by alexwlchan** [comment]
(What if you tilted the “i” to match the slashes?)

**Comment by shazow** [comment]
@alexwlchan Cute! Thank you for sharing. :) The rainbow is a great idea.

**Comment by sigmavirus24** [comment]
I'm worried about the possibility of infringing on the moz://a logo by doing this. I'd be surprised if that isn't trademarked and the semblance would be considered too close for comfort. Does anyone else share those reservations? Could we perhaps draw inspiration without being so close to their logo?

**Comment by pquentin** [comment]
It's also close to the curl logo: https://daniel.haxx.se/blog/2016/05/27/a-new-curl-logo/

**Comment by sethmlarson** [comment]
I'll have to investigate whether the stylized L's are covered. This is something we talked about :)

**Comment by alexwlchan** [comment]
An idea I didn’t sketch out this morning: URLs are often seen in a browser address bar. So set it in a thing that looks like that?

**Comment by sigmavirus24** [comment]
> I'll have to investigate whether the stylized L's are covered. This is something we talked about :)

When you say "This is something we talked about" who is the "we"? Have you already talked to Mozilla about this? If they didn't object already and I'm just bringing us back to a prior point, let me know. I just know that organizations need to police trademark related things strictly in order to keep them (see also the PSF Trademark WG) and I don't like creating busy work for people when that can be avoided. (Nor do I want us to update the logo and then have to immediately change it. Plus it can be scary to be on the receiving end of a Trademark legal letter)

**Comment by sethmlarson** [comment]
Sorry for being vague, I meant @shazow @theacodes and I as "we", I haven't spoken to Mozilla or curl.

**Comment by sigmavirus24** [comment]
Feel free to tell me to bugger off, too. :)

**Comment by sethmlarson** [comment]
Oh no, if anything I'll be begging you to stay. :)

**Comment by theacodes** [comment]
I can reach out to Moz to check.

@alexwlchan are you interested in polishing things up to the final logo? I can help with font licensing and such. Or, if you just want to leave us with the concept I have a few designers that can take over from here. :)

**Comment by sigmavirus24** [comment]
Also, as an aside, I wonder if we could throw a pidgeon in there in homage to all of the April Fools RFCs about [IPoAC](https://en.wikipedia.org/wiki/IP_over_Avian_Carriers) - although, April Fools is a pain and maybe this would be a bad idea to encourage it.

**Comment by theacodes** [comment]
A pigeon would be excellent if we decide to hire an *illustrator* (vs a graphic designer) for the logo (think Moz logo vs Firefox logo).

**Comment by theacodes** [comment]
I've emailed Moz. Will keep y'all updated.

**Comment by sethmlarson** [comment]
Wow that's a great idea with the pigeon! I love that. :bird:

**Comment by theacodes** [comment]
A little pigeon with a letter in its beak. A carrier pigeon. :3

Let's get the lettering logo sorted and then I can reach out to an
illustrator to make that one as well. Why not both? :)

**Comment by haikuginger** [comment]
I like all these options! On the slash-centric ones, maybe move the slashes up so that there's a consistent baseline under all the characters?

I could also maybe see something like `urllib:///` with the slashes being Roman numerals 😂

**Comment by sethmlarson** [comment]
@haikuginger But our URL parser isn't WHATWG compliant :P

**Comment by ryanfeeley** [comment]
quick and dirty with random colour choice, but you could lean into the library idea with something book like… this is just TextEdit.

<img width="732" alt="image" src="https://user-images.githubusercontent.com/68213/58279730-28260b80-7d6d-11e9-8bc7-291943522797.png">

**Comment by shazow** [comment]
Ryan is a friend, I'm amused that it's leaning into the "lib3" part of the name, arguably the worst part. ;)

**Comment by shazow** [comment]
> A little pigeon with a letter in its beak. A carrier pigeon. :3

That letter's name? The number 3.

**Comment by ryanfeeley** [comment]
Written out it is **urᴉᴉib³**

**Comment by sethmlarson** [comment]
I really love the colors there. Emphasizing the 3 twice is great. Then we can use the "!!i" as a square logo too? Ah I love it all :D

**Comment by sigmavirus24** [comment]
What if the pidgeon is carrying the 3 away?! That way it's like it's removing @shazow's most hated thing ;)

**Comment by alexwlchan** [comment]
@theacodes I’m shocked, nay, insulted that I haven’t won you over with my clear MS Paint-level prowess. 😉 

I’d be happy to polish up typographical variants, but a pigeon is way beyond my artistic skills.

**Comment by sethmlarson** [comment]
I'm actually in love with @ryanfeeley's take, the bold font and superscript 3 especially. Very recognizable.

**Comment by haikuginger** [comment]
I also really like @ryanfeeley's take on this.

**Comment by haikuginger** [comment]
Riffing on @ryanfeeley's take, here are a couple potential square logos. I kind of enjoy the network-like feel of the negative-space one.

![Untitled drawing](https://user-images.githubusercontent.com/7773758/58288922-d2039900-7d69-11e9-9d94-bd552f645883.png)

**Comment by shazow** [comment]
The negative-space one looks like a llama-duck.

**Comment by haikuginger** [comment]
> The negative-space one looks like a llama-duck.

CANNOT UNSEE IT.

**Comment by haikuginger** [comment]
Tweaked version with slightly different whitespace.

![urllib3 logo 2](https://user-images.githubusercontent.com/7773758/58290237-e2b60e00-7d6d-11e9-9086-34d78e2459a6.png)

**Comment by sigmavirus24** [comment]
Also, to be clear, I was joking about the pidgeon and also like @ryanfeeley's riffing + the square logos @haikuginger has shown here. Y'all are amazing for having any kind of artistic skill. :pray:

**Comment by theacodes** [comment]
Wait... how do we ultimately decide what to go with?

Am I... am I in charge here? D:

**Comment by sigmavirus24** [comment]
I think the most magical person is the person who makes the decision

**Comment by haikuginger** [comment]
One more. With a 15º tilt.

![urllib3 logo 3](https://user-images.githubusercontent.com/7773758/58293059-e602c700-7d78-11e9-996d-54f5afc8de95.png)

**Comment by ryanfeeley** [comment]
To perfect the square icon for favicon use, I put it on a 16×16 grid. The stems are 4px wide, and the negative space is 3px wide. This way, no blurred edges at small sizes.
<img width="384" alt="image" src="https://user-images.githubusercontent.com/68213/58338544-e1d8b700-7e15-11e9-8041-0a4b45e5322a.png">

**Comment by theacodes** [comment]
Let's see that in the trans colors. :)

**Comment by ryanfeeley** [comment]
Like this?
<img width="375" alt="image" src="https://user-images.githubusercontent.com/68213/58345640-d477f880-7e26-11e9-81bb-ebd34fc1de04.png">

**Comment by theacodes** [comment]
Too many colors, though I ain't mad about it. :)

https://en.wikipedia.org/wiki/Transgender_flags#/media/File:Transgender_Pride_flag.svg

**Comment by alexwlchan** [comment]
💜 Ryan’s logo, so much nice than mine

(Also, that 16x16 grid comment has finally made me realise why one of my other icons always looks blurry. Obvious in hindsight!)

**Comment by alexwlchan** [comment]
I took Ryan’s design and played with it a bit, trying to get versions of the other letters that match the weights of the coloured rectangles. Still Helvetica letters in the SVG rather than actual drawn curves and the “3” looks a bit off, but I like the concept. :)

<img width="673" alt="Screenshot 2019-05-26 at 19 30 45" src="https://user-images.githubusercontent.com/301220/58385731-d095d300-7fec-11e9-9358-8274cd2b83aa.png">

**Comment by sethmlarson** [comment]
What are everyone's thoughts on making the two L's solid?

**Comment by alexwlchan** [comment]
@sethmlarson I think that would lose a lot of the distinctiveness.

**Comment by sethmlarson** [comment]
That's true, I love it in its current state too. :)

**Comment by sethmlarson** [comment]
I'm going to make the executive decision and go with @ryanfeeley for a banner logo and @haikuginger's square logo. Thanks everyone, this really will bring a lot of character to this repository. :)

**Comment by shazow** [comment]
Yay great work! :confetti_ball:

**Comment by haikuginger** [comment]
@sethmlarson do you want me to post a PR with the SVG for the square icon? Also, which one did you mean? Looking back, I went a bit overboard 😂

**Comment by pquentin** [comment]
This one: https://github.com/urllib3/urllib3/blob/master/docs/images/logo.png 😄 

But I think we should use the grid from @ryanfeeley for the square logo, so that we can use it in the favicon for our docs. And try to keep your colors if possible?

We definitely want to use SVG, the logo is perfect for this. I'm currently working on this for the full logo, the current version is:

 <img src="https://raw.githubusercontent.com/pquentin/urllib3/pquentin-patch-1/docs/images/logo.svg?sanitize=true" width="500px" />

**Comment by ryanfeeley** [comment]
Here's an optimized SVG of the original. I just exported the `urᴉᴉib³` from TextEdit and cleaned it up in Illustrator. [urllib.svg.zip](https://github.com/urllib3/urllib3/files/3816946/urllib.svg.zip)

**Comment by pquentin** [comment]
@ryanfeeley Awesome thanks, that looks great! Is this logo under a specific license?

**Comment by shazow** [comment]
@ryanfeeley Ideally we can merge it under the same license as the rest of the repo (MIT), or worst case some variant of CC.

**Comment by ryanfeeley** [comment]
Happily licensed under Attribution 4.0 International (CC BY 4.0)  https://creativecommons.org/licenses/by/4.0/

**Comment by pquentin** [comment]
Great! @shazow where do we want to record this information?

**Comment by sethmlarson** [comment]
We can add a README.md within the images directory?

**Comment by shazow** [comment]
For utilized component licenses, you typically put them in a NOTICE file.
