### ISSUE TITLE
support for HTTP Digest Authentication

### ISSUE THREAD

**Issue by fwjavox** [urllib3/urllib3#1600]
Currently only basic authentication is implemented as far as I can see.
Is there a way to use digest authentication within urllib3?

**Comment by sethmlarson** [comment]
RFC 2617 Digest Authentication isn't supported as a first-class citizen by urllib3 however from a quick Google search [I found a package](https://github.com/dimagi/python-digest) that can aid in the computation of the digest and then you'd only have to set the `WWW-Authenticate` header.
