### ISSUE TITLE
Close unfinished requests

### ISSUE THREAD

**Issue by EpicWink** [urllib3/urllib3#1602]
I have a use-case for wanting to stop a request to a server before the server acknowledges (see: long-polling). There are arguments against allowing the user to abort such a request, but I'm always for giving the user the control, allowing them to do what they want.

The problem currently is when other threads are performing requests, you lose access to their socket connections, so you can't close them. Simply keeping track of those released connections in the ConnectionPool instance allows any thread to close whichever connections they want.

In my use-case, I want to close all released connections in the pool (when I get a response from one of them; ignore race-conditions for this example). My server is already set up to handle closed connections.

If this feature were to be implemented, a decision would have to be made on how high-level the ability would be exposed up to.

I posted a comment [here](https://github.com/kennethreitz/requests/issues/1353#issuecomment-489825930), but I realised that this functionality has to come from `urllib3`, not `requests`.

Related: https://github.com/urllib3/urllib3/issues/779 (but for unfinished responses).

**Comment by sethmlarson** [comment]
I'm not sure urllib3 is the right library for you, we don't offer that sort of low-level control over sockets. Going to close this one since it hasn't garnered any additional interest.
