### ISSUE TITLE
parse_url() for urllib3 1.25.x doesn't allow port numbers higher than 2**16-1

### ISSUE THREAD

**Issue by Bllacky** [urllib3/urllib3#1610]
Unfortunately, I can't give many details regarding the issue because I don't know what exactly it would be relevant.

I am running a service, using Flask, with python 3.6.8.

I've upgraded requests to 2.22.0.

If I upgrade urllib3 to 1.25.2 the service I am opening on whatever port is no longer accessible through other python scripts.

I get InvalidURL('Failed to parse: http://localhost:96768/service',)

In the service.py
@app.route("/service", methods=["POST"])
@wrap_exceptions

 app.run("0.0.0.0", port=args.port, debug=args.debug, threaded=False)
there are no exceptions when running service.py

In a program that accesses the service I have something like this:
URL = "http://localhost:{}/service"

from the URL I then make a list of urls, with different ports. Each port has the same service with slightly different parameters.

and then
get_response = partial (requests.post, data=data)
        response = get_first (get_response, urls)

If I revert to 1.24.3 everything works fine.

**Comment by sethmlarson** [comment]
It's because your port is greater than 65535 because a TCP header is only allowed 16 bits of space for the port thus rfc3986 rejects larger port numbers. Do you happen to be using an alias to access ports higher than 65535?

**Comment by Bllacky** [comment]
> 
> 
> It's because your port is greater than 65535 because a TCP header is only allowed 16 bits of space for the port thus rfc3986 rejects larger port numbers. Do you happen to be using an alias to access ports higher than 65535? cc @sigmavirus24

Interesting. I suppose rfc3986 was implemented after 1.24.3.
Not sure what you mean by aliases, but I don't think I am using them. 

I use these ports only for internal, localhost to localhost connections and I choose high port numbers so I don't conflict with any other service that might be running.

In the future, I plan on putting the service on a separate machine than the programs that access it on another.

So is there any workaround or solution to this? I mean one obvious answer is to choose lower port numbers, but I see that as an unnecessary hard limitation.

**Comment by sethmlarson** [comment]
Probably doesn't need to be a hard limit there. I can remove that requirement.

**Comment by Bllacky** [comment]
After some consideration and given that different users may have different needs than mine. I would say this:

1. There should be no hard limit for using internal port numbers as long as the URL contains "localhost" or "127.0.0.1" 
2. However, my understanding that for external ports, using high port numbers would often be a typo, so it is helpful to know if you are doing something wrong. You can impose a hard limit here or issue a warning.

For situation number 2, I suggest some helpful message to be displayed, like "Warning - Port number outside 1 - 65535 range".

Thank you very much for all your work!

**Comment by sethmlarson** [comment]
Problem is is that it sounds like there's ways to use higher numbered ports even for external addresses via [https://en.wikipedia.org/wiki/IP_aliasing](IP aliasing). So probably removing the limit is the best bet for complete compatibility. Any issues people have with typos, etc in ports will probably be caught by DNS.

**Comment by Bllacky** [comment]
> 
> 
> Problem is is that it sounds like there's ways to use higher numbered ports even for external addresses via [IP aliasing](https://en.wikipedia.org/wiki/IP_aliasing). So probably removing the limit is the best bet for complete compatibility. Any issues people have with typos, etc in ports will probably be caught by DNS.

I see, in that case, I agree. If anything, you could issue a warning and carry on with the code execution.

**Comment by haikuginger** [comment]
I'd like to see some more research into this before proceeding to see what exactly is making this sort of high-number port usage possible behind the scenes, given that conforming IP packets only have a `uint16` for the port number field. `curl` doesn't allow for connecting on ports higher than `2<<15 - 1`, so I'm wondering at what level things are happening that allow for this behavior.

In my testing with the `socket` library, I see a distinct error when attempting to bind to a port higher than `2<<15 - 1`. I really want to ensure that both 1) this isn't some other sort of bug that's allowing for this nonstandard behavior and that 2) this is an expected and deliberate nonconformity.

```python3
>>> import socket
>>> in_range = socket.socket()
>>> in_range.bind(('localhost', 65535))
>>> in_range
<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 65535)>
>>> out_of_range = socket.socket()
>>> out_of_range.bind(('localhost', 65536))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: getsockaddrarg: port must be 0-65535.
```

**Comment by sethmlarson** [comment]
@haikuginger `socket.create_connection()` doesn't have an issue with ports higher than 65535, just reports that there is no connection available. I would assume that from the service side you're not actually binding to a port >65535 but instead binding to one less than that but to connect to that service you'd need to use the port 65535+[port bound by the service]?

@Bllacky You say you're using Flask to bind to a high port on localhost, are you using gunicorn to deploy or? Basically what does your service address and port configuration look like.

**Comment by haikuginger** [comment]
@sethmlarson I do see a different error between 65535 and 65536 when there isn't an open socket listening. I just want to make sure we understand the full scope of the behavior involved (is it platform-specific? does it behave differently under different configurations within a platform? etc.)

```python3
>>> import socket
>>> socket.create_connection(('localhost', 65535))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jshapiro/.pyenv/versions/3.6.6/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/Users/jshapiro/.pyenv/versions/3.6.6/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused
>>> socket.create_connection(('localhost', 65536))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jshapiro/.pyenv/versions/3.6.6/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/Users/jshapiro/.pyenv/versions/3.6.6/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

**Comment by sethmlarson** [comment]
Totally agree that we should try to understand the nuances here. On Linux Python 3.7 I'm receiving a different exception than you are:

```python
>>> import socket
>>> socket.create_connection(("localhost", 65536))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/slarson/.pyenv/versions/3.7.0/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/home/slarson/.pyenv/versions/3.7.0/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by Bllacky** [comment]
@sethmlarson 

I am using Flask native functionality for running a service. Right now, I am still developing the service using it, so I'm not concerned about security or performance.

I supply the port number via an argument to the python script:

```
parser.add_argument("-p", "--port", required=True, type=int, help="port number")

app = Flask(__name__)

if __name__ == "__main__":
    atexit.register(stop_driver,DRIVER)
    try:
        app.run("0.0.0.0", port=args.port, debug=args.debug, threaded=False)
    except Exception as e:
        print(str(e))
```

then I run:
`python service.py -p 96668 -i /tmp/img`

the result looks like this:
`
 * Serving Flask app "service" (lazy loading)
 * Environment: production
 WARNING: This is a development server. Do not use it in a production deployment.
 Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:31132/ (Press CTRL+C to quit)
`

I know it says running on port 31132, but the service will never reply on port 31132, it will answer on 96668.
However, port 31132 is not the port the service will respond to. I did not supply that port number.
http://flask.pocoo.org/docs/1.0/api/ see ` run `section,

**Comment by pquentin** [comment]
(It was not obvious to me that 31132 = 96668 - 65536, so I thought I'd mention it.)

**Comment by sethmlarson** [comment]
What platform are you developing on and can you attach the output of an ifconfig or ipconfig in a text file? I'm wondering about what your setup looks like.

**Comment by Bllacky** [comment]
I'm developing on Linux ( Centos 7 ).

Here is the output you have requested:
# ifconfig
```
eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 86.xxx.xxx.xx6  netmask 255.255.255.0  broadcast 86.xxx.xxx.255
        inet6 fe80::xxx:xxx:xxx:xxx  prefixlen 64  scopeid 0x20<link>
        inet6 fec0::xxx:xxx:xxx:xxx  prefixlen 64  scopeid 0x40<site>
        ether fc:xxx:xxx:xxx:xxx:xxx  txqueuelen 1000  (Ethernet)
        RX packets 10229471  bytes 9273463283 (8.6 GiB)
        RX errors 0  dropped 170  overruns 0  frame 0
        TX packets 8818995  bytes 5478692215 (5.1 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 20  memory 0xf7e00000-f7e20000

enp2s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.xxx.xxx.102  netmask 255.255.255.0  broadcast 192.xxx.xxx.255
        inet6 fe80::xxx:xxx:xxx:xxx  prefixlen 64  scopeid 0x20<link>
        inet6 fec0::xxx:xxx:xxx:xxx  prefixlen 64  scopeid 0x40<site>
        ether fc:xxx:xxx:xxx:xxx  txqueuelen 1000  (Ethernet)
        RX packets 4797918  bytes 1080246290 (1.0 GiB)
        RX errors 0  dropped 92  overruns 0  frame 0
        TX packets 11767625  bytes 12621395264 (11.7 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 1705492  bytes 8217171559 (7.6 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1705492  bytes 8217171559 (7.6 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp3s0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether fa:xx:xx:xx:xxx:xx  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions
``` 0

**Comment by haikuginger** [comment]
Testing on Xubuntu, I'm seeing clean rollaround for both `socket.bind` and `socket.create_connection` in the stdlib - this appears to be happening during the `getaddrinfo` call:

```python3
>>> getaddrinfo('localhost', 96668)
[
    (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 31132)),
    ...
]
```

Meanwhile, `getaddrinfo` on macOS rejects the out-of-range port entirely and the lookup fails:

```python3
>>> getaddrinfo('localhost', 96668)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jshapiro/.pyenv/versions/3.6.6/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

**Comment by sethmlarson** [comment]
The point I'm still hung up on is when @Bllacky said (emp mine):
> I know it says running on port 31132, **but the service will never reply on port 31132, it will answer on 96668**. I did not supply the 31132 port number.

Which implies that somehow on that system the port number matters and doesn't wrap around. @Bllacky what do you get when you run `socket.getaddrinfo("localhost", 96668)`?

**Comment by sethmlarson** [comment]
Also I'm running on CentOS 7 as well and I'm seeing the wrap-around that @haikuginger is experiencing on Xubuntu.

**Comment by haikuginger** [comment]
Yeah, looks like this is a known issue that's basically inherited from C and we're now blocking it through appropriate URL validation:

https://bugs.python.org/issue24169

I suspect that, if anything, Flask is refusing to respond based on a mismatched Host header and is in fact exclusively listening on 31132 due to platform-specific behavior. Unless we can 1. prove otherwise (e.g., `curl -v 'http://localhost:31132/' -H 'Host: localhost:31132'` and 2. figure out a deliberate rationale, I would opt towards closing this as NTBF.

**Comment by sethmlarson** [comment]
Ah that would make sense. I can test a quick mock app and see I can reproduce the refusal, if that's the case I think we can close this as not an issue.

**Comment by sethmlarson** [comment]
I'm unable to reproduce the refusal with this script:

```python
import flask


app = flask.Flask(__name__)


@app.route("/", methods=["GET"])
def index():
    return "Hello, world"

if __name__ == "__main__":
    app.run(host="localhost", port=96668)
```

run with:

`python app.py`

and here's the console output from curl.

```console
bash-4.2$ curl http://localhost:31132/ -H 'Host: localhost:96668'
Hello, world
bash-4.2$ curl http://localhost:31132/ -H 'Host: localhost:31132'
Hello, world
```

Seems happy with either header?

**Comment by Bllacky** [comment]
> 
> 
> The point I'm still hung up on is when @Bllacky said (emp mine):
> 
> > I know it says running on port 31132, **but the service will never reply on port 31132, it will answer on 96668**. I did not supply the 31132 port number.
> 
> Which implies that somehow on that system the port number matters and doesn't wrap around. @Bllacky what do you get when you run `socket.getaddrinfo("localhost", 96668)`?

`print(repr(socket.getaddrinfo("localhost", 96668)))`
result:
`[(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 31132, 0, 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('::1', 31132, 0, 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_RAW: 3>, 0, '', ('::1', 31132, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 31132)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('127.0.0.1', 31132)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_RAW: 3>, 0, '', ('127.0.0.1', 31132))]`

`print(repr(socket.getaddrinfo("localhost", 31132)))`
`
[(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 31132, 0, 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('::1', 31132, 0, 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_RAW: 3>, 0, '', ('::1', 31132, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 31132)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('127.0.0.1', 31132)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_RAW: 3>, 0, '', ('127.0.0.1', 31132))]`


Interesting that you cannot reproduce the refusal. Yes, that is exactly the app I am having.

**Comment by sethmlarson** [comment]
Oh you're able to connect to the wrapped port? Then this is not an issue, you're experiencing truncation of the high port numbers by platform-specific behavior and should be connecting to the truncated port.

**Comment by Bllacky** [comment]
Then why this doesn't happen with urllib3 1.24.3 (which I am using right now) and only with 1.25.x?

**Comment by sethmlarson** [comment]
Because in 1.25.x we switched to a stricter URL parser that checks that a port will fit into a TCP header and guarantee that platform-specific behavior doesn't occur allowing the user to mistakenly connect to a different service (like from port wrap around/truncation). I can't explain why your service isn't letting you connect to 31132 as clearly your call to `getaddrinfo()` is returning back port 31132 which would be the port that Flask binds to.

Unless you have some more information my recommendation would be to stick with ports below 65536, there are ways to guarantee that ports don't conflict with existing ports.

**Comment by Bllacky** [comment]
Ok. That makes sense. Will make the changes.
