### ISSUE TITLE
urllib3.exceptions.LocationValueError: No host specified.

### ISSUE THREAD

**Issue by jlegido** [urllib3/urllib3#1612]
Hi there.

First of all many thanks to all people involved in this project.

I'm facing an issue with version 1.25.2 of this library, which is not happening with version 1.24.1.

Steps to reproduce:

1. Create "requirements.txt" with below content:

```
selenium
urllib3==1.24.1
#urllib3==1.25.2
```

2. Create "Dockerfile" with below content:

```
FROM python:3-stretch

ADD requirements.txt .

RUN pip install -r requirements.txt

COPY test.py /test.py
```

3. Create "test.py" with below content:

```
#!/usr/bin/python

from selenium import webdriver

host = 'selenium'
port = '4444'
url = host + ':' + port + '/wd/hub'

desired_capabilities = {
    'browserName': 'firefox',
    'javascriptEnabled': True,
}

driver = webdriver.Remote(command_executor = url, desired_capabilities =
                                                          desired_capabilities)
print('Success')
driver.quit()
```

4. Create "docker-compose.yaml" with below content:

```version: '3.7'

services:

 urllib3:
  container_name: urllib3
  build:
   context: .
  stdin_open: true
  tty: true

 selenium:
  container_name: selenium
  image: selenium/standalone-firefox
  # Mandatory, to avoid "Message: Failed to decode response from marionette" error
  shm_size: 128m
```

5. Bring up the environment

```
docker-compose up -d --build
```

6. Test it:

```
docker exec -ti urllib3 python /test.py
```

Expected output:

```
Success
```

7. Now edit "requirements.txt"

```
vim requirements.txt
```
And specify version 1.25.2 of urllib3:

```
selenium
#urllib3==1.24.1
urllib3==1.25.2
```

8. Bring down the environment

```
docker-compose down
```

9. Bring up the environment

```
docker-compose up -d --build
```

10. Test it:

```
docker exec -ti urllib3 python /test.py
```

Expected output:

```
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    desired_capabilities)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 402, in _request
    resp = http.request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.7/site-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 315, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "/usr/local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 222, in connection_from_host
    raise LocationValueError("No host specified.")
urllib3.exceptions.LocationValueError: No host specified.
```

11. (Optional) Cleanup

```
docker-compose down
docker rmi localhost/urllib3:latest
```

**Comment by sethmlarson** [comment]
I'm unable to reproduce your issue either with a scheme or without one:

```python
>>> from urllib3.util import parse_url
>>> parse_url("192.168.64.4:4444/wd/hub")
Url(scheme=None, auth=None, host='192.168.64.4', port=4444, path='/wd/hub', query=None, fragment=None)
>>> parse_url("https://192.168.64.4:4444/wd/hub")
Url(scheme='https', auth=None, host='192.168.64.4', port=4444, path='/wd/hub', query=None, fragment=None)
```

And looking at [webdriver source code](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/remote_connection.py#L106) there's a giant block of code that transforms the URL before handing it off to urllib3 that might be the culprit?

Could you try printing `self.driver._url` right after you create the driver instance? This may be a selenium bug instead of a urllib3 bug.

**Comment by sethmlarson** [comment]
(Also I suspect you can fix your issue by adding `http://` to the beginning of your URL)

**Comment by jlegido** [comment]
@sethmlarson thanks for your quick reply.

I updated the description to provide a quick and clear step by step guide about how to reproduce the issue.

As I said using version 1.24.1 of urllib3 I'm not able to reproduce the issue

**Comment by sethmlarson** [comment]
Did you try adding http:// to the beginning of your URL? I can dig deeper into this later.

**Comment by jlegido** [comment]
Adding "http" at the beginning of the URL makes no difference.

**test.py**

```
#!/usr/bin/python

from selenium import webdriver

host = 'selenium'
port = '4444'
url = 'http://' + host + ':' + port + '/wd/hub'
print(url)

desired_capabilities = {
    'browserName': 'firefox',
    'javascriptEnabled': True,
}

driver = webdriver.Remote(command_executor = url, desired_capabilities =
                                                          desired_capabilities)
print('Success')
driver.quit()
```

**Comment by jlegido** [comment]
I think makes sense to re-open this issue.
Thanks

**Comment by jlegido** [comment]
Hi again.

Could you please at least re-open this issue?

I think makes sense in order to provide it more visibility,

Thanks.

**Comment by sethmlarson** [comment]
Can you try with latest master? Also I still want to see the result of `print(driver._url)`.

**Comment by jlegido** [comment]
@sethmlarson same issue with latest master:

**requirements.txt**

```
selenium
#urllib3==1.24.1
#urllib3==1.25.2
```

**Dockerfile**

```
FROM python:3-stretch

RUN pip install git+https://github.com/urllib3/urllib3

ADD requirements.txt .

RUN pip install -r requirements.txt

COPY test.py /test.py
```

**docker-compose.yaml**

```
version: '3.7'

services:

 urllib3:
  container_name: urllib3
  build:
   context: .
  stdin_open: true
  tty: true

 selenium:
  container_name: selenium
  image: selenium/standalone-firefox
  # Mandatory, to avoid "Message: Failed to decode response from marionette" error
  shm_size: 128m
```

BTW driver object has no _url attribute.

```
Traceback (most recent call last):
  File "/test.py", line 17, in <module>
    print(driver._url)
AttributeError: 'WebDriver' object has no attribute '_url'
```

Many thanks for your time

**Comment by sethmlarson** [comment]
I followed your reproduction steps with docker-compose and was unable to get a failure. The URL I was receiving is: `http://selenium:4444/wd/hub`.

**Comment by joaoheron** [comment]
I'm facing the same issue on Selenium==3.141.0 and urllib3==1.25.4.

**Comment by menty666** [comment]
Same, with 3.1.4.0 and urlib3 1.26.7 as well as 1.25.11

This was with 1.25.11 in place:  

`        Traceback (most recent call last):
          File "C:\Program Files\Python310\lib\site-packages\getgauge\executor.py", line 33, in execute_method
            step.impl(*params)
          File "c:\githubfiles\ecp\test_automation\step_impl\shared_impl\drivers\eg_drivers.py", line 154, in get_ecp_driver
            desktop = get_desktop_driver(remote)
          File "c:\githubfiles\ecp\test_automation\step_impl\shared_impl\drivers\eg_drivers.py", line 113, in get_desktop_driver
            desktop = appium.webdriver.Remote(command_executor=remote, desired_capabilities=desired_capabilities)
          File "C:\Program Files\Python310\lib\site-packages\appium\webdriver\webdriver.py", line 151, in __init__
            super().__init__(
          File "C:\Program Files\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
            self.start_session(capabilities, browser_profile)
          File "C:\Program Files\Python310\lib\site-packages\appium\webdriver\webdriver.py", line 225, in start_session
            response = self.execute(RemoteCommand.NEW_SESSION, parameters)
          File "C:\Program Files\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 319, in execute
            response = self.command_executor.execute(driver_command, params)
          File "C:\Program Files\Python310\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 374, in execute
            return self._request(command_info[0], url, body=data)
          File "C:\Program Files\Python310\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 397, in _request
            resp = self._conn.request(method, url, body=body, headers=headers)
          File "C:\Program Files\Python310\lib\site-packages\urllib3\request.py", line 79, in request
            return self.request_encode_body(
          File "C:\Program Files\Python310\lib\site-packages\urllib3\request.py", line 171, in request_encode_body
            return self.urlopen(method, url, **extra_kw)
          File "C:\Program Files\Python310\lib\site-packages\urllib3\poolmanager.py", line 325, in urlopen
            conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
          File "C:\Program Files\Python310\lib\site-packages\urllib3\poolmanager.py", line 231, in connection_from_host
            raise LocationValueError("No host specified.")
        urllib3.exceptions.LocationValueError: No host specified.`
        
        Here, I was using localhost:4723/wd/hub, but previously, I was using {machine_name}:4723/wd/hub, neither worked.  
        
        I'm using python 3.7.10, WinAppDriver 1.2.1
        
        This is my freeze: 
        
        PS C:\WINDOWS\system32> pip freeze
appdirs==1.4.4
Appium-Python-Client==1.0.2
baron==0.9
certifi==2021.10.8
charset-normalizer==2.0.7
click==8.0.3
colorama==0.4.4
comtypes==1.1.7
debugpy==1.5.1
Flask==1.1.1
getgauge==0.3.17
getgauge-cli==1.4.2
grpcio==1.42.0
idna==3.3
itsdangerous==2.0.1
Jinja2==3.0.3
keyboard==0.13.5
Markdown==3.3.6
MarkupSafe==2.0.1
MouseInfo==0.1.3
mysql-connector-python==8.0.27
Pillow==8.4.0
protobuf==3.19.1
psutil==5.6.3
PyAutoGUI==0.9.53
PyGetWindow==0.0.9
PyMsgBox==1.0.9
pyperclip==1.8.2
PyRect==0.1.4
PyScreeze==0.1.28
pytesseract==0.3.8
pytweening==1.0.4
pywin32==302
pywinauto==0.6.8
redbaron==0.9.2
requests==2.26.0
rply==0.7.8
selenium==3.141.0
six==1.16.0
urllib3==1.26.7
Werkzeug==2.0.2

**Comment by AndreiPy13** [comment]
When i change http://selenium:4444/wd/hub on http://X.X.X.X:4444/wd/hub it working
