### ISSUE TITLE
Use black for auto formatting.

### ISSUE THREAD

**Issue by RatanShreshtha** [urllib3/urllib3#1617]
Black describes it as a 
> Black is the uncompromising Python code formatter.

By using black the code will get uniform formatting and will save us from manually formatting which will save time and mental energy for more important matters.

**Comment by theacodes** [comment]
I'm for it.

**Comment by sethmlarson** [comment]
Sounds good to me.

**Comment by haikuginger** [comment]
Very much in favor. Using `black` saves us a lot of mental load at $WORKPLACE.

**Comment by sigmavirus24** [comment]
Same here

**Comment by RatanShreshtha** [comment]
I can send a PR for that, it would also help me in https://github.com/urllib3/urllib3/pull/1614 for the formatting issues.

**Comment by theacodes** [comment]
Great! Feel free to wholesale take the blacken session from Nox's noxfile
https://github.com/theacodes/nox/blob/master/noxfile.py#L47

**Comment by shazow** [comment]
:+1:

**Comment by haikuginger** [comment]
Done! Thank you!
