### ISSUE TITLE
why not use system http proxy

### ISSUE THREAD

**Issue by yyq2013** [urllib3/urllib3#1618]
My computer is set http proxy in IE by administrator, and all inbound or outbound should via the proxy.

I tested a simple url access, java, golang, nodejs all works find without specify the http proxy explicitly but python3 urllib3.
```
import urllib3

http = urllib3.PoolManager(num_pools=5)
r = http.request('GET', 'https://www.howsmyssl.com/a/check')
print(r.data)
```

And why it not detect global http proxy setting and should specify in every reuqest or use a ProxyManager, some libraries, such as kubernets python client, package the ProxyManager in its library and we can't change it in time, how to set it?

**Comment by sethmlarson** [comment]
How is your proxy configuration defined? Have you tried specifying the proxy URL manually via `urllib3.ProxyManager(<proxy url>, num_pools=...)`?

**Comment by yyq2013** [comment]
> How is your proxy configuration defined? Have you tried specifying the proxy URL manually via 

On IE http proxy:
http://myproxyserver:port

Other langauges auto detect it and use it as default http proxy, but urllib3 not.

```python
import urllib3

http = urllib3.PoolManager(num_pools=5)
r = http.request('GET', 'https://www.howsmyssl.com/a/check')
print(r.data)
```
If no proxy, tls error reports, how to fix?
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.howsmyssl.com', port=443): Max retries exceeded with url: /a/check (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))

**Comment by sethmlarson** [comment]
Have you tried the code I supplied above?

**Comment by yyq2013** [comment]
I have no http proxy on personal PC, so not set the proxy, and reports the ssl error I pasted above.

On official computer which set the http proxy and tried the code you supplied, it works fine.

**Comment by sethmlarson** [comment]
urllib3 unfortunately doesn't have a way of automatically detecting your proxy configuration currently. You have to be explicit about whether you're using a proxy or not.

**Comment by yyq2013** [comment]
> urllib3 unfortunately doesn't have a way of automatically detecting your proxy configuration currently. You have to be explicit about whether you're using a proxy or not.

Thanks. It's fine. And what about the SSL error at the simple example?

**Comment by sethmlarson** [comment]
Might be something to do with the chain of certificates if it's talking about a local issuer.
