### ISSUE TITLE
Stop using unittest's addCleanup

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#1623]
We want to stop using the [unittest](https://docs.python.org/3/library/unittest.html) compatibility mode of pytest because:

 * the current code does not work with pytest>=4.2 (possibly a bug in pytest)
 * it's better to use only one test framework, and pytest is nice :)

The pure pytest migration has started in https://github.com/urllib3/urllib3/pull/1614 where @RatanShreshtha has worked on transforming all `self.assert*` calls into Python asserts. This was an important first part because that was the majority of unittest code.

Most of the remaining changes will now be quite limited in scope, but there's one thing left that I would like to talk about here: the [`self.addCleanup`](https://docs.python.org/3/library/unittest.html#unittest.TestCase.addCleanup) calls. We have about 150 of them, and they ensure that the opened connections are closed. `self.addCleanup` is called on the following five classes:

 * HTTPConnectionPool and subclass HTTPSConnectionPool
 * PoolManager and subclass ProxyManager
 * socks.SOCKSProxyManager

(Since this could be tackled by a contributor who isn't familiar with context managers, I preferred to err on the side of verbosity here.)

Let's look at an example:

```python3
def test_redirect(self):
    http = PoolManager()
    self.addCleanup(http.clear)
    r = http.request("GET", "/redirect", ...)
    assert r.status == 303
```

This is equivalent to:

```python3
def test_redirect(self):
    http = PoolManager()
    try:
        r = http.request("GET", "/redirect", ...)
        assert r.status == 303
    finally:
        http.clear()
```

If PoolManager had a `close()` method that behavec like `clear()`, this would also work:

```python3
import contextlib

def test_redirect(self):
    with contextlib.closing(PoolManager()) as http:
        r = http.request("GET", "/redirect", ...)
        assert r.status == 303
```

Alternatively, if PoolManager implemented the context manager protocol (ie. had an `__exit__` method), we could write:

```python3
def test_redirect(self):
    with PoolManager() as http:
        r = http.request("GET", "/redirect", ...)
        assert r.status == 303
```

This last variant is slightly better than the addCleanup variant, I think. But can we do better? I think pytest fixtures can help here. For example, using a pool_manager fixture:

```python3
import pytest

@pytest.fixture
def pool_manager():
    manager = PoolManager()
    try:
        yield manager
    finally:
        manager.clear()


def test_redirect(pool_manager):
    r = http.request("GET", "/redirect", ...)
    assert r.status == 303
```

This reduces verbosity in the tests themselves (look, only two lines left!). (I think that will also help with our async work because it will allow us to pass an AsyncPoolManager too, but that's mostly hypothetical for now.)

Anyway, my proposal is to use the fixtures when there the classes are created without any parameters, and to use the `with PoolManager(args, kwargs) as http:` form otherwise.

What do you think of that plan, @sethmlarson?

**Comment by sethmlarson** [comment]
I almost want to go all the way and say that PoolManager should implement the context manager protocol because (correct me if I'm wrong) a good chunk of our PoolManager invocations use non-default values in the constructor? That seems tougher to maintain when using a fixture.

Fixture is definitely cleaner but might be good to keep test code homogenous as it's already complex as-is.

**Comment by RatanShreshtha** [comment]
`ConnectionPool` class has  implemented the context manager protocol  https://github.com/urllib3/urllib3/blob/master/src/urllib3/connectionpool.py#L82-L85 and the `HTTPConnectionPool` class inherits from it and `HTTPSConnectionPool` is subclass of `HTTPConnectionPool`

`PoolManager` class has  implemented the context manager protocol https://github.com/urllib3/urllib3/blob/master/src/urllib3/poolmanager.py#L172-L175 and the `ProxyManager` and `SOCKSProxyManager` classes inherits from it.

So I think we can go with context manager way to remove `self.addCleanup`.

**Comment by pquentin** [comment]
Sounds good to me.

**Comment by RatanShreshtha** [comment]
I can open a PR for that.

**Comment by sethmlarson** [comment]
Closing this issue now that #1624 has landed. Reopen if I'm wrong.

**Comment by pquentin** [comment]
You're right, thanks!
