### ISSUE TITLE
Add time unit (seconds) to Timeout docs

### ISSUE THREAD

**Issue by bgrant** [urllib3/urllib3#1625]
Neither the [docs](https://urllib3.readthedocs.io/en/latest/user-guide.html#using-timeouts) nor the [docstrings](https://github.com/urllib3/urllib3/blob/master/src/urllib3/util/timeout.py#L20) say what unit timeouts should be provided in.  Looking at the code, it appears to be "seconds", but it would be nice if the docs said this explicitly.

**Comment by sigmavirus24** [comment]
/joking

But how else will we convince people to read our beautiful beautiful source code?

**Comment by sethmlarson** [comment]
@bgrant Thanks for opening this issue! I agree that this would be a good addition. Do you think this is something you could accomplish?

**Comment by bgrant** [comment]
Sure- happy to.
