### ISSUE TITLE
Support getting credentials lazily for HTTP basic auth

### ISSUE THREAD

**Issue by manueljacob** [urllib3/urllib3#1632]
Use case: open a URL, asking the user for username and password if (and only if) the server requests basic auth.

This could be implemented in `HTTPConnectionPool.urlopen()`, similar to how redirects are implemented.

Related tickets are #984 and #1172, although both seem to have a more general use case in mind and propose to extend the `Retry` classes, which seems to be controversial.

**Comment by sethmlarson** [comment]
Realistically due to the reasons mentioned in those two issues we won't be implementing this feature. Thanks for opening the issue.
