### ISSUE TITLE
ssl_match_hostname

### ISSUE THREAD

**Issue by nenadg** [urllib3/urllib3#1639]
Hi, I'm on OpenSuse Tumbleweed, running urllib3 (1.25.3)
This is the error I got:

```
File "/usr/lib/python2.7/site-packages/urllib3/packages/__init__.py", line 3, in <module>
    from . import ssl_match_hostname
ImportError: cannot import name ssl_match_hostname
```
I really don't know what problem could this be, but I've manually changed following lines:

https://github.com/urllib3/urllib3/blob/cdfc9a539cc27f5704f8bcd46d34301b3d218aff/src/urllib3/connectionpool.py#L26

https://github.com/urllib3/urllib3/blob/cdfc9a539cc27f5704f8bcd46d34301b3d218aff/src/urllib3/connection.py#L38

to match `from backports.ssl_match_hostname import ...` and now everything works normally.

Can someone explain me what could be problem here?

**Comment by sethmlarson** [comment]
Given your path of `/usr/lib/python2.7/site-packages/urllib3/packages/__init__.py` it looks like you're using system Python. Just to make sure, you installed the package using whatever package manager comes with the OS and not pip, correct?

Downstream OS package managers like to rebundle packages and usually end up unbundling all of our vendored dependencies and sometimes they make mistakes.  This issue you're having looks like something similar to that. Have you tried raising an issue with OpenSUSE?

**Comment by nenadg** [comment]
@sethmlarson i tried both variants, via package manager and via pip, neither worked. I'll probably raise an issue with OpenSUSE. Thanks anyways.

**Comment by sethmlarson** [comment]
You did this:

```python
python -m venv venv/
source venv/bin/activate
python -m pip install urllib3
python -c "import urllib3"
```

and it fails?

**Comment by nenadg** [comment]
No, I just did `pip install urllib3`. It was a dependency (that I previously thougt I solved) for pritunl (that I build from the source). 

That attempt didn't have any effect and the error remained, until I manually changed imports. As you noticed, it's probably OS vendor problem.
