### ISSUE TITLE
Announcement: @sethmlarson is now the primary maintainer

### ISSUE THREAD

**Issue by theacodes** [urllib3/urllib3#1646]
Hi urllib3 contributors and watchers. 👋 

I've been the primary maintainer since March 2018 (#1347), but my time in that role has come to an end. I'm confident that I'm leaving this project in a good state.

## New maintainer

@sethmlarson is taking responsibility as the primary maintainer and thus the direction of urllib3 moving forward. Seth has been doing the vast majority of the work on urllib3 and we are in great hands.

As before, our family of contributors and co-maintainers will continue to support our new leader as needed.

## Logistics

- [x] Announcement: https://twitter.com/shazow/status/1147248832956100608
- [x] Update README
    - [x] move @sethmlarson to the top of the list. :)
    - [x] Update Sponsors section to note that Google *previously* sponsored my time.
- [x] [Github admin](https://github.com/urllib3/urllib3/settings/collaboration)
- [x] [PyPI admin](https://pypi.org/manage/project/urllib3/collaboration/)
- [x] [ReadTheDocs admin](https://readthedocs.org/dashboard/urllib3/users/)
- [x] CI Admin access

Maintainers, If anything else is need please feel free to comment or edit the list.

---

If anyone has questions or concerns, comments here are welcome or email me. 💜

**Comment by sethmlarson** [comment]
Thank you Thea for everything. :)

**Comment by shazow** [comment]
@theacodes Thank you for your service! Our project has flourished under your guidance.

@sethmlarson Thank you for officially picking up the torch, and for effectively maintaining urllib3 for a while now anyway! :)

You're both a pleasure to work with. :heart:

**Comment by haikuginger** [comment]
Thank you for your hard work, @theacodes! Congratulations to our new fearless leader - we're all pulling for you!

**Comment by theacodes** [comment]
@shazow can you add @sethmlarson as a collaborator on PyPI? (I can't)

**Comment by shazow** [comment]
@theacodes @sethmlarson Done! Added `SethMichaelLarson`.

**Comment by theacodes** [comment]
Thank you.

**Comment by theacodes** [comment]
All these tasks should be done. Bonne chance, @sethmlarson!
