### ISSUE TITLE
idna requirement for pyopenssl

### ISSUE THREAD

**Issue by rouzazari** [urllib3/urllib3#1655]
`cryptopraphy` no longer requires `idna`. If `pyOpenSSL` is installed, `urllib3` can raise an error when trying to import `idna`.  

Should `urllib3` require `idna` on its own (as it is imported in `contrib.pyopenssl`) or should `pyopenssl` require `idna`?

If I misunderstand the need for `idna` then please let me know and close the issue. Thanks!

#### pip installations:
`pip install urllib3==1.25.3 pyOpenSSL==19.0.0`

#### example code:
```python
import urllib3.contrib.pyopenssl as urllib3_contrib_pyopenssl
urllib3_contrib_pyopenssl._dnsname_to_stdlib('abc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv\idna_test\lib\site-packages\urllib3\contrib\pyopenssl.py", line 193, in _dnsname_to_stdlib
    name = idna_encode(name)
  File "venv\idna_test2\lib\site-packages\urllib3\contrib\pyopenssl.py", line 178, in idna_encode
    import idna
ModuleNotFoundError: No module named 'idna'
```

#### requirements.txt
```
asn1crypto==0.24.0
cffi==1.12.3      
cryptography==2.7 
pycparser==2.19   
pyOpenSSL==19.0.0 
six==1.12.0       
urllib3==1.25.3   
```

**Comment by sethmlarson** [comment]
We do require `idna` as a part of the `secure` installation. Installing via `python -m pip install urllib3[secure]==1.25.3` should work properly.

**Comment by rouzazari** [comment]
Thanks @sethmlarson
