### ISSUE TITLE
Question: urllib3 HTTP call (Post) use NTLM

### ISSUE THREAD

**Issue by R-Studio** [urllib3/urllib3#1656]
Hi together
_I am a total noob in python, so sorry for the following dummy question._

**How can I use urllib3 to make a HTTP post call with NTLM authentication?** 

_So in the past I try to use "requests_ntlm" but there is an dependency to the module "six" and in this module there is a [bug](https://github.com/benjaminp/six/issues/118):
@six.add_metaclass(abc.ABCMeta)
AttributeError: module 'six' has no attribute 'add_metaclass'
-> That's the reason I will try this with the urllib3._

**Comment by sethmlarson** [comment]
Assuming that you're using a [virtual environment](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/) for your code: Running `python -m pip install --upgrade six` should fix that issue. Basically you're using an outdated version of six.

Otherwise `urllib3` has an `NTLMConnectionPool` class that can be used like this:

```python
from urllib3.contrib.ntlmpool import NTLMConnectionPool

http = NTLMConnectionPool(user=<username>, pw=<password>, authurl=<ntlm auth url>, host=<host you're connecting to>)
r = http.request("GET", "https://example.com")

**Comment by R-Studio** [comment]
Hi sethmlarson
Thanks for the help, but if I import "from urllib3.contrib.ntlmpool import NTLMConnectionPool" I have following error:
```
>>> import urllib3
>>> from urllib3.contrib.ntlmpool import NTLMConnectionPool
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python37\lib\site-packages\urllib3\contrib\ntlmpool.py", line 9, in <module>
    from ntlm import ntlm
ModuleNotFoundError: No module named 'ntlm'
```

I can't find the module "ntlm"

**Comment by sethmlarson** [comment]
You're required to install `python-ntlm` package to use the module. There are resources online to get you started I'm sure. Please reserve this issue tracker for bugs related to urllib3.
