### ISSUE TITLE
if the name contains a square bracket ('['), I get 400

### ISSUE THREAD

**Issue by nikolasj** [urllib3/urllib3#1658]
The following exception is raised when request method is called for an artifact where its name contains square branckets ('[')

RuntimeError: {
  "errors" : [ {
    "status" : 400,
    "message" : "Bad Request"
  } ]
}

**Comment by sethmlarson** [comment]
There's not information here to figure out what's happening. What code are you using? Is the HTTP endpoint available to the public?

From what you're describing this sounds like an issue with the endpoint or the data you're sending, not urllib3. Closing for now.
