### ISSUE TITLE
Windows Python 3.7.4 tests fail in AppVeyor CI

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#1664]
Quoting myself from https://github.com/urllib3/urllib3/pull/1604#issuecomment-519009281:

> The Python 3.7 Windows failure is reproducible. I compared the [last good 3.7 build](https://ci.appveyor.com/project/urllib3/urllib3/builds/26274262/job/9678kar0ro9ohn1j) with the [first bad 3.7 build](https://ci.appveyor.com/project/urllib3/urllib3/builds/26524209/job/vshduc3gpd898dqp), and noticed that Python was updated from 3.7.3 to 3.7.4, and OpenSSL from 1.1.0j to 1.1.1c as part of https://bugs.python.org/issue34631.
> 
> Here's my understanding of the failures:
> 
>  *  TestConnectionPool.test_source_address_error appears to fail because [InvalidUrl is now being raised in the standard library](https://github.com/python/cpython/blob/3.7/Lib/http/client.py#L1114-L1118) and I guess we no longer catch the correct exception? But why only on Windows?
>  * TestHTTPS.test_client_no_intermediate and TestHTTPS_TLSv1_3.test_client_no_intermediate seem to fail because the OpenSSL exception is being converted into a SocketError in https://github.com/urllib3/urllib3/blob/master/src/urllib3/contrib/pyopenssl.py#L345-L346, maybe because the execution path changed?
>  * TestHTTPS_TLSv1_3.test_set_ssl_version_to_tls_version fails because there are no certs defined in TestHTTPS_TLSv1_3, so self.certs["ssl_version"] can't work

**Comment by tirkarthi** [comment]
> TestConnectionPool.test_source_address_error appears to fail because InvalidUrl is now being raised in the standard library and I guess we no longer catch the correct exception? But why only on Windows?

Travis uses Python 3.7.1 for 3.7 builds which doesn't contain this change and hence passes. This was a security issue fixed in Python stdlib with https://github.com/python/cpython/pull/12755 . Hence this is present in 3.6.x, 3.5.x and 2.7.x series too.

**Comment by pquentin** [comment]
Yeah, I noticed afterwards that we use 3.7.1 for macOS and Linux builds, but forgot to mention it here. Thank you, the detailed explanation is really helpful!

**Comment by sethmlarson** [comment]
I'm wondering if our issues on Windows are due to tornadoweb/tornado#2536
