### ISSUE TITLE
On some https sites, urllib3/requests latest github version hangs

### ISSUE THREAD

**Issue by pythonmobile** [urllib3/urllib3#167]
I installed Commit 7f9d8ee3f5 on python 27 and then tried some https sites with SNI. It seems to be hanging. Is SNI fixed on python2 yet, or was it only for python3?

**Comment by alvare** [comment]
This just happened to me, sadly.
I get the exact same error output when I hit Ctrl-C, too.

In my case it's an AWS instance, trying to send mails with mailgun and sometimes it hangs forever.

For example, it will send 9 mails and hang forever, and then I Ctrl-C, restart and it will send 400 and hang forever.

**Comment by alvare** [comment]
I'm on python 2.7.6 btw, @pythonmobile what are you using?

**Comment by sigmavirus24** [comment]
@alvare this issue is over a year old. Please open a new one
