### ISSUE TITLE
Custom retry handling support

### ISSUE THREAD

**Issue by sonmezonur** [urllib3/urllib3#1675]
Hi, thanks for implementing and maintaining **urllib3**. 

Retry mechanism based on _status_forcelist_ and _method_whitelist_ perfectly works. But in some rare cases, when APIs are not well-constructed, it is required to add custom retry handling. 

* Consider following response format:

`
"status_code": 400,
"body": {
  "error": " Service temporarily unavailable."
}
`

Generally, you don't want to retry on bad requests(400). An ideal response code for this request might be 503. But since it is not restricted, it might be some other HTTP formats. So my proposal is to add a generic solution for retry mechanism which enables  **urllib3** users to integrate their custom logic.

I found it useful to integrate callback function  into [Retry](https://github.com/urllib3/urllib3/blob/master/src/urllib3/util/retry.py#L29), which injects response as a parameter to callback function when [urlopen()](https://github.com/urllib3/urllib3/blob/master/src/urllib3/connectionpool.py#L488) is triggered on [HTTPConnectionPool](https://github.com/urllib3/urllib3/blob/master/src/urllib3/connectionpool.py#L97). Thus, retry logic can be implemented by parsing this response. 

* Example callback function: 
```python
    def callback(res):
            expected_error_msg = "Service temporarily unavailable"
            response_json = res.json()
            error_msg = response_json["error"]
            return res.status_code == 400 and error_msg == expected_error_msg
```

**Comment by sethmlarson** [comment]
Per my comment in your PR, this would definitely be an improvement and has been requested in the past. Unfortunately urllib3's API is frozen and not accepting backwards-incompatible changes, sorry!

**Comment by pquentin** [comment]
We're focusing on the 2.0 milestone to ship urllib3 2.0 as soon as possible, but we do accept pull requests for 2.x issues.

**Comment by sonmezonur** [comment]
I appreciate it if you can add this feature to v2.0. Currently, we are using our fork to handle this use case. Happy to re-open issue/pr for milestone v2.0 if this approach makes sense to you.

**Comment by bruno-fs** [comment]
Is it OK to reopen this for v2.0?
