### ISSUE TITLE
urllib3.util._encode_invalid_chars() changes the percent-encoded bytes to upper case

### ISSUE THREAD

**Issue by calvinpark** [urllib3/urllib3#1677]
https://github.com/urllib3/urllib3/blob/master/src/urllib3/util/url.py#L223-L224
```
# Normalize existing percent-encoded bytes.
for enc in percent_encodings:
    if not enc.isupper():
        component = component.replace(enc, enc.upper())
```

If a URL is parsed using `urllib3.util.parse_url()` then put back together, the original URL does not match the recomposed URL.

```
import urllib3


origin = "https://google.com/some/dir/libgd-gd2-perl_1%3a2.66-1build1.deb"

url = urllib3.util.parse_url(origin)

recomposed = f"{url.scheme}://{url.host}{url.path}"

print(origin)      # https://google.com/some/dir/libgd-gd2-perl_1%3a2.66-1build1.deb
print(recomposed)  # https://google.com/some/dir/libgd-gd2-perl_1%3A2.66-1build1.deb

assert(origin == recomposed)  # Fails
```

**Comment by calvinpark** [comment]
Feature not a bug?

**Comment by sethmlarson** [comment]
This is intended, it's a recommendation of RFC 3986 to uppercase percent-encoded bytes during normalization.

**Comment by calvinpark** [comment]
Is there an option to disable this? A downstream project [ArtifactoryPath](https://github.com/devopshq/artifactory) uses this to reconstruct from-to paths to copy file around and [fails when a path includes `@`](https://github.com/devopshq/artifactory/issues/90)

**Comment by sethmlarson** [comment]
No there isn't an option to disable. If the path segment is being hex-decoded the implementation should handle upper and lowercase. I'm not sure what you mean with `@` or `~` as you mention in the linked issue, the hex for `%3A` decodes into `:`. Am I misunderstanding something?

**Comment by calvinpark** [comment]
Ah, my mistake on saying `%3A` decodes into `@` - it's `:` as you said. 

I saw the RFC and agree that urllib3 is working as intended. It'd just be nice if there were an option to disable this behavior since dependent packages use it to patch together URLs. Now I'm writing a function similar to
```
def _get_path(part, path):
    if path in part:
        return path

    unquoted_path = urllib3.parse.unquote(path)
    if unquoted_path in part:
        return unquoted_path
    else:
        raise ValueError(f"{part} does not include {path}")
``` 
which feels like I'm fighting the tool
