### ISSUE TITLE
Certificate verify failed: self signed certificate (_ssl.c:1056)

### ISSUE THREAD

**Issue by vladns** [urllib3/urllib3#1678]
On the local network, I'm using ProxHTTPSProxyMII https://github.com/wheever/ProxHTTPSProxyMII. When I request from the browser https://192.168.2.1/, I get this error. This only happens with urllib 1.25.x. There is no such problem with the older version of urllib 1.24.2. I am not sure what the problem is in urllib, help sort it out. Sorry if my question is not about the kernel.
![2019-09-16_233512](https://user-images.githubusercontent.com/22105830/64993280-54e2cd80-d8de-11e9-82f1-79a879059da5.png)

**Comment by sethmlarson** [comment]
1.25 turns TLS verification on by default whereas in previous versions it wasn't on by default. Instead of turning off verification you can use the crt or pem for the self-signed certificate your `ca_certs` parameter for your PoolManager.

**Comment by vladns** [comment]
The fact is that the software (ProxHTTPSProxyMII) that I use has a setting in its work logic that disables the verification of any certificate. And it all works, only on urllib3 version below 1.25. Therefore, it seemed to me that due to the latest versions of urllib3, the work used by me by ProxHTTPSProxyMII is somewhat disrupted. Only there I can change it, but it broke.
