### ISSUE TITLE
Unify timeout values used in tests

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#1706]
We have lots of tests that use timeout values, eg. to check that a given operation timeouts as expected or completes a given amount of work before a certain amount of time. Unfortunately, in CI those tests tend to fail some of the time, because say 1% of the time everything is super slow.

In response to this, we went from 0.001 to 0.01 and sometimes 0.1 in the places that failed the most often (#1554 and #1496 are recent examples). But there are still some tests that fail because they were not updated. Since there is no test that is inherently slow in the test suite that I'm aware of, I think it would be nice to share a few timeout values (ideally two) in all tests, so that we can:

 1. bump them all at once if needed
 2. use smaller values in local environments, and larger values in CI

**Comment by shazow** [comment]
:+1: Once upon a time I spent a sprint trying to rewrite as many tests as possible to event-based rather than timeout-based, but it is a lot of work.

I like the idea of using larger values on CI, too.
