### ISSUE TITLE
Urllib3 hangs on some urls

### ISSUE THREAD

**Issue by Yomguithereal** [urllib3/urllib3#1708]
Hello @urllib3 team, thanks for your work.

I am having trouble with urls from the [Miami Herald](https://www.miamiherald.com) that completely hangs my scripts. I am using urllib3 v1.25.6

Here is how to reproduce the issue:

```python
import urllib3
import certifi

http = urllib3.PoolManager(cert_reqs='CERT_REQUIRED', ca_certs=certifi.where())
http.request('GET', 'https://www.miamiherald.com/news/local/article220097825.html') 
```

~~This will never end. If you add a timeout, it will work but sometimes (I am currently trying to pinpoint what triggers this), it will ignore the timeout and hangs forever. It smells like threading race conditions and/or deadlock.~~

Some notes:

1. `urllib.request.urlopen` does not succeed either
2. Web browsers or CURL succeed in retrieving this url just fine
3. Is this somehow linked to the fact that the site attempts to use HTTP/2.0?
4. CURL will get a 403 if you don't spoof your UA but I don't think this is relevant to this issue

Have a good day and tell me how I can help.

EDIT: the timeout not being taken into account is my fault. I found where I messed up.

**Comment by sethmlarson** [comment]
Closed per your edit. If this is still an issue please reopen.

**Comment by Yomguithereal** [comment]
Well, the timeout not firing was my fault. However, the urls I mention still cannot be accessed using urllib3 nor `urllib.request.urlopen` while curl or any browser will open them without issue.

**Comment by Yomguithereal** [comment]
I don't have the option to reopen by the way.

**Comment by hodbn** [comment]
Hi,
It seems that www.miamiherald.com hangs the TCP connection if `Accept` and `Accept-Encoding` headers are not given. Unless we want to send those headers by default, I think this is a server error.

**Comment by sethmlarson** [comment]
Sounds like server error if this is the case. Closing issue, if this isn't true can reopen.
