### ISSUE TITLE
1.25.* uses more CPU than 1.24.*

### ISSUE THREAD

**Issue by lorien** [urllib3/urllib3#1737]
Hey guys,

I am developing web scraping framework and I use gevent and urllib3.
Today I've upgraded from 1.24.1 to 1.25.6 and found that my scraper started eating 100% CPU.
Before upgrade it was eating about 30-40% CPU.

I've tried different versions of urllib3 and it turned out:
 * 1.24.1 and 1.24.2 eats 30-40% CPU
 * 1.25 and higher eats 100% CPU

I've decided to start this issue and maybe get some feedback from other users. I'll try to provide more technical details later, like profiling statistics.

So, my question is is anybody else concern with performance of 1.25+ version?

**Comment by pquentin** [comment]
Can you try the latest release? 1.25 introduced a URL parser that was consuming too much resources, it was removed in 1.25.4, see https://github.com/urllib3/urllib3/issues/1590

**Comment by lorien** [comment]
@pquentin I've tried almost every 1.25.* release, the problem is common for any 1.25.* release. Including recent 1.25.6 release.

**Comment by pquentin** [comment]
Can you try profiling your code then? I've found https://github.com/benfred/py-spy to be easy to use, it would be great if you could share a flamegraph with us.

**Comment by lorien** [comment]
@pquentin yeah, I'll provide more details in few days

**Comment by sethmlarson** [comment]
Could you give us an example URL that you're scraping that you know causes this issue so I can try reproducing myself?

**Comment by lorien** [comment]
So far, I have not collected any data that prove that 1.25 is slower than 1.24.
I am working on network libs benchmarking tool https://github.com/lorien/netbench Results does not show that 1.25 is slower. If I find something interesting I'll update this issue. Thanks.
