### ISSUE TITLE
How to implement a "watcher" thread as suggested by the documentation?

### ISSUE THREAD

**Issue by ingomueller-net** [urllib3/urllib3#1741]
The documentation of the [`timeout`](https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html#module-urllib3.util.timeout) module says:

> If your goal is to cut off any request after a set amount of wall clock time, consider having a second “watcher” thread to cut off a slow request.

How would that work?

It seems like it is [strongly discouraged or even impossible](https://stackoverflow.com/questions/323972/is-there-any-way-to-kill-a-thread) to kill a thread in Python, so what would that watcher thread do?

If it is not possible to write a watcher thread in Python, the documentation shouldn't suggest to do it.

**Comment by pquentin** [comment]
This is a great question. I guess you're right! There's no good way to cut off a request after a set amount of time with urllib3, and we should acknowledge that. 

(This is actually a benefit of libraries based on async I/O such as trio, they support such global timeouts natively without needing cooperation from the HTTP library.)

Would you like to open a pull request to remove this sentence from the documentation?

**Comment by lorien** [comment]
There is a way, without using second thread. First you should use `Timeout(read=...)` to limit time on reading one network chunk, second you should read response by chunks and check elapsed time after each chunk has been received.

**Comment by lorien** [comment]
Also you can use gevent and wrap network operations into `gevent.Timeout`
