### ISSUE TITLE
cannot encode list with filepost.encode_multipart_formdata

### ISSUE THREAD

**Issue by ChemicalXandco** [urllib3/urllib3#1765]
when I run this code:
```py
fields = {'tags': ['tag1', 'tag2']}
(output, contentType) = urllib3.filepost.encode_multipart_formdata(fields)
```
I get this error:
```
(output, contentType) = urllib3.filepost.encode_multipart_formdata(fields)
  File "C:\Program Files\Python36\lib\site-packages\urllib3\filepost.py", line 90, in encode_multipart_formdata
    body.write(data)
TypeError: a bytes-like object is required, not 'list'
```
I expect the list to be encoded, why is it not working?

**Comment by sethmlarson** [comment]
This interface only accepts strings as keys and for values one of: str, bytes, tuple of (string, str/bytes) for (filename, file data), and tuple of (string, str/bytes, string) for (filename, file data, and file content type)
