### ISSUE TITLE
UnicodeError while processing invalid redirect

### ISSUE THREAD

**Issue by lorien** [urllib3/urllib3#1769]
Urllib3 version: 1.25.6
```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 184.95.32.74:443
/home/web/web/domscan/.env/lib/python3.5/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
DEBUG:urllib3.connectionpool:https://184.95.32.74:443 "GET / HTTP/1.1" 302 0
DEBUG:urllib3.util.retry:Incremented Retry for (url='https://184.95.32.74'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
INFO:urllib3.poolmanager:Redirecting https://184.95.32.74 -> https://.../
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ...:443
Traceback (most recent call last):
  File "/home/web/web/domscan/.env/lib/python3.5/encodings/idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    mgr.urlopen('GET', 'https://184.95.32.74')
  File "/home/web/web/domscan/.env/lib/python3.5/site-packages/urllib3/poolmanager.py", line 369, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "/home/web/web/domscan/.env/lib/python3.5/site-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/web/web/domscan/.env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/web/web/domscan/.env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/home/web/web/domscan/.env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/home/web/web/domscan/.env/lib/python3.5/site-packages/urllib3/connection.py", line 334, in connect
    conn = self._new_conn()
  File "/home/web/web/domscan/.env/lib/python3.5/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/web/web/domscan/.env/lib/python3.5/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
```

Command to reproduce:
```python
import logging
import urllib3

logging.basicConfig(level=logging.DEBUG)
mgr = urllib3.PoolManager(cert_reqs='CERT_NONE')
mgr.urlopen('GET', 'https://184.95.32.74')
```

**Comment by sethmlarson** [comment]
The website you visited redirected you to `https://.../`, `...` is not a valid host because the "labels" between the `.` are empty. What would you expect to happen in this sitatution?

**Comment by lorien** [comment]
I expect urllib3 does not raise UnicodeError. I expect it raise built-in urlilb3 exception like InvalidUrl or InvalidRedirect or something like that.
It is not possible to write reliable web scraper if network library might raise exceptions of any kind.

**Comment by sethmlarson** [comment]
Sounds like a valid change, would you be willing to create a PR to accomplish this?

**Comment by hodbn** [comment]
I've reproduced this issue with this minimal example:
```python
import socket
socket.getaddrinfo('...', None)
```
In python2.7 it raises `socket.gaierror`, on python3 it raises the mentioned `UnicodeError`. The reason is that in python3 encodes the node name with the idna codec first.

One solution is to add some idna-validation code while normalizing/validating URIs (before `getaddrinfo` call), based on python3 `idna.Codec.encode` (independent of idna package) that will raise `LocationParseError`.

@sethmlarson what do you think?

**Comment by sethmlarson** [comment]
For this specific issue I think we can catch the `UnicodeError` and re-raise a `LocationParseError` on Python 3.x.
Does the `socket.gaierror` have any specific message on it or its indistinguishable from a DNS resolution failure?

I'd prefer not adding a dependency for a tiny edge-case like this.

**Comment by hramezani** [comment]
@sethmlarson 

> For this specific issue I think we can catch the UnicodeError and re-raise a LocationParseError on Python 3.x.

Yes we can do it for python 3.x

> Does the socket.gaierror have any specific message on it or its indistinguishable from a DNS resolution failure?

No, at least I couldn't find it.

question: In case of Python2.x, Should we catch `socket.gaierror` and re-raise a `LocationParseError`?

**Comment by sethmlarson** [comment]
@hramezani Well for now we can essentially do the checking that CPython does when encoding to idna to ensure we're Python 2.x compatible. If any label is 0 characters long we raise the `LocationParseError` and for good measure we catch `UnicodeError` off of `getaddrinfo()`. The case for a label being too long is much harder for us to catch on our side?
