### ISSUE TITLE
CERT_REQUIRED and ca_certs=None

### ISSUE THREAD

**Issue by lorien** [urllib3/urllib3#1770]
OK, it is a question, not a bug. I have not found link to any mail group or chat, so.
Is there a difference between
`PoolManager(cert_reqs='CERT_REQUIRED', ca_certs=None)`
and
`PoolManager(cert_reqs='CERT_REQUIRED', ca_certs=certifi.where())`
?

I am asking this because I see different CPU usage in these two cases.

**Comment by sethmlarson** [comment]
I'm not seeing any difference as long as you don't call `certifi.where()` inline.

```
$ python -m timeit -s 'import urllib3' 'urllib3.PoolManager(cert_reqs="CERT_REQUIRED", ca_certs=None)'
200000 loops, best of 5: 1.45 usec per loop

$ python -m timeit -s 'import urllib3; import certifi; x = certifi.where()' 'urllib3.PoolManager(cert_reqs="CERT_REQUIRED", ca_certs=x)'
200000 loops, best of 5: 1.45 usec per loop
```

**Comment by pquentin** [comment]
(And hopefully calling `certifi.where()` inline should only make a difference in timeit)
