### ISSUE TITLE
ConnectionError when connection is OK

### ISSUE THREAD

**Issue by earonesty** [urllib3/urllib3#1773]
I ran into this issue recently.   

The result of this is that any issues with reading a local file cause the system to disconnect and reconnect to remote servers that are working fine.... the issue was with a local file that had a read error.

I suspect this is a lower level problem with the python `http.client` library, since it provides no indication which socket had the problem when an OSError is raised, correct?  

```
import io
import urllib3
import requests

buggy_file = io.BytesIO(b"hello")

def raise_ex(*a, **kw):
    raise OSError("oops")

>>buggy_file.read = raise_ex

http = urllib3.PoolManager()

# this raises a urllib3.exceptions.ProtocolError
# is it a the connection to python.org or the buggy_file that failed?

res = http.request("POST", "http://www.python.org", body=buggy_file)

# this raises requests.exceptions.ConnectionError 
res = requests.post("http://www.python.org", data=buggy_file)
```

**Comment by pquentin** [comment]
Thanks for the report, and sorry this has tripped you up!

You're analysis is correct: we can't tell from the exception that it happened when reading the file, since socket errors are actually just `OSError`, so we have to catch them to handle retries.
