### ISSUE TITLE
Traversal is stripped in >1.24.3

### ISSUE THREAD

**Issue by trustedsec** [urllib3/urllib3#1781]
There appears to be normalization of URL's occurring that removes intended functionality through GET/POST requests.

Built a scanner that looks for a directory traversal issue to help to troubleshoot missing patches and it strips out the ../ in the request.

Even with allow_redirects=False the request still gets stripped.

Example:

$ python3
Python 3.7.4 (default, Dec 13 2019, 01:02:18)
[GCC 7.3.1 20180712 (Red Hat 7.3.1-6)] on linux
Type "help", "copyright", "credits" or "license" for more information.

import requests
req = requests.get('https://x.x.x.x/vpn/../vpns/etc/smb.conf', allow_redirects=False)
req.content
b'<script type="text/javascript" src="/vpn/resources.js"></script><script type="text/javascript" language="javascript">var Resources = new ResourceManager("/logon/themes/Default/resources/{lang}", "REDIRECTION_BODY");</script><script type="text/javascript" language="javascript">Resources.Load();</script>'
req.status_code
302
req.url
'https://x.x.x.x/vpns/etc/smb.conf'

Notice the request for ../ is stripped/removed.

Reference: https://github.com/urllib3/urllib3/pull/1487

**Comment by sigmavirus24** [comment]
Correct. They're semantically equivalent. The RFC dictates this is how resolution is to happen too.

**Comment by trustedsec** [comment]
Is there a way to override the behavior as it does have different actions interpreted by the server?

**Comment by trustedsec** [comment]
I was able to figure out a workaround. It would be nice to have a flag to allow true requests to occur. 

   with requests.Session() as s:
        r = requests.Request(method='POST', url=url, data=data, headers=headers)
        prep = r.prepare()
        prep.url = url
        req = s.send(prep)

**Comment by die9o** [comment]
> I was able to figure out a workaround. It would be nice to have a flag to allow true requests to occur.
> 
> with requests.Session() as s:
> r = requests.Request(method='POST', url=url, data=data, headers=headers)
> prep = r.prepare()
> prep.url = url
> req = s.send(prep)

test in  my env ，only work for url strarswith 'https'。
env:
 >>> requests.__version__
'2.24.0'
>>> urllib3.__version__
'1.25.10'

**Comment by jbwdevries** [comment]
Another workaround (I added a print statement to `prepare_url` to check):
```sh
python3.10.6 -m venv venv
venv/bin/pip install urllib3==1.26.11 requests==2.25.1

venv/bin/python -c "import requests ; print(requests.get('http://127.0.0.1:8123/?a=[]'))"
# scheme, auth, host, port, path, query, fragment http None 127.0.0.1 8123 / a=%5B%5D None
# <Response [404]>

venv/bin/python -c "import requests ; import urllib3.util.url ; urllib3.util.url.NORMALIZABLE_SCHEMES = () ; print(requests.get('http://127.0.0.1:8123/?a=[]'))"
# scheme, auth, host, port, path, query, fragment http None 127.0.0.1 8123 / a=[] None
# <Response [404]>
```
