### ISSUE TITLE
Detect and use http_proxy and https_proxy env variables

### ISSUE THREAD

**Issue by kennell** [urllib3/urllib3#1785]
It seems that urrlib3 ignores the `http_proxy`, `https_proxy` and `no_proxy` environment variables. Most HTTP clients out there (including urllib, urllib2, wget, curl, requests) will automatically detect these variables and subsequently make all requests thru the proxy.

Example:

```pycon
http_proxy=http://example.com:8080 https_proxy=https://example.com:8080 python3
>>> import urllib3
>>> http = urllib3.PoolManager()
>>> r = http.request('GET', 'https://www.python.org/')
```
Expected: proxy servers are used
Result: proxy servers are ignored

**Comment by sethmlarson** [comment]
urllib3 historically doesn't get configuration from environment variables. You should use a higher-level HTTP client API if you'd like the library to handle this use-case.

**Comment by chrisinmtown** [comment]
I know voting on a closed issue is silly,  and I don't know all the history of urllib3, but it seems like a huge departure from previous packages. If packages urllib and urllib2 both honor proxy environment variables, why stop honoring them in urllib3?

**Comment by Florents-Tselai** [comment]
Came across this and I have to say this should be considered a bug, not a feature. And I'd also mention this in the docs as a warning.
