### ISSUE TITLE
RFE: Way to construct response objects from as-is response dumps

### ISSUE THREAD

**Issue by scop** [urllib3/urllib3#1786]
It would be nice to be able to create urllib3.response.HTTPResponse objects easily from as-is request dump files, for example ones generated with `curl -i --raw`. Those could then be used e.g. in testing/mocking, for example in requests-mock's "raw" urllib3 responses: https://requests-mock.readthedocs.io/en/latest/response.html#registering-responses

**Comment by sethmlarson** [comment]
Thanks for the suggestion, I don't think we'll be implementing this ourselves currently. Could be done by an external library. :)
