### ISSUE TITLE
Unable to connect through an HTTPS proxy

### ISSUE THREAD

**Issue by mpalki1** [urllib3/urllib3#1797]
We are using an internal HTTPS proxy. When we use urllib3 to make requests through it we get a "Remote end closed connection without response" error.  Given below is code to sort of reproduce the issue.  
Note - When we use a http proxy, then the request goes through. 

```
#This fails
import urllib3
proxy=urllib3.ProxyManager( proxy_url="https://www.yahoo.com");
resp = proxy.request("GET", "https://www.example.com");
resp.data

#Curl establishes the initial CONNECT request but then returns a 404
curl -x https://www.yahoo.com https://www.example.com 
```

**Comment by pquentin** [comment]
Sorry about that @mpalki1! But HTTPS proxies are not supported. There's work at https://github.com/urllib3/urllib3/pull/1679 to add support for them, is it feasible for you to try this code and tell us if it works for you?

Thanks!

**Comment by mpalki1** [comment]
@pquentin - Happy to try it out. But it seems that even with that PR, accessing HTTPS sites through an HTTPS proxy will not be supported.

**Comment by pquentin** [comment]
Right, for now you'll need to try accessing HTTP sites and it won't solve your immediate problem. Hopefully we'll get TLS-in-TLS support in another release, but it's more complicated. :/
