### ISSUE TITLE
Code that uses UnverifiedHTTPSConnection broken by 063d888bc247eb6bd7aedcd32412bbb53c3c6ffb

### ISSUE THREAD

**Issue by zogzog** [urllib3/urllib3#1798]
I guess it now uses the parent (non-https) connect method, which blocks a long time before finally timing out.

See my comments on the commit (https://github.com/urllib3/urllib3/commit/063d888bc247eb6bd7aedcd32412bbb53c3c6ffb) and there: https://github.com/urllib3/urllib3/pull/1726

**Comment by zogzog** [comment]
Also how about I create a ticket to ask for a _simple_ way to use:

* unverified https connections
* that don't warn users

If there is a slight chance that it would be considered favorably I can even contribute a PR.

**Comment by sethmlarson** [comment]
There is definitely an issue with the current `HTTPSConnection` using the parent class `connect()` method, however I don't think restoring the old `HTTPSConnection.connect()` is the solution. The solution IMO is to rename `VerifiedHTTPSConnection` to `HTTPSConnection` and rebind the class to the name `VerifiedHTTPSConnection` so as not to break backwards compatibility.

We should also deprecate the `UnverifiedHTTPSConnection` name rebind so it can be removed later.

We won't be supporting an HTTPS mode without either certificate verification or a warning to the user.

**Comment by sigmavirus24** [comment]
> We won't be supporting an HTTPS mode without either certificate verification or a warning to the user.

:clap: 

Besides, I believe we documented how to silence the warning as a user.
