### ISSUE TITLE
Rename VerifiedHTTPSConnection to HTTPSConnection

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#1799]
The current `HTTPSConnection` object is broken and doesn't serve much purpose. We should use the current `VerifiedHTTPSConnection` object and rebind the name to preserve backwards compatibility.

**Comment by kobayashi** [comment]
Hello folks,

Do I have chance to work for this?

**Comment by sethmlarson** [comment]
@kobayashi Yes please! Let me know if you need any assistance. :)

**Comment by kobayashi** [comment]
Thx @sethmlarson , I made the first PR to fix this.
