### ISSUE TITLE
[mTLS] pass client cert and key content to urllib3.PoolManager as string

### ISSUE THREAD

**Issue by arithmetic1728** [urllib3/urllib3#1803]
It seems urllib3.PoolManager only reads client cert and key from a given path, like the following:
```
http = urllib3.PoolManager(
     cert_file='/path/to/your/client_cert.pem',
     cert_reqs='CERT_REQUIRED',
     key_file='/path/to/your/client.key',
     key_password='keyfile_password')
```
I have client cert and key in memory due to security reason and I cannot save them on disk. How do I pass the cert and key content strings to PoolManager?

**Comment by pquentin** [comment]
Hello @arithmetic1728! I'm sorry that urllib3 does not support this and that this is blocking you. Unfortunately, this is not possible using Python's standard library, see https://bugs.python.org/issue16487 for details.

Also, see https://github.com/urllib3/urllib3/issues/474 for a urllib3 workaround using PyOpenSSL.

We'll be happy to revisit when Python supports this. Until then, I'm closing this issue. Thanks!
