### ISSUE TITLE
Dotted FQDN tests may fail or succeed depending on system DNS configuration

### ISSUE THREAD

**Issue by mgorny** [urllib3/urllib3#1809]
Related to #1475, #1648.

I've recently spent some time debugging test failures reported by Gentoo users, and came to the conclusion that resolving `localhost.` may work or not depending on the system resolver configuration. I've been able to make it work reliably by listing `localhost.` in `/etc/hosts` explicitly or by using `nss_myhostname`. It also may work when external DNS is used and works, though I have no clue why glibc makes it work like that. On the other hand, if the system can't connect to the DNS resolver, it fails.

Since this test is unreliable, could you please disable (skip) it by default and enable only on known-good travis infra? I would supply a patch but I don't really know what values `TRAVIS_INFRA` can have.

**Comment by sethmlarson** [comment]
Yep I definitely run into this issue as well. Maybe we need to skip the test if we can't resolve `localhost.`, change the decorator to run that DNS lookup and on failure just skip.
