### ISSUE TITLE
Error on send query string to service after 1.25

### ISSUE THREAD

**Issue by luiscoms** [urllib3/urllib3#1814]
Before update 1.25 following request was working.

```python
requests.get('http://service.com/endpoint?some=["5","b"]')
```

Now, is converting chars to percent.

**Comment by sethmlarson** [comment]
Per [RFC 3986 Appendix A](https://tools.ietf.org/html/rfc3986#appendix-A) if you find the `query` syntax which doesn't include `[` and `]` meaning we should percent encode them to follow the standard. It's up to the web service being contacted to decode them to `[` and `]` properly.
