### ISSUE TITLE
 InvalidHeader: Invalid Retry-After header: 1m0s with github.com

### ISSUE THREAD

**Issue by ssbarnea** [urllib3/urllib3#1822]
Apparently retry logic inside urllib3 chokes when receiving 429 replies from github itself.
```
self = Retry(total=2, connect=None, read=None, redirect=None, status=None)
retry_after = '1m0s'

    def parse_retry_after(self, retry_after):
        # Whitespace: https://tools.ietf.org/html/rfc7230#section-3.2.4
        if re.match(r"^\s*[0-9]+\s*$", retry_after):
            seconds = int(retry_after)
        else:
            retry_date_tuple = email.utils.parsedate(retry_after)
            if retry_date_tuple is None:
>               raise InvalidHeader("Invalid Retry-After header: %s" % retry_after)
E               InvalidHeader: Invalid Retry-After header: 1m0s
```

Even more interesting, the `parsedate` is now no longer part of the stdlib, https://github.com/urllib3/urllib3/blob/728d9244665ef5b03103cb74d7b409ebe4f23b43/src/urllib3/util/retry.py#L254

**Comment by pquentin** [comment]
Thanks for opening an issue and a pull request! I have a few questions about the issue.

Why would email.utils.parsedate not be part of the standard library? I see it there: https://docs.python.org/3/library/email.utils.html#email.utils.parsedate

1m0s is indeed not a compliant Retry-After header: https://tools.ietf.org/html/rfc7231#section-7.1.3. Do you have a simple way to reproduce the GitHub issue? Did you try submitting a bug to them? They should just send "60" in that case.

Regarding your pull request, urllib3 does not depend on external libraries. We can vendor small libraries, but there needs to be a real use case for this.

**Comment by ssbarnea** [comment]
I was sure I got an error about missing parsedate on newer version of python but apparently is was not removed https://github.com/python/cpython/blob/master/Lib/email/utils.py -- maybe it was caused by some shadowing from another library or relative path imports. I am glad to use it as adding extra dependency for this is a very bad idea.

I did not raise a bug with github yet, even if my hopes about them doing anything about it are very low. Here is the place where I found the issue https://review.rdoproject.org/zuul/build/5c23a6536eff46778c91beb75598c319 and the code generating it can be seen at https://review.rdoproject.org/r/#/c/24100/9/test/test_verify.py

I was still unable to reproduce this error locally, I guess i will have to do much more DDOS requests to trigger the 429 response from github.

So first we need to find a way to reproduce the error with github. If it does reproduce it would make sense to add an extra regex for this case. Clearly external dependency makes no sense, that piece of code will be removed form the next patch.

**Comment by sethmlarson** [comment]
Btw I've found companies usually fairly sympathetic to fix HTTP issues. Has worked for me in the past. :)

**Comment by ssbarnea** [comment]
@sethmlarson

**Comment by ssbarnea** [comment]
I can confirm tha this error comes from github.com, which replies with non-conformant HTTP header value for `Retry-After: 1m0s`, instead of the correct one which should be numerical `Retry-After: 60`

**Comment by sethmlarson** [comment]
I wasn't able to get a `Retry-After` header after using up all of the free tier API requests so I can't verify. If you have additional information to help reproduce the issue I'd put it here and also submit a ticket to GitHub Support to get it fixed.

**Comment by ssbarnea** [comment]
I already submitted a ticket, using two channels. Hopefully they will reply. Is tricky to reproduce because if you ever authenticates the thresholds are really bit. Is much easier to reproduce with a container and ~1000 requests.  I will wait a bit to let them reply on the issue.

Our of curiosity, if they confirm the issue, would it make sense to patch urllib3 to make it work with these invalid values?

**Comment by sethmlarson** [comment]
It's actually sometimes in the interest of the broader community to be strict about breaking when encountering behavior that isn't compliant. GitHub is the only site we've heard doing this, so instead of making more burder for other HTTP clients, browsers, and tools ("hey your website works with urllib3 but not with curl!") we should make the offending party fix their setup ("hey your website doesn't work with any HTTP clients") to reduce non-standard functionality that all HTTP clients have to support. :)

**Comment by pquentin** [comment]
For more details, see https://datatracker.ietf.org/doc/draft-iab-protocol-maintenance/?include_text=1

**Comment by sethmlarson** [comment]
We're going to close this issue as "not a defect in urllib3". GitHub needs to fix their headers.

**Comment by huangsam** [comment]
I recently encountered this issue as well. Good to hear that it's a site bug and not a library bug. Is there someone who is working with GitHub to ensure their headers are corrected?

**Comment by pquentin** [comment]
@huangsam I don't think we're doing anything specific on the urllib3 side, but it would help if you could report this issue to GitHub too. Thanks!

**Comment by ssbarnea** [comment]
What is worse is that I got zero feedback from github and my expectations are low, because these errors are not so common or easy to reproduce. I am not trying to find an excuse for them but considering that it took them 8 months to bring their github iphone app from annount to first public release,... and that was a feature worth of marketing, not a bugfix.

Please report it to github support, https://github.community/, [twitter](https://twitter.com/sbarnea/status/1242466098798186500). The best way to force a big company to react was to reply to one of their own marketing tweets.

**Comment by andriyor** [comment]
Seems like GitHub already fixed it
