### ISSUE TITLE
unexected eof with OpenSSL 1.1.1e

### ISSUE THREAD

**Issue by tomaskrizek** [urllib3/urllib3#1825]
OpelSSL 1.1.1e now raises a non-critical error in cases where it previously didn't. This has been changed in openssl/openssl#10882.

urllib3 should be updated to reflect this change in behaviour. Currently, this error is raised, resulting in the following traceback:

```
File "/usr/lib/python3.8/site-packages/requests/models.py", line 751, in generate
  for chunk in self.raw.stream(chunk_size, decode_content=True):
File "/usr/lib/python3.8/site-packages/urllib3/response.py", line 564, in stream
  data = self.read(amt=amt, decode_content=decode_content)
File "/usr/lib/python3.8/site-packages/urllib3/response.py", line 507, in read
  data = self._fp.read(amt) if not fp_closed else b""
File "/usr/lib/python3.8/http/client.py", line 454, in read
  n = self.readinto(b)
File "/usr/lib/python3.8/http/client.py", line 498, in readinto
  n = self.fp.readinto(b)
File "/usr/lib/python3.8/socket.py", line 669, in readinto
  return self._sock.recv_into(b)
File "/usr/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 332, in recv_into
  raise ssl.SSLError("read error: %r" % e)
ssl.SSLError: ("read error: Error([('SSL routines', 'ssl3_read_n', 'unexpected eof while reading')])",)
```

**Comment by sethmlarson** [comment]
This might be an issue you have to raise in pyOpenSSL? @alex @reaperhulk thoughts?

**Comment by alex** [comment]
I kind of think this is the right behavior.

To close a TLS stream, you're supposed to send a close TLS frame, that way an attacker can't do a truncation attack.

**Comment by tomaskrizek** [comment]
Is there a reason to handle the new EOF exception any differently than the existing `OpenSSL.SSL.SysCallError` when `e.args == -1`?

Currently, whether this raises an exception or not depends the value of  `suppress_ragged_eofs`. The [code](https://github.com/urllib3/urllib3/blob/master/src/urllib3/contrib/pyopenssl.py#L314) reads:
```
try:
    return self.connection.recv_into(*args, **kwargs)
except OpenSSL.SSL.SysCallError as e:
    if self.suppress_ragged_eofs and e.args == (-1, "Unexpected EOF"):
        return 0
    else:
        raise SocketError(str(e))
```

**Comment by t8m** [comment]
> Is there a reason to handle the new EOF exception any differently than the existing `OpenSSL.SSL.SysCallError` when `e.args == -1`?
> 
> Currently, whether this raises an exception or not depends the value of `suppress_ragged_eofs`. The [code](https://github.com/urllib3/urllib3/blob/master/src/urllib3/contrib/pyopenssl.py#L314) reads:
> 
> ```
> try:
>     return self.connection.recv_into(*args, **kwargs)
> except OpenSSL.SSL.SysCallError as e:
>     if self.suppress_ragged_eofs and e.args == (-1, "Unexpected EOF"):
>         return 0
>     else:
>         raise SocketError(str(e))
> ```

Yes, this is exactly the same condition. Basically OpenSSL in 1.1.1e and newer will not return this error anymore but instead gives this `Error([('SSL routines', 'ssl3_read_n', 'unexpected eof while reading')])`

**Comment by t8m** [comment]
The unexpected eof while reading being the key text here.

**Comment by sethmlarson** [comment]
BTW this is went away in OpenSSL 1.1.1f but will be returning in OpenSSL 3.

**Comment by sethmlarson** [comment]
Closing this issue as we're exploring OpenSSL 3 separately.
