### ISSUE TITLE
Switch to Sphinx 3

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#1842]
Here's the changelog: https://www.sphinx-doc.org/en/master/changes.html#release-3-0-0-released-apr-06-2020

It currently fails with an mysterious `ValueError: wrapper loop when unwrapping <MockModule id='139897808864312'>` error: https://travis-ci.org/github/urllib3/urllib3/jobs/671484869

**Comment by sethmlarson** [comment]
This was resolved in #1844

**Comment by pradyunsg** [comment]
From https://urllib3.readthedocs.io/en/latest/reference/urllib3.connectionpool.html:

```
<meta name="generator" content="sphinx-1.8.5, furo">
```

I don't think so...

**Comment by pradyunsg** [comment]
ReadTheDocs does a pip install containing `sphinx<2` prior to doing `pip install ... -r docs/requirements.txt`. I think adding a sphinx>3.0.0 would work!

**Comment by pradyunsg** [comment]
#1964 fixed this!
