### ISSUE TITLE
Why am I seeing InvalidProxyConfigurationWarning when using an HTTPS proxy?

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#1850]
urllib3 up to v1.25.x doesn't support HTTPS proxies. When connecting to an HTTPS URL, urllib3 contacts the proxy via HTTP instead of HTTPS **even if your proxy URL specifies HTTPS**. In urllib3 v1.26.x we're planning on supporting HTTPS proxies properly and are giving an early warning to users to switch their proxy URLs from HTTPS to HTTP to not encounter issues when upgrading later.

```python
import urllib3

# HTTPS proxy, should change!
http = urllib3.ProxyManager("https://1.2.3.4")
http.request("GET", "https://example.com")  # Warning would be raised here.

# Switch to this, will maintain current behavior when connecting to HTTPS URLs.
http = urllib3.ProxyManager("http://1.2.3.4")
http.request("GET", "https://example.com")  # Warning won't be raised, same behavior as above.
```

Your proxy may be configured externally like in a `HTTPS_PROXY` environment variable or via `requests.Session(proxy_url=...)` or configured by your OS. Look in all these places before raising an issue or commenting here.

**Please don't leave a comment unless you have something to add, this will email many people.** If you've received this warning please leave a :+1: reaction so we can gauge how widespread this issue is.

If you do believe there is an issue please open one separately and we will get to it as soon as possible. Thank you. :)

**Comment by sigmavirus24** [comment]
For what it may be worth, you'll have a _lot_ of Requests users running into this potentially

**Comment by sethmlarson** [comment]
@sigmavirus24 Yeah Nate is aware of all of this, I'm hoping that including a link in the warning itself will steer users to the correct landing place. :)

**Comment by sigmavirus24** [comment]
Based on past warnings like this with a link, Requests users will just comment here complaining rather than following your extremely clear instructions. It may be worthwhile to consider locking comments here just to avoid the noise

**Comment by sethmlarson** [comment]
That is definitely an option if things get out of hand. Will monitor the issue closely.

**Comment by sethmlarson** [comment]
This issue has served its purpose now that 1.26 supports HTTPS proxies, thanks all for the :+1:s!
