### ISSUE TITLE
Raw HTML in README.rst causing problems with uploading dists

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#1854]
See: https://travis-ci.org/github/urllib3/urllib3/builds/675807537

For now I've manually uploaded the dists.

We should strip this section from our `long_description` field and maybe run `twine check` within our CI to make sure we don't run into this issue on release time in the future.

**Comment by reillys** [comment]
Not sure if its related, but just in case  - having just run a poetry lock on dependencies it picked up the new version 1.25.9 - but that new version hasn't been picked up/appeared on our pypi mirror.

**Comment by sethmlarson** [comment]
@reillys Probably not related, I released 1.25.9 about an hour ago you mirror may be out of date?

**Comment by reillys** [comment]
@sethmlarson quite likely, will check again our end, just saw the issue here and thought worth a mention just in case  :)
