### ISSUE TITLE
URL containing backslashes in username/password now failing DNS lookup in 1.25.9

### ISSUE THREAD

**Issue by lmocsi** [urllib3/urllib3#1870]
Working from behind a proxy server was fine with urllib3 version 1.25.8.
After upgrading to version 1.25.9, the package fails before reaching the proxy server with the following error:
Traceback (most recent call last):
  File "c:\Anaconda3\lib\site-packages\urllib3\connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "c:\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "c:\Anaconda3\lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

What I do is connecting to a https API through an authenticated proxy server connection.

**Comment by sigmavirus24** [comment]
Can you give more detail than this? Does downgrading to 1.25.8 work for you? Can you share how you're configuring your proxy with urllib3?

The reason I ask is because `socket.getaddrinfo` is the standard library and wraps the operating system calls to resolve a host name. If that is failing as you've described, that does not seem to be a problem with urllib3 at first blush but with your configuration.

**Comment by lmocsi** [comment]
This is how I use it:
import os
import requests
user = 'mydomain\\myuser'.upper()
pass_ = 'mypassword'
os.environ["https_proxy"] = "https://"+user+":"+pass_+"@proxy.dcce.net.sys:8080/"
os.environ["http_proxy"] = "http://"+user+":"+pass_+"@proxy.dcce.net.sys:8080/"

url = 'https://myapi.mysite.com'
r = requests.get(url)

**Comment by lmocsi** [comment]
Currently, I have downgraded to 1.25.8, and it is working.

**Comment by sethmlarson** [comment]
This is an issue with your username which contains a vackslash. Backslash is an authority delimiter so our URL parser is doing a lookup of "myuser". Can you try replacing the backslash with "%5C"?

**Comment by lmocsi** [comment]
Replacing backslashes with %5C solves the problem, but I would not like to rewrite all my scripts.
So I stick to v1.25.8 for the time being. :)
