### ISSUE TITLE
Allow silencing of InsecureRequestWarning for some connections, so others are kept

### ISSUE THREAD

**Issue by bernhardreiter** [urllib3/urllib3#1877]
Adding a way to remove warning for some connections with urllib3, will raise the security value
of the warning.

The use case is one module as part of a bigger application, where an unverified TLS request is fine, e.g. because the connection is guaranteed to go over a VPN and stays internal anyway. But other modules may not be so sure, so they should still get the warning. Because the current possibilies are only to silence all warnings or non, the logs maybe flooded with expected warnings for the connection, where it is fine. So the warning that should be seen, is harder to spot.

An improved behaviour would possibily add another parameter for some connections.

One code place is here:
https://github.com/urllib3/urllib3/blob/d478147543abaf6e71ebb92c404d3b6a5eb81276/src/urllib3/connectionpool.py#L985

One report for the use case is here https://github.com/MISP/PyMISP/issues/579

An alternative could be to add example code how to get a certificate from a single host
(without the CA chain, if that is not available) and such produce the parameter to use for the connection to pin this special host certificate only.

**Comment by sigmavirus24** [comment]
> Because the current possibilies are only to silence all warnings or non, the logs maybe flooded with expected warnings for the connection, where it is fine.

Warnings should be deduplicated within the same process by the warnings module. If you're getting "flooded" something is wrong in how you're using urllib3 or in your version of Python. That's more concerning than adding a parameter that allows people to silence this warning.

**Comment by bernhardreiter** [comment]
Thanks for your hint @sigmavirus24 

> how you're using urllib3 or in your version of Python

#### usage via requests, pymisp, intelmq bot
It is the https://github.com/MISP/PyMISP/ module, that uses requests, which uses urllib3.

A daemon in IntelmMQ (there called a 'bot') makes a "connection" to a MISP instance which is a different system.  using pymisp and then does a lot of operations over the connection which are logged,  each operation ends up with a warning in the log file. We are also seeing a lot of DNS request, so I roughly guess this will be separate calls to  requests (or urllib) in the end via HTTPS using a session token or so.

#### python3 version 
Debian GNU/Linux
Architecture: amd64
Version: 3.7.3-1

**Comment by sethmlarson** [comment]
SecurityWarnings fire on every .warn() call (`simplefilter("all")`) if you want the behavior that @sigmavirus24 is describing you should set the filter to "default".

**Comment by bernhardreiter** [comment]
@sethmlarson thanks for this hint. I'll look up who to do this. (Unless somebody has this ready as a recipe.)

Still I believe it would be cool, if there was a possibility to silence the warning for some connections only, so that other parts of the application are still warning. (However I am not well versed in the python logging framework to say how different commands would affect some modules always or not.)

**Comment by sethmlarson** [comment]
Closing this as not an issue.
