### ISSUE TITLE
Expose the raw response headers bytes string ?

### ISSUE THREAD

**Issue by wesinator** [urllib3/urllib3#1881]
Is it possible to expose the raw response header bytes ? 

Like how browser inspectors such as Firefox have a raw headers toggle:
<img width="551" alt="image" src="https://user-images.githubusercontent.com/5124946/83198308-e90f6080-a10c-11ea-8e16-72a0668820cf.png">

I don't see a way to access this currently under https://urllib3.readthedocs.io/en/latest/reference/index.html#urllib3.response.HTTPResponse, everything is processed into a dict 

Trying [`HTTPResponse.msg`](https://docs.python.org/2/library/httplib.html#httplib.HTTPResponse.msg) gives `None`

**"Use case":** being able to save the original, literal raw unparsed response as returned by the server

Thanks,

**Comment by sigmavirus24** [comment]
It's not possible because the only way to get that is by reading the socket yourself and http.client consumes that before we can to the best of my (potentially outdated) knowledge

**Comment by sethmlarson** [comment]
Yes by the point we see headers they're already parsed. I don't think this is feasible for us.

**Comment by wesinator** [comment]
ack, thanks
