### ISSUE TITLE
Add additional documentation for HTTPSConnection parameters

### ISSUE THREAD

**Issue by sirosen** [urllib3/urllib3#1884]
I'm not sure if this is intentional or not, but the reference doc for connection objects ( https://urllib3.readthedocs.io/en/latest/reference/index.html#urllib3.connection.VerifiedHTTPSConnection ) seems a little bit spare on details about the parameters accepted.

In particular, I was looking at using `server_hostname`, and I didn't find it anywhere in the reference doc.
I did eventually find it (I assume with the same meaning) documented on [this utility function](https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html#urllib3.util.ssl_wrap_socket).

Coming to these docs having very rarely needed to work directly with urllib3 (it's usually the transport used by some higher-level library I'm using, like `requests`), it seemed like the docs for the connection object were missing bits. If I were to open a PR adding a line to the docstring for each parameter, would it be welcome? Or are these params meant to be covered elsewhere in the docs?

**Comment by pquentin** [comment]
`HTTPSConnection` is a thin wrapper over `util.ssl_wrap_socket`, which creates a `SSLContext`, loads certificates, and wraps the socket. All the accepted parameters are thoroughly documented in https://docs.python.org/3/library/ssl.html, which is probably why we did not feel the need to expand too much on this.

I don't know what the right course of action would be here. I'm not sure we want to duplicate the documentation, but there is certainly room for improvement. There is a tension here, though: this documentation is generated from our source code, and is used both by urllib3 developers and users. For developers, it's better to have the utility function documented, but for users it make more sense to document `HTTPSConnection`.

Here is a possible plan:

 1. Mention in `HTTPSConnection` that the parameters are documented in `util.ssl_wrap_socket`
 2. Extend the advanced docs to document missing parameters like `server_hostname`

Would that help?

**Comment by sirosen** [comment]
I think that course of action would be perfect! If I can find time (and remember to do it) I'll work up a PR to add a reference from HTTPSConnection to util.ssl_wrap_socket and add a segment to the advanced doc which shows how to use `server_hostname` and `assert_hostname` to connect to an SNI host by IP address.
