### ISSUE TITLE
Forbid use of cadata arg in pyOpenSSL backend

### ISSUE THREAD

**Issue by MarSoft** [urllib3/urllib3#1885]
The class `urllib3.contrib.pyopenssl.PyOpenSSLContext` as a `load_verify_locations()` method. This method accepts `cadata` as its third parameter.
If this parameter is given then it wraps the provided certificate data in `io.BytesIO()` and passes to `OpenSSL.SSL.Context.load_verify_locations()` as `cafile` param.
But `OpenSSL.SSL.Context.load_verify_locations` does not support a file-like object for `cafile` param, it expects only file path.

This seems to break intentions of #1804.

**Comment by pquentin** [comment]
Hmm, this is a tricky one, thanks for pointing this out. As you said, pyOpenSSL does not support cadata, and only accepts cafile (a file path) or capath (a directory path). 

While we *could* write the data in a temporary file, I don't think urllib3 shoud write any kind of data to the filesystem. I think the best option is here is to refuse to handle the `cadata` argument, just like #1804 does it with Python < 2.7.9.

@sethmlarson @sigmavirus24 Thoughts?

**Comment by sigmavirus24** [comment]
> While we _could_ write the data in a temporary file, I don't think urllib3 shoud write any kind of data to the filesystem

Agreed

>  I think the best option is here is to refuse to handle the `cadata` argument, just like #1804 does it with Python < 2.7.9.

Makes sense to me

**Comment by sethmlarson** [comment]
I'm also in agreement here, no filesystem hacks instead fail loudly.

**Comment by pquentin** [comment]
@MarSoft Would you be interested in working on this?

**Comment by IvanLauLinTiong** [comment]
pyOpenSSL is deprecated and will be removed in future release version 2.x (https://github.com/urllib3/urllib3/issues/2691).
