### ISSUE TITLE
urllib3 should send http/1.1 ALPN extension by default

### ISSUE THREAD

**Issue by tiran** [urllib3/urllib3#1892]
Some servers start to require ALPN extension and shut down HTTPS connections forecefully when a client does not indicate HTTP protocol version in ALPN extension. The fix is a trivial one-liner. Daniel told me that curl has been setting ALPN header for years without any negative side-effects.

See https://bugs.python.org/issue40968 for CPython bug
See https://github.com/python/cpython/pull/20959 for CPython PR

**Comment by sethmlarson** [comment]
Thanks for opening this! I agree we should implement this.

**Comment by pquentin** [comment]
> The fix is a trivial one-liner.

It ended up being a 200 lines fix, as we support PyOpenSSL, SecureTransport, and had to test this. But it's in the master branch now :)

**Comment by sethmlarson** [comment]
I should know better that anything with the `TLS` label should disqualify the `Contributor Friendly` label just based on what we've got going in the TLS department. :)
