### ISSUE TITLE
Strange timeout on an IP request

### ISSUE THREAD

**Issue by muxishuihan** [urllib3/urllib3#1901]
Hi, i encountered a timeout while making a request to an IP, i have set the timeout parameter but the program is still stuck.My code is below:

```
import urllib3

url='47.104.233.88:80'
http = urllib3.PoolManager(timeout=urllib3.Timeout(connect=1.5, read=1.5))
rq = http.urlopen('GET',url='http://' + url)
```

I'm not sure if this is a silly question, if it is, I'm sorry for disturbing.
Look forward to your reply.

**Comment by sigmavirus24** [comment]
This can happen when the server sends some data within the 1.5s timeout but it's a small amount of data each time. Sending a byte every 0.9s could cause this as an example.

**Comment by muxishuihan** [comment]
@sigmavirus24 
Thank you for your reply, do you have any suggestions on this issue?

**Comment by sethmlarson** [comment]
@muxishuihan You can try using a tool like wireshark to capture what's happening on the wire and compare that to urllib3's behavior.
