### ISSUE TITLE
macOS Big Sur dynamic linker cache causes contrib/securetransport to raise an ImportError

### ISSUE THREAD

**Issue by sheagcraig** [urllib3/urllib3#1904]
On macOS Big Sur, Apple has added a "dynamic linker cache". When ctypes tries to find the Security and CoreFoundation frameworks, an ImportError is raised, really because `ctypes.utils.find_library` can't see that the path exists. However, if you go ahead and load it anyway, everything is happy.

Please see: https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11-beta-release-notes
Specifically:
New in macOS Big Sur 11 beta, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)

I have a PR for this ~incoming~ #1905 .

**Comment by sethmlarson** [comment]
Closed in #1905
