### ISSUE TITLE
Change request headers in between retries

### ISSUE THREAD

**Issue by alfred-soroush** [urllib3/urllib3#1913]
Consider an http request using an OAuth token. The access token needs to be included in the header as bearer. However, if the token is expired, another request needs to be made to refresh the token and then try again. So the custom Retry object will look like:

```
class OAuthRetry(Retry):
    def increment(self, method, url, *args, **kwargs):
        # refresh the token here
        return super(OAuthRetry, self).increment(method, url, *args, **kwargs)
```

The problem is that after the token is refreshed, HTTPConnectionPool is still using the same `headers` to make the request after calling `increment`. See: [https://github.com/urllib3/urllib3/blob/master/src/urllib3/connectionpool.py#L787](https://github.com/urllib3/urllib3/blob/master/src/urllib3/connectionpool.py#L787).
Although the instance of the pool is passed in `increment`, changing the headers there will not affect the call since it is using a local copy of the headers.

This seems like a use case that should come up frequently for the request parameters to change in between retries.

Is there a plan to support this?

**Comment by sigmavirus24** [comment]
> This seems like a use case that should come up frequently for the request parameters to change in between retries.

I don't think it's ever come up actually. Retries weren't meant to handle literally every possible case that someone might want to retry a request on. Further some AuthN schemes rely on there being multiple requests to execute the right thing. Hiding that in retry logic isn't semantically correct.

**Comment by pquentin** [comment]
Agreed with @sigmavirus24, I don't think this type of retry should be handled at the urllib3 level using the urllib3 API, but at the application level instead.

**Comment by alfred-soroush** [comment]
@pquentin @sigmavirus24 Thanks for looking into this so quickly. I agree with your comments that such a use case is not something that should be handled by urllib3 internally. However, at the moment the library allows custom implementations of `Retry`. Lacking the ability to modify the requests in `increment`, I believe renders the `Retry` redundant. If the request cannot be changed then `Retry` can merely retry the same request which can be done by just defining a number of `max_retries` rather than an implementation. I think a way to make a `Retry` implementation useful is to allow access to the request rather than just the url/method.

**Comment by pquentin** [comment]
> Lacking the ability to modify the requests in `increment`, I believe renders the `Retry` redundant.

All urllib3 internals are documented, but we don't make any promises that they can necessarily be useful for third parties. `increment()` is a useful function for urllib3 itself, that's all.

(I also believe that documenting everything like this was a mistake.)

**Comment by sigmavirus24** [comment]
@pquentin I appreciate you think it's a mistake but one could come up with alternative algorithms and subclass and would need to know the API
