### ISSUE TITLE
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=38771): Max retries exceeded with url: /session/3143eb49468d87d5490d14852be56fe1/cookie (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31faf32a30>: Failed to establish a new connection: [Errno 111] Connection refused'))

### ISSUE THREAD

**Issue by azamet90** [urllib3/urllib3#1915]
```
        try:
            time.sleep(2)
            browser.close()
            browser.quit()
            browser.delete_all_cookies()
            os.system("pkill chromium")
            os.system("pkill chromedriver")
            time.sleep(1)
            recaptchashit()
            Discord()
        except MaxRetryError:
            browser.delete_all_cookies()
            time.sleep(1)
            main()
```
this is a part of my code but i cannot understand how to close a window and open it again without getting urllib3.exceptions.MaxRetryError ?

it only happens if i close and quit the browser and open it with new proxy ...

**Comment by sethmlarson** [comment]
From your code example it's not obvious to me where urllib3 is being used. Can you provide an example which can be reproduced completely by us? Include Python version, OS and version, packages installed and how urllib3 is being used/ behaving unexpectedly.

Until this is provided I'm going to close this, will reopen if you provide above info.

**Comment by rish-hyun** [comment]
Well, I have encountered this too!!
I am using selenium in colab, if I interrupt a cell in which selenium is working, and then again re run, this type of error is being throwed. So If i run 
```
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
driver = webdriver.Chrome('chromedriver',options=chrome_options)
```
The program runs again but this is not I wanted to do again and again

**Comment by pquentin** [comment]
This is the urllib3 repository, we don't know anything about Selenium: locking.
