### ISSUE TITLE
Separate kind of error for the case of an unsuccessful attempt to establish a tunnel through a proxy

### ISSUE THREAD

**Issue by OneMoreZanuda** [urllib3/urllib3#1917]
The `_tunnel` method from the `http.client` raises an `OSError` when it fails to establish a tunnel through the proxy. This error is caught in the method urlopen as `SocketError` and wrapped in `ProxyError` with a message "Cannot connect to proxy.". Although in fact it was possible to connect to the proxy. It would be nice if a separate type of error was added (for example, ProxyTunnelError) that would contain the proxy's response to the request `CONNECT`. Probably, this could be the starting point for implementing proxy-authentication in the urllib3 (I mean complex authentication protocols: NTLM, Kerberos, Digest).

**Comment by OneMoreZanuda** [comment]
It might be more appropriate to create this issue for CPython, but it seems to me that the urllib3 is developing more dynamically and it is faster to rewrite the method _tunnel in the urllib3, than to wait for this from cpython.

**Comment by sethmlarson** [comment]
This has been completed for v2.0 so we can close this issue! :tada: Errors are wrapped in a `ProxyError`.
