### ISSUE TITLE
Incorrect handling of Retry-After (2.7)

### ISSUE THREAD

**Issue by hodbn** [urllib3/urllib3#1934]
`email.utils.parsedate_tz` behaves differently on python2.7/3 if the input string has no timezone. On [python3](https://docs.python.org/3/library/email.utils.html#email.utils.parsedate_tz), the last item of the return value is `0` where on [python2.7](https://docs.python.org/2/library/email.utils.html#email.utils.parsedate_tz) it is `None`. 

Since `email.utils.mktime_tz` assumes a ```None``` timezone to be the local timezone, the resulting date might be wrong when calculating `Retry-After` timeout of a value without a timezone.

To reproduce run the following test on a python2.7 machine with timezone != UTC:
`test/test_retry.py::TestRetry::test_respect_retry_after_header_sleep[Mon Jun  3 11:30:12 2019-True-1812]`

(Luckily, `freezegun` doesn't hide the issue since it freezes only the time using `tz_offset` but it doesn't patch the timezone.)

**Comment by sethmlarson** [comment]
Huh, wasn't seeing Python 2.7 failures on macOS, do you have a link to a failure. How'd you catch this issue?

**Comment by hodbn** [comment]
I ran it on my Linux VM which has weird timezone.

**Comment by sethmlarson** [comment]
Ahhh makes sense, glad you caught this! :)
