### ISSUE TITLE
Write a Migration Guide for v1.26.x -> v2.0.0

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#1973]
Can be a part of the v2.0.0 Roadmap documentation. Would be good to detail the specific steps and causes of all DeprecationWarnings and be URL-linkable so we can point to these docs within the actual warnings.

**Comment by sethmlarson** [comment]
This doesn't seem realistic right now, going to close this one until we can get volunteers.

**Comment by pquentin** [comment]
I do think we need something like that, but it can live in the breaking section of the changelog

**Comment by sethmlarson** [comment]
Always read issue titles closely before closing. Thought this was the docs translation issue.

**Comment by pquentin** [comment]
Useful migration guides that can be used for inspiration:
 * https://www.elastic.co/guide/en/elasticsearch/client/python-api/master/migration.html
 * https://esrally.readthedocs.io/en/stable/migrate.html
