### ISSUE TITLE
Initial Setup for Weblate Translations

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#1974]
https://hosted.weblate.org/projects/urllib3

- [ ] Created Weblate Libre project w/o approval yet
- [ ] Setup sphinx-intl for our project and commit untranslated .PO files
- [ ] Figure out how to do "Continuous Translations" as is documented in Weblate
- [ ] Request Approval for Libre project after components are uploaded

**Comment by comradekingu** [comment]
I can help you if you remove the CoC. :)

**Comment by pquentin** [comment]
@comradekingu What is the problem with the Code of Conduct? We're certainly not planning to remove it

**Comment by sethmlarson** [comment]
I think for now we're setting translations aside.
