### ISSUE TITLE
[v2] Detect unsupported Python versions and raise a helpful ImportError

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#1987]
We'll need to ensure our `urllib3/__init__.py` is still Python 2.x compatible for early urllib3 v2.x releases. If we detect an unsupported Python version we raise a helpful error message recommending pinning to `urllib3<2`

**Comment by pquentin** [comment]
Is the reasoning is that we're catering for users that still don't use pip 9+, released four years ago in November 2016? When should we be allowed to only rely on `python_requires`?

By the way, https://python3statement.org/practicalities/ is an interesting documentation about this issue, and here is what Django does: https://github.com/django/django/blob/3.1.3/setup.py#L7-L33

**Comment by sethmlarson** [comment]
@pquentin Yeah for old pip installs, still a good amount of them out there. 

Nice find! Yeah something exactly like Django would be great :)
