### ISSUE TITLE
[v2] Change default TLS and ciphers to 1.2+

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#1989]
- If we're given no `ssl_context`, `ssl_version`, or `ssl_ciphers` we should be using TLS 1.2+ and a much tighter cipher list.
- ~If we're given ssl_ciphers:~
  - ~Use TLS 1.0+~
- ~If we're given ssl_version:~
  - ~If it's TLS 1.2+, use tightened default ciphers~
  - ~If it's includes anything not TLS 1.2+, use previous list of ciphers~

We should do the above for all SSLContext implementations we support.

**Comment by pquentin** [comment]
Two questions:

 * Is TLS 1.0+ the minimum supported version for v2?
 * Is this why we have to default to 1.0+ when given ciphers? Because eg. the use case for `ssl_ciphers` is to add an old/not so secure cipher?

**Comment by sethmlarson** [comment]
- We haven't discussed minimum protocol version, I'm not sure we need to take a stance on this as the problem will likely resolve itself via OpenSSL+Python dropping support for insecure protocols as time goes on. We do need to be wary of when Python removes these `OP_NO_SSLv2` options though?

- I think we've decided to go a different direction wrt ciphers, for OpenSSL 1.1.1 we trust the systems configuration to be good enough as a default so run with that. For OpenSSL 1.1.0 and earlier though we currently have a PR our which drops RSA but that's it. Proposals have been to mirror what is on OpenSSL 1.1.1 defaults or take this information from some other source rather than curating our own list.

(Given the above bullet point I'm going to strikethrough the original comment suggestion of basing default ciphers off TLS version)
