### ISSUE TITLE
[v2] Add support for Content-Encoding: zstd

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#1992]
See: https://tools.ietf.org/html/rfc8478

### Minimum requirements

:moneybag: **You can get paid to complete this issue! [Please read the docs for more information](https://urllib3.readthedocs.io/en/latest/contributing.html#getting-paid-for-your-contributions).**

- [ ] Evaluate all zstandard packages that are available for Python, which makes sense for us to support? One, multiple?
- [ ] Add support for a `ZstandardDecoder`, don't enable `zstd` in `Accept-Encoding` by default though.
- [ ] Add documentation for the feature
- [ ] Add test cases for the feature, see `BrotliDecoder` and `Content-Encoding: brotli` tests for inspiration.

**Comment by sethmlarson** [comment]
Tagging @mamico here so I can assign this issue to you.

**Comment by Tins70** [comment]
#2752
