### ISSUE TITLE
[v2] Add a top-level urllib3.request() method

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#1993]
Use a default `PoolManager()` instance configured with certifi if it's available. Document it as not recommended for production use, recommended only for experimenting or quick scripts.

**Comment by imba-tjd** [comment]
Would you consider adding a default `Accept-Encoding: gzip` or sth? As I understand `identity` means no compression.

**Comment by sigmavirus24** [comment]
@imba-tjd this is completely unrelated to the original issue

**Comment by imba-tjd** [comment]
Yes, it's related. I'm only thinking adding the header to this "quick scripts".

**Comment by sigmavirus24** [comment]
I'd argue that changing the default for the library versus adding a convenience function as a proxy to a method on a commonly used object are two orthogonal feature requests. While this may have spurred the idea, they are not inextricably related and thus separate concerns

**Comment by shazow** [comment]
I'm curious, what's the thinking behind this part?

> Document it as not recommended for production use, recommended only for experimenting or quick scripts.

Perhaps better to document that this is a module-global instance and side effects on this instance from other code will be retained across dependencies?

**Comment by pquentin** [comment]
Done in #2150.
