### ISSUE TITLE
Reconsider using the official brotli package

### ISSUE THREAD

**Issue by jmelchiori** [urllib3/urllib3#2011]
This was proposed in #1620  but eventually rejected.

Problem being that use of brotlipy in urllib3 prevents anyone from using the official brotli package because they have conflicting namespaces.

**Comment by sethmlarson** [comment]
You can use the official Brotli package like so: `python -m pip install urllib3 brotli` (Note that we're not installing `urllib3[br]`)

urllib3 is compatible and is tested against both packages.
