### ISSUE TITLE
Documentation on the body parameter of urlopen is missing/out-of-date

### ISSUE THREAD

**Issue by jmholla** [urllib3/urllib3#2019]
### Subject

Documentation is out  of date.

### Environment

The Internet.

### Steps to Reproduce

1. Go to https://urllib3.readthedocs.io/en/latest/reference/urllib3.connectionpool.html#urllib3.HTTPConnectionPool.urlopen
2. Desire to learn more about the `body` parameter.
3. Find out `HTTPConnectionPool.post_url` doesn't exist.

### Expected Behavior

The documentation should point me somewhere else.

### Actual Behavior

Tears.

**Comment by sethmlarson** [comment]
Yeah I've already captured this issue here: https://github.com/urllib3/urllib3/issues/2003 so I'm closing this as a duplicate.

If you'd like to contribute the documentation fix I'd review it :)

**Comment by matthewhughes934** [comment]
Just noting: the docs didn't build for me without `pyopenssl` and `brotli` installed:

```
$ urllib3/docs$ make html
<----TRUNCATED---->
Warning, treated as error:
autodoc: failed to import module 'pyopenssl' from module 'urllib3.contrib'; the following exception was raised:
No module named 'OpenSSL'
```

```
$ urllib3/docs$ make html
<----TRUNCATED---->
Warning, treated as error:
autodoc: failed to import class 'BrotliDecoder' from module 'urllib3.response'; the following exception was raised:
Traceback (most recent call last):
```

(since `BrotliDecoder` appears to only be defined if `import brotli` doesn't raise an `ImportError`). Not convinced this wasn't just me missing something in the setup though.
