### ISSUE TITLE
urllib3 logo is unreadable in docs in dark mode

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#2028]
This is a recent Furo addition, you can see it in this pull request build: https://urllib3--2026.org.readthedocs.build/en/2026/index.html. Here's what I see (with Firefox on macOS with dark mode enabled):

<img width="237" alt="urllib3 logo in dark mode in docs" src="https://user-images.githubusercontent.com/42327/96408490-ad2c8300-11f4-11eb-8054-661fb38a6c23.png">

I'm not sure what the correct fix is here. The obvious one would be to force a white background. I guess we could also... add a dark mode urllib3 logo, by switching black letters to white?

(The rest of the content looks good, even if the contrast seems low to me.)

**Comment by sethmlarson** [comment]
Looks like this is supported by Furo now: https://github.com/pradyunsg/furo/issues/27

**Comment by pradyunsg** [comment]
There's a release containing the support now.

> if the contrast seems low to me.

Is this for the content? The contrast on the sidebar is intentionally lower -- otherwise it was distracting for me while I was designing this.
