### ISSUE TITLE
IPv6 slower than IPv4

### ISSUE THREAD

**Issue by oktorok** [urllib3/urllib3#2030]
### Subject

If i try to do a get request on 'https://geoportal.minetur.gob.es/VCTEL/infoantenasGeoJSON.do?idCapa=null&bbox=-1.5525697885398,39.26519497205,-1.549179476345,39.273649294864&zoom=4' on my system `socket.getaddrinfo` return a list where the first element is the IPv6 one and the second the IPv4 one in that case the request takes 2 minutes but in another system the returned list has IPv4 and not IPv6 and takes less than one second

### Environment

```
OS Linux-5.4.72-1-MANJARO-x86_64-with-glibc2.32
Python 3.9.0
urllib3 1.25.11
```
### Steps to Reproduce

```
import urllib3
http = urllib3.PoolManager()
url = 'https://geoportal.minetur.gob.es/VCTEL/infoantenasGeoJSON.do?idCapa=null&bbox=-1.5525697885398,39.26519497205,-1.549179476345,39.273649294864&zoom=4'
r = http.request("GET", url)
```

### Expected Behavior

Should take less than one second

### Actual Behavior

Takes 2 minutes

### More Info
I tried modifying, `urllib/utils/connection.py`, adding `sorted(sockets.getaddrinfo(...)) and it worked perfectly.
Should take always IPv6 as a primary option?? is this intended? the specs of a system where sockets.getaddrinfo() doesn't return IPv6 are:

```
OS Linux-4.18.0-25-generic-x86_64-with-Ubuntu-18.10-cosmic
Python 3.6.8
urllib3 1.22
```

I know that is a bit outdated but once agains would this be a server problem or urllib should be able to take the faster option from IPv6 and IPv4?

**Comment by sigmavirus24** [comment]
Do you know if the time is spent connecting via IPv6 or is the time consumed elsewhere? If it's spent connecting, I suspect a connect timeout would help you best here along with Retries

**Comment by sethmlarson** [comment]
At one point we had a PR for happy eyeballs (I think I was the author?). That would likely mediate the problem you're facing where connection to IPv6 is much slower than IPv4.

**Comment by oktorok** [comment]
@sigmavirus24  The time is spent on `sock.connect(sa)` and yes, effectively a timeout "solve" the problem. I don't think this is the better solution as you must wait atleast timeout seconds but of course is better than an error or 2 minutes wait.

But for a future what would be the correct behavior? add a happy eyeballs algorithm?

**Comment by sigmavirus24** [comment]
@oktorok your connect timeout can be fractions of a second (e.g., `0.1`)

**Comment by oktorok** [comment]
@sigmavirus24 this would work perfectly for a one time thing, but if you need to perform multiple requests, setting low timeouts can provoke errors because ping or latency.

Anyway, im not sure what should be the correct way of handle this, maybe happy eyeballs is the good idea for a future, meanwhile i think is not a big deal as after work 3 years with this library is the first time i face this problem.

**Comment by sigmavirus24** [comment]
> but if you need to perform multiple requests, setting low timeouts can provoke errors because ping or latency

That's not been my experience, but what do I know. I just run an engine doing thousands of requests a second as an integration system

**Comment by PMig24** [comment]
I'm sorry I cannot help you to answer why (I works find for me), but you can try this other way:

from urllib.request import urlopen
url = urlopen('https://geoportal.minetur.gob.es/VCTEL/infoantenasGeoJSON.do?idCapa=null&bbox=-1.5525697885398,39.26519497205,-1.549179476345,39.273649294864&zoom=4')
print(url.read())

**Comment by PMig24** [comment]
On the other hand, 
can I ask you a couple of questions?

- How did you know that the url to query against is that one?  (I cannot find the parameters in its ):
https://geoportal.minetur.gob.es/VCTEL/infoantenasGeoJSON.do?idCapa=null&bbox=-1.5525697885398,39.26519497205,-1.549179476345,39.273649294864&zoom=4

- is there any way to guess the coordinates of the squares you are querying against (to get all the towers in a city)?

Many thanks in advance.

**Comment by ZurMaD** [comment]
> @sigmavirus24 The time is spent on `sock.connect(sa)` and yes, effectively a timeout "solve" the problem. I don't think this is the better solution as you must wait atleast timeout seconds but of course is better than an error or 2 minutes wait.
> 
> But for a future what would be the correct behavior? add a happy eyeballs algorithm?

It's not directly related but I'm using a library called gdown to download google drive files and the code just freezes at  `sock.connect(sa)`  while using urllib3 

![image](https://user-images.githubusercontent.com/28235457/103102648-ffba5f00-45ea-11eb-8b25-f21750dbf6b6.png)

**Comment by jakermx** [comment]
IPv6 adreeesing is 4 times  larger than IPv4, 128 vs 32....

IPv6 is not  fully implemented on all systems, neither on all Networing Devices... so thinking about this.... lets say you implent IPv6 on your home Router...but your ISP havent...but your ISPs GigaPOP have it... and so....the IP4 to IP6 and Viceversa Proxying betweet your client device and the end side.. will take larger time than just IP4, because, the NAT and Session Map.

There are several OS commands to test if a netpath is fully IP6 compatible,if so...you can freely use IP6 to that specific Address (not URI or URL) if not....fallback to IP4

**Comment by jakermx** [comment]
I forgot to say..... IP4 and IP6 have very diferent MTU sizes, and fragmentation may occour...which is a Well Known Security Issue, and most of the FW branches will drop the packets with Fragmentention Flag set on 1, try decreassing your IP6 MTU below 1000 and keep us posted

**Comment by sethmlarson** [comment]
I'm going to close this as duplicate of #797 which is the correct solution.
