### ISSUE TITLE
[v2] Change "brotli" extra to depend on brotli instead of brotlipy (/brotlicffi) for CPython

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2040]
Google's brotli bindings are much more performant as they don't use cffi, the only reason I can remember for us using brotlipy was to support PyPy. On PyPy we can continue to install brotlipy but on CPython it doesn't make sense for us to take the performance hit.

There are also plans to rename brotlipy to `brotlicffi` in order to resolve the name conflict with Google's brotli bindings: https://github.com/python-hyper/brotlipy/issues/145

**Comment by pquentin** [comment]
@sethmlarson Thanks for renaming brotlipy to brotlicffi! Should we wait for a release before tackling this?

**Comment by sethmlarson** [comment]
This work can proceed now that `brotlicffi` is released: https://pypi.org/project/brotlicffi

**Comment by sethmlarson** [comment]
Closed in https://github.com/urllib3/urllib3/pull/2099
