### ISSUE TITLE
Address the automated release failure for v1.26.0

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2043]
https://travis-ci.com/github/urllib3/urllib3/builds/199806823

Might be good if we could be running release dry-runs semi-frequently so we don't get surprised when it's showtime.

**Comment by hugovk** [comment]
Looks like this, there's a pending PR and workaround available: https://travis-ci.community/t/cant-deploy-to-pypi-anymore-pkg-resources-contextualversionconflict-importlib-metadata-0-18/10494/9?u=hugovk

---

Something I've been doing to keep the release mechanism well-oiled: deploy to TestPyPI on merges to master, and deploy to prod PyPI on tags.

Travis CI example:

* https://github.com/pylast/pylast/blob/69d5d6ec9aa463cdbf703192c61fc17fb8f2c72b/.travis.yml#L43-L66

GHA example:

* https://github.com/hugovk/pypistats/blob/master/.github/workflows/deploy.yml

(And will be likely moving most Travis stuff to GHA.)

**Comment by pquentin** [comment]
+1 on auto-deploying to TestPyPy from GHA on merges to master, I was going to suggest that!

**Comment by hugovk** [comment]
btw the Travis problem should be fixed now:

https://travis-ci.community/t/cant-deploy-to-pypi-anymore-pkg-resources-contextualversionconflict-importlib-metadata-0-18/10494/25?u=hugovk

**Comment by sethmlarson** [comment]
Going to close this one, we're not on Travis any longer.
