### ISSUE TITLE
 '<' not supported between instances of 'list' and 'int'

### ISSUE THREAD

**Issue by kiranajij** [urllib3/urllib3#2056]
File "/***/anaconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 483, in is_exhausted
    return min(retry_counts) < 0
TypeError: '<' not supported between instances of 'list' and 'int'

Think this can be updated easily

**Comment by sethmlarson** [comment]
Can you give more information (fill out the issue template) so we can respond to this issue? Without that information we can't do much here.

**Comment by kiranajij** [comment]
Never mind it was the error of the Library I was using
