### ISSUE TITLE
Dealing with new DeprecationWarning about using method_whitelist argument of Retry

### ISSUE THREAD

**Issue by andy-maier** [urllib3/urllib3#2057]
We are using the `method_whitelist` init parameter of `Retry`. Version 1.26.0 of urllib3 introduced a replacement init parameter named `allowed_methods` and at the same time started issuing a DeprecationWarning for using `method_whitelist`.

Our tests are set up to fail if unexpected warnings are issued. Also, our package is included in Linux distributions so we are relatively conservative regarding version upgrades of dependent packages such as urllib3. Also, upgrading the minimum version of urllib3 would drive other upgrades: For example, we are using a minimum version of requests 2.20.1 which specifies urllib3>=1.21.1,<1.25.

Therefore, we would like to have a way to figure out whether the `allowed_methods` argument is already supported or not. Since this is a change to the init method, it is difficult to react to that change in user code. For example, one could check if the Retry object has an attribute named `allowed_methods` but for that the object first needs to have been created.

One way to check this seems to be to verify the urllib3 package version which I would rather try to avoid if possible.

Another solution would be to suppress the DeprecationWarning, but we would not like to do that globally, and catching the warning just for this object creation seems like overkill. Plus, this approach would fail once you remove the old init argument.

Is there a simple way to find out whether Retry supports the `allowed_methods` init argument?

PS: I have a hard time understanding why you did this change in the first place. Just for a nicer name? From one of your user's perspective, this was definitely not worth it. Just my 2 cents on that.

**Comment by andy-maier** [comment]
We are now using the following approach:

At the module level:
```
with warnings.catch_warnings():
    warnings.filterwarnings('error')
    try:
        urllib3.Retry(method_whitelist={})
    except (DeprecationWarning, AttributeError):
        RETRY_METHODS_PARM = 'allowed_methods'
    else:
        RETRY_METHODS_PARM = 'method_whitelist'

RETRY_KWARGS = dict(
    total=HTTP_TOTAL_RETRIES,
    connect=HTTP_CONNECT_RETRIES,
    read=HTTP_READ_RETRIES,
    redirect=HTTP_MAX_REDIRECTS,
    backoff_factor=HTTP_RETRY_BACKOFF_FACTOR
)
RETRY_KWARGS[RETRY_METHODS_PARM] = {'POST'}
```

When the Retry object is created:
```
retry = urllib3.Retry(**RETRY_KWARGS)
```

I verified this works with urllib3 versions 1.25.0 and 1.26.2 on Python 3.9.

**Comment by sethmlarson** [comment]
Thanks for opening this issue! You can use the `Retry.DEFAULT` object potentially:

```
use_allowed_methods = hasattr(urllib3.util.Retry.DEFAULT, "allowed_methods")
```

**Comment by sethmlarson** [comment]
Regarding the why, we wanted to migrate to names that don't have racial charge/connotations and instead are immediately easier to understand by someone not from the same culture as the author.

Our decision to do this predates Google but they have a good writeup on their own migration away from such terminology: https://chromium.googlesource.com/chromium/src/+/master/styleguide/inclusive_code.md#racially-neutral

**Comment by pquentin** [comment]
I'd recommend using `hasattr` too as it seems simpler than try/except/else + using the warnings module.

I don't think there was a better way to handle that change than a warning in 1.26.x and removing it in 2.x. It's more work if you want to support multiple urllib3 versions and avoid warnings like you do, and we would like to apologize for that added work. Hopefully the rest of the migration to 2.x should be smooth, and this workaround will soon be an issue of the past.

In any case, I don't think there's anything actionable left for us here.

**Comment by AdamWill** [comment]
Just wanted to chip in that I just ran slap bang into this same problem. Saw the deprecation warning when testing on urllib 1.26 (Fedora 35), switched to the recommended new method, then things started blowing up when deployed on a slightly older system that has urllib 1.25 (Fedora 34).

This does seem like a really aggressive deprecation schedule. It would've been nice if it had been smoothed out *somehow*.
