### ISSUE TITLE
[v2] For consideration: Providing a minimal "Transport API" interface.

### ISSUE THREAD

**Issue by tomchristie** [urllib3/urllib3#2073]
Raising this one in order to explore if there's potential here or not?...

Many high-level HTTP clients have an API layer that separates out the "high level" elements such as request/response models, cookie handling, redirects, authentication schemes, content encoding and decoding, environment based configuration, and the "network layer" that's responsible for actually sending the HTTP request.

* requests has ["Transport Adapters"](https://requests.readthedocs.io/en/latest/user/advanced/#transport-adapters).
* aiohttp has ["Connectors"](https://docs.aiohttp.org/en/stable/client_advanced.html#connectors).
* httpx has the ["Transport API"](https://www.python-httpx.org/advanced/#writing-custom-transports).
* hip has some similar [design discussions](https://github.com/python-trio/hip/issues/124#issuecomment-529412759).

With HTTPX we've taken a lot of care over iterating on this API, so that our Transport API only use plain data types, and allowing users to switch out the default `httpcore`-based transport with alternates, including `ASGI` or `WSGI` transports, or mock transport implementations.

We've been wondering if there's any mileage in us trying to align our work here with the upcoming `urllib3` version 2.0. For example, URLLib3 could potentially expose the same interface, allowing for this kind of usage:

```python
import httpx
import urllib3

client = httpx.Client(transport=urllib3.HTTPTransport())
```

Certainly it's the case that we don't *necessarily* need URLLib3 to expose the Transport API in order to provide this kind of functionality - we can [shim over the existing `PoolManager` interface](https://gist.github.com/florimondmanca/d56764d78d748eb9f73165da388e546e) to provide a third-party implementation. But there are arguably ecosystem benefits if we're able to work from the same interface.

We're able to pool our design expertise, developers have a single interface to learn which can then be reused in different contexts, and we're able to share transport implementations or adapters which modify a transport. (eg. A transport layer that implements HTTP caching support.)

There's also other areas of the ecosystem that it could impact. For example, a future version of `requests` could potentially add support for the transport API, without requiring fundamental API changes or large internal refactoring...

```python
import requests
import httpcore

# Use httpcore, for HTTP/2 support.
session = requests.Session(transport=httpcore.HTTPTransport(http2=True))
```

I'd rather aim this conversation towards a more general sounding out of *"is this worth exploring?"*, rather than getting bogged down in specific elements of our design decisions there, but for the sake of context, our transport API aims to fulfil the following objectives:

* Make an HTTP request and return the HTTP response, with a plain API involving only primitive datatypes.
* URLs should be provided as a pre-parsed tuple of `(scheme, host, port, target)`, which ensures URL parsing does not differ on the client-side vs. the network handling, and also allows HTTP requests such as `OPTIONS *` or proxy `CONNECT` requests to be properly expressed.
* Provide an interface for ensuring that responses are always closed once the stream onto the response body is no longer required.
* Allow a point of extension for elements that don't fit into the core abstraction - timeout parameters, trailing HTTP headers, raw connections in response to CONNECT/Upgrade requests, HTTP/2 server push etc...

The synchronous version of the interface boils down to a context managed method, like so:

```python
@contextmanager
def request(self, method, url, headers, stream, extensions):
    """
    method: bytes
    url: tuple[bytes, bytes, Optional[int], bytes]
    headers: list[tuple[bytes, bytes]]
    stream: iterable[bytes]
    extensions: dict
    
    return: tuple[
      int,
      list[tuple[bytes, bytes]],
      iterable[bytes],
      dict
    ]
    """
    yield (status_code, headers, stream, extensions)
```

I've no problem with this conversation falling squaring into the "out of scope" bucket if it's not really an avenue worth exploring for URLLib3 version 2, or isn't really considered a great fit for your project directions, but I'd be interested to get your collective thoughts on if it's there's something worth us trying to work on together here?

Prompted by #1944

Related bits of Transport API design issues on httpx and httpcore: https://github.com/encode/httpx/issues/1274, https://github.com/encode/httpx/issues/1358, https://github.com/encode/httpcore/issues/145#issuecomment-728855132

**Comment by sigmavirus24** [comment]
I'm wary of trying to coordinate this without a base definition of interfaces which makes us start acting like Java (where there's a package defining interfaces that other libraries implement).

We can do that, but it's worth asking the question, do we want to build a common definition via `zope.interface` such that we can verify the object or `abc.ABCMeta`? Do either of those packages allow us to verify all packages are using the same types? Do we need to ship something else?

Potentially orthogonal to this, I've long stated that the Requests API while initially always appealing is an example of a hydra that one can't rein in and is confusing to users. It's the wrong API. Shimming that is one thing, but I think most structured types would be worth the trouble.

**Comment by sethmlarson** [comment]
Thanks for opening this proposal. I'm in favor of us working towards having interfaces that are compatible across different clients.

Adding to what @sigmavirus24 mentioned wrt "what do we ship": my initial thought was creating a repository that has ABC/type hint files along with accompanying requirements of both users and implementations (a "host" header must be sent, headers case must be preserved, etc) must follow. Almost like a PEP but not necessarily tied to the PEP process. What are your thoughts on this?

With extra ambition, I am also hopeful that starting here we can expand this to other interfaces (headers, TLS, and proxies -- oh my!) to ease the pain of "lock-in" so-to-speak across HTTP clients when it comes to libraries that build on top of/extend HTTP clients.

My thoughts on the actual interface/types: I'd prefer a file-like API for response body for better control of the data that is pulled. Otherwise seems good to me.

**Comment by sigmavirus24** [comment]
I think the other thing, to @sethmlarson last point is we need someway of testing transports to ensure consistent behaviour not just consistent APIs. And I think there's nuance there. It's worth the effort in my opinion though

**Comment by tomchristie** [comment]
Thanks folks, so...

Yup, I don't have a problem with the base definition being an actually packaged interface. I think it's a bit hard to take a call on what the pros/cons of that are vs. taking the looser style where there's just a defined contract. (Eg as with WSGI/ASGI/DBAPI).

And, yup, it makes sense to *also* tightly specify other expectations of the contract that go beyond the type interface.

The closest we have at the moment is the type definition in `httpcore`, here... https://github.com/encode/httpcore/blob/0fce6d3ee4f440abd1512924b776acd69181fbfe/httpcore/_sync/base.py#L64-L71

Which we're proposing to iterate on slightly, and switch out to a context managed style, here... https://github.com/encode/httpcore/blob/f9563cf75d65325f7ab6904c5481a05577b8cc3e/httpcore/_sync/base.py#L35-L50 because we *think* it's preferable to callbacks-to-close.

See also the [corresponding async variant](https://github.com/encode/httpcore/blob/f9563cf75d65325f7ab6904c5481a05577b8cc3e/httpcore/_async/base.py#L35-L50).

> Almost like a PEP but not necessarily tied to the PEP process. What are your thoughts on this?

Indeed yup. Aware it *could* be difficult to avoid getting stuck in bikeshedding, or to get to a consensus on some corners of this, so I'm going to hold the hope lightly at the moment, but... 🤞😀

Obvious variations on what we have at the moment might be...

* Returning object instances for responses, rather than a plain tuple-of-types interface.
* Accepting request instances, rather than named parameters.
* Supporting a "close-as-callback" interface, rather than a context-managed style. I *think* we're minded to prefer the later style, but it's a difficult one.
* Supporting a file-like interface for reads, rather than a plain iterator (with per-instance configuration to control internal buffer-size, and higher-level clients providing more flexible interfaces over the top).

I reckon we're probably able to be flexible on changing things on our side around those areas if it helps us build a consensus.

One potentially contentious areas are the extensions. (Which I think are awkward and finicky, but probably necessary. In leaky abstractions at least let's make sure to keep the leaks nicely isolated.)

Right now we've got the following...

Request extensions:

* `timeout` - `Dict[float]`. Optional. With httpcore we currently support timeout configurations of `"pool"`, `"connect"`, `"read"`, `"write"`.

Response extensions:

* `reason_phrase` - `bytes`. Optional. Not used with HTTP/2+.
* `http_version` - `bytes`. Optional. Not always available, eg. with WSGI transports, mock transports. Client may default to `b"HTTP/1.1"`.

Examples of future areas that'd be expected to fall under extensions...

* Raw socket interface in response to `CONNECT`/`Upgrade`.
* Interface to support trailing headers.
* HTTP/2 server push support.
* Potentially stuff like socket address information / certificate info.
* Perhaps zero-copy/sendfile support sometime.

Another awkward area is what expectations to have around valid exception classes. We've got a pretty tightly defined hierarchy in `httpcore`, but it's not clear if that's exactly what you'd want to do for a baseline abstract interface.

**Comment by sigmavirus24** [comment]
> Another awkward area is what expectations to have around valid exception classes. We've got a pretty tightly defined hierarchy in `httpcore`, but it's not clear if that's exactly what you'd want to do for a baseline abstract interface.

I'd prefer no hierarchy. We should be using `zope.interface` as that can actually verify the contract is upheld (as best as we can hope for in a language like Python).

**Comment by tomchristie** [comment]
> We should be using zope.interface as that can actually verify the contract is upheld

Upholding the contract sounds potentially valuable, tho I probably wouldn't be keen on a base interface package pulling in a dependancy to `zope`?

**Comment by sigmavirus24** [comment]
> Upholding the contract sounds potentially valuable, tho I probably wouldn't be keen on a base interface package pulling in a dependancy to `zope`?

You don't get all of `zope`. There are `namespace` packages in python such that `zope.interface` works despite `zope` not being installed. Twisted uses it like this as do many other libraries. `zope.interface` is also literally the package name. https://zopeinterface.readthedocs.io/en/latest/hacking.html

**Comment by sigmavirus24** [comment]
https://glyph.twistedmatrix.com/2009/02/explaining-why-interfaces-are-great.html is also a good post

**Comment by tomchristie** [comment]
> You don't get all of zope. There are namespace packages in python such that zope.interface works despite zope not being installed.

Ah gotcha.

Anyways, certainly I'm on the same page that subclassing for interfaces isn't the most elegant, and that an actual *interface system* can make sense. Tho not sure I could take a call on how I felt about the benefits of using zope.interface vs. the more vanilla just-subclass-it style just yet.

I guess either way around, we've still got the same question around what we'd expect the interface to be.

**Comment by sigmavirus24** [comment]
On the one case, there's a way to verify the implementers are implementing the interface (zope.interface) and on the other we have ... nothing of real value towards ensuring people providing objects are doing anything other than inheriting from the right objects. And `attrs` provides a nice way to validate things if you use that to build your classes.

**Comment by tomchristie** [comment]
With `httpx 0.18` we've settled on a formalised Transport API.

Documented here: https://www.python-httpx.org/advanced/#custom-transports
Monthly report blog post exploring the Transport API: https://www.encode.io/reports/april-2021

Somewhat minded for `httpx` 1.0 to include a built-in optional urllib3 transport, so...

```python
import httpx

client = httpx.Client(transport=httpx.URLLib3Transport())
```

Which would be based on [Florimond's gist from a slightly earlier draft of the Transport API](https://gist.github.com/florimondmanca/d56764d78d748eb9f73165da388e546e).

Anyways, just throwing this stuff out there for visibility, since there's some intersection between our work here.

**Comment by sethmlarson** [comment]
Since this hasn't moved in some time I think we're going to close this one for now. I think having some sort of "[Python PSR-17](https://www.php-fig.org/psr/psr-17/)" would be helpful, if anything it'd be interesting to standardize the `request(method, url, headers, body) -> resp(status, headers, body)` type signature.

**Comment by tomchristie** [comment]
> Since this hasn't moved in some time I think we're going to close this one for now.

Yes good call Seth, thanks.
