### ISSUE TITLE
Start using towncrier for tracking changes

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2085]
This will make sure that we don't miss anything. Asking if anyone on our team has configured towncrier in the past :)

**Comment by pquentin** [comment]
I did :)

Are we OK with the five default categories or do we want to customize that? https://towncrier.readthedocs.io/en/actual-freaking-docs/quickstart.html#creating-news-fragments

**Comment by sethmlarson** [comment]
Can we add a section for breaking changes?
