### ISSUE TITLE
Possible bug in decoding

### ISSUE THREAD

**Issue by rbpasker** [urllib3/urllib3#209]
I was getting a stacktrace in my app today from ContextIO, which uses rauth, which uses requests, which uses urllib3:

```
  File "/Users/rbp/Projects/Python-ContextIO/contextio/__init__.py", line 1592, in get_content
    return StringIO.StringIO(response.read())
  File "/Users/rbp/Projects/tengahdb/default/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 191, in read
    buf = self._decoder.decompress(binary_type())
error: Error -2 while decompressing: inconsistent stream state
```

This was traced to a bug elsewhere, but I did notice that `get_content` was being called with  `decode_content=False`, so I developed this patch, which helped me ultimately find the root cause

--bob

```
***************
*** 191,193 ****  
!             if flush_decoder and self._decoder:
                  buf = self._decoder.decompress(binary_type())
                  data += buf + self._decoder.flush()

--- 191,193 ----
!             if flush_decoder and decode_content and self._decoder:
                  buf = self._decoder.decompress(binary_type())
                  data += buf + self._decoder.flush()
```

**Comment by bryanhelmig** [comment]
Cross posted in the downstream related requests issue:

---------

Found a way to reproduce this:

```python
>>> r = requests.get('http://www.newyorklantern.com/wp-content/uploads/2015/01/golden-crystal-ball-129x150.jpg', stream=True)
>>> _ = r.raw.read(10000, decode_content=True); print len(_)
4412
>>> _ = r.raw.read(10000, decode_content=True); print len(_)
0
>>> _ = r.raw.read(10000, decode_content=True); print len(_)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/bryanhelmig/.virtualenvs/zapier/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 224, in read
    "failed to decode it." % content_encoding, e)
DecodeError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -2 while decompressing: inconsistent stream state',))
```

For anyone Googling this. Dunno if it is a bug? But if the server is not delivering gzip - you can read from the socket all day long with no stream errors.

**Comment by Lukasa** [comment]
I suspect our gzip decoder doesn't expect to get an empty read twice in a row.

**Comment by bryanhelmig** [comment]
Yeah - we have a few layers of generator wrappers that pass chunks up so sometimes it will try yet another `read()` on an exhausted stream. Just sloppy code on our part, but it might be a nicer API to match the non-gzip stream behavior. If I get a few hours I'll try and surface a urllib3 specific test case and PR.

**Comment by bryanhelmig** [comment]
Continuing this thread in https://github.com/shazow/urllib3/pull/535.
