### ISSUE TITLE
Investigate default TLS ciphers for pyOpenSSL

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2090]
https://github.com/urllib3/urllib3/pull/2082 makes system ciphers the default with stdlib `SSLContext` implementation. Can we take a similar approach with pyOpenSSL or should we still rely on urllib3's default list?

If we're relying on urllib3's default list we only need to make `pyopenssl.inject_into_urllib3()` set `USE_SYSTEM_SSL_CIPHERS` to `False` unconditionally.

cc @tiran @alex

**Comment by alex** [comment]
pyOpenSSL doesn't provide its own default list, so it's a matter of whether you're happy with OpenSSL's defaults (across a wide variety of OpenSSL, naturally).

My memory of "which OpenSSL versions have acceptable defaults" is kind of hazy, so I don't have a better suggestion than to flip the setting, and hit https://www.howsmyssl.com/s/api.html from a few different linux distros with different OpenSSL versions and see if the settings look ok.

**Comment by sethmlarson** [comment]
@alex Thanks for the reply, it looks like the best way to determine the OpenSSL version of pyOpenSSL to use `cryptography.hazmat.backends.openssl.backend.backend.openssl_version_number()`.

We're planning on using OpenSSL-configured defaults on OpenSSL 1.1.1+, so would be `>= 0x10101000`

**Comment by tiran** [comment]
Caution, ``>= 0x10101000`` is no good with LibreSSL. It always reports OpenSSL version ``0x20000000``.

**Comment by sethmlarson** [comment]
@tiran Yikes, is there a canonical way to detect OpenSSL & v1.1.1+?

**Comment by tiran** [comment]
```
IS_LIBRESSL = ssl.OPENSSL_VERSION.startswith('LibreSSL')
IS_OPENSSL_1_1_1 = not IS_LIBRESSL and ssl.OPENSSL_VERSION_INFO >= (1, 1, 1)
```

**Comment by sethmlarson** [comment]
Instead of filtering out LibreSSL should we instead only use OpenSSL? `ssl.OPENSSL_VERSION.startswith("OpenSSL")`?

**Comment by tiran** [comment]
IMO it makes more sense to special case LibreSSL as they decided to redefine ``OPENSSL_VERSION_NUMBER``. CPython code and PyCA cryptography code have been checking for either ``LIBRESSL_VERSION_NUMBER`` C macro or ``ssl.OPENSSL_VERSION.startswith('LibreSSL')`` for years, too.
