### ISSUE TITLE
Investigate default TLS ciphers for SecureTransport

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2091]
#2082 makes system ciphers the default with stdlib SSLContext implementation. Can we take a similar approach with SecureTransport or should we still rely on urllib3's default list?

If we're relying on urllib3's default list we only need to make securetransport.inject_into_urllib3() set USE_SYSTEM_SSL_CIPHERS to False unconditionally.

We should remove all the RSA ciphers from the list if we end up not using system ciphers.

cc @pquentin would be great if you could test this out as our resident macOS owner :)

**Comment by pquentin** [comment]
Can you please clarify what you would like me to test?

**Comment by sethmlarson** [comment]
@pquentin Seeing if we can remove the section where we explicitly configure ciphers and SecureTransport chooses mostly secure ciphers by default. If that's the case then we can rely on Apple/system defaults, otherwise we'll continue configuring our own.

**Comment by pquentin** [comment]
SecureTransport in macOS 10.15 and 11.0 enables the following list by default:

```
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
TLS_RSA_WITH_AES_256_GCM_SHA384
TLS_RSA_WITH_AES_128_GCM_SHA256
TLS_RSA_WITH_AES_256_CBC_SHA256
TLS_RSA_WITH_AES_128_CBC_SHA256
TLS_RSA_WITH_AES_256_CBC_SHA
TLS_RSA_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_3DES_EDE_CBC_SHA
```

Travis supports many older macOS versions, I can run my script there if there's interest

**Comment by pquentin** [comment]
Since [Travis supports macOS 10.11+](https://docs.travis-ci.com/user/reference/osx/), I asked it to [print ciphers for macOS 10.11 to 10.15](https://github.com/pquentin/urllib3/commit/a3397a4c500cf30851f7d0f64ff3edf80a3f40a0).

The result : all versions from macOS 10.12 to 10.15 support precisely the ciphers mentioned above.

macOS 10.11 supports those too:

```
TLS_ECDHE_ECDSA_WITH_RC4_128_SHA
TLS_ECDHE_RSA_WITH_RC4_128_SHA
TLS_RSA_WITH_RC4_128_SHA
TLS_RSA_WITH_RC4_128_MD5
```

But macOS 10.11 was EOL'd in September 2018, so we can probably ignore those extra ciphers.

**Comment by pquentin** [comment]
As discussed on Discord today, this investigation is over: SecureTransport uses sensible ciphers and can remove one it it's broken. There's no need to set our own cipher list here.
