### ISSUE TITLE
CLOSE_WAIT connections left unclosed when using library with dataflow

### ISSUE THREAD

**Issue by daisy1754** [urllib3/urllib3#2100]
### Subject

When I use elasticsaerch-py or requests library (both uses urllib3's connection manager under the hood), there is a CLOSE_WAIT connections piling up after running job sometime and eventually caused connection timeout because all connections in the pool stuck in CLOSE_WAIT status.

### Steps to Reproduce

I reported https://github.com/elastic/elasticsearch-py/issues/1459 with sample code and repro steps. Also I was able to repro the same behaviour when I use requests package like below:

```
        session = requests.Session()
        adapter = requests.adapters.HTTPAdapter(pool_maxsize=20, max_retries=3)
        session.mount('https://', adapter)
```

### Expected Behavior

 - urllib3 closes connection properly and there is no CLOSE_WAIT socket for long period of time
 - urllib3 somehow detect connection got stuck and request a new connection (not ideal but better than job got stuck)

### Actual Behavior

Some connection got stuck in CLOSE_WAIT status (I can see it with `netstat -a`) and as a result application program experience connection timeout error.

![Screen Shot 2020-12-03 at 4 53 46 PM](https://user-images.githubusercontent.com/980077/101107887-2b1bd200-3588-11eb-848e-dc7b30b62b04.png)

**Comment by sethmlarson** [comment]
CLOSE_WAIT is expected if you have "burstiness" in an application, if some TCP connections aren't needed then they will naturally go into the CLOSE_WAIT state. This is why we check to see if a connection is dropped whenever we request a connection from the ConnectionPool.

Also the way that we push and pop connections from the queue in a non-rotational way. We actually pull the most recently used connection (LIFO) that's in the queue as it's most likely to be "alive" even if this means that some connections are "ignored" if there isn't enough demand for them and so naturally go into the CLOSE_WAIT state.

We don't do background management of connections in the queue as that'd be more involved. Perhaps instead you can reduce the maximum number of connections in your pool to match your requirements, you'd be surprised how many requests per second a small number of connections can handle :)

Let me know if this matches what you're seeing.

**Comment by daisy1754** [comment]
Hi @sethmlarson thanks for response.

We call elasticsearch server from Google cloud's dataflow job (which would probably cause burtisness, as dataflow/beam is parallel execution framework). Job works fine for a few hours but after that we starts to see "connection timeout" (stacktrace below). Once VM got in this situation, it keeps producing the similar log and it never makes successful HTTP call.

Then I ssh into the VM and do netstat to do a screenshot. In above there are 40 connections. My program initialize pool with `pool_maxsize=20` and dataflow internally creates two python processes per VM so 40 is max number of connections I expect. I somehow assumed CLOSE_WAIT is cause of the issue we're seeing but maybe that was red herring. On trying small number of connection, I also tried max_size of 5 before and had same issue.

Do you have any idea why we were getting connection timeout? I contacted both elasticsearch and google cloud but either said they didn't see any issue. Any tips on debugging this further would be appreciated.

```
Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 1213, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 570, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "main.py", line 159, in process
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 1617, in search
    body=body,
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/transport.py", line 390, in perform_request
    raise e
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/transport.py", line 365, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 258, in perform_request
    raise ConnectionError("N/A", str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPSConnection object at 0x7fe5d04e5690>: Failed to establish a new connection: [Errno 110] Connection timed out) caused by: NewConnectionError(<urllib3.connection.HTTPSConnection object at 0x7fe5d04e5690>: Failed to establish a new connection: [Errno 110] Connection timed out)
```

**Comment by sethmlarson** [comment]
Since we haven't heard anything in some time I'm going to close this one, let me know if we need to reopen.

**Comment by ZbigniewRA** [comment]
For other people reading this issue I want to say I expeirence the same problem.

In my project I often:
- create a new `requests` `Session`,
- do one `get()`,
- `close()` the `Response`
- `close()` the `Session`.

But the connections are never actually closed and I get hundreds of them in the `CLOSE_WAIT` state.
Very soon I get `OSError: [Errno 24] Too many open files`.

I would file a new bug report for that, but I could not get it working on a minimal reproduction example, and I'm not even sure if that is an issue in `requests` or `urlib3`. What I've noticed however is that doing `del response` forced some connections to actually close, but not all. Doing `gc.collect()` forced some more to close, but not all.
