### ISSUE TITLE
Make sure README looks good in GitHub dark mode

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#2103]
GitHub just added dark mode support in its app and web site. We had this issue in the docs but could use fancy CSS there. In the case of GitHub I guess the only option is to add a white background to the logo?

**Comment by ZurMaD** [comment]
Not important but can be better

![image](https://user-images.githubusercontent.com/28235457/103101261-b0713000-45e4-11eb-9fd7-fc34734bfbcb.png)

**Comment by boyuan12** [comment]
Can I try to work on this issue?

**Comment by sethmlarson** [comment]
@boyuan12 You certainly can!

**Comment by chetanugale** [comment]
@boyuan12 @sethmlarson did we fix this issue or can I work on it?

**Comment by sethmlarson** [comment]
@chetanugale I believe this issue is available for you to work on :)

**Comment by chetanugale** [comment]
thanks @sethmlarson 👍
