### ISSUE TITLE
Better error message when connecting to HTTPS proxy results in non-certificate connection errors

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2105]
Many users attempting to connect to "HTTPS" proxies that receive errors like:

- RemoteDisconnected
- Connection reset by peer
- [SSL: WRONG_VERSION_NUMBER] wrong version number

we should somehow make it more obvious that the error is likely because their proxy wants to speak HTTP, not HTTPS.
Not sure by what exact method we can do this, potentially the `ProxyManager` can do something here?

References:
- https://github.com/pypa/pip/issues/9216

**Comment by pquentin** [comment]
Do we understand why https://github.com/urllib3/urllib3/issues/1850 did not catch this? (This issue now has four thumbs up, by the way.)

**Comment by sethmlarson** [comment]
@pquentin I think it's because Pip wasn't handling/enabling the new warning so wasn't visible to users.

**Comment by jalopezsilva** [comment]
The ``ssl`` APIs make it difficult to clearly send a a consistent error for these cases. The best we can do probably is catch errors when we are trying to establish the TLS session with the proxy, and raise another exception with a better error: https://github.com/urllib3/urllib3/blob/master/src/urllib3/connection.py#L329

I'll take a stab at that unless anyone has better suggestions.

**Comment by pradyunsg** [comment]
> @pquentin I think it's because Pip wasn't handling/enabling the new warning so wasn't visible to users.

Yea -- let me know if there's some way for pip to better expose urllib3's warnings to our end users.

**Comment by sethmlarson** [comment]
This has been solved in https://github.com/urllib3/urllib3/pull/2434

**Comment by pradyunsg** [comment]
Neato! Imma be annoying and ask: when's the release? 🙃

**Comment by sethmlarson** [comment]
@pradyunsg if no blockers are found then next week is the plan.
