### ISSUE TITLE
URL with single double quote returns a valid URL object (when it shouldn't)

### ISSUE THREAD

**Issue by andreamoro** [urllib3/urllib3#2116]
### Subject

URL with single double quote returns a valid URL object when it shouldn't as not compliant with the RFC 3986.

### Environment

Describe your environment.
At least, paste here the output of:

```python
import platform
import urllib3

print("OS", platform.platform())
print("Python", platform.python_version())
print("urllib3", urllib3.__version__)
```

OS macOS-10.16-x86_64-i386-64bit
Python 3.8.6
urllib3 1.26.2

### Steps to Reproduce

```
>>> from urllib3 import util
>>> util.parse_url('"')
Url(scheme=None, auth=None, host='"', port=None, path=None, query=None, fragment=None)
```

### Expected Behavior

URL object should not be created because the given input is not parseable into a valid URL object. Either return a False or None

### Actual Behavior

A URL whose host equale to single double quote is returned.

**Comment by minipuppy** [comment]
according to the regex defined here 
https://github.com/urllib3/urllib3/blob/main/src/urllib3/util/url.py#L15
and the parse code  here 
https://github.com/urllib3/urllib3/blob/main/src/urllib3/util/url.py#L386
the param `path` never change  
1. the str is not valid uri. Users should follow RFC 3986
2. Shall we add some validation code to raise Exception or `Url()`

**Comment by sethmlarson** [comment]
Our URL parser isn't set up to deal with this as it's not super handy as a strict URL validator. If you need that we suggest using the rfc3986 or checking the values returned from our parser directly.
