### ISSUE TITLE
Integrating continuous fuzzing by way of OSS-Fuzz

### ISSUE THREAD

**Issue by DavidKorczynski** [urllib3/urllib3#2138]
Hi,

I was thinking that it would be nice to set up continuous fuzzing of urllib3, by way of OSS-Fuzz. In this PR: https://github.com/google/oss-fuzz/pull/4997 I have done exactly that, namely created the necessary logic from an OSS-Fuzz perspective to integrate urllib3. This includes developing initial fuzzers as well as integrating into OSS-Fuzz.

Essentially, OSS-Fuzz is a free service run by Google that performs continuous fuzzing of important open source projects. The only expectation of integrating into OSS-Fuzz is that bugs will be fixed. This is not a "hard" requirement in that no one enforces this and the main point is if bugs are not fixed then it is a waste of resources to run the fuzzers, which we would like to avoid.

If you would like to integrate, could I please have an email(s) that will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats. Notice the emails affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

**Comment by sethmlarson** [comment]
@DavidKorczynski Thank you for opening this! We're very much interested in using OSS-Fuzz, you can add `sethmichaellarson@gmail.com` and `quentin.pradet@gmail.com` to the list being notified of bugs. Is there anything else we need to do? Feel free to close this issue when integration is complete :)

**Comment by sethmlarson** [comment]
Thanks @DavidKorczynski, closing this issue now that the mentioned PR has been merged. Let me know if there are more things to do here.

**Comment by DavidKorczynski** [comment]
Ah apologies for not updating here @sethmlarson - I completely lost track.

Nothing more needed for you to be done here. However, it would be nice to take the fuzzers from the OSS-Fuzz repository and merge them in here? We can also create a set up such that it becomes easy for you to develop new fuzzers, is that something you would like (am happy to do it if so)?

**Comment by sethmlarson** [comment]
@DavidKorczynski That sounds nice, thank you! Would we still be notified by email?

**Comment by DavidKorczynski** [comment]
They would still be run on Google's servers and you will still be notified by email. The only difference will be that the Dockerfile in the OSS-Fuzz repository (https://github.com/google/oss-fuzz/blob/master/projects/urllib3/Dockerfile) would no longer use the `fuzz_urlparse.py` from the OSS-Fuzz repository, but would instead used it from the upstream.

**Comment by DavidKorczynski** [comment]
i.e. the OSS-Fuzz setup (also shown in the Dockerfile linked above) grabs the github repo of urllib3 and builds the fuzzers based on the latest code. So we can put whatever fuzzers we want in here and OSS-Fuzz will run them.

**Comment by pquentin** [comment]
I'm happy to include the fuzzer in our tree, especially if we can run it locally, but is it expected that I did not receive a single email from OSS-Fuzz yet?

**Comment by pquentin** [comment]
I opened a pull request to fix the recent build failures: https://github.com/google/oss-fuzz/pull/7205
