### ISSUE TITLE
url encoding not working propperly when bracheds are part of the url

### ISSUE THREAD

**Issue by s3gm3ntationFault** [urllib3/urllib3#2146]
### Context

What are you trying to do?
When requesting an image to mapbox, one of the fields is the bounding box of the image, which expects a format like "[minlon, minlat, maxlon, maxlat]"
After encoding the url the brackets are % encoded, making the mapbox request to fail.

According to RFC3986 brackets "[" "]" are now inside the reserved block, so they should not be percent encoded right?

How do you expect to do it?
requests.get(url)

Is it something you currently cannot do?
Have a workaround, downgrading urllib3 to prior version

Is this related to an existing issue/problem?
I guess not, already checked the current issues to find something similar

### Alternatives
Downgrade urllib3 to version 1.25.3

Can you achieve the same result doing it in an alternative way?
Yes, downgrading urllib3 lib to version 1.25.3

Is the alternative considerable?
It is, but not desirable

## Sample Code
```
import requests

url = "https://api.mapbox.com/styles/v1/mapbox/light-v10/static/{}/600x600"
read_only_token = "pk.eyJ1Ijoiam1hcmltb24iLCJhIjoiY2tlMTZ5eXloNTlxazJ6cm84bjFrZ2l4cCJ9.PEzBnKFct38JPEswATygoA"
params = {"access_token": read_only_token}
bbox = "[0, 0, 10, 10]"
r = requests.get(url.format(bbox), params=params)
print(r.request.url)
print("status code:", r.status_code)
```

Output:
```
URL: https://api.mapbox.com/styles/v1/mapbox/light-v10/static/%5B0,%200,%2010,%2010%5D/600x600?access_token=pk.eyJ1Ijoiam1hcmltb24iLCJhIjoiY2tlMTZ5eXloNTlxazJ6cm84bjFrZ2l4cCJ9.PEzBnKFct38JPEswATygoA
status code: 422
msg: b'{"message":"Longitude, latitude, zoom, bearing and pitch must all be numbers."}'
```
Expected:
```
URL: https://api.mapbox.com/styles/v1/mapbox/light-v10/static/[0,%200,%2010,%2010]/600x600?access_token=pk.eyJ1Ijoiam1hcmltb24iLCJhIjoiY2tlMTZ5eXloNTlxazJ6cm84bjFrZ2l4cCJ9.PEzBnKFct38JPEswATygoA
status code: 200
msg: b'' # image bytes
```

**Comment by sethmlarson** [comment]
Your reading of RFC 3986 isn't correct, `[` and `]` are in gen-delims and thus should be percent encoded in the path and query:

See Appendix A:

```
gen-delims    = ":" / "/" / "?" / "#" / "[" / "]" / "@"

path           = (summarized as basically pchar and "/")
pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"  <-- Notice gen-delims is not here
```

Might be worth contacting someone at MapBox to let them know about this problem.

**Comment by pquentin** [comment]
It looks like this is a difference between RFC 3986 and WHATWG URL. Browsers follow WHATWG URL. I don't understand the spec, but it seems to allow brackets: https://github.com/whatwg/url/issues/411.

And indeed, curl does not encode brackets, with the caveat that [URL globbing](https://everything.curl.dev/cmdline/globbing) needs to be disabled in some cases.

**Comment by s3gm3ntationFault** [comment]
> Your reading of RFC 3986 isn't correct, `[` and `]` are in gen-delims and thus should be percent encoded in the path and query:
> 
> See Appendix A:
> 
> ```
> gen-delims    = ":" / "/" / "?" / "#" / "[" / "]" / "@"
> 
> path           = (summarized as basically pchar and "/")
> pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"  <-- Notice gen-delims is not here
> ```
> 
> Might be worth contacting someone at MapBox to let them know about this problem.

@sethmlarson thanks for the clarification, I'll get in touch with MapBox
