### ISSUE TITLE
Feature Request: Cache responses 

### ISSUE THREAD

**Issue by FredHappyface** [urllib3/urllib3#2166]
### Context

Cache responses from the github api for 1 hour. The idea is to match a url + post data, look this up in a local db and if the data does not exist then make the request

### Alternatives

Using requests and requests-cache though this will have additional performance overhead + require refactoring a codebase 

### Duplicate

No duplicates as far as I am aware

### Contribution

Not sure how I'd go about implementing such a feature but happy to help any way I can

Thanks :)

**Comment by sigmavirus24** [comment]
This library shouldn't implement it's own caching solution. Something like cachecontrol should be improved to allow for use with urllib3 (or urllib3 should be improved to make it easier to use cachecontrol with it)

**Comment by sethmlarson** [comment]
Closing based on above comment, thanks @sigmavirus24.
