### ISSUE TITLE
Poolmanager exception on pop()

### ISSUE THREAD

**Issue by richiemann** [urllib3/urllib3#2172]
We have encountered an error on http to https redirects where code in the poolmanager raises an exception. It apperas that the pop() function is used incorrectly. Removing the second argument solves the issue.

```  
File "/usr/local/lib/python3.7/dist-packages/urllib3/poolmanager.py", line 401, in urlopen
    kw["headers"].pop(header, None)
TypeError: pop() takes 2 positional arguments but 3 were given```

https://github.com/urllib3/urllib3/blob/6d799ce26a6a565c1921a930e1dbd41de1f45f62/src/urllib3/poolmanager.py#L378

**Comment by pquentin** [comment]
Can you share more information about how you're sending `headers`? This is what our bug report template is for. `headers` is expected to be a Mapping such as a dict, and `dict.pop` in that case accepts two parameters to avoid raising a `KeyError`. (Also, this line is covered by our extensive test suite.)

Are you sending a list instead?

**Comment by richiemann** [comment]
Hello @pquentin ,
Thanks for the quick reply. I was not offer the report template when opening the bug report. Apologies for that.
We are indeed sending a list.

All the best,

Ricardo
