### ISSUE TITLE
Documentation search is broken

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#2175]
### Steps to Reproduce

Search for something: https://urllib3.readthedocs.io/en/latest/search.html?q=test&check_keywords=yes&area=default

### Expected Behavior

Results

### Actual Behavior

No results!

cc @pradyunsg

**Comment by pradyunsg** [comment]
![Screenshot_20210310-061132_Brave](https://user-images.githubusercontent.com/3275593/110584686-83ee9e00-8167-11eb-8db8-3c544ec727df.jpg)

Seems OK to me?

**Comment by pradyunsg** [comment]
If you're able to reproduce this please share the console output! :)

**Comment by pquentin** [comment]
Embarrassingly, this was broken for days on Firefox macOs, and now I can't reproduce it :/

Sorry about the noise!

**Comment by pradyunsg** [comment]
The most recent release has a bug fix for this, so maybe that fixed it?

https://pradyunsg.me/furo/changelog/#beta28
