### ISSUE TITLE
Enable hostname_checks_common_name on Python versions that support it

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#2191]
We'll have to wait on the resolution of https://bugs.python.org/issue43522, and then based on that decide how we detect the feature:

 * use an hypothetical new flag?
 * 3.10?
 * 3.7.x, 3.8.x, 3.9.x and 3.10 since this fix will be backported?

We'll have to wait for https://github.com/python/cpython/pull/24899 to land and to be in the 3.10 we use in GitHub Actions, probably when 3.10.0a7 get released.

**Comment by pquentin** [comment]
We'll use version detection, https://docs.python.org/3.10/library/ssl.html#ssl.SSLContext.hostname_checks_common_name documents the version where this works.

Not sure for PyPI yet.

**Comment by pquentin** [comment]
PyPy does not support this at all: https://foss.heptapod.net/pypy/pypy/-/issues/3539. So we'll continue to use our own matching there.

**Comment by pquentin** [comment]
The problem with reporting bugs to PyPy is that they get fixed quickly :D. Thanks @mattip for this! The good news is that on PyPy checking for `ssl.HAS_NEVER_CHECK_COMMON_NAME` is going to be enough, we don't have to worry about https://bugs.python.org/issue43522.

**Comment by mattip** [comment]
(PyPy already had much of the fix for the issue in re-using CPython's stdlib v3.8.10, PyPy only needed to additionally expose the `_ssl.HAS_NEVER_CHECK_COMMON_NAME` attribute which I missed when updating the code for Python3.8)
