### ISSUE TITLE
Respect SSLContext.hostname_checks_common_name set manually by users

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2192]
If a user sets `SSLContext.hostname_checks_common_name` we should respect their request and check commonName. This provides a fallback we can point to in case users rely on commonName support.

**Comment by sethmlarson** [comment]
Adding `Breaking Changes` solely for being considered a blocker of v2.0

**Comment by tiran** [comment]
The issue is now fixed in OpenSSL and Python has a workaround for previous OpenSSL versions, https://bugs.python.org/issue43522.

You either need

* Python 3.8.9+
* Python 3.9.3+
* Python 3.10

or

* OpenSSL 1.1.1l
* OpenSSL 3.0.0-alpha15

As of today none of the versions are released yet.
