### ISSUE TITLE
Can we make InsecureRequestWarning an info instead of a warning?

### ISSUE THREAD

**Issue by rlewkowicz** [urllib3/urllib3#2196]
```
InsecureRequestWarning: Unverified HTTPS request is being made to host
```

Working on corporate networks there's always some sort of SSL interception and even if you get bundles working then you have to deal with containers and on and on. There's ALWAYS some sort of pain point with this library for me in this warning. This frustrating error floats up in EVERYTHING and there's varying degrees of success on disabling it. For example if you install the aws cli on mac via pkg, you can't disable it at all.

**Comment by sigmavirus24** [comment]
The warnings system doesn't have an `info` level. You're thinking of logging, which isn't how this happens.
