### ISSUE TITLE
Python 3.10 ssl module deprecations

### ISSUE THREAD

**Issue by tiran** [urllib3/urllib3#2200]
### Context

Heads up! I'm in the processing of cleaning up the ssl module. Python 3.10's ssl module will raise deprecation warnings for a lot of old cruft that has been deprecated since 3.6 and 3.7. For example  SSL 3.0 to TLS 1.1, ``OP_NO_SSL/TLS*``, and more old features are going away. You'll also need OpenSSL 1.1.1+ for testing.

* https://bugs.python.org/issue43669
* https://bugs.python.org/issue43880

### Alternatives

None

### Duplicate

No

### Contribution

Would you be willing to submit a PR?
Sorry, no time :)

**Comment by sethmlarson** [comment]
Thanks for the heads up, I'll create a PR for this :)

**Comment by AdamWill** [comment]
I'm still seeing two deprecations with Python 3.10 rc2 and urllib3 1.26.7:

    /usr/lib/python3.10/site-packages/urllib3/connection.py:542: DeprecationWarning: ssl.match_hostname() is deprecated
      match_hostname(cert, asserted_hostname)
    /usr/lib/python3.10/site-packages/urllib3/util/retry.py:38: DeprecationWarning: Using 'Retry.DEFAULT_METHOD_WHITELIST' is deprecated and will be removed in v2.0. Use 'Retry.DEFAULT_ALLOWED_METHODS' instead
      warnings.warn(
    /usr/lib/python3.10/site-packages/urllib3/connection.py:542: DeprecationWarning: ssl.match_hostname() is deprecated
      match_hostname(cert, asserted_hostname)
    /usr/lib/python3.10/site-packages/urllib3/connection.py:542: DeprecationWarning: ssl.match_hostname() is deprecated
      match_hostname(cert, asserted_hostname)

**Comment by AdamWill** [comment]
oh, the second one is probably a deprecation warning in the app I'm running, ignore that. But the `ssl.match_hostname()` one is in urllib3 itself.

**Comment by pquentin** [comment]
Right, only the `ssl.match_hostname` are our faults. Opened https://github.com/urllib3/urllib3/issues/2439 to fix it.
