### ISSUE TITLE
is_connection_dropped checks against None but uses False as default value for getattr

### ISSUE THREAD

**Issue by Oberon00** [urllib3/urllib3#2203]
I happened to read this line and the code looks fishy. I did not otherwise verify the potential bug.

See implementation of `is_connection_dropped(conn: socket.socket) -> bool`:

https://github.com/urllib3/urllib3/blob/287052a16a59bcaba5772387de36fa9a49eb8378/src/urllib3/util/connection.py#L19-L23

If there is no property `sock` on `conn`, then we will call `wait_for_read(False, timeout=0.0)`, which e.g. may end up putting the `False` into the iterable passed to `select`.

Since this seemed to never have caused problems, the `sock = getattr(conn, "sock", False)` can probably be replaced with just `sock = conn.sock`.

Alternatives would be to replace the default (last argument of `getattr`) of `False` with `None` or replace the `if sock is None` with `if not sock`.

**Comment by sethmlarson** [comment]
Great catch, luckily this doesn't effect any released version as 1.26.x series has the [proper handling of `conn` without `sock`](https://github.com/urllib3/urllib3/blob/1.26.x/src/urllib3/util/connection.py).

Would you be willing to submit a PR changing `False` to `None`?

**Comment by Oberon00** [comment]
Here you are: #2204.

**Comment by sigmavirus24** [comment]
Would it be useful to distinguish between `conn.sock is None` and `conn.sock` isn't an attribute present by having `False` versus having `None`? We could use `if not sock` then instead of `if sock is None` but would allow for future debugging if needed/desired

**Comment by Oberon00** [comment]
This is what the version linked by @sethmlarson on the 1.26.x branch does. I wonder why it was changed.
