### ISSUE TITLE
Stop disabling Nagle's algorithm explicitly

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#2207]
I played with https://mysteries.wizardzines.com/50ms-request.html today, which mentions that CPython disables Nagle's algorithm by default. I checked, and indeed, it's disabled in Python 3.6.0+: https://github.com/python/cpython/commit/9d8a3ad02acdd7800775b4e1e205bf7c8e47162f. (If you're interested in the arcane TCP details, read https://github.com/python-trio/trio/issues/1792.)

This means that in the `main` branch which support Python 3.6+ we can stop disabling Nagle's algorithm in urllib3 by:
 * setting `default_socket_options` to an empty list in https://github.com/urllib3/urllib3/blob/26e9f27692193f898e78f88ea8169558ced30d12/src/urllib3/connection.py#L112-L116 and updating the docstring above
 * ~~removing the test_nagle test~~

**Comment by sigmavirus24** [comment]
Do we have tests that will allow us to ensure it is the correct behaviour? I believe we've seen other things be "default" behaviour and something else we do disables that default quietly and without warning

**Comment by pquentin** [comment]
Yeah, we have `test_nagle` that I suggested removing. Let's keep it then

**Comment by franekmagiera** [comment]
I think this can't be done. `http.client.HTTPConnection` disables Nagle's algorithm in `connect()` method, which is overloaded by `urllib3.HTTPConnection` and calls `urllib3.util.connection.create_connection()`, where socket options are set. So setting the `default_socket_options` to an empty list will not set any options to the socket.

**Comment by pquentin** [comment]
@franekmagiera Thanks, you're right! I had overlooked this. Closing, then, sorry for the trouble
