### ISSUE TITLE
Make all type hint aliases private

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2221]
Types like `HTTPBody`, `PeerCertRetType`, etc should be private so users don't think they're supported features of our API.

**Comment by sethmlarson** [comment]
We should also be consistent ie `_TYPE_PEER_CERT` instead of `PeerCertType`.

**Comment by csurfer** [comment]
@SethMichaelLarson I can try working on this if no one else has picked it up already. Is there a comprehensive list of aliased types that I can index on? Also I am thinking of raising one alias change per commit. WDYT?

**Comment by sethmlarson** [comment]
@csurfer Happy to hear you're interested! Unfortunately there isn't a defined list, you'd have to take a peek into all the files under `src/urllib3` and see what you find. They should all be in the global scope so easy to spot.

Everything would be squashed to one commit so I'm fine with it all be submitted as one big commit.

**Comment by csurfer** [comment]
@sethmlarson Have raised https://github.com/urllib3/urllib3/pull/2286 for the same.
