### ISSUE TITLE
TestRetry::test_respect_retry_after_header_sleep tests failing on fedora rawhide

### ISSUE THREAD

**Issue by nirik** [urllib3/urllib3#2225]
### Subject

TestRetry::test_respect_retry_after_header_sleep tests are failing in 1.26.x when building on fedora rawhide

### Environment

Fedora rawhide. python3-3.9.5

### Steps to Reproduce

time mock -r fedora-35-x86_64 python-urllib3-1.26.4-1.fc35.src.rpm

### Expected Behavior

No test failures.

### Actual Behavior

=========================== short test summary info ============================
FAILED test_retry.py::TestRetry::test_respect_retry_after_header_sleep[UTC-Mon, 3 Jun 2019 12:00:00 UTC-True-3600]
FAILED test_retry.py::TestRetry::test_respect_retry_after_header_sleep[UTC-Mon, 03 Jun 2019 11:30:12 GMT-True-1812]
FAILED test_retry.py::TestRetry::test_respect_retry_after_header_sleep[UTC-Monday, 03-Jun-19 11:30:12 GMT-True-1812]
FAILED test_retry.py::TestRetry::test_respect_retry_after_header_sleep[UTC-Mon Jun  3 11:30:12 2019-True-1812]
FAILED test_retry.py::TestRetry::test_respect_retry_after_header_sleep[Asia/Jerusalem-Mon, 3 Jun 2019 12:00:00 UTC-True-3600]
FAILED test_retry.py::TestRetry::test_respect_retry_after_header_sleep[Asia/Jerusalem-Mon, 03 Jun 2019 11:30:12 GMT-True-1812]
FAILED test_retry.py::TestRetry::test_respect_retry_after_header_sleep[Asia/Jerusalem-Monday, 03-Jun-19 11:30:12 GMT-True-1812]
FAILED test_retry.py::TestRetry::test_respect_retry_after_header_sleep[Asia/Jerusalem-Mon Jun  3 11:30:12 2019-True-1812]
FAILED test_retry.py::TestRetry::test_respect_retry_after_header_sleep[None-Mon, 3 Jun 2019 12:00:00 UTC-True-3600]
FAILED test_retry.py::TestRetry::test_respect_retry_after_header_sleep[None-Mon, 03 Jun 2019 11:30:12 GMT-True-1812]
FAILED test_retry.py::TestRetry::test_respect_retry_after_header_sleep[None-Monday, 03-Jun-19 11:30:12 GMT-True-1812]
FAILED test_retry.py::TestRetry::test_respect_retry_after_header_sleep[None-Mon Jun  3 11:30:12 2019-True-1812]
FAILED test_retry_deprecated.py::TestRetry::test_respect_retry_after_header_sleep[UTC-Mon, 3 Jun 2019 12:00:00 UTC-True-3600]
FAILED test_retry_deprecated.py::TestRetry::test_respect_retry_after_header_sleep[UTC-Mon, 03 Jun 2019 11:30:12 GMT-True-1812]
FAILED test_retry_deprecated.py::TestRetry::test_respect_retry_after_header_sleep[UTC-Monday, 03-Jun-19 11:30:12 GMT-True-1812]
FAILED test_retry_deprecated.py::TestRetry::test_respect_retry_after_header_sleep[UTC-Mon Jun  3 11:30:12 2019-True-1812]
FAILED test_retry_deprecated.py::TestRetry::test_respect_retry_after_header_sleep[Asia/Jerusalem-Mon, 3 Jun 2019 12:00:00 UTC-True-3600]
FAILED test_retry_deprecated.py::TestRetry::test_respect_retry_after_header_sleep[Asia/Jerusalem-Mon, 03 Jun 2019 11:30:12 GMT-True-1812]
FAILED test_retry_deprecated.py::TestRetry::test_respect_retry_after_header_sleep[Asia/Jerusalem-Monday, 03-Jun-19 11:30:12 GMT-True-1812]
FAILED test_retry_deprecated.py::TestRetry::test_respect_retry_after_header_sleep[Asia/Jerusalem-Mon Jun  3 11:30:12 2019-True-1812]
FAILED test_retry_deprecated.py::TestRetry::test_respect_retry_after_header_sleep[None-Mon, 3 Jun 2019 12:00:00 UTC-True-3600]
FAILED test_retry_deprecated.py::TestRetry::test_respect_retry_after_header_sleep[None-Mon, 03 Jun 2019 11:30:12 GMT-True-1812]
FAILED test_retry_deprecated.py::TestRetry::test_respect_retry_after_header_sleep[None-Monday, 03-Jun-19 11:30:12 GMT-True-1812]
FAILED test_retry_deprecated.py::TestRetry::test_respect_retry_after_header_sleep[None-Mon Jun  3 11:30:12 2019-True-1812]
=========== 24 failed, 676 passed, 8 skipped, 16 warnings in 30.61s ============

(attaching full build.log) 
[build.log](https://github.com/urllib3/urllib3/files/6497355/build.log)

**Comment by sethmlarson** [comment]
You're going to have to do more investigation than this because as you can see our [test suite is passing right now](https://github.com/urllib3/urllib3/actions/runs/850802511).

Remember, we're volunteers just like you. In the future please respect our time and document what you've tried already, what you think might be happening, and reach out on another channel instead of opening an issue with a log file attached expecting us to fix a problem that clearly only exists on your machine.

Since this continues to happen I think our policy from now on is going to include deleting zero-effort issues like these from repackagers.

**Comment by sethmlarson** [comment]
I'm going to unlock this thread so you can provide more context since I did say "from now on".
