### ISSUE TITLE
Drop support for SSLv2 and SSLv3 in SecureTransport and PyOpenSSL

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2233]
Python has deprecated the `PROTOCOL_SSLv2` and `PROTOCOL_SSLv3` constants since Python 3.6 and the protocols aren't available in modern OpenSSL. We should not support setting these on our third-party SSLContext implementations.

For completion the following is required:
- It should not be possible to enable SSLv2 or SSLv3 in pyOpenSSL (`contrib/pyopenssl`) or SecureTransport (`contrib/securetransport`, `contrib/_securetransport`)
- Add test cases attempting to set SSLv2 and SSLv3 and ensure that the configuration isn't valid. Should test setting via `ssl_version`, `ssl_minimum_version`, and `ssl_maximum_version`.
  - Because the values mentioned above will be removed in future Python versions we should store their old values within the test suite.

**Comment by tiran** [comment]
I recommend to drop TLS 1.0 and 1.1 as well. Python 3.10 no longer claims that TLS 1.0 and 1.1 work. Most vendors and Linux distros have disabled TLS 1.0 and 1.1 as well. On some distros it is possible to detect this and re-enable TLS 1.0 and 1.1 with ``ctx.minimum_version = ssl.TLSVersion.TLSv1``. On other distros it's more complicated / not possible.

Ubuntu's OpenSSL patches make this rather ... awkward.

* https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1899878
* https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1917625

**Comment by sethmlarson** [comment]
@tiran Thanks, this is good info. What we're planning now is to make TLS 1.2+ the default as we've been issuing deprecation warnings about default TLS configs returning anything below TLS 1.2 in v1.26. If Python/OpenSSL drops support its all good, this issue is more about making it impossible to use SSLv2 and 3.

**Comment by KOLANICH** [comment]
TLS 1.1 and 1.2 are not broken yet.

**Comment by tiran** [comment]
TLS 1.1 has known weaknesses, e.g. it depends on SHA-1 during handshake. See RFC 8996.

**Comment by KOLANICH** [comment]
Thanks for the info.

**Comment by justlund** [comment]
I will take a look at this issue!
