### ISSUE TITLE
Map all keyword arguments to the top level `request` wrapper.

### ISSUE THREAD

**Issue by ubdussamad** [urllib3/urllib3#2235]
Right now, only a small number of keyword arguments are supported in the top-level wrapper `urllib3.request` function.
It wraps the `poolManager.request()` function by creating a default `poolManager` instance.
It was added to make the interface even simpler for users.

Currently supported kwArgs are: `body=None, fields=None, headers=None`.

The ones which are **not** supported: `preload_content, timeout, retries, redirect` and maybe some more which I might've missed.

This reduces the quality of the wrapper function as the user might not know what else they could do with this method and also makes adding type hints harder which is something we don't want in v2.

The wrapper method resides in the file [__init.py__.](https://github.com/urllib3/urllib3/blob/main/src/urllib3/__init__.py)

The original `request` method from the `poolManager` instance catches these kwArgs through **kwArgs.

If you need to look at an example of adding one, @venthur recently added the body parameter to the request function. (#2226)

**Comment by ubdussamad** [comment]
@sethmlarson Should it be labeled contributor friendly? It'll attract more people.

**Comment by csurfer** [comment]
@ubdussamad Looks like your recent PR takes care of all the requisites. Is something left to be done for this issue?

**Comment by sethmlarson** [comment]
I think there are still more to work on here, might take a bit of discovery! One I can think of is `chunked`, I'm sure there are plenty more.

**Comment by ubdussamad** [comment]
Hi @csurfer , yes there are a couple more, some of them are mentioned in my PR, for others you might have to a bit of digging.

**Comment by sethmlarson** [comment]
I'm going to mark this as closed, I don't think there are any other parameters to be forwarded. Thanks everyone!
