### ISSUE TITLE
Document HTTPResponse cleanup scenarios

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2236]
Document the following methods within the Advanced Usage page when using `preload_content=False`

- `HTTPResponse.close()` (Closes the connection, doesn't return it to the pool, throws away data still on wire)
- `HTTPResponse.drain_conn()` (Throws away data still on wire, call before release_conn if there is unread data)
- `HTTPResponse.release_conn()` (Releases the connection back into the pool, should only be called if all data is read)

Also document that when using `preload_content=True` (the default setting) that the ConnectionPool will release the connection for you.

**Comment by harshakhmk** [comment]
I would like to work on this issue

**Comment by sethmlarson** [comment]
@harshakhmk Sounds good, let us know if you need help or have questions.

**Comment by harshakhmk** [comment]
Should I add document the same in ```advanced-usage.rst ```? Do I need to add any code snippets?

**Comment by sethmlarson** [comment]
Yep that file is good, and should include short code examples.

**Comment by sethmlarson** [comment]
@Pradhvan You definitely can!

**Comment by furkanonder** [comment]
[PR](https://github.com/urllib3/urllib3/pull/2659) is ready to review.
