### ISSUE TITLE
Request ignores KeyboardInterrupt

### ISSUE THREAD

**Issue by mrx23dot** [urllib3/urllib3#2237]
### Subject

Request ignores CTRL+C KeyboardInterrupt when it does it's timeout.

### Environment

```
OS Windows-10-10.0.18362-SP0
Python 3.6.5
urllib3 1.26.3
```
!Doesn't happen on linux.

### Steps to Reproduce
```
from http.client import HTTPConnection
conn = HTTPConnection('192.1.5.2', 80, timeout=50)
conn.request('GET', '/')
conn.getresponse()
```

### Expected Behavior

It should give up waiting when requested and exit immediately.

### Actual Behavior

What happens instead.
Keeps doing it's timeout until elapse then exits.

**Comment by sethmlarson** [comment]
Pulling a direct quote from Nate in the previous issue:

> You can reproduce the same issue without Requests or Urllib3 with the code below.

The issue is in `socket.connect`, not in urllib3. You can try opening an issue on the Python issue tracker.
