### ISSUE TITLE
No released version supporting Python 3.10

### ISSUE THREAD

**Issue by ctheune** [urllib3/urllib3#2238]
### Context

What are you trying to do?

I'm trying to start porting my code to Python 3.10. One of the issues is that some `pkg_resources` stuff has changed and there's been an update of six.

I saw that the currently unreleased `master` branch has removed the dependency on six. However, there have been maintenance releases of the 1.26 branch in between and I wonder whether it would be possible to get a 1.26.5 that pulls in an updated version of the vendored `six`?

### Alternatives

I can imagine that you might want to release master soon, but I'm not involved enough to know what the expectation would be here.

### Duplicate

Could not find one.

### Contribution

Sure, I'd be happy to create a PR with an updated vendored version.

**Comment by sethmlarson** [comment]
We're not planning on releasing `main` soon, there's still a good amount of work to do for v2.0. Python 3.10 support will be coming to v1.26.5 with an updated version of six.

**Comment by ctheune** [comment]
Great, thanks! Do you need help with that?

**Comment by sethmlarson** [comment]
@ctheune Question, where are you seeing breakage with regards to urllib3's vendored `six` package? I ran our test suite on Python 3.10 and it's passing except for the additional TLS deprecation warnings we've already identified in https://github.com/urllib3/urllib3/pull/2209.

**Comment by ctheune** [comment]
Here's the issue that I see:
https://github.com/flyingcircusio/batou/runs/2638868539?check_suite_focus=true#step:6:245

**Comment by tirkarthi** [comment]
Six related issue was fixed in https://github.com/benjaminp/six/pull/352

**Comment by sethmlarson** [comment]
Closed in #2239, will release likely early next week.
