### ISSUE TITLE
Proposal: Improve support for JSON

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2243]
Many APIs are simply JSON bodies over HTTP, it'd be nice if we could make that experience more enjoyable for most users.

On the request side:

- Raise a `ValueError` if `body` is given or if `fields` is given when within `request_encode_body`
- Set `Content-Type: application/json` via `headers.setdefault()` to avoid stepping on custom Content-Types.
- Encode the JSON to bytes and set as the `body` parameter, remove spaces after delimiters.
- Add `json` to `urllib3.request()`

On the response side:

- Add a function `json()` to `HTTPResponse`
- `HTTPResponse.json()` should parse the JSON via `json.loads(resp.data)` and return the parsed object.

On the documentation side:

- In the JSON section, recommend using `json=` instead of encoding your own JSON to bytes if you're not doing anything special
- Document how to use a custom JSON library/encoder like orjson by encoding to bytes and sending via `body=`
  and to pull `resp.data` for decoding JSON responses

**Comment by pquentin** [comment]
This looks great! I have two thoughts.

I don't think we should expose an `encoding` parameter: since Python 3.6, `json.loads` supports all standard JSON encodings automatically. If you're handling JSON that is not UTF-8, UTF-16 or UTF-32, then you're on your own.

Regarding alternative JSON packages, I think the cool kid is orjson, especially for encoding to bytes: https://pythonspeed.com/articles/faster-json-library/

**Comment by sethmlarson** [comment]
@pquentin Oh nice, today I learned! Begone, `encoding`! And sounds good, we'll use `orjson` as an example.

**Comment by justlund** [comment]
Hi, I'd like to work on this issue!

**Comment by sethmlarson** [comment]
@justlund Sounds good, let me know if you have questions :)

**Comment by V1NAY8** [comment]
@sethmlarson  I'll try to work this as well. I am understanding the repository. I am ok if this gets implemented before I do

Can you give me an example like, what would it look like a sample request and response and calling of this method or a use case ?

So, I can understand where to implement it.

**Comment by sethmlarson** [comment]
Answering questions raised by @V1NAY8 on Discord:

> 1. We should add a new parameter that says json= to all request methods ?

Yeah, all `request*` methods in `RequestMethods` like `request`, `request_encode_url`, and `request_encode_body` along with the top-level `urllib3.request` function should handle `json=` but the parameter should not be anywhere else.

> 2. And that json should consist of all the header, body , fields as keys. (if we get any extra throw exception)
> if we don't get header we do headers.setdefault()
> if they don't give fields its fine for all methods,  except for request_encode_body 
> if they don't give body its fine

If the `json=` parameter is specified there should be errors in the follow scenarios:
- `body` is non-None
- `fields` is non-None within `request_encode_body`

3. (header,body, fields) and json are mutually exclusive ?
if they give any one the left and json , then throw exception.

Does the above answer cover this or am I missing something extra? `headers` shouldn't trigger an error.

> 4. Also for this point "Encode the JSON to bytes and set as the body parameter, remove spaces after delimiters."
> https://urllib3.readthedocs.io/en/latest/user-guide.html#json
> As seen in this example
> JSON is already encoded and passed to body parameter, 
> to make it more user friendly, 
> We internally do the encoding using orgjson to utf-8 ? 

Yes we're going to be doing the encoding ourselves and passing via `body=` to `urlopen`

**Comment by sethmlarson** [comment]
Mentioning @V1NAY8 to see if I can assign them to this issue :)

**Comment by V1NAY8** [comment]
Yeah, I will do this :)
