### ISSUE TITLE
Investigate removing `object` from the `Union[...]` of many `timeout` types

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2252]
`object` is only there because of the `socket` module "default" sentinel value which is kind-of an unfortunate hack if you ask me.

It's causing a lot of problems type-wise when going from urllib3 timeout to http.client timeouts, let's take a peek if we can instead remove `object` and add `type: ignore` only where the socket default timeout sentinel is used.

**Comment by pquentin** [comment]
Related discussion: https://github.com/encode/httpx/issues/1384

**Comment by hramezani** [comment]
I've tested it on my own setup. by removing `object`, we will have to add 9 `type: ignore` and 9 `type: ignore` will be removed.
I can create a PR if you agree
