### ISSUE TITLE
Tolerate the strict parameter being passed via connection_from_context()

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2263]
If we test Requests against urllib3 `main` branch we receive the following:

```
  File "/home/sethmlarson/urllib3/src/urllib3/poolmanager.py", line 354, in connection_from_url
    return self.connection_from_host(
  File "/home/sethmlarson/urllib3/src/urllib3/poolmanager.py", line 294, in connection_from_host
    return self.connection_from_context(request_context)
  File "/home/sethmlarson/urllib3/src/urllib3/poolmanager.py", line 310, in connection_from_context
    pool_key = pool_key_constructor(request_context)
  File "/home/sethmlarson/urllib3/src/urllib3/poolmanager.py", line 143, in _default_key_normalizer
    return key_class(**context)
TypeError: __new__() got an unexpected keyword argument 'key_strict'
```

This started in https://github.com/urllib3/urllib3/pull/2064. One of the goals of v2 is to be mostly API compatible so downstream projects can immediately start using v2. Should we add the following within `PoolManager.connection_from_context`?

```python
        if "strict" in request_context:
            import warnings

            warnings.warn(
                "The 'strict' parameter is no longer needed on Python 3+. "
                "This will raise an error in urllib3 v3.0.0.",
                DeprecationWarning
            )
            request_context.pop("strict")
```

to maintain API compatibility with Requests and other libraries that support Python 2?

Another small thought is to add a simple integration test with `requests.get(...)` to our test suite so we can track that we don't lose complete API compatibility.

**Comment by hramezani** [comment]
> Should we add the following within PoolManager.connection_from_context?

Yes, if we are going to be mostly compatible.

> Another small thought is to add a simple integration test with requests.get(...) to our test suite so we can track that we don't lose complete API compatibility.

Good point :+1: 

I can work on this.
