### ISSUE TITLE
Change all Readthedocs URLs in 1.26.x branch to reference 1.26.x documentation

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2281]
Many URLs in the urllib3 1.26.x release stream reference `/en/latest` in their documentation URLs. However `latest` is actually the documentation for v2.0 development. There is a chance that the documentation isn't relevant anymore or that additional features have been added that aren't released.

To avoid confusing users, let's change all the URLs that look like this: `https://urllib3.readthedocs.io/en/latest/...` to this: `https://urllib3.readthedocs.io/en/1.26.x/...`.

This change should be done in the `1.26.x` branch.

**Comment by DmytroLitvinov** [comment]
Hi @sethmlarson ,
Could you please paste at least 1 URL with reference in 1.26.x branch at service readthedocs to `/en/lastest/`?

**Comment by sethmlarson** [comment]
@DmytroLitvinov Sure! An example is in `src/urllib3/util/ssl_.py` there's a link to `https://urllib3.readthedocs.io/en/latest/advanced-usage.html` in a docstring.

The change on `1.26.x` branch the link should be `https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html`

**Comment by pquentin** [comment]
Done in #2298, closing
