### ISSUE TITLE
Deprecate NTLMConnectionPool in 1.26.x

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2282]
As was mentioned in https://github.com/urllib3/urllib3/pull/2278#issuecomment-864414599 and https://github.com/urllib3/urllib3/pull/2278#issuecomment-864450016 we're moving to remove `NTLMConnectionPool` and the `urllib3.contrib.nltmpool` module from urllib3 in v2.0 if we don't find a new maintainer for the module (perhaps as a third-party package ie `urllib3-ntlmpool`?)

- The module is not covered by our test suite.
- It is not clear even which pypi package is needed for it.
- It has fallen into disrepair (e.g. timeout/ssl/other options not being respected).
- According to Wikipedia, "Since 2010, Microsoft no longer recommends NTLM in applications"
- Seems like it's not used often, if at all.

In the `1.26.x` branch we should unconditionally raise a `DeprecationWarning` when the module is imported. Should link to this issue with a call to action to comment in the issue if they are a user. This should help us better discover who (if any) our users are here so we can better make a decision.

**Comment by imkaka** [comment]
I will try to work on this.

**Comment by sethmlarson** [comment]
Sounds good @imkaka, let me know if you have questions.

**Comment by sethmlarson** [comment]
Closed via https://github.com/urllib3/urllib3/pull/2289

**Comment by notatallshaw** [comment]
FYI I do work use Python with sites that use ntlm authentication. But historically I've used, and the only library other ntlm users have recommended, https://github.com/requests/requests-ntlm which is also no longer maintained and stopped working from urlib3 1.25.4 onwards anyway.

So as someone who still occasionally uses ntlm for legacy sites I wasn't even aware urllib3 had a corresponding module.
