### ISSUE TITLE
Make top-level request() function parameters keyword-only

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2283]
- Make all parameters after `method` and `url` for `urllib3.request()` keyword only by adding `*,` (see [PEP-3102](https://www.python.org/dev/peps/pep-3102/))
- Add a test case for the error that's raised when a parameter isn't used as a keyword

**Comment by aitoehigie** [comment]
I think I can handle this.

**Comment by fvlima** [comment]
I was doing this, but I had doubts about the best place to put the test case

**Comment by aitoehigie** [comment]
> I was doing this, but I had doubts about the best place to put the test case

There is a test directory. I believe you will need to create a test_request.py file in it. Going by the convention in that directory

**Comment by fvlima** [comment]
> There is a test directory. I believe you will need to create a test_request.py file in it. Going by the convention in that directory

yep, but I thought that would be strange to have just one test case in this `test_request.py`. It was exactly what I was doing...

**Comment by fvlima** [comment]
I'm pushing the PR and we can discuss there

**Comment by fvlima** [comment]
https://github.com/urllib3/urllib3/pull/2284
