### ISSUE TITLE
Transfer-Encoding: chunked header can be sent twice if specified in headers w/ chunked=True

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2287]
https://github.com/urllib3/urllib3/blob/1.26.x/src/urllib3/connection.py#L252 should be checking `header_keys` not `headers`.

Reproducer (notice the casing of `transfer-Encoding`):

```python
http.request("POST", "http://hhtpbin.org/anything", body=b"hello, world", chunked=True, headers={"transfer-Encoding": "chunked"})
```

If you check Wireshark there are two `Transfer-Encoding` headers sent:

```
    POST /anything HTTP/1.1\r\n
    Host: httpbin.org\r\n
    Accept-Encoding: identity\r\n
    User-Agent: python-urllib3/2.0.0.dev0\r\n
    transfer-Encoding: chunked\r\n
    Transfer-Encoding: chunked\r\n
    \r\n
```

should be:

```
    POST /anything HTTP/1.1\r\n
    Host: httpbin.org\r\n
    Accept-Encoding: identity\r\n
    User-Agent: python-urllib3/2.0.0.dev0\r\n
    transfer-Encoding: chunked\r\n
    \r\n
```

This issue effects v2.0 and v1.26.x

**Comment by csurfer** [comment]
IMO tests of form `test_preserve_user_agent()` and `test_preserve_transfer_encoding()` are missing from `test_chunked_transfer.py` which would have otherwise caught the above issue. If you think this approach is ok, I can fix the issue and add the two tests I have mentioned earlier.

**Comment by sethmlarson** [comment]
@csurfer That sounds good to me, thanks! You can make the fix on `main` and we'll backport the commit to `1.26.x`.
