### ISSUE TITLE
Add support for a minimum time between retries on the Retry utility

### ISSUE THREAD

**Issue by GlenTiki** [urllib3/urllib3#2308]
### Context

> What are you trying to do?

I manage an integration with a brittle platform that I need to do some work on, on my side of the integration. The owners of this platform have requested that I only issue at most one request every 3 seconds to their API. I would like to configure my Retry class to have a minimum time between retries to respect this.

> How do you expect to do it?

I would like to be able to configure a property (possibly `BACKOFF_MIN`?) on the Retry class like the existing `BACKOFF_MAX` property to ensure that the retry sleeps for a minimum amount of time. I'm happy to respect `Retry-After` and the exponential backoff component when it is above this proposed `BACKOFF_MIN`.

> Is it something you currently cannot do?

Yes, I can't manage this with the existing Retry class and would need to roll my own logic for it.

> Is this related to an existing issue/problem?

No

### Alternatives

Can you achieve the same result doing it in an alternative way?
Yeah, I can manage retries manually, myself

Is the alternative considerable?
Yes, but it's manual work outside the scope of this library that I think would add to it.

### Duplicate

> Has the feature been requested before? If so, please provide a link to the issue.

I couldn't find a link

### Contribution

> Would you be willing to submit a PR?
_(Help can be provided if you need assistance submitting a PR)_

Yes. I would be happy to add support for this, but I would like to understand what the maintainers view as acceptable behaviour with this before opening a related PR.

**Comment by sethmlarson** [comment]
Have you considered sub-classing `Retry` to return a minimum of `0.333` seconds of backoff time?

```python
from urllib3.util import Retry

class RetryMax3PerSecond(Retry):
    def get_backoff_time():
        return max(super().get_backoff_time(), 0.333)
```

Then you can pass that object in via `retries=...`

**Comment by GlenTiki** [comment]
Ah, that's a good solution I hadn't thought of! I'll make use of that now. Feel free to close if you don't think it's needed in the library. Otherwise, I'm still happy to contribute this.

**Comment by sethmlarson** [comment]
I think given these unique requirements it's likely not necessary, going to close this. Glad we could solve the problem.
