### ISSUE TITLE
[v2] Chaining exceptions

### ISSUE THREAD

**Issue by bluetech** [urllib3/urllib3#2313]
### Context

Currently urllib3 doesn't chain exceptions explicitly when wrapping exceptions (this feature wasn't available in Python 2 AFAIK). For example:

https://github.com/urllib3/urllib3/blob/1831327b881880ed871f96f56a6977d360042e1b/src/urllib3/response.py#L539-L557

If the `SocketTimeout` happens, then it renders as

```
... SocketTimeout stacktrace ...

During handling of the above exception, another exception occurred:

... ReadTimeoutError stacktrace ...
```

Explicit chaining would be

```py
 except SocketTimeout as e:
     raise ReadTimeoutError(self._pool, None, "Read timed out.") from e
```

then the error is the nicer

```
... SocketTimeout stacktrace ...

The above exception was the direct cause of the following exception:

... ReadTimeoutError stacktrace ...
```

Alternatively, if we don't want to expose the cause exception, can do

```py
 except SocketTimeout:
     raise ReadTimeoutError(self._pool, None, "Read timed out.") from None
```

then only the `ReadTimeoutError` is shown.

IMO, the first case looks like a bug to the user, and, if this issue is resolved, would indicate an unexpected exception in urllib3.
So I suggest going over all cases of exception wrapping in urllib3 and changing them to either explicitly chain or suppress the wrapped exception.

There's is a question whether an exception's `__cause__` could be considered part of the API promise. IMO, there is no such expectation and we shouldn't guarantee this. But if we do, then we'd want to be a lot more picky with chaining vs. suppressing.

### Contribution

> Would you be willing to submit a PR?

Yes.

**Comment by sethmlarson** [comment]
Thanks for opening this! Let's move towards the explicit chaining if only for the better message. This work will also expose places where maybe we do want the `from None`.
