### ISSUE TITLE
Document how to use custom SSLContext objects

### ISSUE THREAD

**Issue by pradyumna212** [urllib3/urllib3#2320]
### Context

What are you trying to do?
Provide an example of how to configure urllib3 to enable Partial Certificate chain validation.

How do you expect to do it? Document update with an example or Provided as a standard option/flag in Poolmanager.

Is it something you currently cannot do? Right

Is this related to an existing issue/problem? Yes. There is no option to configure enabling of partial chain validation.

### Alternatives

Can you achieve the same result doing it in an alternative way?
Is the alternative considerable?

### Duplicate

Has the feature been requested before? No idea.
If so, please provide a link to the issue.

### Contribution

Would you be willing to submit a PR? Unplanned.
_(Help can be provided if you need assistance submitting a PR)_

**Comment by sethmlarson** [comment]
How would this be implemented via `SSLContext`? If it can be implemented this way then urllib3 can do it, otherwise it's likely not going to be possible. Either way I'm not sure this information should live here, perhaps a blog post / Gist / StackOverflow question?

**Comment by sethmlarson** [comment]
Quentin highlighted to me that we don't document the `ssl_context` parameter or how you can configure a custom `SSLContext` so perhaps we can document those scenarios and that'd be sufficient for the urllib3 documentation?
