### ISSUE TITLE
Add decode_content parameter to top-level APIs

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2325]
Like the title says, add `decode_content` to the top-level APIs `urllib3.request()`.

See https://github.com/urllib3/urllib3/commit/ddf7361ac0467431a2f3df6ba346c9c506c29d56 for an example.

**Comment by V1NAY8** [comment]
I'm on it

**Comment by V1NAY8** [comment]
I will work on this. What is the functionality of this parameter ?

**Comment by sethmlarson** [comment]
The functionality is already implemented, only needs to be forwarded to the lower levels.

**Comment by imkaka** [comment]
@V1NAY8 please let me know if you are working on this, else I will love to work on this.

**Comment by V1NAY8** [comment]
@imkaka go ahead and implement it. I'll pick something else.

**Comment by imkaka** [comment]
Cool @V1NAY8, will start on this.
