### ISSUE TITLE
Clearer formatting of warning 

### ISSUE THREAD

**Issue by ninoCan** [urllib3/urllib3#2334]
https://github.com/urllib3/urllib3/blob/21945b84b0707a3143b09ade5c59e8dbf6a69a0f/src/urllib3/connectionpool.py#L781

The variables _retries_ and _err_ are returned as raw objects in the message. This makes this warning rather esoteric for the developer who is not familiar with which class these objects belong to.

If _err_ is an actual error, it would be nice to see the stack trace in a more pythonic form.

**Comment by sethmlarson** [comment]
At that level stack traces are huge and very difficult to read. If you're trying to implement your own logging perhaps disabling retries and handling them yourself within your application is the way forward?
