### ISSUE TITLE
parse_url coerces upper-case letter to lower case in host name

### ISSUE THREAD

**Issue by dmitrypolo** [urllib3/urllib3#2337]
### Subject

`parse_url` coerces a host to lower case if there is an uppercase letter after a `-`

### Environment

OS macOS-10.14.6-x86_64-i386-64bit
Python 3.9.1
urllib3 1.26.3

```python
import platform
import urllib3

print("OS", platform.platform())
print("Python", platform.python_version())
print("urllib3", urllib3.__version__)
```

### Steps to Reproduce
```python
from urllib3.util import parse_url
url = "http://service-A/foo"
parse_url(url).host

"service-a"
```

### Expected Behavior

`host` should remain as `service-A`

### Actual Behavior

`host` ends up being `service-a`

**Comment by sigmavirus24** [comment]
As stated on psf/requests#5886, this is both allowed by RFC 3986 and every subsequent update to how URIs should be handled (and easily found with quick google searches) and encouraged as normalization of a URI is important. If you're relying on case-sensitivity, then you have a problem in how you're configuring your environment. All hosts are to be treated without case sensitivity.
