### ISSUE TITLE
Possible bug in securetransport _cert_array_from_pem() error handling

### ISSUE THREAD

**Issue by bluetech** [urllib3/urllib3#2338]
While working on an unrelated change, I noticed this line, which *seems* to miss a `raise` after the free in the `except` block. I may be wrong; I didn't try at all to understand what the code does, it just looks wrong to me so thought I'd report it.

https://github.com/urllib3/urllib3/blob/21945b84b0707a3143b09ade5c59e8dbf6a69a0f/src/urllib3/contrib/_securetransport/low_level.py#L186-L206

**Comment by sigmavirus24** [comment]
Ahh, I think we're missing `raise` in there to re-reaise the exception raised in the `try`-block. Good catch

**Comment by bluetech** [comment]
OK, I'll send a PR.
