### ISSUE TITLE
ci: putting a time limit on jobs

### ISSUE THREAD

**Issue by bluetech** [urllib3/urllib3#2341]
Some CI runs got stuck and only failed after 6 hours, example: https://github.com/urllib3/urllib3/actions/runs/1064318368

Even though it's free it's seems like a big waste, so I propose we set a time limit on all jobs. I think 10 minutes is reasonable (from a glance it seems most jobs take 1m-2m). The `timeout-minutes: ...` directive does this.

**Comment by sethmlarson** [comment]
Sounds good to me!
