### ISSUE TITLE
Type check tests?

### ISSUE THREAD

**Issue by bluetech** [urllib3/urllib3#2344]
Currently the tests are not typed and not type checked. In my experience, doing so is useful, foremost as a way for testing the typing of the main code itself. But others think it adds too much friction when writing tests.

I propose we do it, as a way to gain some confidence in our own typing. There are two ways to go about it:

1. Do a sweep and add `-> None` to all test functions, and possibly fixture arguments etc.
2. Use mypy `check_untyped_defs = True` for the tests. This means mypy will type check even when the test is not annotated.

I personally prefer 2 because I prefer to be strict and explicit, but don't mind either way.

**Comment by sethmlarson** [comment]
This sounds like a good idea, maybe we can adopt a similar construction for incrementally adding types like in the package? cc @hramezani

**Comment by hramezani** [comment]
Sounds good to me as well.
I can help on this topic

**Comment by bluetech** [comment]
WIP here: https://github.com/bluetech/urllib3/commits/tests-typing

**Comment by sethmlarson** [comment]
Closing this issue as we've completed type hints on all tests!
