### ISSUE TITLE
Fix missing link targets in docs

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#2378]
Since the BaseHTTPResponse split in #2083, various links in the docs are broken. Here's how the [Response Content](https://urllib3.readthedocs.io/en/stable/user-guide.html#response-content) looks like:

<img width="580" alt="Screenshot 2021-08-18 at 11 34 23" src="https://user-images.githubusercontent.com/42327/129857043-3f8ddf59-fa22-4c27-b8c9-9333d4a2194c.png">

There are other cases, eg. the API Reference doesn't include the top-level functions, so `disable_warnings()` or `request()` are not documented.

To fix everything in one go, we need to enable Sphinx's `nitpicky` mode. Despite the vague name, it only does one thing: warn about missing references. And since we treat Sphinx warnings as errors, this will allow us to fix those missing references and prevent any regressions in the future.

Here's how Trio configures this `nitpicky` mode: https://github.com/python-trio/trio/blob/cb48b33a42b09dde955617f93923ed8f5fa02426/docs/source/conf.py#L39-L57

The process here, for each of the 78 failures is to figure out if:

 * the link is wrong and should be fixed,
 * the function exists and should be in the API Reference (in that case, add it somewhere in docs/reference),
 * or the link should be added to `nitpicky_ignore`.

It's OK to open a PR that fixes only a few issues!

**Comment by V1NAY8** [comment]
`-W` flag has to be removed in `noxfile.py` in `docs` method, otherwise it stops at the first error

**Comment by pquentin** [comment]
@V1NAY8 Do you still intend to work on this?

**Comment by V1NAY8** [comment]
Nope. It's good for anyone else to pick :)

**Comment by V1NAY8** [comment]
@pquentin I did some work on this. This is still open for anyone else to contribute for other missing links

**Comment by RatanShreshtha** [comment]
I can pick this up

**Comment by pquentin** [comment]
@RatanShreshtha It turns out @V1NAY8 opened https://github.com/urllib3/urllib3/pull/2416, so if he's still interested please focus on a different file
