### ISSUE TITLE
builtins.TypeError in connectionpool.py (line 440)

### ISSUE THREAD

**Issue by sylvainmouquet** [urllib3/urllib3#2385]
### Subject

Hello,

I have some errors  : 

connectionpool.py
line 440 : builtins.TypeError 

python 3.8

![image](https://user-images.githubusercontent.com/184874/130227760-2082b47a-e6bd-4135-b6cd-66db02b6554b.png)

i will try to get more information about it

**Comment by pquentin** [comment]
Without having at least the urllib3 version, there's not much we can do. I'll reopen when we have more info

**Comment by sylvainmouquet** [comment]
__version__ = "1.26.6"

**Comment by sethmlarson** [comment]
Looks like that line is `conn.getresponse()` which is the standard library so you'll have to give us a full traceback along with the code you're using to trigger the error for us to diagnose further.

**Comment by sylvainmouquet** [comment]
ok i try to find more information about this error

**Comment by sylvainmouquet** [comment]
```
                except BaseException as e:
                    # Remove the TypeError from the exception chain in
                    # Python 3 (including for exceptions like SystemExit).
                    # Otherwise it looks like a bug in the code.
                    six.raise_from(e, None)
```

**Comment by pquentin** [comment]
Thanks! However, do you have an actual traceback instead of those lines of code?
