### ISSUE TITLE
Invalid file object in urlopen on Jython

### ISSUE THREAD

**Issue by jaraco** [urllib3/urllib3#2396]
In psf/requests#3992, the user reports an issue where `urlopen` fails with a `ValueError: Invalid file object`.

> I'm running into a repeatable error when testing [omniconf](https://github.com/cyso/omniconf/tree/1.1.1) on Jython with requests >= 2.13.0:
> 
> ```
> ======================================================================
> 1) ERROR: test suite for <class 'omniconf.tests.backends.test_vault.TestVaultBackend'>
> ----------------------------------------------------------------------
>    Traceback (most recent call last):
>     .tox/jython/Lib/site-packages/nose/suite.py line 209 in run
>       self.setUp()
>     .tox/jython/Lib/site-packages/nose/suite.py line 292 in setUp
>       self.setupContext(ancestor)
>     .tox/jython/Lib/site-packages/nose/suite.py line 315 in setupContext
>       try_run(context, names)
>     .tox/jython/Lib/site-packages/nose/util.py line 471 in try_run
>       return func()
>     omniconf/tests/backends/test_vault.py line 87 in setUpClass
>       cls.manager.initialize()
>     .tox/jython/Lib/site-packages/hvac/tests/util.py line 44 in initialize
>       assert not self.client.is_initialized()
>     .tox/jython/Lib/site-packages/hvac/v1/__init__.py line 92 in is_initialized
>       return self._get('/v1/sys/init').json()['initialized']
>     .tox/jython/Lib/site-packages/hvac/v1/__init__.py line 944 in _get
>       return self.__request('get', url, **kwargs)
>     .tox/jython/Lib/site-packages/hvac/v1/__init__.py line 971 in _Client__request
>       response = self.session.request(method, url, headers=headers,
>     .tox/jython/Lib/site-packages/requests/sessions.py line 488 in request
>       resp = self.send(prep, **send_kwargs)
>     .tox/jython/Lib/site-packages/requests/sessions.py line 609 in send
>       r = adapter.send(request, **kwargs)
>     .tox/jython/Lib/site-packages/requests/adapters.py line 413 in send
>       resp = conn.urlopen(
>     .tox/jython/Lib/site-packages/requests/adapters.py line 413 in send
>       resp = conn.urlopen(
>     .tox/jython/Lib/site-packages/requests/packages/urllib3/connectionpool.py line 588 in urlopen
>       conn = self._get_conn(timeout=pool_timeout)
>     .tox/jython/Lib/site-packages/requests/packages/urllib3/connectionpool.py line 588 in urlopen
>       conn = self._get_conn(timeout=pool_timeout)
>     .tox/jython/Lib/site-packages/requests/packages/urllib3/connectionpool.py line 241 in _get_conn
>       if conn and is_connection_dropped(conn):
>     .tox/jython/Lib/site-packages/requests/packages/urllib3/util/connection.py line 27 in is_connection_dropped
>       return bool(wait_for_read(sock, timeout=0.0))
>     .tox/jython/Lib/site-packages/requests/packages/urllib3/util/connection.py line 27 in is_connection_dropped
>       return bool(wait_for_read(sock, timeout=0.0))
>     .tox/jython/Lib/site-packages/requests/packages/urllib3/util/wait.py line 33 in wait_for_read
>       return _wait_for_io_events(socks, EVENT_READ, timeout)
>     .tox/jython/Lib/site-packages/requests/packages/urllib3/util/wait.py line 24 in _wait_for_io_events
>       selector.register(sock, events)
>     .tox/jython/Lib/site-packages/requests/packages/urllib3/util/selectors.py line 314 in register
>       key = super(PollSelector, self).register(fileobj, events, data)
>     .tox/jython/Lib/site-packages/requests/packages/urllib3/util/selectors.py line 179 in register
>       key = SelectorKey(fileobj, self._fileobj_lookup(fileobj), events, data)
>     .tox/jython/Lib/site-packages/requests/packages/urllib3/util/selectors.py line 163 in _fileobj_lookup
>       return _fileobj_to_fd(fileobj)
>     .tox/jython/Lib/site-packages/requests/packages/urllib3/util/selectors.py line 47 in _fileobj_to_fd
>       raise ValueError("Invalid file object: {0!r}".format(fileobj))
>    ValueError: Invalid file object: <_socket._socketobject object at 0x1cc>
>    -------------------- >> begin captured logging << --------------------
>    requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost
>    requests.packages.urllib3.connectionpool: DEBUG: http://localhost:18200 "GET /v1/sys/init HTTP/1.1" 200 22
>    --------------------- >> end captured logging << ---------------------
> ```
> 
> My test [initializes hvac](https://github.com/cyso/omniconf/blob/1.1.1/omniconf/tests/backends/test_vault.py#L78), which in turn checks if the requests client [is already initialized](https://github.com/ianunruh/hvac/blob/v0.2.17/hvac/v1/__init__.py#L92). This seems to do a GET request, but when [opening the response](https://github.com/kennethreitz/requests/blob/v2.13.0/requests/packages/urllib3/util/selectors.py#L45), the resulting file object is reported as being invalid.
> 
> I can reproduce this error when running omniconf tests with `tox -e jython`, after installing Jython and Hashicorp Vault (see the [.travis-ci.yml](https://github.com/cyso/omniconf/blob/1.1.1/.travis.yml#L34) for steps).
> 
> Older versions of requests work fine, specifically when specifying `requests < 1.12.0` (because of the earlier issues with `Method code too large!`).

If the issue is not going to be fixed, it would be nice to at least exclude `Jython` from the supported Python implementations in the package metadata so that `pip install requests` will only pick up viable versions of requests on Jython.

**Comment by sethmlarson** [comment]
Hmm, we haven't tested against Jython is a really long time. I wonder if we lost compatibility after https://github.com/urllib3/urllib3/commit/9782e1f866aa6d0d176dce8678aee448aeb492dd which was first released in 1.23.

**Comment by sigmavirus24** [comment]
Jython is also only supporting Python 2.7 iirc and barely maintained last I checked. I don't think anyone should be spending significant time supporting it at this point - especially since it's the implementation that doesn't behave according to the reference implementation (CPython) or any other implementation (PyPy for example).

**Comment by sigmavirus24** [comment]
> If the issue is not going to be fixed, it would be nice to at least exclude `Jython` from the supported Python implementations in the package metadata so that `pip install requests` will only pick up viable versions of requests on Jython.

This bit doesn't belong on urllib3. It's hard to know when compatibility broke and there have likely been many many releases of both urllib3 and requests since then, none of which we can update after-the-fact to indicate that they don't support Jython

**Comment by sethmlarson** [comment]
Yeah I don't think there's much we can do, Python 2.7 is not going to be supported in v2.0 and if we lost compatibility that long ago and this is the first we're hearing of it I'm not sure the reward vs. effort is worth it. Going to close this one.

**Comment by pquentin** [comment]
> If the issue is not going to be fixed, it would be nice to at least exclude `Jython` from the supported Python implementations in the package metadata so that `pip install requests` will only pick up viable versions of requests on Jython.

Not only I don't know how to do that, but how would it help? Many released versions are already broken

**Comment by jaraco** [comment]
> Not only I don't know how to do that, but how would it help? Many released versions are already broken

I was thinking you could (a) re-release a few older versions with an 0.0.1 bump and including the exclusion followed by (b) yank the older versions (such that they only get installed when specifically requested).

But I realized the feature I was thinking of (`python_implementation` marker) only applies to dependencies and not `python_requires`, so you're right, I'm also not aware of any way to achieve what I was imagining.
