### ISSUE TITLE
While making a request to a server (supporting HTTP/2.0 ) it receives HTTP status code 503 with response body as "upstream connect error or disconnect/reset before headers. reset reason: remote refused stream reset"

### ISSUE THREAD

**Issue by mejuhi** [urllib3/urllib3#2408]
### Subject

While making a request to HTTP/2.0 server, some requests end up with `503` with response body as `upstream connect error or disconnect/reset before headers. reset reason: remote refused stream reset`

It feels like connection gets closed even before whole request is sent and hence it is unexpectedly terminated for few requests and we receive this error. 
### Environment

Describe your environment.
At least, paste here the output of:

```python
import platform
import urllib3

print("OS", platform.platform())
print("Python", platform.python_version())
print("urllib3", urllib3.__version__)
```
Output of above code
```
OS Linux-4.4.0-x86_64-with-debian-buster-sid
Python 3.7.10
urllib3 1.26.3
```

### Steps to Reproduce

We are using following implemented method to make a POST request to server 

```
import requests
from urllib3.util.retry import Retry
from requests.adapters import HTTPAdapter

def invokeHttpPost(httpEndpoint, httpParameters, httpHeaders, httpPayload):
    try:
        httpSession = requests.Session()
        #just use post rather than pu, post
        retryConfig = Retry(total=3, backoff_factor=0, status_forcelist=[502, 503, 425, 504, 507, 506, 508, 511, 400],
                        raise_on_status=False, allowed_methods = frozenset(['POST']))
        httpSession.mount('https://', HTTPAdapter(max_retries=retryConfig))
        httpResponse = httpSession.post(httpEndpoint, params=httpParameters, headers=httpHeaders, data=httpPayload, timeout=main.RETRY_TIMEOUT)
        return httpResponse 
    except Exception as ex:
        raise ex
```

### Expected Behavior

All request should should go successfully

### Actual Behavior

Some requests return HTTP response `503`  with response body message as `upstream connect error or disconnect/reset before headers. reset reason: remote refused stream reset`

### Noted Behavior
It use to work as expected when we use to call server with HTTP/1.0 compatibility

**Comment by mejuhi** [comment]
Do you thing is it due to streaming? and will [`preload_content=False `](https://urllib3.readthedocs.io/en/latest/advanced-usage.html?highlight=stream#streaming-and-i-o)help us in this issue?

**Comment by sethmlarson** [comment]
So we'll likely not be able to diagnose "why" you're seeing this error, you'll likely have to know the HTTP server being used and do your own research. urllib3 uses HTTP/1.1 only so there's no HTTP/2 component to this issue, the server likely supports multiple HTTP versions if you're using urllib3 successfully.

Using `preload_content` likely won't solve your issue, this only changes whether we read all content from the wire immediately or wait for manual calls to `.read()`.

One suggestion for you, you're using a new `requests.Session` per request which is really inefficient. You should try to reuse the session to have your connections longer lived.

Closing this issue as there's nothing additional for us to do.
