### ISSUE TITLE
Add support for assert_proxy_cert_fingerprint and assert_proxy_hostname

### ISSUE THREAD

**Issue by jalopezsilva** [urllib3/urllib3#2409]
For v2, it would be nice if we expand the ways we can match an HTTPS proxy certificate. After #2407  is merged, we'll only have hostname verification but it would be ideal to be consistent in what we support for HTTPS destinations.

### Minimum requirements

:moneybag: **You can get paid to complete this issue! [Please read the docs for more information](https://urllib3.readthedocs.io/en/latest/contributing.html#getting-paid-for-your-contributions).**

* [ ] Add new parameter ``assert_proxy_cert_fingerprint``
* [ ] Add new parameter ``assert_proxy_hostname``
* [ ] Add test cases for both parameters with similar rigor to the parameters `assert_cert_fingerprint` and `assert_hostname` tests.

**Comment by AllMight2099** [comment]
Hey there!
I'm Nishanth, and I was hoping I could work on this issue, I had a few doubts I was hoping that could be clarified:
1. I'd like to get more clarification on what you mean by parameter. Does it mean a function parameter when we initialize a proxy object or is it something else?
2. Are there example tests that I could look at? I did look at the test folder, but wanted to confirm if I'm going in the right direction by looking at the proxymanager's test

**Comment by sethmlarson** [comment]
The parameters would go on `ProxyManager.__init__` and get put into the `ProxyConfig` object with other proxy HTTPS config parameters.

For finding tests you can search for `assert_hostname` and `assert_cert_fingerprint` in the `test/` folder and see what's already there.

**Comment by jschneier** [comment]
I've opened a PR that I believe implements this feature but need to add tests, however I could use some guidance since I'm not that familiar with proxy functionality.

I found the tests in `with_dummyserver/test_https.py` that can serve as a model for new ones in `with_dummyserver/test_proxy_poolmanager.py` but my confusion is about _what_ am I validating. Is it the connection to the proxy or the eventual response from the server? I assume the latter but I'm a bit confused about how [this test](https://github.com/urllib3/urllib3/blob/main/test/with_dummyserver/test_proxy_poolmanager.py#L654) differs from the desired functionality.

**Comment by jalopezsilva** [comment]
@jschneier Good progress so far! 

Your goal with the tests is to validate that the following [code](https://github.com/urllib3/urllib3/blob/d7378a1a3a0546409eab63a4e0c864774a4b6525/src/urllib3/connection.py#L649-L672) is executed when you are performing a TLS connection to the proxy. Both options ``assert_fingerprint`` and ``assert_hostname`` allow you to customize the SSL certificate verification that is done when connecting to a destination. In this case, we want to ensure those two options apply to HTTPS proxies when provided.

The [test_https.py](https://github.com/urllib3/urllib3/blob/7636345843bb66be17c2de8065b4235d37d05eb2/test/with_dummyserver/test_https.py) file has the best examples of how you can add a custom hostname/fingerprint for verification.  Hope that helps!

**Comment by jschneier** [comment]
@jalopezsilva thanks, and potentially. I believe you are saying that it is the proxy connection itself that we are testing because the destination is handled by the already existing (non-proxy) `assert_(hostname|fingerprint)`, right?

**Comment by jalopezsilva** [comment]
> @jalopezsilva thanks, and potentially. I believe you are saying that it is the proxy connection itself that we are testing because the destination is handled by the already existing (non-proxy) `assert_(hostname|fingerprint)`, right?

Exactly. We don't have any way to assert hostname/fingerprint for HTTPS proxy connections today and that's what this issue aims to resolve.

**Comment by jschneier** [comment]
@jalopezsilva I think this is now complete / ready for review!
