### ISSUE TITLE
Add a dummy HTTPS proxy that can be used for debugging / development

### ISSUE THREAD

**Issue by jalopezsilva** [urllib3/urllib3#2410]
HTTPS proxies are not that common and setting one up through nginx or squid is not trivial. We need an easy way for the core team to be able to run an HTTPS proxy, test new features, debug, etc.

I'll aim to create a ``dummyserver/https_proxy`` that can be run locally with minimal set up.

**Comment by sethmlarson** [comment]
Closed in https://github.com/urllib3/urllib3/pull/2435
