### ISSUE TITLE
Allow custom authentication (in particular NTLM) to proxies

### ISSUE THREAD

**Issue by hickford** [urllib3/urllib3#242]
(Upstreamed from https://github.com/kennethreitz/requests/issues/1582 )

While Requests allows custom authentication (any class implementing AuthBase) to content servers, it only supports Basic auth to proxies. It would be great to support custom authentication for proxies too.

In particular, NTLM proxies are common in Windows corporate networks.  Python development can't get off the ground in my office because the package manager falls over at the proxy.

I note  urllib3's ProxyManager can only do Basic authentication, and not any other kind. https://github.com/shazow/urllib3/blob/master/urllib3/poolmanager.py#L174
##

**Comment by voltagex** [comment]
@Lukasa has anything changed in regards to cost in the last few years?

**Comment by Lukasa** [comment]
Nope.

**Comment by jakubvedral** [comment]
Hi everyone, we have the same problem at our company... As a workaround we user cURL with PyCurl, but it is not a good solution in the long run (PyCurl is not as actively maintained as requests). Also it is difficult to use it for webscraping....

Any updates on this issue?

**Comment by Lukasa** [comment]
Nope.

**Comment by railocius** [comment]
If anybody wants to test HTTPS CONNECT with your own NTLM proxy server, you can just set-up an Apache web server: https://stackoverflow.com/a/48238953

**Comment by sethmlarson** [comment]
Since we've deprecated and removed NTLM support I don't think we'll ever get to implementing this natively in urllib3. Going to close this one.
