### ISSUE TITLE
unclear which certificate failed

### ISSUE THREAD

**Issue by srl295** [urllib3/urllib3#2440]
### Subject

SSL failures don't say which cert expired

### Environment

Python 3.8.8 Windows 10 (Anaconda)

### Steps to Reproduce

I actually can't repro this on my own system, but others have. Here is some sample code that failed in one environment

```python
import urllib3
#import certifi
import logging

logging.root.setLevel("DEBUG")
logging.captureWarnings(True)

http = urllib3.PoolManager(
#    cert_reqs="CERT_REQUIRED",
#    ca_certs=certifi.where()
)

r = http.request('HEAD', 'https://st.unicode.org')
print(r.data)
print(r.headers)
print(r.status)
```

### Expected Behavior

successful run

### Actual Behavior

On some systems, a failure similar to the following.

```
DEBUG:urllib3.util.retry:Incremented Retry for (url='/'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1125)'))': /
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (2): ourhost.example.com:443
```

So the root (haha) issue was the letsencrypt X3 expiration <https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/> however, the error message does not say WHICH certificate expired.  Is there a way to find out which certificate it was that expired?  It wasn't my host (ourhost.example.com) it was actually X3's certificate.

Uncommenting the commented lines, above, to use certifi's certs, fixed the issue for those users.  

It's unclear to me how `certifi` is supposed to be automatically picked up given that it isn't specifically imported by urllib3. 

I'm not asking for a fix to the cert issue, but for help in how to get more information about what exactly broke, so that 'next time' it will be easier to diagnose.

**Comment by sethmlarson** [comment]
Unfortunately we don't get any visuals into the certificate chain, we only get the error (the error and message originate from OpenSSL, not even from Python) so I'm unsure if there's anything urllib3 can do here yet? Maybe with certificate chain support we can give a slightly better error message but even that's down the road from now.

**Comment by srl295** [comment]
@sethmlarson I wondered if this would be the case. Basically, it sounds like urllib3 doesn't have any further details at that point, and one would have to do a separate diagnostic inquiry *with different API calls* to try to reproduce why the failure occurred. Am I right?

I got as far as `ssl.get_server_certificate((hostname, port))` before, and that just returned the cert I expected to see (which, as I mentioned above, is definitely not expired).   I'd need `ssl.get_server_certificate_chain()` or something, and digging into py's `ssl.py` there doesn't seem to be anything like that mentioned.

Of course I can do it with `openssl s_client -showcerts` but the kicker here is that on another system, that showed the winning path, not the path with any expired root certs in it. And, for some reason, a different bundle was picked up by python than expected.

Thanks for the reply, and go ahead and close this as desired…

**Comment by sigmavirus24** [comment]
@srl295 I suspect you're bitten by https://github.com/certifi/python-certifi/pull/162 (not the fact that you're using certifi exactly so much as the certificate that has expired) and that `openssl s_client -showcerts` isn't even giving you exactly what you think it might be or isn't the same openssl that your Python is linked against. I don't know about anaconda but on Python, I believe we use the Windows trust store by default so the certificate causing you trouble might be in there
