### ISSUE TITLE
[1.26] Remove Python 3.5 support

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#2449]
See https://github.com/urllib3/urllib3/pull/2012 from @hramezani for inspiration. (Yay, this work will end up being useful.)

**Comment by chetanugale** [comment]
@pquentin @sethmlarson can I try this ?

**Comment by rakitaj** [comment]
Is this already complete? I grabbed main and I don't see any references to Python 3.5, and it looks like most or all of the work in #2456 is also done in main.

**Comment by sethmlarson** [comment]
Completed in https://github.com/urllib3/urllib3/pull/2456 for 1.26
