### ISSUE TITLE
[CI] Switch to the new codecov uploader

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#2459]
As announced in https://about.codecov.io/blog/introducing-codecovs-new-uploader/, the Bash uploader that we currently use is deprecated. It will stop working on February 1, but [15 minutes brownouts are already happening](https://about.codecov.io/blog/codecov-uploader-deprecation-plan/).

Here's the file that needs to change: https://github.com/urllib3/urllib3/blob/main/ci/upload_coverage.sh (we'll also have to backport this to 1.26.x)

**Comment by imkaka** [comment]
I will work on this.

**Comment by pquentin** [comment]
Please go ahead :) You don't need permission to work on it, declaring intent (as @imkaka did) is enough, and even that is not mandatory
