### ISSUE TITLE
Unable to import reraise from `util/util.py`

### ISSUE THREAD

**Issue by maxyousif15** [urllib3/urllib3#2480]
### Subject

Unable to import `reraise` function from `urllib3/util/util.py`. The test file https://github.com/urllib3/urllib3/blob/main/test/test_util.py#L38 indicates that utilities from that file are being tested, but not the `reraise` method.

### Environment

```
>>> import platform
>>> import urllib3
>>> 
>>> print("OS", platform.platform())
OS macOS-10.16-x86_64-i386-64bit
>>> print("Python", platform.python_version())
Python 3.8.5
>>> print("urllib3", urllib3.__version__)
urllib3 1.26.7
```

### Steps to Reproduce

```
# This throws a ModuleNotFoundError error 
from urllib3.util.util import to_bytes, to_str

# Similarly, this also throws ModuleNotFoundError error 
from urllib3.util.util import reraise
```

### Expected Behavior

To be able to import the utility functions defined in `util/util.py`

### Actual Behavior
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-15-925465d4645f> in <module>
----> 1 from urllib3.util.util import reraise

ModuleNotFoundError: No module named 'urllib3.util.util'
```

Note - I could re-define the `reraise` method in my codebase, but was wondering why this is not an accessible method which has not been tested.

**Comment by pquentin** [comment]
`urllib3.util.util` is a new module in the main branch for the upcoming 2.0 release. It doesn't exist in the 1.26.x branch which was used for the 1.26.7 release.

We don't test reraise directly (maybe we could) but we test it indirectly as we maintain 100% test coverage.

**Comment by pquentin** [comment]
By the way, those utilities were never part of our public API, please install and use the six package if you need them!
