### ISSUE TITLE
Support for connection idle timeout

### ISSUE THREAD

**Issue by garrettheel** [urllib3/urllib3#2498]
### Context

What are you trying to do?

Timeout idle connections after a given period of time automatically. 

How do you expect to do it?

I'd expect to be able to pass in a kwarg when creating a `ConnectionPool`, such as `idle_timeout=600` to timeout idle connections after 10 minutes.

Is it something you currently cannot do?

Correct, I read the docs/source and cannot find any functionality to do this.

Is this related to an existing issue/problem?

Not one on this repo, as far as I can tell.

### Alternatives

Can you achieve the same result doing it in an alternative way?

I don't think so, short of throwing away the entire connection pool.

Is the alternative considerable?

### Duplicate

Has the feature been requested before? Not that I can find
If so, please provide a link to the issue.

### Contribution

Would you be willing to submit a PR? Potentially, if folks are amenable to adding this.

**Comment by sethmlarson** [comment]
Currently we don't have active idle connection cleanup as doing so would likely require background work (ie threads). Instead we have passive idle connection cleanup where a TCP connection naturally gets closed as a part of TCP_KEEPALIVE. When a connection is pulled from the pool it's checked to see if the underlying socket is still open and if not the connection is reopened.

Are there additional wins we'd get from active cleanup over the current idle connection cleanup implementation?

**Comment by sethmlarson** [comment]
Going to close this as it's not clear what this brings over our current scheme.

**Comment by abebeos** [comment]
> Are there additional wins we'd get from active cleanup over the current idle connection cleanup implementation?

See https://github.com/urllib3/urllib3/issues/3184
