### ISSUE TITLE
_is_key_file_encrypted tracebacks if keyfile param is not a filename

### ISSUE THREAD

**Issue by jco-odoo** [urllib3/urllib3#2508]
### Subject
From v1.25, _is_key_file_encrypted is introduced to be able to use encrypted key files. However, if we do not want 
_is_key

### Environment

As there is no way to set a Session.cert which is not a file and we want to avoid it for security reasons, we added a custom HTTPAdapter which made it possible to use the actual contents instead of the keyfile itself.  (for reference: https://github.com/odoo/odoo/blob/5af586d5d09291400c6297a72994054248681a59/addons/l10n_es_edi_sii/models/account_edi_format.py#L54 ) 

### Steps to Reproduce

The simple test might be passing something else than a filename to that method. 

### Expected Behavior
Ideally, make it possible to pass the contents of the file instead of filenames.  But for the moment, it would already help a lot if it would not traceback (e.g. by encapculating in a try except and if it excepts, we return False as the only functionality is to check if the file is encrypted.  )

### Actual Behavior
Even adapting the behaviour in an adaptive way (HTTPAdapter), we still have the traceback. 
(we can of course monkey-patch the _is_key_file_encrypted method, but it is not ideal)

**Comment by sethmlarson** [comment]
The result of `_is_key_file_encrypted` is passed to [`SSLContext.load_cert_chain(keyfile=...)`](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.load_cert_chain) which only accepts file paths, not key data. Which TLS backend are you using?

**Comment by jco-odoo** [comment]
Unless we override it...  Using the file system can be a security issue and it would be cool if the library could be improved to support passing the contents immediately.  And just putting the try...except might allow us to do it already without having to monkey-patch.

**Comment by jco-odoo** [comment]
Another way might be to put the method in a class, so it is easier to override.

**Comment by pquentin** [comment]
> Unless we override it...

What are you suggesting to override?

I'm confused: what are you asking for exactly?

If someone passes `key_file`, isn't it expected that it gets read? We would also prefer to have an API that accepts file contents, but OpenSSL does not support it, so we need to have the contents on the file system.

**Comment by sethmlarson** [comment]
Going to close this, for now we'll stick with what we have.

**Comment by jco-odoo** [comment]
Thanks for the comments and the closing.  We could go around it by passing the contents in cert_file instead of key_file.  And we patch load_cert_chain indeed which is probably not the best idea doing in this library.  Putting methods like _is_key_file_encrypted in a class would just make it more override-friendly.

**Comment by pquentin** [comment]
Can you please share what patching you're doing?

**Comment by jco-odoo** [comment]
https://github.com/odoo/odoo/blob/15.0/addons/l10n_es_edi_sii/models/account_edi_format.py#L46
