### ISSUE TITLE
Change set_file_position() type to use proper sentinel with _FAILEDTELL

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2512]
Currently `_FAILEDTELL` in `urllib3.util.request` uses `object` as a sentinel type, we should give this object the same treatment as `_DEFAULT_TIMEOUT` and switch to a `Final[Enum]`. This type should be used wherever `body_pos` is used.

cc @hramezani

**Comment by imkaka** [comment]
I will work on this.

**Comment by sethmlarson** [comment]
@imkaka Sounds good, I await a PR! 🙇‍♂️
