### ISSUE TITLE
Parsing localhost with port using parse_url 

### ISSUE THREAD

**Issue by tomers** [urllib3/urllib3#2523]
### Subject
When parsing URL which if of the pattern `localhost:<port>`, then `localhost` is parsed as `scheme` instead of `host`, and the port is parsed as `path` instead of `port`:
```
>>> assert parse_url('localhost').host == 'localhost'
>>> assert parse_url('localhost:1234').host == 'localhost'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError

>>> parse_url('localhost:1234')
Url(scheme='localhost', auth=None, host=None, port=None, path='/1234', query=None, fragment=None)
```

### Environment
OS Linux-5.4.0-92-generic-x86_64-with-glibc2.29
Python 3.8.10
urllib3 1.25.11

### Expected Behavior
```
>>> assert parse_url('localhost:1234') == Url(host="localhost", port=1234)
```

### Actual Behavior

```
>>> parse_url('localhost:1234')
Url(scheme='localhost', auth=None, host=None, port=None, path='/1234', query=None, fragment=None)
```

**Comment by pquentin** [comment]
Thanks for the clear bug report! As you mentioned in the requests issue, `parse_url` is not expected to work without a scheme, the current behavior is expected.
