### ISSUE TITLE
Can upload bandwidth be limited to 50kb/s?

### ISSUE THREAD

**Issue by bucibucii** [urllib3/urllib3#2527]
### Context

I want to limit the upload bandwidth up to 50kb/s

Is it possible to do it?

**Comment by sethmlarson** [comment]
Yes, you'd have to create your own mechanism to slowly feed request body data to urllib3 with a moving window. Here's an example that shows urllib3 is a capable of streaming from a generator which can be tweaked to make this a 50KB/s moving window:

```python
import urllib3
import time

http = urllib3.PoolManager()

def slow_stream():
    for _ in range(10):
        yield b"x" * 100
        time.sleep(1)

http.request("POST", "http://httpbin.org/anything", body=slow_stream())
```

The above isn't your solution, that will be up to you to write, but urllib3 is capable of this. Closing this issue as the question is answered.
