### ISSUE TITLE
[1.26] Coverage dropped below 100% when vendoring ssl_match_hostname

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#2543]
https://github.com/urllib3/urllib3/pull/2540 shows that in the 1.26.x branch, the following lines are not covered:

https://github.com/urllib3/urllib3/blob/b1f60e44d43b13e5272d5b6003f125af9c25c8ad/src/urllib3/util/ssl_match_hostname.py#L118-L122

This was never covered, we just notice it now because we vendored that code. We need a test.

https://github.com/urllib3/urllib3/blob/b1f60e44d43b13e5272d5b6003f125af9c25c8ad/src/urllib3/util/ssl_match_hostname.py#L150

It seems like this line is covered in the main branch, maybe adding a `raise ValueError()` and running the main tests will show how it's covered? (It's surprising because we have the same tests in both branches.)

In the meantime, since this blocks merging 1.26 PRs, I'd suggest using a nocover pragma.

@chetanugale @hramezani This issue may be of interest to you as you've touched those files in the past.

**Comment by hramezani** [comment]
Thanks @pquentin for the issue. 
I will check later uncovered line in  `ssl_match_hostname.py` 
 https://github.com/urllib3/urllib3/blob/b1f60e44d43b13e5272d5b6003f125af9c25c8ad/src/urllib3/util/ssl_match_hostname.py#L150

> In the meantime, since this blocks merging 1.26 PRs, I'd suggest using a nocover pragma.

Sound good to me for now!

**Comment by hramezani** [comment]
To cover `UnicodeError` except:
https://github.com/urllib3/urllib3/blob/b1f60e44d43b13e5272d5b6003f125af9c25c8ad/src/urllib3/util/ssl_match_hostname.py#L118-L122

As [UnicodeError  is a subclass of ValueError](https://docs.python.org/3.8/library/exceptions.html#UnicodeError), and in both `except` blocks we have `host_ip = None`, I would suggest to merge this two blocks:

```
except (UnicodeError, ValueError): 
```

Or remove `UnicodeError` block,
Or move `UnicodeError` above the `ValueError` and add a test for it.

What do you think @pquentin ?

**Comment by hramezani** [comment]
@pquentin I think we can close this now!

**Comment by sethmlarson** [comment]
Yes we can! Thanks @hramezani
