### ISSUE TITLE
Stop linking to codecov in README

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#2551]
We currently have a coverage badge in our README:

![image](https://user-images.githubusercontent.com/42327/151172735-3686867c-d312-4d08-9d18-9e7bdce1d99f.png)

We're very proud that we had 100% coverage for years. Not only it's very useful to us, but it highlights that urllib3 has high code quality and exhaustive tests. However, this badge currently links to codecov. We stopped using codecov, though, because it was too flaky, see https://github.com/urllib3/urllib3/pull/2502.

Since we want to keep the 100% badge, let's keep it in the README by inlining it in `docs/_static` and removing the link to codecov. It won't be live anymore but we enforce that 100% coverage and it was like that for years, so it's not like we're going to deceive anyone.

**Comment by imkaka** [comment]
I will pick this one.
