### ISSUE TITLE
Incorrect "Your proxy appears to only use HTTP and not HTTPS" error message during connection errors to HTTPS websites using a HTTP proxy

### ISSUE THREAD

**Issue by nyuszika7h** [urllib3/urllib3#2564]
### Subject

I'm 100% certain I'm using `http://` for my proxy, however I receive warnings like this which are due to the proxy being unstable:

```
2022-02-13 00:37:43 [W] urllib3.connectionpool :  - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))': /[redacted]
```

The warnings miraculously go away after a few retries, which proves what urllib3 is saying is not the issue.

### Environment

```
OS Linux-5.10.0-11-amd64-x86_64-with-glibc2.31
Python 3.10.1
urllib3 1.26.8
```

### Steps to Reproduce

1. Use a HTTP proxy to connect to a HTTPS website. I'm using [windscribe-proxy](https://github.com/Snawoot/windscribe-proxy) with `requests` like this: `session.proxies.update({"all": "http://127.0.0.1:28080"})`
2. Wait for an error in the proxy to trigger a "wrong version number" error.

### Expected Behavior

urllib3 should check whether the proxy string it's using actually starts with `https://` before saying "Your proxy appears to only use HTTP and not HTTPS".

### Actual Behavior

There is a blanket check on the "wrong version number" error which erroneously assumes every instance of that error is due to using `https://` on a HTTP proxy.

**Comment by sethmlarson** [comment]
Thanks for reporting this, I agree that we should only be giving this error message on HTTPS proxies. Would you be up for contributing a fix with a test case for this?

**Comment by hramezani** [comment]
Hey @sethmlarson, I can work on this. my plan is to pass the proxy scheme to the `_wrap_proxy_error` and then check it there.
something like:

```diff
diff --git a/src/urllib3/connection.py b/src/urllib3/connection.py
index cd095d17..35c7c41d 100644
--- a/src/urllib3/connection.py
+++ b/src/urllib3/connection.py
@@ -685,7 +685,7 @@ def _match_hostname(
         raise
 
 
-def _wrap_proxy_error(err: Exception) -> ProxyError:
+def _wrap_proxy_error(err: Exception, proxy_scheme: str) -> ProxyError:
     # Look for the phrase 'wrong version number', if found
     # then we should warn the user that we're very sure that
     # this proxy is HTTP-only and they have a configuration issue.
@@ -702,7 +702,7 @@ def _wrap_proxy_error(err: Exception) -> ProxyError:
     )
     new_err = ProxyError(
         f"Unable to connect to proxy"
-        f"{http_proxy_warning if is_likely_http_proxy else ''}",
+        f"{http_proxy_warning if is_likely_http_proxy and proxy_scheme == 'https' else ''}",
         err,
     )
     new_err.__cause__ = err
diff --git a/src/urllib3/connectionpool.py b/src/urllib3/connectionpool.py
index 57646d38..782eabe4 100644
--- a/src/urllib3/connectionpool.py
+++ b/src/urllib3/connectionpool.py
@@ -421,7 +421,7 @@ class HTTPConnectionPool(ConnectionPool, RequestMethods):
             if isinstance(
                 new_e, (OSError, NewConnectionError, TimeoutError, SSLError)
             ) and (conn and conn._connecting_to_proxy):
-                new_e = _wrap_proxy_error(new_e)
+                new_e = _wrap_proxy_error(new_e, conn.proxy.scheme)
             raise new_e
 
         # conn.request() calls http.client.*.request, not the method in
@@ -787,7 +787,7 @@ class HTTPConnectionPool(ConnectionPool, RequestMethods):
                     HTTPException,
                 ),
             ) and (conn and conn._connecting_to_proxy):
-                new_e = _wrap_proxy_error(new_e)
+                new_e = _wrap_proxy_error(new_e, conn.proxy.scheme)
             elif isinstance(new_e, (OSError, HTTPException)):
                 new_e = ProtocolError("Connection aborted.", new_e)

```

What do you think?

For testing, I think it we can add a new test like https://github.com/urllib3/urllib3/blob/f0dffb4e2437cb2da2ba0a6bbea6211f6fd0fa4b/test/with_dummyserver/test_socketlevel.py#L1163

with `http` proxy but I am not sure.

**Comment by sethmlarson** [comment]
@hramezani That solution works for me!

**Comment by sethmlarson** [comment]
@hramezani I'm not sure the new test function is correct to reproduce this error. I think it needs to have an HTTP proxy that succeeds to connect and then after creating the CONNECT tunnel to the website the HTTPS handshake starts and then fails because the website sends an HTTP response. Does that make sense?
