### ISSUE TITLE
Start using brotlicffi on non-CPython implementations on 1.26.x

### ISSUE THREAD

**Issue by DManowitz** [urllib3/urllib3#2574]
I would like to make a suggestion regarding the use of the brotlipy package.  I see that there has already been a fix made for urllib3 v2 to use the official brotli package for cpython, and that it has been marked as a breaking change.  However, since urllib3 v2 has not yet been released, and it may take some time for this version to be released and even more time for it to be picked up by the other packages that depend on it as well, I would like to suggest that you release an update to urllib3 v1 that uses the brotlicffi package instead of the brotlipy package so that users who would like to install other packages that rely on the official brotli package can install these other packages as well as urllib3 without having to worry about the namespace conflict.  It may not be as performant as the fix with the official brotli package, but it will avoid this namespace conflict in the meantime.

**Comment by pquentin** [comment]
@sethmlarson would you accept a pull request that backports #2099 to 1.26.x?

**Comment by pquentin** [comment]
Can this issue be closed now?

**Comment by sethmlarson** [comment]
Yes! Closed in #2579
