### ISSUE TITLE
Getting partial content from the website

### ISSUE THREAD

**Issue by nvakhilnair** [urllib3/urllib3#2584]
### Subject

Getting partial content from the website after sending the requests with the requests module (urllib3 version 1.26.9). But after downgrading the urllib3 to version 1.22 the issues are being resolved.
Does anyone have any idea why this is happening?

### Environment
Install packages: Same for both versions of urllib3
[installed package.txt](https://github.com/urllib3/urllib3/files/8329944/installed.package.txt)

Python version: 3.8.10 [GCC 9.3.0] on Linux

Output with urllib3 1.26.9 -  
[partial_content.zip](https://github.com/urllib3/urllib3/files/8329894/partial_content.zip)

Output with urllib3 1.22
[complete_content.zip](https://github.com/urllib3/urllib3/files/8329899/complete_content.zip)

### Steps to Reproduce
```python
import requests

headers = {
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.5',
    'Accept-Encoding': 'gzip, deflate, br',
    'DNT': '1',
    'Connection': 'keep-alive',
    'Upgrade-Insecure-Requests': '1',
    'Sec-Fetch-Dest': 'document',
    'Sec-Fetch-Mode': 'navigate',
    'Sec-Fetch-Site': 'none',
    'Sec-Fetch-User': '?1',
    'Pragma': 'no-cache',
    'Cache-Control': 'no-cache'
        }
url = "https://www.amazon.co.uk/b/?node=2110345031&ref_=Oct_d_odnav_d_471475031_4&pd_rd_w=BnRir&pf_rd_p=6141e0ca-76e3-43a6-9135-d17159cee607&pf_rd_r=JV9DVVNQCAA4NFTKWR9Z&pd_rd_r=f216d3ad-5498-42ee-9a37-f425410138f9&pd_rd_wg=CvVKN"
res = requests.get(url=url,headers=headers)
data = res.content
with open('content.html','wb') as f:
    f.write(data)
```

### Expected Behavior
Sending requests to the URL should fetch the entire content from the website, not the partial content.

### Actual Behavior
Using urllib3 version 1.26.9  unable to fetch the entire content only partial content is fetched.

**Comment by nateprewitt** [comment]
I took a quick look at the actual output. I think we may be conflating different files sizes with incomplete responses. You'll see both pages begin and end with the same header/footer (implying the page is in fact complete). However, likely due to fingerprinting or some other mechanism, the server is responding with significantly truncated content in the body.

While it does appear this is related to some behavior in urllib3, it's not a defect in the library. We have little control over how a server chooses to respond to a given request.

**Comment by nvakhilnair** [comment]
> I took a quick look at the actual output. I think we may be conflating different files sizes with incomplete responses. You'll see both pages begin and end with the same header/footer (implying the page is in fact complete). However, likely due to fingerprinting or some other mechanism, the server is responding with significantly truncated content in the body.

It makes sense but what I don't understand is why this is consistently working in version less than 1.24.3.
