### ISSUE TITLE
Potential security Vulnerability

### ISSUE THREAD

**Issue by ranjit-git** [urllib3/urllib3#2590]
A potential security vulnerability has been disclosed for this repo https://huntr.dev/bounties/b94dbb2c-0875-4316-b2fc-81d2d32cc8fa/ 3 months ago .
But i see it still not addressed .
Kindly validate the bug

**Comment by sethmlarson** [comment]
If you'd like to report a vulnerability you should do so via our [documented security disclosure contact](https://github.com/urllib3/urllib3/blob/main/.github/SECURITY.md) including all information about the potential issue. We don't use third party services that require personal information.

**Comment by ranjit-git** [comment]
@sethmlarson huntr.dev team already sent you the report details to provided email in https://github.com/urllib3/urllib3/blob/main/.github/SECURITY.md .
You should have received the report details in mail already . In that mail there is a magick unique link , by using this you can view the report details without signup . In mail just search for "https://huntr.dev/" .
I will ask the admin to resend the report details again .
