### ISSUE TITLE
Add a simple CLI tool to download files

### ISSUE THREAD

**Issue by danielhoherd** [urllib3/urllib3#2597]
### Context

It would be great if urllib3 came with a simple CLI tool for downloading files. I'm thinking of something equivalent to the reduced functionality `wget` included with busybox.

The reason for this is that urllib3 is pure-python, and can be installed without root permissions, and it would be great to have that available in different build environments that have python available. EG: when running a `docker build` on alpine, redhat, and ubuntu, a download tool to fetch a required file that is needed for the build would be great to have built into urllib, instead of having to install a third party downloader and then clean it away.

This could also serve as a reference design on how write software using urllib3. There is already a demo of how to use urllib3 to download a file in the README, and having that as a cli tool or the default function for `python -m urllib3` would be great.

### Alternatives

I've looked for alternatives, such as a pure-python implementation of wget, and I found several, but most of them appear to be abandonware or in a broken state.

### Duplicate

Not that I could find.

### Contribution

Would you be willing to submit a PR? Yes.

**Comment by sigmavirus24** [comment]
Why not use something like httpie? It has the same properties and does exactly what you ask

**Comment by sethmlarson** [comment]
Thanks for opening, unfortunately this isn't in the scope for our project. I recommend checking out curl, wget, httpie, or another tool for this.

**Comment by danielhoherd** [comment]
@sigmavirus24 httpie is actually almost exactly what I was looking for, and I completely forgot about it, but it didn't show up in searches for "alternatives to curl" and "pure python downloader"
