### ISSUE TITLE
Differentiate between timeout and http errors in Retry mechanism

### ISSUE THREAD

**Issue by Eandrju** [urllib3/urllib3#2603]
### Context

I'm writing a client for a service that might response with 503 to a POST request. If it do so I'm supposed to retry after 0.1s. That's kinda achievable with backoff_factor, no problem here. However, I'd like to have a timeout set for this request, let's say 3s. Problem is that I don't want to retry on timeout, because the server might still process the request without an error. 

Currently retry mechanism treats timeout errors and http status errors the same way. There is no way to differentiate between them. 

I'd expect the Retry class to accept additional parameter 'timeout' that let's you specify how many retries due to timeouts you accept. So for example:
`Retry(read=4, timeout=0)` would retry only on http status errors, but it wouldn't on timeouts. 

### Alternative
Currently my hacky, ugly workaround is to overload `_is_read_error` method
```python
class DoNotRetryOnTimeout(Retry):
    def _is_read_error(self, err):
        return isinstance(err, ProtocolError)

retry = DoNotRetryOnTimeout(
    total=5,
    other=0,
)
```

### Contribution

I can submit PR for that.

**Comment by sethmlarson** [comment]
For customized retry behavior we recommend disabling our automatic retries and using a library like "tenacity" to implement the retry behavior you're interested in.
