### ISSUE TITLE
is_time_off warning on __del__ event

### ISSUE THREAD

**Issue by liRONCO11** [urllib3/urllib3#2607]
### Context

I'm trying to use urllib3 on ```__del__``` event
```
is_time_off = datetime.date.today() < RECENT_DATE
if is_time_off:
    warnings.warn(
        (
            "System time is way off (before {0}). This will probably "
            "lead to SSL verification errors"
        ).format(RECENT_DATE),
        SystemTimeWarning,
    )
```
Can we make that warn check optional?
currently throws [Python ImportError: sys.meta_path is None, Python is likely shutting down](https://stackoverflow.com/questions/72238460/python-importerror-sys-meta-path-is-none-python-is-likely-shutting-down)

### Alternatives

Find another package that doesn't try to get today's date using datetime.date.today()
Fix this part of the code which throws exception in order to warn user..

### Duplicate

I don't think so as it is not best practice to send request on gc time.

### Contribution
I already did but it was closed. maybe with your help we can find a better solution which will be acceptable.
one possibility is to add try-catch over this warning?
Please help,
Thanks.
https://github.com/urllib3/urllib3/issues/2606 https://github.com/urllib3/urllib3/pull/2605 https://github.com/urllib3/urllib3/pull/2608

**Comment by pquentin** [comment]
We already explained you why using urllib3 inside `__del__` is a bad idea: https://github.com/urllib3/urllib3/issues/2606#issuecomment-1125318527. We won't make changes to try supporting it. Please stop!

**Comment by liRONCO11** [comment]
`RECENT_DATE = datetime.date(2020, 7, 1)
is_time_off = datetime.date.today() < RECENT_DATE
if is_time_off:
    warnings.warn(
        (
            "System time is way off (before {0}). This will probably "
            "lead to SSL verification errors"
        ).format(RECENT_DATE),
        SystemTimeWarning,
    )`
Why is that warning so important? how about just removing it?

Please help me find another approach, 
I need to log out automatically when my auth python object is destructed.
Thanks for the quick reply.
