### ISSUE TITLE
PyOpenSSLContext.load_cert_chain raises OpenSSL.SSL.Error unwrapped

### ISSUE THREAD

**Issue by sfreilich** [urllib3/urllib3#2628]
### Subject

PyOpenSSLContext.load_cert_chain raises OpenSSL.SSL.Error instead of the expected c. This causes urllib3 to return OpenSSL.SSL.Error in a situation where the client is looking for urllib3.exceptions.SSLError. (The logic one layer up in urllib3 wraps ssl.SSLError with urllib3.exceptions.SSLError.)

This was discovered due to a failure in this test for pytest_httpbin:
https://github.com/kevin1024/pytest-httpbin/blob/7b0f902822aa1dc698188ac1ceecc7c5207332e4/tests/test_server.py#L46

(Under the hood that's using Requests, which is expecting urllib3.exceptions.SSLError and wrapping that in requests.exceptions.SSLError.)

### Environment

Debian Linux, Python 3.9, urllib built from head

### Steps to Reproduce

I have a patch with a test-case in PR #2627.

### Expected Behavior

The methods of PyOpenSSLContext should consistently wrap OpenSSL.SSL.Error with ssl.SSLError

### Actual Behavior

Many of the methods in that class have that behavior, but load_cert_chain does not.

**Comment by sethmlarson** [comment]
Closed in https://github.com/urllib3/urllib3/pull/2627
