### ISSUE TITLE
urllib3 v2 (unreleased) negotiates the wrong version of TLS when used with OpenSSL 1.0.2

### ISSUE THREAD

**Issue by graingert** [urllib3/urllib3#2636]
### Subject

urllib3 v2 negotiates the wrong version of TLS when used with OpenSSL 1.0.2

Note: I secretly reported this issue, but was asked to make a public issue instead because this is in an unreleased version

### Environment
Python 3.7 on centos 7 dockerfile here: https://gist.github.com/graingert/5013c338991753b059424d1d7a41b875

### Steps to Reproduce

```python
# import tlslite.messages
import sys
import ssl
import concurrent.futures
import socket
import urllib3.util
import pprint
import trustme


ca = trustme.CA()
hostname = "test-host.example.org"
server_cert = ca.issue_cert(hostname)


def client(sock):
    ctx = urllib3.util.create_urllib3_context(ssl_minimum_version=ssl.TLSVersion.TLSv1_2)
    ca.configure_trust(ctx)
    with ctx.wrap_socket(sock, server_hostname=hostname) as ssock:
        print(f"client connection made! ssock.cipher()={ssock.cipher()} ssock.version()={ssock.version()}")
        pass

def server(sock):
    ctx = ssl.create_default_context(purpose=ssl.Purpose.CLIENT_AUTH)
    ctx.minimum_version = ssl.TLSVersion.TLSv1
    ctx.maximum_version = ssl.TLSVersion.TLSv1
    ctx.options |= ssl.OP_NO_TLSv1_2 | ssl.OP_NO_TLSv1_1
    print(ctx.options)
    server_cert.configure_cert(ctx)
    with ctx.wrap_socket(sock, server_side=True) as ssock:
        print(f"server connection made! ssock.cipher()={ssock.cipher()} ssock.version()={ssock.version()}")
        pass


def main():
    with concurrent.futures.ThreadPoolExecutor(max_workers=2) as tpe:
        a, b = socket.socketpair()
        with a, b:
            a.settimeout(1)
            b.settimeout(2)
            client_fut = tpe.submit(client, a)
            server_fut = tpe.submit(server, b)
            for fut in concurrent.futures.as_completed([client_fut, server_fut]):
                fut.result()


if __name__ == "__main__":
    sys.exit(main())

```

### Expected Behavior
```
Traceback (most recent call last):
  File "/home/graingert/projects/py37-old-ssl/demo.py", line 48, in <module>
    sys.exit(main())
  File "/home/graingert/projects/py37-old-ssl/demo.py", line 44, in main
    fut.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/graingert/projects/py37-old-ssl/demo.py", line 30, in server
    with ctx.wrap_socket(sock, server_side=True) as ssock:
  File "/usr/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL] internal error (_ssl.c:997)
```

### Actual Behavior

```
Options.OP_ALL|OP_NO_TLSv1_1|OP_NO_TLSv1_2|OP_NO_SSLv3|OP_NO_SSLv2|OP_CIPHER_SERVER_PREFERENCE|OP_SINGLE_DH_USE|OP_SINGLE_ECDH_USE|OP_NO_COMPRESSION
server connection made! ssock.cipher()=('ECDHE-RSA-AES256-SHA', 'TLSv1/SSLv3', 256) ssock.version()=TLSv1
client connection made! ssock.cipher()=('ECDHE-RSA-AES256-SHA', 'TLSv1/SSLv3', 256) ssock.version()=TLSv1
Removing intermediate container 4123de09e3b3
```

this is because `ssl.SSLContext.minimum_version` is silently ignored in Python3.7 when running on openssl 1.0.2

**Comment by sethmlarson** [comment]
Thanks for opening this @graingert. As we discussed, this isn't a security issue as the code in question hasn't been released. I'll add this to the v2.0 milestone to ensure we don't cut a release without addressing this first.

**Comment by winterqt** [comment]
> What do you think about dropping support for ssl_maximum_version?

This seems reasonable to me, I don't see a (good) reason why a client would want to force a maximum version, if a server supports a version that's >= ssl_minimum_version, anyways.

> And forcing ssl_minimum_version to always be >= 1.2 then this becomes easy to fix

I'm not sure if this is a good idea, though. Wouldn't this break compat with legacy servers unconditionally?

**Comment by sethmlarson** [comment]
I think we should keep `ssl_maximum_version` for now if only to allow pairing with `ssl_minimum_version` to target a specific TLS version.

wrt forcing TLS 1.2+ always, the new default value is `ssl_minimum_version=TLSv1_2` so almost all users will be getting the behavior we desire, I think it's valuable to allow an escape hatch when users are connected to a legacy server.

**Comment by winterqt** [comment]
> I think we should keep `ssl_maximum_version` for now if only to allow pairing with `ssl_minimum_version` to target a specific TLS version.

Doesn't this functionality already exist as `ssl_version`?

**Comment by jschneier** [comment]
Happy to submit a PR to fix this given the prior art of `httpx` linked by @graingert. Is the work to integrate that + test?

Too bad the `HTTPHeaderDict` task was claimed, I believe I am the original author of it (nee `CaseInsensitiveDict` iirc?) heh.

**Comment by graingert** [comment]
Here's my first proposal at building a thing that would work with all versions:

https://gist.github.com/graingert/1e7ecb4e7cecf95972e574b904350515 

The trouble is you can't support flags like `tls_max_version=TLSVersion.MINIMUM_SUPPORTED`

My fix in distributed was possible only because the flags supported are 1.2 and 1.3 https://github.com/dask/distributed/pull/6562

**Comment by graingert** [comment]
> I think we should keep `ssl_maximum_version` for now if only to allow pairing with `ssl_minimum_version` to target a specific TLS version.

I think people needing this option should mutate the SSLcontext themselves rather than use the urllib3 wrapper

**Comment by sethmlarson** [comment]
Now that we've changed https://github.com/urllib3/urllib3/issues/2168 to drop OpenSSL <1.1.1 I'm not sure this will be needed for v2.0.

**Comment by sethmlarson** [comment]
Closing as superseded by https://github.com/urllib3/urllib3/issues/2168.
