### ISSUE TITLE
[FR] Make HTTPHeaderDict support pipe operator

### ISSUE THREAD

**Issue by imba-tjd** [urllib3/urllib3#2641]
### Context

Support https://docs.python.org/3.9/whatsnew/3.9.html#dictionary-merge-update-operators

Currently it says `TypeError: unsupported operand type(s) for |: 'HTTPHeaderDict' and 'dict'`

**Comment by sethmlarson** [comment]
We're actually trying to move away from using `dict`'s write semantics as they unambiguous when it comes to duplicates and multiple values. Given this it's unlikely we'll implement the pipe operator. Instead you should use `.extend()`, `.add()` or `__setitem__`.
