### ISSUE TITLE
HTTPConnection should return urllib3.HTTPResponse instead of http.client.HTTPResponse

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2648]
Part of https://github.com/urllib3/urllib3/issues/1985

Currently our `urllib3.connection.HTTPConnection` classes return directly a `http.client.HTTPResponse`. This ties our APIs directly to `http.client` which isn't desirable for future additions of new HTTP protocol implementations.

Instead our `HTTPConnection` APIs should return an instance of `urllib3.response.HTTPResponse` directly and should be forwarded upwards instead of doing the wrapping inside of `HTTPConnectionPool.urlopen`.

#### Minimum requirements

- [ ] Research and understand which exceptions can be raised at which stage from `HTTPConnection.urlopen` and `HTTPConnection.getresponse` in both urllib3 and http.client. This research should be posted into this issue.
- [ ] Move the wrapping of `http.client.HTTPResponse` from `HTTPConnectionPool` to `HTTPConnection`
- [ ] Update type hints for `HTTPConnection`
- [ ] Add test cases for `HTTPConnection` directly returning a `urllib3.response.HTTPResponse`.
- [ ] Change existing test cases for the new logic.

**Comment by sethmlarson** [comment]
@shadycuz It sounds like you're on the right path!

**Comment by shadycuz** [comment]
@sethmlarson

> Research and understand which exceptions can be raised at which stage from HTTPConnection.urlopen and HTTPConnection.getresponse in both urllib3 and http.client. This research should be posted into this issue.

Do you want this research before or after my refactor? Please don't say both!

**Comment by shadycuz** [comment]
@sethmlarson 

I'm too lazy to do the reaserch on the exceptions... so I spent the entire weekend building tools (yes plural) to do it for me...

```python3
def test_exceptions():

    parser = ParseExceptions()

    parser.process_method(HTTPConnection.getresponse, module=http.client)

    assert parser.visited_nodes == 24489
    print(parser.raw_exceptions)
    print(parser.found_exceptions)
```

The call to `http.client.HTTPConnection.getresponse()` results in 24489 visited AST nodes. It's possible for the following exceptions to be thrown and in this order:

```python3
['ResponseNotReady', 'LineTooLong', 'RemoteDisconnected', 'BadStatusLine', 'BadStatusLine', 'BadStatusLine', 'LineTooLong', 'RemoteDisconnected', 'BadStatusLine', 'BadStatusLine', 'BadStatusLine', 'LineTooLong', 'HTTPException', 'UnknownProtocol', 'LineTooLong', 'HTTPException', 'IncompleteRead', 'LineTooLong', 'EmptyRaise', 'IncompleteRead', 'LineTooLong', 'IncompleteRead', 'IncompleteRead', 'IncompleteRead', 'IncompleteRead', 'LineTooLong', 'EmptyRaise', 'IncompleteRead', 'LineTooLong', 'IncompleteRead', 'IncompleteRead', 'IncompleteRead', 'EmptyRaise', 'IncompleteRead', 'LineTooLong', 'EmptyRaise', 'IncompleteRead', 'LineTooLong', 'IncompleteRead', 'IncompleteRead', 'IncompleteRead', 'LineTooLong', 'EmptyRaise', 'LineTooLong', 'IncompleteRead', 'LineTooLong', 'EmptyRaise', 'IncompleteRead', 'LineTooLong', 'IncompleteRead', 'LineTooLong', 'EmptyRaise', 'IncompleteRead', 'LineTooLong', 'IncompleteRead', 'IncompleteRead', 'IncompleteRead', 'LineTooLong', 'EmptyRaise', 'IncompleteRead', 'LineTooLong', 'IncompleteRead', 'IncompleteRead', 'IncompleteRead', 'IncompleteRead', 'IncompleteRead', 'IncompleteRead', 'LineTooLong', 'EmptyRaise', 'IncompleteRead', 'LineTooLong', 'IncompleteRead', 'IncompleteRead', 'LineTooLong', 'EmptyRaise', 'IncompleteRead', 'LineTooLong', 'IncompleteRead', 'LineTooLong', 'EmptyRaise', 'IncompleteRead', 'LineTooLong', 'IncompleteRead', 'IncompleteRead', 'LineTooLong', 'EmptyRaise', 'IncompleteRead', 'LineTooLong', 'ResponseNotReady', 'ResponseNotReady', 'LineTooLong', 'RemoteDisconnected', 'BadStatusLine', 'BadStatusLine', 'BadStatusLine', 'LineTooLong', 'RemoteDisconnected', 'BadStatusLine', 'BadStatusLine', 'BadStatusLine', 'LineTooLong', 'HTTPException', 'UnknownProtocol', 'LineTooLong', 'HTTPException', 'IncompleteRead', 'LineTooLong', 'EmptyRaise', 'IncompleteRead', 'LineTooLong', 'IncompleteRead', 'IncompleteRead', 'IncompleteRead', 'IncompleteRead', 'LineTooLong', 'EmptyRaise', 'IncompleteRead', 'LineTooLong', 'IncompleteRead', 'IncompleteRead', 'IncompleteRead', 'EmptyRaise', 'IncompleteRead', 'LineTooLong', 'EmptyRaise', 'IncompleteRead', 'LineTooLong', 'IncompleteRead', 'IncompleteRead', 'IncompleteRead', 'LineTooLong', 'EmptyRaise', 'LineTooLong', 'IncompleteRead', 'LineTooLong', 'EmptyRaise', 'IncompleteRead', 'LineTooLong', 'IncompleteRead', 'LineTooLong', 'EmptyRaise', 'IncompleteRead', 'LineTooLong', 'IncompleteRead', 'IncompleteRead', 'IncompleteRead', 'LineTooLong', 'EmptyRaise', 'IncompleteRead', 'LineTooLong', 'IncompleteRead', 'IncompleteRead', 'IncompleteRead', 'IncompleteRead', 'IncompleteRead', 'IncompleteRead', 'LineTooLong', 'EmptyRaise', 'IncompleteRead', 'LineTooLong', 'IncompleteRead', 'IncompleteRead', 'LineTooLong', 'EmptyRaise', 'IncompleteRead', 'LineTooLong', 'IncompleteRead', 'LineTooLong', 'EmptyRaise', 'IncompleteRead', 'LineTooLong', 'IncompleteRead', 'IncompleteRead', 'LineTooLong', 'EmptyRaise', 'IncompleteRead', 'LineTooLong', 'ResponseNotReady', 'ResponseNotReady', 'EmptyRaise', 'EmptyRaise']
```

The unique exceptions are:
```python3
['ResponseNotReady', 'LineTooLong', 'RemoteDisconnected', 'BadStatusLine', 'HTTPException', 'UnknownProtocol', 'IncompleteRead', 'EmptyRaise']
```
The `EmptyRaise` is a bug from:

```python3
except SomeException:
  # do something
  raise
```

I'm working on fixing that bug and another with `super()`.

**Comment by shadycuz** [comment]
I think super is mostly fixed? I can't remember. Still need to fix the bare raise bug. I did publish the first tool [Deep-AST](https://github.com/DontShaveTheYak/deep-ast) that makes it possible to parse all callable code. 

I plan on releasing a second tool that will address the bug in the bare raise.
