### ISSUE TITLE
Problem with urllib3.HTTPResponse.geturl() type hint

### ISSUE THREAD

**Issue by salahbsmdz** [urllib3/urllib3#2654]
### Subject

Why the return type hint for `urllib3.response.BaseHTTPResponse.geturl()` is `Optional[Union[str, "Literal[False]"]]` but not `Optional[str]` ?

**Comment by hramezani** [comment]
Fixed by https://github.com/urllib3/urllib3/commit/ff402b824d5c35325625c4abfdcdf584ee3f3cb5
