### ISSUE TITLE
requests dependency for gdata and pandas 

### ISSUE THREAD

**Issue by jannielove** [urllib3/urllib3#2668]
this error return in pycharm CE i tried a few work arounds to no avail. any ideas?
requests 2.21.0 requires urllib3<1.25,>=1.21.1, but you have urllib3 1.26.9 which is incompatible.

**Comment by pquentin** [comment]
The urllib3 issue tracker is meant for urllib3 bugs, not general questions about using pip, so I'll have to close this, sorry.

See https://pip.pypa.io/en/stable/topics/dependency-resolution/#dealing-with-dependency-conflicts for more details about this issue.
