### ISSUE TITLE
document `sigstore verify` workflow

### ISSUE THREAD

**Issue by graingert** [urllib3/urllib3#2675]
the current documentation here https://twitter.com/sethmlarson/status/1545072787638870023 is missing the "--cert-email" flag and so would allow anyone with github OIDC to forge a urllib3 wheel

**Comment by sobelek** [comment]
@graingert Like to twitter seems not working

**Comment by graingert** [comment]
You'll need to join my discord and I'll like anything you want on Twitter

**Comment by sobelek** [comment]
oppsie. I mean 'link' from issue is not working

**Comment by pquentin** [comment]
Closing as urllib3 no longer uses sigstore: https://github.com/urllib3/urllib3/pull/2716

**Comment by graingert** [comment]
This is getting fixed directly in truststore
