### ISSUE TITLE
httpx how to add openssl parameters --groups X25519

### ISSUE THREAD

**Issue by nmweizi** [urllib3/urllib3#2677]
- https://kjt.hebei.gov.cn/ need to use parameters --groups X25519 to be able to connect ssl.
- example
   openssl s_client -connect kjt.hebei.gov.cn:443 --state **--groups X25519**
- urllib3 how to add openssl parameters **--groups X25519**

**Comment by sethmlarson** [comment]
There's no native urllib3 parameter for configuring your curve, but there may be for Python's `SSLContext` if I remember correctly? You can pass a configured SSLContext object via the `ssl_context` parameter to urllib3:

```python
import urllib3

http = urllib3.PoolManager(ssl_context=...)
http.request("GET", "https://...")
```

Hope this helps!

**Comment by nmweizi** [comment]
@sethmlarson thx

```
from urllib3.util.ssl_ import create_urllib3_context
ssl_context = create_urllib3_context()
ssl_context.set_ecdh_curve('X25519')
```

```
---------------------------------------------------------------------------
SSLError                                  Traceback (most recent call last)
Input In [8], in <cell line: 1>()
----> 1 ssl_context.set_ecdh_curve('X25519')

SSLError: [EC: UNKNOWN_GROUP] unknown group (_ssl.c:4342)
```

**Comment by sigmavirus24** [comment]
The openssl your python is linked against doesn't support the curve you require.
