### ISSUE TITLE
docs should mention Python 3.6 support was removed

### ISSUE THREAD

**Issue by kenyee** [urllib3/urllib3#2690]
### Subject

The last update mentioned only Python 3.5 support was removed, but it's actually Python 3.6 that was removed because of:

urllib3/_collections.py:16, <module>
      from typing import OrderedDict as OrderedDictType

From https://docs.python.org/3/library/typing.html
class typing.OrderedDict(collections.OrderedDict, MutableMapping[KT, VT])
A generic version of [collections.OrderedDict](https://docs.python.org/3/library/collections.html#collections.OrderedDict).

New in version 3.7.2.

Deprecated since version 3.9: [collections.OrderedDict](https://docs.python.org/3/library/collections.html#collections.OrderedDict) now supports []. See [PEP 585](https://www.python.org/dev/peps/pep-0585) and [Generic Alias Type](https://docs.python.org/3/library/stdtypes.html#types-genericalias).

### Environment

Describe your environment.
print("OS", platform.platform())
OS Darwin-21.6.0-x86_64-i386-64bit
>>> print("Python", platform.python_version())
Python 3.6.4

### Steps to Reproduce

Try using latest urllib3 in python 3.6

### Expected Behavior

Error should not happen if only Python 3.5 is not supported

### Actual Behavior

see description above

**Comment by hramezani** [comment]
Actually, we are preparing urllib3 for version 2 and the code that you tested is from [main](https://github.com/urllib3/urllib3).
We've dropped Python3.6 from main.

On the other hand, we are still updating [1.26.x](https://github.com/urllib3/urllib3/tree/1.26.x). The latest release was `1.26.11`. And we support Python3.6 on `1.26.x`

**Comment by kenyee** [comment]
ahh...thanks for the clarification :-)
