### ISSUE TITLE
Add deprecation warnings for urllib3.contrib.pyopenssl

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2691]
#### Minimum requirements

- [x] Create a newsfragment about the deprecation
- [x] Add deprecation warning section to the pyOpenSSL docs
- [x] Emit a `DeprecationWarning` for urllib3's pyOpenSSL support when importing the `urllib3.contrib.pyopenssl` module. The deprecation should point to the new docs.
- [x] Add the `urllib3-secure-extra` dependency to the `secure` extra
- [x] Emit a `DeprecationWarning` for `urllib3[secure]` when it's detected that the `urllib3-secure-extra` package is importable. The deprecation should point to the new docs.
- [x] Find all issues in the issue tracker about pyOpenSSL and put them in this issue to be closed.

Part of: https://github.com/urllib3/urllib3/issues/2680

**Comment by IvanLauLinTiong** [comment]
Hi @sethmlarson,  quick question for task 5: 
``Emit a DeprecationWarning for urllib3[secure] when it's detected that the urllib3-secure-extra package is importable. The deprecation should point to the new docs.``

Perhaps I miss out something, but I don't see the `urllib3-secure-extra` package resides here. Thus how do I add the `warnings.warn()`  method on the file ?

**Comment by sethmlarson** [comment]
@IvanLauLinTiong I uploaded the package `urllib3-secure-extra` to PyPI not long ago: https://pypi.org/project/urllib3-secure-extra

You'd add this package to our `[secure]` extra and then if it's importable (via `import urllib3_secure_extra`) then you know that the `[secure]` extra was used somewhere.

**Comment by IvanLauLinTiong** [comment]
> @IvanLauLinTiong I uploaded the package `urllib3-secure-extra` to PyPI not long ago: https://pypi.org/project/urllib3-secure-extra
> 
> You'd add this package to our `[secure]` extra and then if it's importable (via `import urllib3_secure_extra`) then you know that the `[secure]` extra was used somewhere.

Hi @sethmlarson,  I managed to add `urllib3-secure-extra` to `secure` extra under `pyproject.toml`. However, I don't understand, how could we yank `urllib3-secure-extra` with the `DeprecationWarning` message if we  `import urllib3_secure_extra` ?  That's because from file `urllib3_secure_extra.py` it does not have `warnings.warn()` implemented or does it?:
![image](https://user-images.githubusercontent.com/23013350/182911748-0cb92f0c-6b3d-4ad6-8c39-170626fefd50.png)

Did I miss out something I don't know? :)

**Comment by sethmlarson** [comment]
@IvanLauLinTiong We wouldn't yank the package, it would only serve as a marker to show that the `[secure]` extra was installed. Instead of the warning being inside of `urllib3_secure_extra` module we'd have something like this within `urllib3/__init__.py`:

```python
try:
    import urllib3_secure_extra
except ImportError:
    pass
else:
    warnings.warn("The urllib3[secure] extra is deprecated ...")
```

Let me know if this makes sense. Thanks for looking into this!

**Comment by IvanLauLinTiong** [comment]
@sethmlarson  I never thought that we can do it in this try-catch testing way.. Thanks for the pointer.

**Comment by IvanLauLinTiong** [comment]
All issues in the issue tracker about pyOpenSSL:
- #2168
- #1885 
- #1768 
- #1071
- #892 
- #855 
- #590 
- #367

**Comment by sethmlarson** [comment]
Thanks @IvanLauLinTiong! I'll look to close these issues if they're no longer necessary.

**Comment by graingert** [comment]
> ```python
> ImportError
> ```

ModuleNotFoundError

**Comment by graingert** [comment]
> We wouldn't yank the package

Why not?

**Comment by sethmlarson** [comment]
Because that would break old versions' reproducibility unnecessarily? The break can happen at the time the actual code  and extra are removed just as well.

**Comment by graingert** [comment]
> break old versions' reproducibility unnecessarily

A yank isn't supposed to do that

**Comment by sethmlarson** [comment]
Yanks won't break if you're installing via `urllib3_secure_extra==...` but that's not how the `[secure]` extra depends on the package. So if someone was installing via `python -m pip install urllib3[secure]` (or more likely, was installing a package that had `install_requires=["urllib3[secure]"]` they would start seeing an error if we were to yank.

**Comment by graingert** [comment]
Ah I see, I hadn't thought about it that way. I still think you should yank it one day

looking at pypistats will inform what to do, eg you could yank it on Fridays and unyank it on Mondays

**Comment by sethmlarson** [comment]
Closed in https://github.com/urllib3/urllib3/pull/2701 and https://github.com/urllib3/urllib3/pull/2713.
