### ISSUE TITLE
ProxyManager has memory leak

### ISSUE THREAD

**Issue by jeff-xiao-2021** [urllib3/urllib3#2694]
hi, all. I find a bug in urllib3. When I use ProxyManager, I find my application memory leak. how to solve it? thanks.
Do i need close or release ProxyManager?

**Comment by sethmlarson** [comment]
You're going to have to provide a lot more context, otherwise we can't help solve your problem. Things like Python version, urllib3 version, example code you're using, etc. Since you haven't followed the template I'm going to close this issue, if you provide the information requested we can reopen.
