### ISSUE TITLE
Notify packages using urllib3[secure] about it's deprecation

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2700]
:dollar: **You can get paid to complete this issue! [Please read the docs for more information](https://urllib3.readthedocs.io/en/latest/contributing.html#getting-paid-for-your-contributions).**

### Packages to notify

- [x] selenium
- [x] scout-apm
- [x] cpp-coveralls
- [x] sentry
- [x] awscurl
- [x] mastercard-api-core
- [x] mastercard-oauth1-signer
- [x] cloud-files
- [x] google-assistant-sdk
- [x] minet
- [x] cloud-volume
- [x] azure-cli-appservice
- [x] runway-python
- [x] lyricsmaster
- [x] pyramid-oereb
- [x] flexmeasures
- [x] optimove
- [x] comet-git-pure

### What to do for each package

- Find the source repository (GitHub/GitLab/BitBucket/etc)
- Create a PR which includes the following:
  - Mentions that pyOpenSSL and urllib3[secure] are deprecated in the upcoming release (1.26.12)
  - Links to https://github.com/urllib3/urllib3/issues/2680
  - Removes `[secure]` extra from the `urllib3` dependencies
  - If needed, add `pyOpenSSL>=0.14`, `cryptography>=1.3.4`, `idna>=2`, and `certifi` to their dependencies. These dependencies should only be added back if they're actually used within the project. If they're not used (including `pyopenssl.inject_into_urllib3`) then they can likely be omitted.
  - If `urllib3.contrib.pyopenssl.inject_into_urllib3` is used anywhere in the project (search for `inject_into_urllib3`) then make the change to the following:

    ```python
    try:
        import ssl
    except ImportError:
        ssl = None
    
    if not getattr(ssl, "HAS_SNI", False):
        from urllib3.contrib import pyopenssl
    
        pyopenssl.inject_into_urllib3()
    ```

    This is the logic that is [used in Requests](https://github.com/psf/requests/blob/main/requests/__init__.py) to only use pyOpenSSL if SNI isn't available (which is very rare).
- After creating each PR, add it as a comment to this issue. 

PRs don't need to be merged to complete this issue, we only want to create the PRs so that maintainers of these projects are aware of the upcoming changes.

Part of https://github.com/urllib3/urllib3/issues/2680

**Comment by umarfarouk98** [comment]
Created a Pull Request to https://github.com/scoutapp/scout_apm_python
https://github.com/scoutapp/scout_apm_python/pull/746

**Comment by umarfarouk98** [comment]
###Created a Pull Request to Selenium
https://github.com/SeleniumHQ/selenium/pull/10932

**Comment by umarfarouk98** [comment]
Created a Pull Request to cpp-coveralls
https://github.com/eddyxu/cpp-coveralls/pull/166

**Comment by pquentin** [comment]
@umarfarouk98 Make sure to only remove `[secure]`, not the whole urllib3 dependency!

**Comment by umarfarouk98** [comment]
Yes i only removed secure and other modules aren't tampered with

**Comment by pquentin** [comment]
The current diff for cpp-coveralls look like this:

```diff
  idna>=2.5,<3
  requests>=2.25.1
- urllib3[secure]
  future
```

This means urllib3 will not be installed at all. Instead it should like this:

```diff
  idna>=2.5,<3
  requests>=2.25.1
- urllib3[secure]
+ urllib3
  future
```

**Comment by sethmlarson** [comment]
When you're making changes you should start with `urllib3[secure] ` and should only remove the `[secure]` part, meaning `urllib3` and any version information will still be there.

Example: `urllib3[secure]>=1.26, <2` should get changed to `urllib3>=1.26, <2`

Also if urllib3 1.25.x or earlier is being installed you can leave the [secure] for those cases like scout_apm.

Can you fix your earlier PRs?

**Comment by umarfarouk98** [comment]
noted, currently on it

**Comment by umarfarouk98** [comment]
Created a Pull Request to mastercard-oauth1-signer
https://github.com/Mastercard/oauth1-signer-python/pull/41

**Comment by umarfarouk98** [comment]
Created a Pull Request to cloud-files
https://github.com/seung-lab/cloud-files/pull/77

**Comment by umarfarouk98** [comment]
Created a Pull Request to minet
https://github.com/medialab/minet/pull/446

**Comment by umarfarouk98** [comment]
Created a Pull Request to cloud-volume
https://github.com/seung-lab/cloud-volume/pull/552

**Comment by umarfarouk98** [comment]
Hi @sethmlarson the runway-python repo is in archive already.
<img width="1280" alt="Screenshot 2022-08-10 at 2 14 25 PM" src="https://user-images.githubusercontent.com/55334829/183910711-4d0f61d1-a718-466c-b6e1-89199a340420.png">

**Comment by umarfarouk98** [comment]
Created a Pull Request to azure-cli
https://github.com/Azure/azure-cli/pull/23494

**Comment by umarfarouk98** [comment]
Created a Pull Request to lyricsmaster
https://github.com/SekouD/lyricsmaster/pull/1094

**Comment by sethmlarson** [comment]
@umarfarouk98 FYI, you need to also be checking for `inject_into_urllib3` and do the other parts of this task if that's present, not only removing `[secure]`. For example in azure-cli `inject_into_urllib3` is present:

https://github.com/Azure/azure-cli/search?q=inject_into_urllib3

**Comment by umarfarouk98** [comment]
ok i'll work on that now @sethmlarson

**Comment by umarfarouk98** [comment]
modified inject_into_urllib3()
tunnel.py and custom.py azure-cli

**Comment by umarfarouk98** [comment]
Created Pull Request to pyramid-oereb
https://github.com/openoereb/pyramid_oereb/pull/1598

**Comment by umarfarouk98** [comment]
Created Pull Request to flexmeasures
https://github.com/FlexMeasures/flexmeasures/pull/473

**Comment by umarfarouk98** [comment]
Created Pull Request to optimove
https://github.com/nicolasramy/optimove/pull/19
No "inject_into_urllib3()" used

**Comment by umarfarouk98** [comment]
Created Pull Request to awscurl
https://github.com/okigan/awscurl/pull/145
No "inject_into_urllib3()" used

**Comment by umarfarouk98** [comment]
Hi @sethmlarson 
sentry doesn't seem to use the [secure] extra for urllib3
https://github.com/getsentry/sentry-python/

**Comment by umarfarouk98** [comment]
Created Pull Request to google-assistant-sdk
No "inject_into_urllib3()" used
https://github.com/googlesamples/assistant-sdk-python/pull/441

**Comment by umarfarouk98** [comment]
Created Pull Request to mastercard-api-core
https://github.com/mfuery/mastercard-core-api-python/pull/2
No "inject_into_urllib3()" used

**Comment by umarfarouk98** [comment]
Hi @sethmlarson please could you point me to the comet-git-pure repo.
finding it hard to locate

**Comment by sethmlarson** [comment]
@umarfarouk98 If you can't locate the repo that's fine, I also can't find it so we tried our best :)

For the PRs that require a CLA like azure-cli and the Google Assistant one can you sign the CLA so the PR can be accepted? Thanks!

**Comment by umarfarouk98** [comment]
@sethmlarson think this might be it, not sure but i created a PR to it 
https://github.com/comet-ml/dulwich/pull/1

**Comment by umarfarouk98** [comment]
Also i've signed the CLA for both azure and the google assistant-sdk

**Comment by pquentin** [comment]
> sentry doesn't seem to use the [secure] extra for urllib3 https://github.com/getsentry/sentry-python/

https://pypi.org/project/sentry/ on PyPI is the Sentry *server*, whose repo is https://github.com/getsentry/sentry. They don't require `[secure]` in their direct dependencies, but they depend on Selenium. So there's nothing to do yet.

> @sethmlarson think this might be it, not sure but i created a PR to it [comet-ml/dulwich#1](https://github.com/comet-ml/dulwich/pull/1)

This is only a fork, I think upstream is https://github.com/jelmer/dulwich. It has active pull requests. Can you please open a pull request there instead?

**Comment by umarfarouk98** [comment]
ok will create the pull request to  https://github.com/jelmer/dulwich. now

**Comment by umarfarouk98** [comment]
create the pull request to  jelmer/dulwich
https://github.com/jelmer/dulwich/pull/998
No "inject_into_urllib3()" used

**Comment by umarfarouk98** [comment]
Hi @sethmlarson  @pquentin is there anything left for me to do ?

**Comment by sethmlarson** [comment]
@umarfarouk98 Let me run one more query to make sure we've got all the packages in the list. I'll let you know by the end of the day if there's any more work to do.

Thanks for all your work so far!

**Comment by sethmlarson** [comment]
@umarfarouk98 Okay I checked the list again and it looks like every package is covered, thank you for doing this. You can submit the invoice to the Open Collective for $300.

I just ask that you don't close the PRs you've opened so the maintainers of those repositories can see them and if you have any time to get them across the finish line it'd be appreciated but not necessary to be paid for the work you've already done. Thanks much!

**Comment by umarfarouk98** [comment]
OK @sethmlarson thanks to you too, I'll try to do a follow up on the PRs also.
