### ISSUE TITLE
v2 and psf requests

### ISSUE THREAD

**Issue by achapkowski** [urllib3/urllib3#2704]
I hope this is the best place to ask this, but with v2 getting closer to release, is the urllib3 team working with the `requests` team to sync up the breaking changes?  I know they are different packages, but they do go hand in hand.

thanks

**Comment by sethmlarson** [comment]
Great question. We run the test suites of our two biggest dependencies (Requests and botocore) on each PR against the `main` branch: https://github.com/urllib3/urllib3/blob/main/.github/workflows/integration.yml

Does this answer your question?

**Comment by achapkowski** [comment]
@sethmlarson yes thank you!
