### ISSUE TITLE
`format` session fail to run locally on Window platform

### ISSUE THREAD

**Issue by IvanLauLinTiong** [urllib3/urllib3#2709]
### Subject
When I ran `nox -rs format` to format the files,  the format process terminates due to `FileNotFoundError` reported at line 139 at file `noxfile.py`:

![image](https://user-images.githubusercontent.com/23013350/184066564-3a322445-c7b8-48ba-8ee9-4e747e964037.png)

### Environment
Window 10

### Steps to Reproduce
Just ran `nox -rs format` on Window machine.

I suspect the created `process` could not find the files properly, and my workaround is to using `session.run()` instead:
```python
@nox.session()
def format(session: nox.Session) -> None:
    """Run code formatters."""
    session.install("pre-commit")
    session.run("pre-commit", "--version")

    # process = subprocess.run(
    #     ["pre-commit", "run", "--all-files"],
    #     env=session.env,
    #     text=True,
    #     stdout=subprocess.PIPE,
    #     stderr=subprocess.STDOUT,
    # )
    # # Ensure that pre-commit itself ran successfully
    # assert process.returncode in (0, 1)

    session.run("pre-commit", "run", "--all-files") # my workaround

    lint(session)
```

Perhaps this failure is due to my improper environment setup for the repo. If so, please correct me.

Thanks.

**Comment by pquentin** [comment]
Nice catch! Actually we can completely remove the call to `pre-commit run --all-files` in `format()`, since `lint()` calls it already. Can you please open a pull request to do that?

**Comment by IvanLauLinTiong** [comment]
@pquentin 
Ya, It seems the `lint()` calls it already. I can create the PR for that.  

Before this, my another question is: what's the difference between `format()` and `lint()`?  From the code, they seems doing the same thing. Can we completely remove  `format()` function from the file  or we might add on something in this function in the future?

**Comment by pquentin** [comment]
We're using pre-commit right now, and indeed it's good practice with pre-commit to have a single command to lint and format. That way when `git commit` fails you can simply apply the resulting fixes. So we could change the body of `format()` to just call `lint()`.

Why keep `format()`, then? Four reasons:

 * `nox -rs format` is more explicit, we don't have to mention to contributors that `nox -rs lint` formats too
 * `nox -rs format` is muscle memory at this point for at least Seth and I
 * if we move to something else where `format()` and `lint()` are indeed different we'll be glad to have kept it (and yes, we tend to update our tooling a lot)
 * it allows us to optimize `format`: it could only call `black`, `pyupgrade` and `isort` and not flake8 or mypy.

**Comment by IvanLauLinTiong** [comment]
@pquentin 
I see. thanks for the explanation :)
