### ISSUE TITLE
HTTPResponse does not support "seek"

### ISSUE THREAD

**Issue by ycwang-hello** [urllib3/urllib3#2710]
I want to read only part of a very large hdf5 file on the Internet (the file is too large so I don't want to get the full content):
```Python
http = urllib3.PoolManager()
r = http.request(
    'GET',
    '...', # url of the hdf5 file
    preload_content=False)
h5py.File(r) # or simply run r.seek()
```
However, an exception occurred:
```
UnsupportedOperation: seek
```
It seems that `urllib3.response.HTTPResponse` does not support the `seek` method, so it is somewhat different from a file-like object. But `h5py.File` seems to need `seek()`. 

Is it possible to support `seek()`, or are there alternative ways to do it? Sorry if I'm asking this question in the wrong place...

**Comment by pquentin** [comment]
It's not possible to support seek with streaming downloads: `HTTPResponse` with `preload_content=False` only supports reading more data. To support seek we would have to keep data in memory.

**Comment by mullenkamp** [comment]
Just for reference, you can use io.BufferedReader with the HTTPResponse from urllib3 to "enable" seek as subtly shown in the docs:
https://urllib3.readthedocs.io/en/stable/advanced-usage.html#streaming-and-i-o

This does buffer everything that is read into memory though.

For the OP's use case, you should probably just write the file to disk (iteratively as the file might be really large) then pass the new file name to h5py.
