### ISSUE TITLE
Handle '0' Value in Retry-After Header

### ISSUE THREAD

**Issue by moseswynn** [urllib3/urllib3#2718]
### Context

What are you trying to do?
_Optionally specify an overriding duration in the instance that the Retry-After header is '0' in `utils.Retry`._

How do you expect to do it?
_Add an optional parameter called `retry_after_replace_zero` to the class and update the `Retry.parse_retry_after` method to handle if this parameter is set._

Is it something you currently cannot do?
_I don't think so._

Is this related to an existing issue/problem?
_No_

### Alternatives

Can you achieve the same result doing it in an alternative way?
_Not currently._

Is the alternative considerable?

### Duplicate

Has the feature been requested before?
If so, please provide a link to the issue.
_I don't think so._

### Contribution

Would you be willing to submit a PR?
_(Help can be provided if you need assistance submitting a PR)_
Yes

**Comment by sethmlarson** [comment]
Reason for closing is summarized in this comment: https://github.com/urllib3/urllib3/pull/2719#issuecomment-1221424364
