### ISSUE TITLE
Weird delay caused by {method 'recv_into' of '_socket.socket' objects}

### ISSUE THREAD

**Issue by robd003** [urllib3/urllib3#2741]
### Subject

When executing requests it looks like there is a several second arbitrary delay caused by `{method 'recv_into' of '_socket.socket' objects}`

### Environment

Describe your environment.
At least, paste here the output of:

```
OS Linux-5.15.0-1020-aws-aarch64-with-glibc2.35
Python 3.10.6
urllib3 1.26.12
```

### Steps to Reproduce

Connecting to a webserver running on localhost and do an HTTP POST that takes ~200ms to process. However there is a 2.5+ second delay.

I'm doing this with the most basic urllib3 use case possible:

```
import urllib3
from urllib3.connection import HTTPConnection

data = {
    'a': 'thing',
    'another': 'item'
}

socket_opts = HTTPConnection.default_socket_options + [(socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1)]

conn = connection_from_url('http://127.0.0.1:4200/', socket_options=socket_opts)
r = conn.request('POST', '/test', fields=data)
```

### Expected Behavior

As soon as the server returns 200 OK urllib3 should return control.

### Actual Behavior

As stated before, there's a 2.5+ second delay from `{method 'recv_into' of '_socket.socket' objects}` for no apparent reason.

cProfile output:

```
         3834 function calls (3598 primitive calls) in 2.742 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    2.742    2.742 <string>:1(execute)
        1    0.000    0.000    2.736    2.736 /home/robd003/slow-urllib3-test/env/lib/python3.10/site-packages/urllib3/connectionpool.py:522(urlopen)
        1    0.000    0.000    2.736    2.736 /home/robd003/slow-urllib3-test/env/lib/python3.10/site-packages/urllib3/connectionpool.py:361(_make_request)
        1    0.000    0.000    2.735    2.735 /usr/lib/python3.10/http/client.py:1330(getresponse)
        1    0.000    0.000    2.735    2.735 /usr/lib/python3.10/http/client.py:311(begin)
        1    0.000    0.000    2.735    2.735 /usr/lib/python3.10/http/client.py:278(_read_status)
        4    0.000    0.000    2.735    0.684 {method 'readline' of '_io.BufferedReader' objects}
        1    0.000    0.000    2.735    2.735 /usr/lib/python3.10/socket.py:691(readinto)
        1    2.735    2.735    2.735    2.735 {method 'recv_into' of '_socket.socket' objects}
       15    0.001    0.000    0.001    0.000 {built-in method builtins.exec}
       46    0.000    0.000    0.001    0.000 {method 'join' of 'str' objects}
```

**Comment by pquentin** [comment]
Can you please try to capture packets using Wireshark and send that to us? We don't have a hidden `time.sleep(2.5)` call :) So it's not clear if this an urllib3 issue.

You could also try reproducing using https://docs.python.org/3/library/http.client.html which urllib3 uses under the hood.

**Comment by sethmlarson** [comment]
Closing this as we can't make a determination without further information on trying to reproduce with http.client and a packet capture. I'm almost positive this isn't an issue with urllib3 specifically.
