### ISSUE TITLE
Unexpected urllib parse result

### ISSUE THREAD

**Issue by planetA** [urllib3/urllib3#2746]
### Subject

I parse an IP address with port to get a url, but `ParseResult` does not look right.

### Environment

Describe your environment.
At least, paste here the output of:

```python
OS Linux-5.10.0-17-amd64-x86_64-with-glibc2.31
>>> print("Python", platform.python_version())
Python 3.9.2
>>> print("urllib3", urllib3.__version__)
urllib3 1.26.12
```

### Steps to Reproduce

```python
from urllib.parse import urlparse
urlparse('192.168.1.132:16992')
```

### Expected Behavior

```
ParseResult(scheme='', netloc='192.168.1.132:16992', path='', params='', query='', fragment='')
```

### Actual Behavior

```
ParseResult(scheme='192.168.1.132', netloc='', path='16992', params='', query='', fragment='')
```

I guess scheme should not be an IP address

**Comment by pquentin** [comment]
We're urllib3, not urllib. I know, it's confusing! Consider submitting a bug to python/cpython instead.

**Comment by pquentin** [comment]
However I don't think it's a bug, your URL should have a scheme.

**Comment by planetA** [comment]
I still resubmitted, but probably you are right. https://www.rfc-editor.org/rfc/rfc1738#section-2.1 seems to allow scheme to look like an IP address 🤷
