### ISSUE TITLE
Move pytest, isort and mypy configuration from setup.cfg to pyproject.toml

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#2773]
What the title says. Now that we have a pyproject.toml, we should strive to use it as our only configuration file. Annoyingly, flake8 [refuses supporting pyproject.toml](https://github.com/PyCQA/flake8/issues/234), but we should still migrate the others.

**Comment by hugovk** [comment]
Some useful tools for this:

* https://github.com/abravalheri/ini2toml to convert `setup.cfg` to `pyproject.toml` (but watch out for https://github.com/abravalheri/ini2toml/issues/50)

* https://github.com/abravalheri/validate-pyproject to check the output

* https://github.com/tox-dev/pyproject-fmt/ to apply a consistent format

The validator and formatter have a pre-commits hook in case you want to put them in `.pre-commit-config.yaml`.
