### ISSUE TITLE
Change deprecation warnings from "in a future version" to "in v2.1.0"

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2781]
Currently we have a bunch of `DeprecationWarnings` being emitted that use similar phrasing: don't do X, it's deprecated and will be removed in a future version". The last part: "in a future version" isn't concrete enough, users might be tempted to do nothing and see how long they can get away with it.

Instead @pquentin and I propose a more explicit timeline: deprecated features will be removed in v2.1.0 which assuming we release the first alpha of 2.0.0 in the next few days will come sometime in the spring or summer of 2023. We suggest this more aggressive timeline as the most impactful deprecated features have been deprecated for almost 2 years which is way more than enough advance warning.

What that means for 2.0.0:

- Find all deprecation warnings in `main` and `1.26.x` and update them to the new messaging.
- Make a release of 1.26.x if needed.
- Update documentation with this new timeline.

**Comment by hugovk** [comment]
For extra visibility, consider documenting these on a single page, like:

* https://docs.pytest.org/en/7.2.x/deprecations.html#deprecations
* https://pillow.readthedocs.io/en/stable/deprecations.html

I find these useful both as a user and a maintainer.

**Comment by sethmlarson** [comment]
Thanks for the suggestion @hugovk! I like the long form rationale.
