### ISSUE TITLE
Enhance the urllib3 developer experience

### ISSUE THREAD

**Issue by shadycuz** [urllib3/urllib3#2782]
### Context

I would like to make it easier for people to contribute to `urlib3`. 

I would like to start with the following:
- Add a contributors guide to the repository
 - Add a [vscode devcontainer](https://code.visualstudio.com/docs/devcontainers/containers) to be able to run most of the checks that we do in GitHub actions. That means being able to do the following:
   - Install the correct python versions
   - Install and setup pre-commit
   - Install and configure nox
- Add vscode settings to the repository. This will allow vscode users to have code formatting, linting and import sorting while they are writing code. This is a nicer experience than writing a bunch of code, trying to commit and having pre-commit reject it.

I already have completed some of this work for when I submitted #2649, I just need to clean it up and submit a PR.

I found getting started with contributing to `urllib3` was harder than my usual experience with open-source projects and I think lowering the barrier to entry would be impactful for this project.

I know lots of these features are specific to vscode, but they would not hinder non-vscode users from contributing. I think it would still help non-vscode users because we can point them to the vscode settings in this repo that show what tooling is being used and with what settings. They can use that as a reference to set up their preferred editor/IDE. I will also make sure to have something in the contributing guide for non-vscode users.

### Alternatives

I think we can do nothing but I know `urllib3` is trying to attract contributors.

### Contribution

I have everything ready to go. Just need to clean up some stuff.

**Comment by sethmlarson** [comment]
Still interested in bolstering our contributors guide, would love to see more there.

**Comment by sethmlarson** [comment]
Since this hasn't moved and the content is mostly generic instead of specific improvements to the contributors guide I think I'm going to close this one.
