### ISSUE TITLE
How can we minimize memory consumption when decoding data?

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#2787]
For the needs of https://github.com/urllib3/urllib3/pull/2712, I'm looking for a queue-like data structure that:

 * holds bytes
 * supports put()ing an arbitrary number of bytes
 * supports get()ing an arbitrary number of bytes
 * consumes O(size()) memory
 * is less complex than a [rope](https://en.wikipedia.org/wiki/Rope_(data_structure))!

**Comment by pquentin** [comment]
The current solution is a bytearray, which is pretty bad because it consumes three times the amount of bytes for get() operations:
 * the data still in the buffer
 * the byterarray slice
 * the bytes conversion of that slice


Here's a self-contained illustration of that problem:

```python3
from urllib3.response import MultiDecoder


class ByteArrayDecoder:
    def __init__(self):
        self.buffer = bytearray()
        self.decoder = MultiDecoder("gzip")

    def put(self, compressed_data: bytes):
        decoded = self.decoder.decompress(compressed_data)
        self.buffer.extend(decoded)

    def get(self, n: int):
        decoded_data = bytes(self.buffer[:n])
        del self.buffer[:n]
        return decoded_data
```

I'm using this code on the following test data (2GiB of zeroes, this compresses to 2MiB of data):

```python3
import gzip

with open("zeroes.gc", "w") as f:
    f.write(bytes(2**31))
```

And then I run the following code using memray:

```python3
with open("zeroes.gz", "rb") as f:
    compressed = f.read()

decoder = ByteArrayDecoder()
decoder.put(compressed)
decoder.get(2**31)
```


We can use a memoryview to avoid one of the extra copies:

```python3
class MemoryViewDecoder:
    def __init__(self):
        self.buffer = bytearray()
        self.decoder = MultiDecoder("gzip")

    def put(self, compressed_data: bytes):
        decoded = self.decoder.decompress(compressed_data)
        self.buffer.extend(decoded)

    def get(self, n: int):
        buffer_view = memoryview(self.buffer)
        decoded_data = bytes(buffer_view[:n])
        del buffer_view
        del self.buffer[:n]
        return decoded_data
```

Now both `put` and `get` do an extra copy, so we're looking at 4GiB of memory use. Hmm. put() too!? Let's confirm that:

```python3
from urllib3.response import MultiDecoder

with open("zeroes.gz", "rb") as f:
    compressed = f.read()
decoder = MultiDecoder("gzip")
decoded = decoder.decompress(compressed)
```

OK, this script also consumes 4GiB. Is `MultiDecoder` at fault? Let's try without it:

```python3
import zlib

with open("zeroes.gz", "rb") as f:
    compressed = f.read()

obj = zlib.decompressobj(16 + zlib.MAX_WBITS)
decoded = obj.decompress(compressed)
assert len(decoded) == 2**31
```

OK, that's also 4GiB. What if I read the file in chunks:


```python3
import zlib


def chunks():
    with open("zeroes.gz", "rb") as f:
        while chunk := f.read(2**20):
            yield chunk


obj = zlib.decompressobj(16 + zlib.MAX_WBITS)
output = bytearray()
for chunk in chunks():
    output += obj.decompress(chunk)
output += obj.flush()
assert len(output) == 2**31
```

This is where the results start to be intriguing. For zeroes.gz, the max is at 3GiB with 21 allocations. But for a random file that does not compress at all (`head -c 2G </dev/urandom > rand && gzip rand`), the max is at 2.1GiB with 7 allocations.

Aha! By reducing the chunk size from 2**20 to 2**10 in the zeroes case, I also get down to 2.1GiB with 7 allocations. This makes sense. zeroes uncompress extremely well, so 1MiB of compressed data is roughly 1GiB uncompressed, which means we only had two chunks.

If we get back to MultiDecoder, another inefficiency here is that MultiDecoder uses a bytearray internally, returns bytes, and we then convert them back to a bytearray! We could avoid a copy.

All in all, it sounds like the following tricks could help us significantly:
 * memoryview
 * read in chunks (but the optimal size would have to be tuned)
 * avoid the bytearray -> bytes -> bytearray roundtrip

We would likely still use 4GiB in get() though. To be continued.

**Comment by pquentin** [comment]
The more I think about it, the more I want to try a queue of `bytes` objects.

**Comment by illia-v** [comment]
https://github.com/urllib3/urllib3/pull/2657#discussion_r907028735 might be a discussion of a similar problem. This was a chosen solution for the latter:

https://github.com/urllib3/urllib3/blob/f88b3c24cc2e559af9e877eaf10de368cc56a805/src/urllib3/response.py#L698-L716

**Comment by pquentin** [comment]
Yes I'm familiar with that buffer but in `_fp_read` we only append data to the right. For #2712 we need efficient right append but also left pop, which I don't think is something that can be done efficiently with a file-like object such as BytesIO.

**Comment by pquentin** [comment]
> The more I think about it, the more I want to try a queue of `bytes` objects.

I could not resist trying. Here is the result:


```
import collections
import io

from urllib3.response import MultiDecoder


class BytesQueueDecoder:
    def __init__(self):
        self.buffer = collections.deque()
        self.decoder = MultiDecoder("gzip")

    def put(self, compressed_data: bytes):
        decoded = self.decoder.decompress(compressed_data)
        self.buffer.append(decoded)
        print(len(self.buffer))

    def get(self, n: int):
        if not self.buffer:
            raise ValueError("nothing to get")
        elif n < 0:
            raise ValueError("n should be non-negative")

        fetched = 0
        ret = io.BytesIO()
        while fetched < n:
            print(len(self.buffer))
            remaining = n - fetched
            chunk = self.buffer.popleft()

            if remaining < len(chunk):
                left_chunk, right_chunk = chunk[:remaining], chunk[remaining:]
                ret.write(left_chunk)
                self.buffer.appendleft(right_chunk)
                break
            else:
                ret.write(chunk)
                fetched += len(chunk)
        return ret.getvalue()


decoder = BytesQueueDecoder()
with open("zeroes.gz", "rb") as f:
    while chunk := f.read(2**15):
        decoder.put(chunk)

assert len(decoder.get(2**31)) == 2**31
```

Let's compare the memoryview and deque approaches:

### MemoryViewDecoder

![memoryview](https://user-images.githubusercontent.com/42327/201271172-3dd40a60-0d4b-4e39-aa4c-60876d5c7938.png)

### BytesQueueDecoder

![byteslist](https://user-images.githubusercontent.com/42327/201271472-4394a4a3-22f4-446c-9c9b-1665a82394f4.png)

**Comment by pquentin** [comment]
I captured a CPU profile to check that this would not be too slow. Regardless of the buffer size, 14% of the time is spent converting to bytes in MultiDecoder, another 14% is spent writing into the BytesIO (a price that is a paid only in the streaming case), and the rest (70%) is the actual decompression. Seems OK.

![image](https://user-images.githubusercontent.com/42327/201277465-4848dc08-1e3b-43de-87bd-66d9fbfc7ced.png)

This [spike](https://en.wikipedia.org/wiki/Spike_(software_development)) is done, closing. Now let's try to use that in #2712. :rocket:
