### ISSUE TITLE
Use the `typing.` namespace consistently throughout the project

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2789]
When we originally did our typing work, I recommended using `from typing import X; X` instead of using `import typing; typing.X`. Namespaces are a honking good idea, we should have been using them instead of polluting our module namespaces.

Let's change all occurrences of `from typing import X` into `import typing` and then use `typing.X`.

As a part of this issue, make sure to check `.coveragerc` to only skip coverage on `typing.TYPE_CHECKING`.

cc @hramezani

**Comment by pquentin** [comment]
This is probably only practical if we merge #2779
