### ISSUE TITLE
Integrating the pre-commit tests and mypy into nox?

### ISSUE THREAD

**Issue by venthur** [urllib3/urllib3#2808]
### Context

When I tried to provide a PR for urllib3, I realized **only** after I pushed that there's a whole battery of tests being executed on the CI pipeline -- namely the `pre-commit` (isort, black, etc) and `mypy`, which were not covered by the normal `nox` run.

Since we're already using nox, I wonder if you'd accept a PR that integrates the tools that are run by `pre-commit` and `mypy` into the `nox` pipeline?

The advantage is that users that are not aware that you should install `pre-commit` would still benefit from running all the tests when executing `nox`. While `pre-commit` is a convenient tool for the developer, there's not really a guarantee that contributors are using it, so from that POV it might make sense to put all tests into nox.

### Contribution

Would you be willing to submit a PR? -- Of🐴

**Comment by venthur** [comment]
Well, maybe it does actually include the tools in `nox` already but I never saw because I always cancelled the nox run after the third iteration of test-runs. I feel something could be improved here, i.e. only running the pytests only once locally, so you actually get to run the linter, black, etc. in a reasonable amount of time and keep testing the against all python versions, brotli, etc. for the ci pipeline. Anyways, closing this issue.

**Comment by pquentin** [comment]
Is `nox -rs lint` what you had in mind or do you need something different?

We should require Python 3.8 there so that it reports the same results as the nox mypy session. And I guess calling nox from the CI would avoid the confusion.

**Comment by venthur** [comment]
I'd love to somehow improve (i.e simplifying) the whole testing pipeline a bit. But there's many options. Is there an interest in that or some plan already written down? Or is everyone happy with the current status quo?
