### ISSUE TITLE
Disable warnings as a context manager

### ISSUE THREAD

**Issue by mgrazebrook** [urllib3/urllib3#2809]
### Context

In a  development context, I'm making insecure API requests. I'd like to disable just one warning (InsecureRequestWarning in this case) for just that call - after all, other warnings may indicate bugs!

It would be nicer to be able to disable only one warning for only one call in a context manager.

### Alternatives

I can disable all or one warning. I can reset all warnings but not, I think, only one. If the warning I want to have temporarily disabled is already filtered, I can't easily revert to that state.

### Duplicate

I did some rough keyword searching on your issue list so apologies if I missed something.

### Contribution

Would you be willing to submit a PR?
_(Help can be provided if you need assistance submitting a PR)_
Could be fun, I'm a decent programmer and know git but would like support to ensure I work within the project style and integrate nicely with docs.

**Comment by sethmlarson** [comment]
You can suppress individual warnings in Python using [`warnings.catch_warnings()`](https://docs.python.org/3/library/warnings.html#warnings.catch_warnings). Hope this covers your use case.
