### ISSUE TITLE
Sign releases with Sigstore

### ISSUE THREAD

**Issue by tetsuo-cpp** [urllib3/urllib3#2834]
### Context

There have been some usability improvements since the last time urllib3 used Sigstore to sign releases. I realise there is a bit of overlap with what SLSA provides however, there's value in being able to bundle the verification materials as release artifacts like before.

I think the most convenient way to use Sigstore to sign releases would be via the [official GitHub Action](https://github.com/sigstore/gh-action-sigstore-python).

### Contribution

I'd be happy to make a PR if you're interested.

**Comment by sethmlarson** [comment]
We've previously used Sigstore, we didn't move to SLSA due to usability (it's arguably less usable!), only due to additional proof of provenance. What would we gain from adopting Sigstore additionally?

**Comment by sethmlarson** [comment]
Going to close this as it's stalled out? If you answer my questions above I can reopen the issue.
