### ISSUE TITLE
Retry cant handle float in retry-after header

### ISSUE THREAD

**Issue by feba66** [urllib3/urllib3#2861]
### Subject

When the Retry-After header contains a float, for example "0.503", then parse_retry_after raises an invalid header error.

### Environment

OS Windows-10-10.0.19045-SP0
Python 3.10.3
urllib3 1.26.13

### Steps to Reproduce

I cant really give an easy way to reproduce...
the tedious way:
generate python code with openapi-generator from this api https://github.com/SpaceTradersAPI/api-docs/tree/2.0.0-rc.2
hit any endpoint often enough to trigger the ratelimit which should be 2 requests/sec

EDIT:
pull my repo change the main() in api.py a bit to send enough requests and see the ratelimit apply
https://github.com/feba66/spacetraders-sdk

### Expected Behavior

parse the float correctly and wait the correct time before retrying  

### Actual Behavior

the regex match returns false because a dot is present and then tries to parse the date from "0.503" which fails

### possible fix

change the regex to allow for a float and change the conversion from int(retry_after) to float(retry_after)

**Comment by sethmlarson** [comment]
The `Retry-After` header is defined in [RFC 9110 Section 10.2.3](https://www.rfc-editor.org/rfc/rfc9110#name-retry-after) to be `1*DIGIT` meaning 1 or more `[0-9]` characters, this is why we only do whole second values for `Retry-After`. A possible fix here is for the server to adhere to the RFC.

Is there another client you know of that handles decimal values?

**Comment by pquentin** [comment]
Closing until we have more evidence of other clients supporting floats.
