### ISSUE TITLE
Sometimes proxies are specified by envars and all clients are expected to use them

### ISSUE THREAD

**Issue by Jeff-Silverman** [urllib3/urllib3#2867]
### Context

What are you trying to do?
Several places I have worked have environmental variables, typically HTTP_PROXY or similar, which point to a proxy server.  Sending traffic through the proxy is required.  You may assume that the proxy is under the control of the cybersecurity organization.
How do you expect to do it?
Set up these envars in a bash script or windows
Is it something you currently cannot do?
Not with urllib3,  Request can do it.
Is this related to an existing issue/problem?
Not that I know of.

### Alternatives

Can you achieve the same result doing it in an alternative way?
Yes.  Use os.getenv to look for http_proxy, https_proxy, HTTP_PROXY and HTTPS_PROXY, and use those values as inputs to the urllib3.ProxyManager constructor.
Is the alternative considerable?
Yes.

### Duplicate

Has the feature been requested before?
If so, please provide a link to the issue.

### Contribution

Would you be willing to submit a PR?
yes.
_(Help can be provided if you need assistance submitting a PR)_
I will need help submitting the PR.

**Comment by pquentin** [comment]
There are no immediate plans to support this in urllib3, sorry.

**Comment by Jeff-Silverman** [comment]
If I fix the problem myself, would you accept my bugfix?  I think I know how to do it.  I also think I have an effective test plan, by using my webserver as the proxy - it's running nginx and their is a proxy module for it.  I can verify that it is working properly using tcpdump on the client and both sides of the webserver.

Jeff

**Comment by Jeff-Silverman** [comment]
Here is the problem: I am contemplating buying some COTS.  My corporation requires that I go though a proxy that is under the control of cyber security.  Security requires that I use the envar mechanism.  I am not allowed to hardcode the IP addresses.  The vendor will not allow me to modify the software, although perhaps to make a sale, they might be willing to make a sale.  Another possibility would be to do some fun and games with the PYTHONPATH but I am not thrilled with that idea, hopefully for obvious reasons.  I supposed I could use a venv to accomplish the same thing.

I think I know how to fix the problem.  I forget the names at the moment, but I can look them up if necessary.  Just before a constructor is called, call os.env on the four variables, use some sort of decision criteria if they disagree, and feed those proxy values into the constructor.  I worked this out a couple of weeks ago so I'd have to refer to my notes and I am a little rushed right now.




Sincerely yours,

Name: Jeff Silverman
Title: Linux Systems Engineer

Direct    +(253) 459-2318
Email     ***@***.******@***.***>

Expeditors  |  Seattle, WA, USA
1015 Third Ave
www.expeditors.com<http://www.expeditors.com/>

**Comment by pquentin** [comment]
> I think I know how to fix the problem. I forget the names at the moment, but I can look them up if necessary. Just before a constructor is called, call os.env on the four variables, use some sort of decision criteria if they disagree, and feed those proxy values into the constructor. I worked this out a couple of weeks ago so I'd have to refer to my notes and I am a little rushed right now.

You can use `urllib.request.getproxies()` from the standard library to lookup the environment variables for you.
