### ISSUE TITLE
urllib3 on various conda channels still depends on brolipy

### ISSUE THREAD

**Issue by DManowitz** [urllib3/urllib3#2876]
I don't know if anyone here deals with urllib3 on any conda channels, but at least on the main conda channel and on conda-forge, the urllib3 package still has brotlipy as a dependency.

**Comment by sigmavirus24** [comment]
There's a conda forge organization that has the recipes for conda. Please file this there and maybe even fix it if you're inclined

**Comment by sethmlarson** [comment]
Closing this in favor of https://github.com/conda-forge/urllib3-feedstock/issues/62, but if that doesn't cover it completely could you open an issue there?
