### ISSUE TITLE
ssl.SSLContext.get_ca_certs() support for PoolManager ca_certs

### ISSUE THREAD

**Issue by nojetlag** [urllib3/urllib3#2886]
### Context

I tried to feed PoolManager ca_certs parameter with trusted Root CAs which are stored in my machine's windows certificate store. 

For this I used the following code

```
import ssl
mysql = ssl.create_default_context()

httpClient = urllib3.PoolManager(
         cert_reqs='CERT_REQUIRED',
         ca_certs=myssl.get_ca_certs())
```

this fails because ca_certs expects a file location, however on windows certificates are normally not stored in files, therefore for windows systems it would be very nice if one just could hand over the list of certificates that are provided by SSLContext.get_ca_certs() from the ssl model to feed PoolManager with the necessary CA certs.

### Alternatives

Exporting certificates from the windows certificate store as .pem files. 

### Duplicate

not that I know

**Comment by sethmlarson** [comment]
Sorry for the brevity, I'm currently traveling. Could you try truststore for accessing Windows system certificates?

https://truststore.readthedocs.io/en/latest/

**Comment by nojetlag** [comment]
Thanks a lot, had to struggle with Python 3.11.1 in my working environment but now all is sorted out and truststore approach works like a charm!
