### ISSUE TITLE
urllib3 returning 403 when requests via other methods succeed (Docker container)

### ISSUE THREAD

**Issue by am-zq** [urllib3/urllib3#2915]
### Subject

Hello, I have a strange issue where a request to a certain website gives error 403 using urllib3, but succeeds using urllib and curl. The code is running in Docker using an official Python image. I have attempted to match the headers sent by urllib3 to the ones sent by urllib, however it still didn't succeed. The issue does not occur on the Docker host (which is an Ubuntu VM). 

### Environment

Docker image: python:3.10.6-bullseye
Platform: OS Linux-5.15.0-58-generic-x86_64-with-glibc2.31
Python: Python 3.10.6
urllib3: urllib3 1.26.5

### Steps to Reproduce

Dockerfile and script to send a few test requests using urllib and urllib3 below. The specific package versions were to match the Docker host where the request is successful, but the latest versions installed by pip had the same issue.

**Dockerfile**
```
FROM python:3.10.6-bullseye

RUN apt-get update

RUN apt-get install -y openssl

RUN pip install requests==2.25.1 pyopenssl==21.0.0 urllib3==1.26.5 certifi==2020.6.20 cryptography==3.4.8

WORKDIR /code
COPY . .

CMD ["python3", "test.py"]
```

**docker-compose.yaml**
```
version: "3.9"
services:
  tests:
    build: .
```

**test.py**
```
import requests
import logging

import http.client as http_client
http_client.HTTPConnection.debuglevel = 1
logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)

url = 'https://www.blackrock.com/uk'

print(">> NOW TRYING: urllib.request")
import urllib.request
handler = urllib.request.HTTPSHandler(debuglevel=1)
opener = urllib.request.build_opener(handler)
req = opener.open(url)

print(">> NOW TRYING: urllib3")
import urllib3
http = urllib3.PoolManager()
r = http.request('GET', url)
print(r.status)

print(">> NOW TRYING: urllib3 with headers and ordering matching urllib")
r = http.request('GET', url, headers={'Accept-Encoding': 'identity', 'Host': 'www.blackrock.com', 'User-Agent': 'Python-urllib/3.10', 'Connection': 'close'})
print(r.status)

```

### Expected Behavior

The request should succeed, as it does using urllib.

```
tests_1  | >> NOW TRYING: urllib.request
tests_1  | send: b'GET /uk HTTP/1.1\r\nAccept-Encoding: identity\r\nHost: www.blackrock.com\r\nUser-Agent: Python-urllib/3.10\r\nConnection: close\r\n\r\n'
tests_1  | reply: 'HTTP/1.1 200 OK\r\n'
...
```
Full output attached: [docker_urllib_test_output.txt](https://github.com/urllib3/urllib3/files/10687880/docker_urllib_test_output.txt)

### Actual Behavior
It returns a 403 error. Note that the `send: b'GET...` log line in the second attempt exactly matches the successful attempt from urllib above. I thought this would mean exactly the same bytes were being sent, but possibly something is being handled differently behind the scenes.
```
tests_1  | >> NOW TRYING: urllib3
tests_1  | DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.blackrock.com:443
tests_1  | send: b'GET /uk HTTP/1.1\r\nHost: www.blackrock.com\r\nAccept-Encoding: identity\r\nUser-Agent: python-urllib3/1.26.5\r\n\r\n'
tests_1  | reply: 'HTTP/1.1 403 Forbidden\r\n'
...
tests_1  | >> NOW TRYING: urllib3 with headers matching urllib
tests_1  | DEBUG:urllib3.connectionpool:Resetting dropped connection: www.blackrock.com
tests_1  | send: b'GET /uk HTTP/1.1\r\nAccept-Encoding: identity\r\nHost: www.blackrock.com\r\nUser-Agent: Python-urllib/3.10\r\nConnection: close\r\n\r\n'
tests_1  | reply: 'HTTP/1.1 403 Forbidden\r\n'
...
```

I have spent a few hours on this, but this is as far as I got with the debug logging. I get that this could potentially be a Docker issue, but the fact that urllib succeeds with the same request led me to post here. I'm happy to do some more testing if someone has suggestions for what else to try.

**Comment by am-zq** [comment]
Installing urllib3 from git got it working: `pip install git+https://github.com/urllib3/urllib3.git`

I was curious which commit in the 2.x.x branch fixed it, so I did some testing. This is the commit which changes the result from 403 to 200:
* 841a727 - Use system TLS ciphers if using OpenSSL 1.1.1+ or SecureTransport

My OpenSSL version was `OpenSSL 1.1.1n  15 Mar 2022`, so I presume that the server didn't accept the non-system ciphers...

I will try to use 2.0.0a3. The `requests` library requires an older version, but installing like this gets the `requests.get` to succeed:
```
RUN pip install requests
RUN pip install git+https://github.com/urllib3/urllib3.git@2.0.0a3
```

The warning from pip is:
```
requests 2.25.1 requires urllib3<1.27,>=1.21.1, but you have urllib3 2.0.0a3 which is incompatible.
```

Your docs say v2.0 has 99% functional API compatibility, so hopefully it will just work!

Is it worth merging that commit into 1.26.x branch so others don't run into this issue?

**Comment by sethmlarson** [comment]
This is almost certainly the server filtering on something that urllib3 is doing like a User-Agent, TLS etc, but I can't tell you what that thing is since we don't have access to the server source code. Since this isn't a defect in the library itself I don't think there's much we can do here. Going to close this issue.
