### ISSUE TITLE
Requesting release of 1.26.15

### ISSUE THREAD

**Issue by nickwilliams-zaxiom** [urllib3/urllib3#2929]
### Context

Apologies if this is not the correct forum for this request. A couple months ago, I submitted a pull request (#2869), which was merged, to fix an issue we're having in urllib3 1.26.14. This PR backported a fix that was already present in the 2.0.x series. This issue has become a bigger issue for us recently, and it would be great if we could deploy the fix. Could we get a release of 1.26.15 soon(-ish?)?

### Alternatives

The workaround we currently have for our issue is to increase all timeouts, but that causes other issues for our software.

### Duplicate

n/a

### Contribution

See above.

**Comment by sethmlarson** [comment]
That sounds like a good idea, we actually allow anyone to kick off a release-candidate PR. We describe the [short process here](https://github.com/urllib3/urllib3/blob/1.26.x/docs/contributing.rst#releases), in general you should aim for something that looks like [this](https://github.com/urllib3/urllib3/pull/2871). Would you be interested in putting one of those together? We can handle the rest after that :)

**Comment by nickwilliams-zaxiom** [comment]
Sure, I can get it started. Thanks!

**Comment by sethmlarson** [comment]
Done! https://github.com/urllib3/urllib3/pull/2931
