### ISSUE TITLE
 Why can I use urllib 3-1.25.11 without making any errors? Using urllib 3-1.26.15 can cause the following errors:(_ssl.c:1131)

### ISSUE THREAD

**Issue by bfundac** [urllib3/urllib3#2944]
### Why can I use urllib 3-1.25.11 without making any errors? Using urllib 3-1.26.15 can cause the following errors:(_ssl.c:1131)

HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/models (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

### What is the main reason for this error? 

How can I avoid this error when upgrading to the latest urllib 3? (I can only use urllib 3-1.26.15 now)

**Comment by sethmlarson** [comment]
We have a template for reporting an issue, please fill out the template so we can provide proper assistance. Closing this issue.
