### ISSUE TITLE
Native support for Pyodide, PyScript (emscripten?)

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2951]
When PyScript was announced at PyCon US 2022 I immediately tried to add support for synchronous HTTP requests w/ Pyodide/PyScript into urllib3 but was unfortunately unsuccessful at the time. I can see that support for this has grown since that time :rocket:

There's a lot to look at and learn on this topic, this issue is currently a stub and needs more filling in.

General thoughts right now from me are having a new module `urllib3.contrib.fetch` which exposes an `HTTP[S]Connection` implementation that uses Pyodide's pyfetch (and the equivalent for emscripten) under the hood. Wouldn't need to support the full range of options available to urllib3 (things like custom certificates, etc) but I suspect we'd get a lot from just method, url, headers, body, and some other basic features.

The tougher parts of this would be testing and documentation, we can learn from the below projects potentially?

## Requirements

- [ ] Figure out how we can test urllib3 consistently in a browser
- [ ] Add functionality which uses the JavaScript fetch API instead of httplib in a third-party module (ie `urllib3.contrib.fetch`)
- [ ] Document the new feature and restrictions
- [ ] Verify that Requests works with urllib3 in the browser

## Related projects / issues

- https://github.com/koenvo/pyodide-http
- https://github.com/emscripten-forge/requests-wasm-polyfill
- https://github.com/koenvo/pyodide-http/issues/28
- https://github.com/koenvo/pyodide-http/issues/6
- https://github.com/pyodide/pyodide/issues/3160

cc @koenvo

**Comment by sethmlarson** [comment]
@koenvo Hmm, do you see the requirement for security headers changing anytime soon? If not I think (assuming there's a way to detect when these features are available) to do the best thing for users in their current situation by default and then adding an option to force behavior one way or the other when necessary. I'm not sure what kinds of problems blocking the main JS thread can do if we're offering a sync HTTP API. Documentation will help a lot here, too.

**Comment by sethmlarson** [comment]
Created this project on pyscript.com which shows the current state of affairs:

https://b15ad9a9-0744-48ba-8e37-eedddba9292c.pyscriptapps.com/7b5d346e-e490-43f0-b43f-cdeae7f24665/latest/

**Comment by koenvo** [comment]
This is awesome! This means I can add an urllib3 version check in pyodide-http and skip the patching, right?

**Comment by joemarshall** [comment]
@koenvo - yes. I'm gonna put a PR into pyodide to include requests and urllib3 as a core package when I have the time.

**Comment by sethmlarson** [comment]
@joemarshall Thanks for doing that! Could you include me on those PRs if only just to see what is happening over there? :)
