### ISSUE TITLE
urllib3 ability to trust a local CA bundle

### ISSUE THREAD

**Issue by paneerlovr** [urllib3/urllib3#2957]
### Context

What are you trying to do?

My company uses Zscaler to implement a man in the middle, essentially  they eavesdrop on all my traffic.  I'd like to trust a local certificate authority bundle with urllib3.  The reason for this is because Google Cloud CLI uses urllib3, and the installer is failing verification.

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)

How do you expect to do it?

I'm hoping for help to set an environment variable, ie, URLLIB3_CA_BUNDLE=mypathtopemfile

Is it something you currently cannot do?

If there is a workaround, kindly advise...

Is this related to an existing issue/problem?

Yes

### Alternatives

Can you achieve the same result doing it in an alternative way?

I'm not sure how since my company uses zscaler.

Is the alternative considerable?

I don't think so.

### Duplicate

Has the feature been requested before?

I searched and didn't see it...

If so, please provide a link to the issue.

### Contribution

Would you be willing to submit a PR?

Unfortunately, I don't know how to do this...

_(Help can be provided if you need assistance submitting a PR)_

**Comment by sigmavirus24** [comment]
https://stackoverflow.com/questions/67978745/how-to-solve-certificate-verify-failed-error-when-install-gcloud

I'd also try setting the `CURL_CA_BUNDLE` environment variable which Requests honors and based on that StackOverflow post the installer may be using requests (which uses urllib3).

Otherwise the installer needs to allow you to specify this

**Comment by sethmlarson** [comment]
Unfortunately if this isn't available through the method that @sigmavirus24 suggests, we are not likely to add support for environment variables to configure urllib3. My suggestion is look at the Google Cloud CLI for a way to specify your CA bundle, put your custom CA directly into certifi (or whatever the Google Cloud CLI uses for its CA bundle) and open a feature request there.
