### ISSUE TITLE
Auth in url is not taken into account

### ISSUE THREAD

**Issue by ndclt** [urllib3/urllib3#2968]
### Subject

When putting the username and password in the url like this `http://username:password@localhost`, they are not converted into an `auhorization` header.

### Environment

Describe your environment.
At least, paste here the output of:

```
OS Linux-5.15.0-69-generic-x86_64-with-glibc2.35
Python 3.10.6
urllib3 1.26.12
```

### Steps to Reproduce

* Run an echo server with docker `docker run mendhak/http-https-echo`
* run the following snippets:
```python
import urllib3

pool = urllib3.poolmanager.PoolManager()
pool.urlopen("GET", "http://user:pass@localhost")
```

### Expected Behavior

We should see the following headers in the output of the ``http-https-echo` server
```json
{
    "headers": {
        "host": "localhost",
        "accept-encoding": "identity",
        "user-agent": "python-urllib3/1.26.12"
        "authorization": "Basic dXNlcjpwYXNz"
    }
}
```

### Actual Behavior
The authorization is missing.
```json
{
    "headers": {
        "host": "localhost",
        "accept-encoding": "identity",
        "user-agent": "python-urllib3/1.26.12"
    }
}
```

When trying with other tools like `curl` or `httpx` it works fine I get the header with the authorization.

### Root cause?

I suspect the root cause to be around [this line](https://github.com/urllib3/urllib3/blob/5a24dc55d86e4c5ca7fe0bd496da768caf617591/src/urllib3/poolmanager.py#L422) of the `urlopen` function in the `PoolManager` class.

When debugging, I saw that the `u = parse_url(url)` gives an object like this:
```
Url(scheme='http', auth='user:pass', host='localhost', port=None, path=None, query=None, fragment=None)
```
and the `auth` attribute is never used after.

Would something like the following snippet works?
```python
import base64
...
class PoolManager(RequestMethods):
...
    def urlopen(  # type: ignore[override]
        self, method: str, url: str, redirect: bool = True, **kw: typing.Any
    ) -> BaseHTTPResponse:
        """
        Same as :meth:`urllib3.HTTPConnectionPool.urlopen`
        with custom cross-host redirect logic and only sends the request-uri
        portion of the ``url``.
        The given ``url`` parameter must be absolute, such that an appropriate
        :class:`urllib3.connectionpool.ConnectionPool` can be chosen for it.
        """
        u = parse_url(url)

        conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)

        kw["assert_same_host"] = False
        kw["redirect"] = False

        if "headers" not in kw:
            kw["headers"] = self.headers
        if u.auth is not None:
            encoded_auth = base64.b64encode(u.auth.encode())
            authorization_headers = {"authorization": "Basic {}".format(encoded_auth)}
...
```

**Comment by FreerGit** [comment]
I can submit a PR for this.

**Comment by FreerGit** [comment]
Pr above now opened for this issue.
