### ISSUE TITLE
Questions about allowed method options in Retry.py

### ISSUE THREAD

**Issue by wonjerry** [urllib3/urllib3#2982]
### Context
Hi, I'm currently using urllib3 well, but I have one question: why is the post method not added to the default allowed method of Retry? - Here is the code: https://github.com/urllib3/urllib3/blob/85d71221a5eb3ce561c73b9619afc0a37d3d11ed/src/urllib3/util/retry.py

I use post request a lot and I've been debugging for a while thinking there's an error because it doesn't retry.

I was wondering if for some reason, you couldn't add post to the allowed method or make the allowed method default to false?

### Contribution

If you don't mind, I'd like to fix it and PR it

**Comment by sigmavirus24** [comment]
urllib3 allows you to post file-like objects. Those may not be rewindable and thus we can't retry them. When users pass those, it's often to avoid storing everything in memory and so we also cannot cache that data to resend it.

**Comment by pquentin** [comment]
Also, see https://www.rfc-editor.org/rfc/rfc9110#name-common-method-properties: POST is the only method which is neither safe nor idempotent, and thus can't be retried by default. I'll close this issue.

Thanks!
