### ISSUE TITLE
urllib3 2.0.0 breaks twine

### ISSUE THREAD

**Issue by tra-github** [urllib3/urllib3#2997]
16:55:44  Successfully installed Pygments-2.15.1 SecretStorage-3.3.3 bleach-6.0.0 cffi-1.15.1 cryptography-40.0.2 docutils-0.19 importlib-metadata-6.6.0 importlib-resources-5.12.0 jaraco.classes-3.2.3 jeepney-0.8.0 keyring-23.13.1 markdown-it-py-2.2.0 mdurl-0.1.2 more-itertools-9.1.0 pkginfo-1.9.6 pycparser-2.21 readme-renderer-37.3 requests-toolbelt-0.10.1 rfc3986-2.0.0 rich-13.3.5 twine-4.0.2 typing-extensions-4.5.0 urllib3-2.0.0 webencodings-0.5.1 zipp-3.15.0
16:55:44  /usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.0.0) or chardet (3.0.4) doesn't match a supported version!
16:55:44    warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
16:55:44  Traceback (most recent call last):
16:55:44    File "/usr/local/lib/python3.8/dist-packages/requests_toolbelt/_compat.py", line 48, in <module>
16:55:44      from requests.packages.urllib3.contrib import appengine as gaecontrib
16:55:44  ImportError: cannot import name 'appengine' from 'urllib3.contrib' (/usr/local/lib/python3.8/dist-packages/urllib3/contrib/__init__.py)
16:55:44  
16:55:44  During handling of the above exception, another exception occurred:
16:55:44  
16:55:44  Traceback (most recent call last):
16:55:44    File "/usr/local/bin/twine", line 8, in <module>
16:55:44      sys.exit(main())
16:55:44    File "/usr/local/lib/python3.8/dist-packages/twine/__main__.py", line 33, in main
16:55:44      error = cli.dispatch(sys.argv[1:])
16:55:44    File "/usr/local/lib/python3.8/dist-packages/twine/cli.py", line 121, in dispatch
16:55:44      main = registered_commands[args.command].load()
16:55:44    File "/usr/local/lib/python3.8/dist-packages/importlib_metadata/__init__.py", line 210, in load
16:55:44      module = import_module(match.group('module'))
16:55:44    File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
16:55:44      return _bootstrap._gcd_import(name[level:], package, level)
16:55:44    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
16:55:44    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
16:55:44    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
16:55:44    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
16:55:44    File "<frozen importlib._bootstrap_external>", line 848, in exec_module
16:55:44    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
16:55:44    File "/usr/local/lib/python3.8/dist-packages/twine/commands/upload.py", line 26, in <module>
16:55:44      from twine import settings
16:55:44    File "/usr/local/lib/python3.8/dist-packages/twine/settings.py", line 22, in <module>
16:55:44      from twine import repository
16:55:44    File "/usr/local/lib/python3.8/dist-packages/twine/repository.py", line 18, in <module>
16:55:44      import requests_toolbelt
16:55:44    File "/usr/local/lib/python3.8/dist-packages/requests_toolbelt/__init__.py", line 12, in <module>
16:55:44      from .adapters import SSLAdapter, SourceAddressAdapter
16:55:44    File "/usr/local/lib/python3.8/dist-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
16:55:44      from .ssl import SSLAdapter
16:55:44    File "/usr/local/lib/python3.8/dist-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
16:55:44      from .._compat import poolmanager
16:55:44    File "/usr/local/lib/python3.8/dist-packages/requests_toolbelt/_compat.py", line 50, in <module>
16:55:44      from urllib3.contrib import appengine as gaecontrib
16:55:44  ImportError: cannot import name 'appengine' from 'urllib3.contrib' (/usr/local/lib/python3.8/dist-packages/urllib3/contrib/__init__.py)

**Comment by sigmavirus24** [comment]
Neither twine nor it's dependencies explicitly request urllib3 2.0 and in fact forbid it. So this may be a problem with how you install twine or with you trying to eagerly update urllib3 beyond what is supported by those tools. 2.0 was a long-publicized breaking change.

**Comment by sethmlarson** [comment]
This is being handled in requests-toolbelt: https://github.com/requests/toolbelt/pull/355

I'm going to close this issue since there's nothing for urllib3 to do here. Thanks for the report.

**Comment by pquentin** [comment]
For future reference, and as mentioned in the twine issue you also opened (https://github.com/pypa/twine/issues/989), requests-toolbelt 1.0.0 is out with urllib3 2.0 support: https://pypi.org/project/requests-toolbelt/1.0.0/ Fun fact: I uploaded the release with twine 4.0.2, requests 2.29.0, requests-toolbelt 1.0.0 and urllib3 2.0.1.
