### ISSUE TITLE
Potential regression in 2.0.0 (commit ea96fde9450b2d0d233f0414c7be0a75148fae8b)

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2999]
Previously the test `test_ssl_cert_pinning_fails` would succeed in 1.26.15, but fails by hanging in 2.0.0:

Ref: https://github.com/elastic/apm-agent-python/blob/main/tests/transports/test_urllib3.py#L256

From bisecting, the offending commit is: https://github.com/urllib3/urllib3/commit/ea96fde9450b2d0d233f0414c7be0a75148fae8b

**Comment by pquentin** [comment]
I was able to reproduce the hang wihout apm-agent-python: https://gist.github.com/pquentin/dddb538fe71d6a2b31e57918cda74047. Just run `pytest -v`, the second test will hang with urllib3 2.0.

**Comment by pquentin** [comment]
So we have tests in urllib3 that do exactly that: `test_verify_none_and_good_fingerprint` and `test_verify_none_and_bad_fingerprint`.

I'm slowing turning the apm-agent-python tests into the urllib3 tests until I understand the difference. See https://github.com/pquentin/urllib3-issue-2999

**Comment by graingert** [comment]
This is fixed by https://github.com/urllib3/urllib3/pull/2992
