### ISSUE TITLE
urllib3 2 causes partial response to be returned (using requests 2.30.0)

### ISSUE THREAD

**Issue by DrShushen** [urllib3/urllib3#3009]
### Subject

**Please note - already submitted a [bug report to requests](https://github.com/psf/requests/issues/6439).**

Submitting also here, as this appears to be a regression issue when upgrading to `urllib3 2.0`. 
The below problem stops happening if I downgrade `urllib3` to `<2` (`pip install "urllib3<2"`).

### Environment

Output of:
```python
import platform
import urllib3

print("OS", platform.platform())
print("Python", platform.python_version())
print("urllib3", urllib3.__version__)
```
... is:
```txt
OS Linux-5.19.0-41-generic-x86_64-with-debian-bookworm-sid
Python 3.7.16
urllib3 2.0.1
```

Using `requests 2.30.0`.

See also output of:
```sh
$ python -m requests.help
```
```txt
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "3.1.0"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.4"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.16"
  },
  "platform": {
    "release": "5.19.0-41-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.30.0"
  },
  "system_ssl": {
    "version": "1010114f"
  },
  "urllib3": {
    "version": "2.0.1"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}
```

### Steps to Reproduce

```python
import requests

url = "https://raw.githubusercontent.com/autonlab/auton-survival/cf583e598ec9ab92fa5d510a0ca72d46dfe0706f/dsm/datasets/pbc2.csv"
request = requests.get(url, timeout=5).content
request.decode("utf-8")
```

### Expected Behavior

Expect to see the entire content of the file [pbc2.csv](https://raw.githubusercontent.com/autonlab/auton-survival/cf583e598ec9ab92fa5d510a0ca72d46dfe0706f/dsm/datasets/pbc2.csv):
```txt
"sno.","id","years", ...
...
... 200,128,13.4,3,0<EOF is here>
```

### Actual Behavior

Get the content of the file truncated around line `1683` (out of total `1946` lines):
```txt
"sno.","id","years", ...
...
... 71,306,11,4,0\n"<This is not EOF>
```

**Comment by nateprewitt** [comment]
This is the minimal repro I was able to produce without Requests:


```python
import urllib3

url = "https://raw.githubusercontent.com/autonlab/auton-survival/cf583e598ec9ab92fa5d510a0ca72d46dfe0706f/dsm/datasets/pbc2.csv"
http = urllib3.PoolManager(num_pools=1)
conn = http.connection_from_url(url)

resp = conn.urlopen(
    'GET',
    url,
    headers={'Accept-Encoding': 'gzip'},
    decode_content=False,
    preload_content=False,
)

data = b"".join(i for i in resp.stream(1024*10, decode_content=True))

assert len(data) == 296085, f"Data length was: {len(data)}"
```

The issue is specifically with streaming gzipped responses. Removing the `Accept-Encoding` header does not reproduce this issue.

**Comment by sethmlarson** [comment]
Having bisected for the above reproducer, I've found this to be the bad commit: c35033f6cc54106ca66ef2d48a9e3564d4fb0e07

**Comment by sethmlarson** [comment]
urllib3 2.0.2 has been released with the fix for this issue: https://github.com/urllib3/urllib3/releases/tag/2.0.2
