### ISSUE TITLE
Document the parameters for `urllib3.request()`

### ISSUE THREAD

**Issue by brettcannon** [urllib3/urllib3#3011]
### Context

https://urllib3.readthedocs.io/en/stable/reference/urllib3.request.html has no details on any of its parameters. I assume they ultimately come from https://urllib3.readthedocs.io/en/stable/reference/urllib3.connectionpool.html#urllib3.HTTPConnectionPool.urlopen except for the `json` parameter which seems to be indirectly documented via https://urllib3.readthedocs.io/en/stable/user-guide.html#json . But since this is meant to be the high-level API that folks might grab over e.g. requests, directly documenting or linking to the appropriate function for details would probably be helpful.

### Contribution

Would you be willing to submit a PR?
_(Help can be provided if you need assistance submitting a PR)_

Yes, I'm willing to help out with a PR depending on how you want the docs to look.

**Comment by geeksambhu** [comment]
Hi @brettcannon, I would love to work on this

**Comment by sethmlarson** [comment]
@geeksambhu Great! Ideally I would like all of this documented at the top of the User Guide.

**Comment by geeksambhu** [comment]
@sethmlarson, I will work on the User Guide, Can you please assign this to me?

**Comment by sethmlarson** [comment]
@geeksambhu We don't assign folks to issues unless there's a created PR, as you can imagine there's a high number of people that say they'll contribute but then life gets in the way and we don't want to discourage others from working on something until there's proof that the effort would be duplicated. Hope you understand!

**Comment by brettcannon** [comment]
> Ideally I would like all of this documented at the top of the User Guide.

So you don't want the parameter details in the API/reference docs? Or are you saying you would like to have them covered in both the reference guide  **and** the user guide?

**Comment by sethmlarson** [comment]
@alexwlchan has an open PR for this issue, so marking it as claimed.

**Comment by alexwlchan** [comment]
@sethmlarson Are you waiting for anything more from me of that PR, or is it just waiting for a reviewer to have time for it?

**Comment by sethmlarson** [comment]
@alexwlchan  Reviewer to have time! Sorry about the delay :)
