### ISSUE TITLE
Add guidance for Amazon Linux, RedHat Enterprise Linux, wrt OpenSSL versions

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#3016]
This error has been cropping up in a few GitHub issues/comments:

```
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2k-fips  26 Jan 2017. See: https://github.com/urllib3/urllib3/issues/2168
```

There's likely some additional guidance we can give folks that are receiving this error in our v2 migration guide:

- Create a separate section for this issue and how to mitigate it
- Have this error message verbatim in the migration guide under the section
- Mention specifically Amazon Linux and RHEL, but also other platforms we're aware of
- Recommend to users to figure out if they can upgrade their OpenSSL version or platform to get onto an OpenSSL release which is receiving security releases
- If they can't, then they need to pin `urllib3<2` until they do.

**Comment by cmawhorter** [comment]
on amazon linux 2, openssl 1.1 is available as a different package named openssl11

this worked for me w/pyenv:
1. remove (or don't install) openssl-devel
2. yum install openssl11 openssl11-devel
3. pyenv install 3.9
