### ISSUE TITLE
urllib3>=2.0 does not work with system Python on macOS

### ISSUE THREAD

**Issue by andy-maier** [urllib3/urllib3#3020]
### Subject

The system Python on macOS 12.6.5 is Python 3.9.6 whose ssl module is compiled with LibreSSL 2.8.3.

The removal of LibreSSL support in urllib3 2.0 makes it impossible to be used with the system Python on macOS.

What are you recommending to macOS users that do not want to or are not allowed to use a Homebrew version of Python?

In our Python packages that use requests / urllib3, we will now either have to pin urllib3 to <2.0, or have to have a trouble shooting documentation for how to deal with that.

At the least, I think urllib3 should add some trouble shooting info on how to find out what the Python ssl module is compiled with, and the options to deal with the issue.

Note that issue #2168 misses one important case: The user created a virtualenv based on the system Python. Using a virtualenv makes it possible and reasonable to install packages from Pypi. That is how a macOS user gets into the problem of using a Python that was compiled with LibreSSL and uses urllib3>=2.0.

That is the case that issue describes as "The combination of the above three is very unlikely.", but that is exactly how it happens and I don't think it is unlikely. There is no rule (that I know of) that prevents or discourages from using the system Python for a virtualenv, and then to install packages from Pypi.

**Comment by sigmavirus24** [comment]
While true, CPython is removing support for compiling against Libressl so it's unlikely to be the case long term.

**Comment by andy-maier** [comment]
Note that [PEP-644](https://peps.python.org/pep-0644) lists macOS in its OpenSSL section as "macOS (python.org installer)" and does not show the system Python provided in macOS at all, which uses LibreSSL up to Ventura. 

Considering the use of the system Python on macOS, the statement in PEP-644 "No macOS and Windows user will be affected by the deprecation." is simply not true.

So if urllib3 refers to PEP-644, it should also be aware of the fact that that PEP seems to ignore the use of the system Python on macOS. There are environments where you simply don't have the choice to install anything else.

**Comment by sigmavirus24** [comment]
The system python on macOS is actively recommended against by most resources I'm aware. It's there for macOS tooling and development (software developed by Apple).I believe the PSF has no sway over language decisions so you want to blame the Steering Council for accepting the PEP. (Although, really wildly accusing other humans who volunteer to work on a project like Python of malicious intent or incompetence is really shitty behavior regardless of whether you address the right group or not.)

The reality is that Python offers dmg files for macOS users that are complied against openssl and there are other options like asdf(, pyenv, etc.) for local user installation and homebrew.

If you're looking to blame someone for incompatibilities, look to the Libressl project. They forked hard. Between Google's boringssl, Libressl, and openssl the APIs are too different for one person (the only person willing to maintain `ssl`) who does the maintenance entirely in their free time. (At least that's my guess - that it's too much to be able to be confident in the secure usage of the various APIs).

It's not a great place to be, I agree, but regardless of whether this library checks that or not, Libressl is not going to be well supported and likely not trustable within Python on any platform that compiles against it. There will be patches used to make it compile and likely those will be carried forward until something makes it hard to get those to work or a CVE is found in the fragile integration.

**Comment by andy-maier** [comment]
> Although, really wildly accusing other humans who volunteer to work on a project like Python of malicious intent or incompetence is really shitty behavior regardless of whether you address the right group or not.

I did not intend to accuse anyone (and don't think I did), and particularly not the great folks that lead the development of Python. I just pointed out particular single-sidedness of that PEP w.r.t. macOS.

**Comment by andy-maier** [comment]
I have the same feelings about LibreSSL as you expressed, but with Apple choosing that library, the situation has become more difficult. That decision has given LibreSSL a certain weight.

**Comment by andy-maier** [comment]
Do you have a link to where Apple states that the system Python in macOS has the restricted purpose you stated above?

**Comment by pquentin** [comment]
Thanks for your excellent points. We might revisit our decision, but need to investigate more. That said, I wanted to answer to one specific question.

> Do you have a link to where Apple states that the system Python in macOS has the restricted purpose you stated above?

Yes, see the macOS 10.15 release notes: https://developer.apple.com/documentation/macos-release-notes/macos-catalina-10_15-release-notes#Scripting-Language-Runtimes

> ## Scripting Language Runtimes
> ### Deprecations
> 
> * Scripting language runtimes such as Python, Ruby, and Perl are included in macOS for compatibility with legacy software. Future versions of macOS won’t include scripting language runtimes by default, and might require you to install additional packages. If your software depends on scripting languages, it’s recommended that you bundle the runtime within the app. (49764202)
>  * Use of Python 2.7 isn’t recommended as this version is included in macOS for compatibility with legacy software. Future versions of macOS won’t include Python 2.7. Instead, it’s recommended that you run python3 from within Terminal. (51097165)

Python 2.7 was then [officially deprecated in macOS 12.0](https://developer.apple.com/documentation/macos-release-notes/macos-12_0_1-release-notes#Python) and [removed in macOS 12.3](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes). https://github.com/python/cpython/pull/95284 acknowledged this.

There's no more "system Python": Python 3 is now installed only if you install the Xcode Command Line Tools, and is meant for LLDB scripting, as described in the [LLVM docs](https://lldb.llvm.org/resources/caveats.html) and the [Xcode 13 release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-13-release-notes) which state:

> * LLDB’s Python scripting no longer supports Python 2. (73956573)

**Comment by pquentin** [comment]
Even though the "system Python" is only installed with developer tools and is only meant for scripting a debugger when using Xcode, I realize this is hurting users.

We mentioned that we were following the lead of PEP 644, but:

 * I don't think this Xcode Python existed when the PEP was written in October 2020?
 * The wording in the PEP is harsh, but even CPython is not actively dropping LibreSSL, see https://github.com/python/cpython/pull/28728 for example. (Patches are still needed on Gentoo though: https://github.com/gentoo/libressl/tree/master/dev-lang/python/files)
 * Unlike Gentoo which already patched urllib3, users hitting the LibreSSL issue on macOS are often new to Python, and this is not welcoming.
 * cryptography dropped support for OpenSSL<1.1.1, but they still actively support LibreSSL

Should we open the door to LibreSSL? One issue is that LibreSSL 2.8.3 was released in December 2018 and has been EOL since December 2019. Still, my opinion is that **requiring** OpenSSL is harsh and a warning should be enough for users that are not using OpenSSL for now.

@sethmlarson @sigmavirus24 What do you think?

**Comment by sigmavirus24** [comment]
I am on board with relaxing the restriction. I'm only worried about debugging Libressl problems if they come up when it's not something we can easily support or test against and the support provider will likely be per-downstream.

What do folks think about something like what requests has to provide additional debugging info in the bug template?

**Comment by pquentin** [comment]
> What do folks think about something like what requests has to provide additional debugging info in the bug template?

Good idea. requests has https://github.com/psf/requests/blob/main/.github/ISSUE_TEMPLATE/Bug_report.md which asks to run `python -m request.help` which is quite comprehensive, but we have https://github.com/urllib3/urllib3/blob/main/.github/ISSUE_TEMPLATE/02_bug_report.md and I can extend it to print `ssl.OPENSSL_VERSION` which gives `OpenSSL 3.0.8 7 Feb 2023` on my Linux laptop and `LibreSSL 2.8.3` on my Macbook.

**Comment by sethmlarson** [comment]
I'm also on board with relaxing the restriction to allow any version of LibreSSL as long as we explicitly emit a warning that LibreSSL isn't supported and continue to raise an error for non-OpenSSL/LibreSSL implementations. The unfortunate thing is I'm unsure how we are going to test that whatever we've done is at least correct initially for us to feel comfortable releasing it at all, anyone have ideas how to get an authentic Python build that uses LibreSSL?

**Comment by mistermocha** [comment]
Hey I came across this, and I do the bulk of my work in virtual environments. My newly created venv picks up the ssl module from whatever-the-system-ssl-module is.

It took lots of digging to figure out that if I install openssl1.1.1 from homebrew, blow away my bin folder in my venv, then recreate my venv entirely, it links the ssl package properly. 

I'm happy to document the process for those that are having trouble if someone can point me to the right place for it,

**Comment by mistermocha** [comment]
I understand. This was the first big break that happened for me as a result of the upgrade. I'll work on my own post somewhere so that it helps someone, because I'm sure there's another person who's having the same problem.

**Comment by timsutton** [comment]
> I don't think this Xcode Python existed when the PEP was written in October 2020?

It was: Apple had begun shipping a Python 3 linked against LibreSSL with their Command Line Tools and Xcode when Catalina was released in October 2019, first previewed in June 2019.

I re-watched a [section of this Python-on-macOS talk](https://youtu.be/Y_4I5MSHh4Y?t=1863) I did a couple years ago and it seems like its linked LibreSSL version was at the same 2.8.3 that it is today :/

**Comment by hoochanlon** [comment]
first

```
pip3 uninstall urllib3
```

second

```
pip3 install urllib3==1.26
```

it's worked.so far so good.

**Comment by aleksei-dereviankin** [comment]
Macports version 3.9 compiled with openssl and works properly. install macports and use python from it, working on my m2

**Comment by pluveto** [comment]
Any solution?

```
NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
```

**Comment by pquentin** [comment]
Please use urllib3 2.0.3 or above.

**Comment by sigmavirus24** [comment]
@pluveto also, you're seeing a warning, not an error. If you wish to silence the error you can look into how to do so with the python warnings module.

**Comment by sigmavirus24** [comment]
@mm-webx correct. That's expected. Prior to 2.0.3, it was an exception instead

**Comment by ceciquin** [comment]
Hi, I've been trying to fix with all the suggestion and still not working. 

context : 

- using macOS Ventura 13.2.1
- using VScode 1.75.1
- my vscode it's using a .venv as virtual environment
- I'm using commands like : python3 -m pip install yfinance 
- OpenSSL version: OpenSSL 3.1.1 30 May 2023 
- urllib3 version: 2.0.4

Error trying to use yfinance and pandas_datareader : 

../.venv/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

**Comment by nyky75** [comment]
```
NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn( 
```

can you help me? Im using urllib3-2.0.3

tried also urllib3-2.0.4 
same problem

**Comment by pquentin** [comment]
This is only a warning telling you that we don't really support LibreSSL (especially this old version). We would recommend installing Python from Homebrew or python.org but you can still use this system Python if you want to: this is a warning, not an exception.

**Comment by qinggeouye** [comment]
The error no longer occurs after upgrading Python from 3.8 to 3.9.13. For reference only.

**Comment by jbreazeale** [comment]
I am using homebrew with python@3.11, running a Python script and getting this warning:

/usr/local/lib/python3.11/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

Again, I am using the Python from Homebrew.  Is there anything I can do about this?

**Comment by sigmavirus24** [comment]
It's a warning, not a blocking exception. If you wish to silence the warning the standard library documentation around warnings shows how to suppress arbitrary warnings

**Comment by jbreazeale** [comment]
> 

It turns out that I was using Python 3.8 and didn't realize it.  Now that I'm truly using Python 3.11 the warning has disappeared.  Thank you for time!

**Comment by pquentin** [comment]
This is not related to the architecture. Most likely, you're using the Python provided by the Xcode Command Line Tools on your M1, and another Python (maybe provided by Homebrew?) on your Intel Mac.

**Comment by b0gdanw** [comment]
`sudo sed -i '' 's/else:/#else:/g' /Library/Python/3.9/site-packages/urllib3/__init__.py`

**Comment by davis** [comment]
what is the solution?

**Comment by sethmlarson** [comment]
Locking this thread as we've already relaxed the restriction from an error to a warning in the latest versions of urllib3 2.x. We won't be removing the warning, it's up to users to either move to a Python compiled with OpenSSL or be okay with running in an untested configuration.

Issues that aren't related to the above should be opened separately.
