### ISSUE TITLE
Raise a better error message when 1.26.x users call `urllib3.request()`

### ISSUE THREAD

**Issue by SAMAD101** [urllib3/urllib3#3046]
When making a request through ...
`
import urllib3
urllib3.request("GET", "https://httpbin.org/robots.txt")
`
Screenshot:
![Screenshot_20230524_201701](https://github.com/urllib3/urllib3/assets/71956678/822fb172-ddd4-4ddf-ac24-2fd29c2fd792)

This should not be the case. The README.md  and the official documentation have this introductory example as well.

### Info:
My Python version: 3.10.10

### Steps to Reproduce
Just try to execute the ` urllib3.request()` in any 1.26x version.

### Expected Behavior
The request should do its job as demonstrated in the example.

### Bounty requirements

- https://github.com/urllib3/urllib3/issues/3046#issuecomment-1566233015
- https://github.com/urllib3/urllib3/issues/3046#issuecomment-1567464853

**Comment by sigmavirus24** [comment]
Without all the information requested in the issue template, I suspect you're not using urllib3 v2.0 which added the function in the documentation. You'll want to read the documentation for the version you're using

**Comment by SAMAD101** [comment]
> Without all the information requested in the issue template, I suspect you're not using urllib3 v2.0 which added the function in the documentation. You'll want to read the documentation for the version you're using

Oh, yes I just pip installed urllib3 and, it installed a preceding version. 
Maybe, if this example is on the front of the repository (README.md), it should be mentioned there or, another example like using PoolManager() should be used?

**Comment by sethmlarson** [comment]
This is where I wish that [modules were callable](https://peps.python.org/pep-0713/) in all the versions we support, we could return a much nicer error in this case. :cry:

**Comment by pquentin** [comment]
Looks like we could use the `sys.modules[__name__].__class__ = FancyModule` syntax mentioned in the PEP? The only mentioned downside is typing but we don't have types in 1.26.x anyway and this is only about providing an error message.

**Comment by sigmavirus24** [comment]
That fancy module was used by requests for import side effects and it was very bug ridden. Pip had similar problems

**Comment by sethmlarson** [comment]
If the route you suggest @pquentin works as expected, I think we should go that route. Going to convert this issue into an investigation into providing a better error message for folks that try to call `urllib3.request(...)` in `1.26.x`.

**Comment by SAMAD101** [comment]
@sethmlarson  can you please assign me this issue? I'd like to work on this.

**Comment by sethmlarson** [comment]
Thanks for the enthusiasm! We assign people to an issue once a PR has been created in order to not dissuade others from starting work that others may have abandoned.

See these docs: https://urllib3.readthedocs.io/en/stable/contributing.html#getting-paid-for-your-contributions

**Comment by pquentin** [comment]
Thanks @sg3-141-592! We just approved your expense on Open Collective: https://opencollective.com/urllib3/expenses/156741
