### ISSUE TITLE
Cannot pass ssl kwarg cert_data in proxy context

### ISSUE THREAD

**Issue by Ousret** [urllib3/urllib3#3065]
Discovered that one while writting tls-in-tls http/2 tests in #3030 

While we can do

```python
with proxy_from_url("...", ca_certs=DEFAULT_CA) as http:
    ...
```

we cannot 

```python
with proxy_from_url("...", cert_data=open(DEFAULT_CA, "rb").read()) as http:
    ...
```

output `unexpected kw key_cert_data for pool conn`

I suspect that we missed propagating required kw.

It is an easy fix.

should patch `SSL_KEYWORDS = (....)` and `class PoolKey(typing.NamedTuple):`

**Comment by imkaka** [comment]
will try to add a PR for this.

**Comment by sethmlarson** [comment]
@ravi-kale this issue now has a bounty.

**Comment by ravi-kale** [comment]
Thank you @sethmlarson for the bounty
