### ISSUE TITLE
Default blocksize inconsistencies between PoolManager and HttpConn

### ISSUE THREAD

**Issue by Ousret** [urllib3/urllib3#3066]
Witnessed that behavior when debugging the network stack, I saw blocks of different sizes whenever I instantiated the conn or passed via the poolmanager.

https://github.com/urllib3/urllib3/blob/7bdf9757c00e7935343ed6d4526683c1ed560052/src/urllib3/poolmanager.py#L52

https://github.com/urllib3/urllib3/blob/7bdf9757c00e7935343ed6d4526683c1ed560052/src/urllib3/connection.py#L137

Is there any adjustment required in your opinion?

**Comment by sethmlarson** [comment]
iirc, the `blocksize` on connections is due to standard library. It might be okay to change it to our own default of 16kB?

**Comment by imkaka** [comment]
will add a patch for it.

**Comment by rajat315315** [comment]
Can someone kindly review and Merge?
