### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by sumit-jr** [urllib3/urllib3#3073]
### Subject

When i try to run the code the pycharm runs code but the postman raises error "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8501): Max retries exceeded with url: /v1/models/potatoes_model:predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x13fff4760>: Failed to establish a new connection: [Errno 61] Connection refused'))"

### Environment

tensorflow==2.13.0rc1
fastapi~=0.97.0
uvicorn~=0.22.0
python-multipart
pillow~=9.4.0
tensorflow-serving-api==2.5.0
matplotlib
numpy~=1.24.2

requests~=2.28.2

At least, paste here the output of:

```from fastapi import FastAPI, File, UploadFile
from fastapi.middleware.cors import CORSMiddleware
import uvicorn
import numpy as np
from io import BytesIO
from PIL import Image
import tensorflow as tf
import requests

app = FastAPI()

origins = [
    "http://localhost",
    "http://localhost:3000",
]
app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

endpoint = "http://localhost:8501/v1/models/potatoes_model:predict"

CLASS_NAMES = ["Early Blight", "Late Blight", "Healthy"]


@app.get("/ping")
async def ping():
    return "Hello, I am alive"


def read_file_as_image(data) -> np.ndarray:
    image = np.array(Image.open(BytesIO(data)))
    return image


@app.post("/predict")
async def predict(
        file: UploadFile = File(...)
):
    image = read_file_as_image(await file.read())
    img_batch = np.expand_dims(image, 0)

    json_data = {
        "instances": img_batch.tolist()
    }

    response = requests.post(endpoint, json=json_data)
    prediction = np.array(response.json()["predictions"][0])

    predicted_class = CLASS_NAMES[np.argmax(prediction)]
    confidence = np.max(prediction)

    return {
        "class": predicted_class,
        "confidence": float(confidence)
    }


if __name__ == "__main__":
    uvicorn.run(app, host='localhost', port=8000)

```

### Steps to Reproduce

A simple and isolated way to reproduce the issue. A code snippet would be great.

### Expected Behavior

It should predict the image of potato and detect disease with confidence.

### Actual Behavior
Postman
Internal Server Error

Pycharm
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8501): Max retries exceeded with url: /v1/models/potatoes_model:predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x13fff4760>: Failed to establish a new connection: [Errno 61] Connection refused'))

**Comment by sethmlarson** [comment]
Your issue doesn't look like a defect in urllib3, it's almost certainly an error of configuration. Unfortunately we're not in a position to debug your issue because it's highly context/environment dependent. Try to figure out if urllib3 isn't configured the same as Postman or if there's something in between your server and client that is different.

**Comment by ranch-hands** [comment]
hi dear @sumit-jr 
I encounter the same problem. how did u manage to solve it?
