### ISSUE TITLE
Connection pool is full

### ISSUE THREAD

**Issue by stevenhubhub** [urllib3/urllib3#3074]
![247110481-33ff3814-7e9c-4e2c-9a5d-3e6d971f13ce.png](https://github.com/urllib3/urllib3/assets/122353354/779a3a96-476e-40a5-8345-f4a52ba9091a)

**Comment by sethmlarson** [comment]
A screenshot of error messages doesn't give us enough information in order to help you. Please fill out the issue template before opening an issue so we can try our best to assist.
