### ISSUE TITLE
NewConnectionError

### ISSUE THREAD

**Issue by stevenhubhub** [urllib3/urllib3#3076]
(pid=34612) WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026A80F76F10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/40444381cdfb64bd9e4a763c4c6cedc9/se/log

(pid=34612) WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026A813D67F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/40444381cdfb64bd9e4a763c4c6cedc9/se/log

(pid=34612) WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026A813D63D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/40444381cdfb64bd9e4a763c4c6cedc9/se/log

**Comment by sethmlarson** [comment]
We can't help you debug your issue unfortunately, it appears as though the target is refusing your connection. Try debugging the connectivity between the two peers.
