### ISSUE TITLE
[1.26] GHA Python 2 support ended on June 17th

### ISSUE THREAD

**Issue by graingert** [urllib3/urllib3#3077]
Warning: The support for python 2.7 will be removed on June 19. Related issue: https://github.com/actions/setup-python/issues/672

**Comment by sethmlarson** [comment]
If anyone can figure out how we can continue testing 2.7 on GitHub Actions that will complete this issue.

**Comment by illia-v** [comment]
@sethmlarson I believe #3137 fixed the issue, do you think anything else should be done?

**Comment by sethmlarson** [comment]
Thanks @illia-v, I thought this hadn't been completed! I'll close this issue and remove the bounty. Closed in https://github.com/urllib3/urllib3/pull/3137
