### ISSUE TITLE
Add BaseHTTPResponse to urllib3.__all__

### ISSUE THREAD

**Issue by Eutropios** [urllib3/urllib3#3078]
### Context

What are you trying to do?

* Attempting to type-hint a function that returns a page.
How do you expect to do it?

```py
def foo(<args>) -> BaseHTTPResponse:
    page: urllib3.BaseHTTPResponse = urllib3.request("GET", <some_url>, <etc>)
    # some form of validation
    return page
```
Is it something you currently cannot do?

* I currently cannot due this do to BaseHTTPResponse not being defined within the __all__ dunder.

Is this related to an existing issue/problem?

* It's related to the intentional choice of deserializing the response into a json after the return statement. I have intentionally chosen this due to the way my functions handle the data in specific cases.

### Alternatives

Can you achieve the same result doing it in an alternative way?

* I could force it into a string and return that instead. Doing that, I would have to import the json module and deserialize the string.

Is the alternative considerable?

* It's considerable but not preferred.

### Duplicate

Has the feature been requested before?

* I have looked through opened and closed issues and this request has not been made before.

### Contribution

Would you be willing to submit a PR?

* Potentially. My idea was to just add BaseHTTPResponse to __all__

**Comment by sethmlarson** [comment]
Sounds like a good idea, thanks for suggesting it. If you're interested you can make this change yourself or we can wait for someone else to tackle it :)

**Comment by Eutropios** [comment]
I can give it a shot! :D
