### ISSUE TITLE
Exception thrown at the import line when using an outdated version of openSSL

### ISSUE THREAD

**Issue by isidore** [urllib3/urllib3#3104]
### Environment
OS: windows
Python: 3.7 (specifically on Windows)
OpenSSL: OpenSSL 1.1.0h 27 Mar 2018
urllib3: v2.0

### Steps to Reproduce
1. Use a system with Windows configured with Python 3.7.
2. Ensure the system's OpenSSL version is 1.1.0h.
3. Execute the code:
```python
import requests as requests
```

### Expected Behavior
The library should load without throwing exceptions, even if the system is configured incorrectly.

### Actual Behavior
An exception is thrown with the message:
``` 
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.1.0h 27 Mar 2018'. See: https://github.com/urllib3/urllib3/issues/2168 
```

### Proposed Fix
To enhance the user experience and adhere to good programming practices, I propose that the exception regarding OpenSSL version incompatibility should be thrown when the library is first called or used, instead of during the import process. This will allow users to handle the exception more gracefully and understand the cause without facing immediate interruptions in their code execution.

This can be achieved by:
1. Moving the version check and exception throw from the module's initialization process to the primary functions/methods of the library.
2. Providing clear documentation or a warning in the library's README or user guide about the OpenSSL version requirements and potential issues.

By making this change, developers will have a smoother experience, especially if they have downstream libraries that depend on this package, while still being informed of the critical version mismatch.

**Comment by sigmavirus24** [comment]
If the prerequisites for an application to work are not present, starting the application and crashing later is far more deceptive than immediately communicating to a user that the prerequisites are not satisfied.

**Comment by isidore** [comment]
the code might not be used. this required me to move the import line into the function so I could do a proper try/except block. that can't be the best practice

**Comment by sethmlarson** [comment]
I think we are going to keep the error as-is, almost all of our users should be using HTTPS so delaying the error until usage doesn't make much of a difference.
