### ISSUE TITLE
urllib3 on python 3.10 seems to load tls module if used as root

### ISSUE THREAD

**Issue by nkshirsagar** [urllib3/urllib3#3105]
### Subject

urlopen() call loads the tls module even if its not loaded. This happens only on python 3.10 and newer. (not on 3.9). 

I was wondering if it has anything to do with this code, in src/urllib3/util/ssl_.py , 

~~~
            # This warning message is pushing users to use 'ssl_minimum_version'
            # instead of both min/max. Best practice is to only set the minimum version and
            # keep the maximum version to be it's default value: 'TLSVersion.MAXIMUM_SUPPORTED'
            warnings.warn(
                "'ssl_version' option is deprecated and will be "
                "removed in urllib3 v2.1.0. Instead use 'ssl_minimum_version'",
                category=DeprecationWarning,
                stacklevel=2,
            )

    # PROTOCOL_TLS is deprecated in Python 3.10 so we always use PROTOCOL_TLS_CLIENT
    context = SSLContext(PROTOCOL_TLS_CLIENT)

    if ssl_minimum_version is not None:
        context.minimum_version = ssl_minimum_version
    else:  # Python <3.10 defaults to 'MINIMUM_SUPPORTED' so explicitly set TLSv1.2 here
        context.minimum_version = TLSVersion.TLSv1_2

    if ssl_maximum_version is not None:
        context.maximum_version = ssl_maximum_version

~~~

### Environment

~~~
Python 3.11.4 (main, Jun  9 2023, 07:59:55) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> import ssl
>>> import urllib3
>>> 
>>> print("OS", platform.platform())
OS Linux-6.2.0-26-generic-x86_64-with-glibc2.37
>>> print("Python", platform.python_version())
Python 3.11.4
>>> print(ssl.OPENSSL_VERSION)
OpenSSL 3.0.8 7 Feb 2023
>>> print("urllib3", urllib3.__version__)
urllib3 1.26.12
>>> 
~~~

### Steps to Reproduce

~~~
from urllib import error, request
url='https://ubuntu.com/'
headers={'user-agent': 'debug'}
req = request.Request(url, headers=headers)
resp = request.urlopen(req)
$ sudo rmmod tls; lsmod | grep tls; echo "no sudo"; python3 testr.py; lsmod | grep tls; echo "sudo"; sudo python3 testr.py; lsmod | grep tls;

no sudo
sudo

tls                   147456  0
~~~

### Expected Behavior

urllib3 should not load the tls module if its not loaded already. This breaks several applications using urllib3 and python 3.10 which are not allowed to load any modules themselves if they're not already loaded. For eg see https://github.com/sosreport/sos/issues/3326

### Actual Behavior
tls module is left loaded after the above code is run as root. 

Thank you [christian.ehrhardt@canonical.com](mailto:christian.ehrhardt@canonical.com) for helping with debugging this and with the  reproducer.

**Comment by nkshirsagar** [comment]
If it helps debug this, we noticed that when the reproducer is run, there's no trace of module loaded in dmesg & journal, nor a failure of loading it if run as non root.

**Comment by sigmavirus24** [comment]
We issue no commands. We rely on the Python on the system to provide OpenSSL bindings. If you're system is detecting that TLS is required and auto enabling it, that's not our big to solve.

In all likelihood you could reproduce this just by importing `ssl` from the standard library and using it to establish a connection. In other words, something in how Python is packaged and distributed is enabling that when tls is used. We are not responsible for inspecting the system for whether that is enabled or not. We are responsible for attempting to secure the connection using what is available to us.

**Comment by pquentin** [comment]
Also note that we're the third-party urllib3 library, while urllib used in your reproducing steps is part of the Python standard library: https://docs.python.org/3/library/urllib.html
