### ISSUE TITLE
下载请求存在问题

### ISSUE THREAD

**Issue by mtrdong** [urllib3/urllib3#3151]
As shown in the figure, for the same URL, urllib can download data normally, but urllib3 returns empty data:

![Snipaste_2023-10-09_10-46-39](https://github.com/urllib3/urllib3/assets/96556098/b3520918-554b-49ff-8161-18fae4ddebf6)

**Comment by pquentin** [comment]
Please don't paste screenshots of code. Pasting code as text is more accesssible and can be modified and run easily. And please open issues in English, using an online translator if needed.

That said, using the following script I get an empty response for both cases:

```
import urllib.request
import urllib3

url = "https://fanyi.baidu.com/etts?lan=uk&text=good&spd=3&source=web"
# urllib
response = urllib.request.urlopen(url)
content = response.read()  # content: b'\xff\xfb...'
print(len(content))
# urllib3
response2 = urllib3.request("GET", url)
content2 = response2.data
print(len(content2))
```

Note that urllib3 and urllib.request both use [http.client](https://docs.python.org/3/library/http.client.html) under the hood, but can send different headers, such as the user agent. And web servers can respond to it differently.

But nothing so far points to a bug in urllib3.
