### ISSUE TITLE
ver 2.x make SSL error

### ISSUE THREAD

**Issue by Mitchell-kw-Lee** [urllib3/urllib3#3171]
### Subject
The exception.
Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_ILLEGAL_PARAMETER] sslv3 alert illegal parameter (_ssl.c:1006)')))

### Environment

Describe your environment.
OS Windows-10-10.0.22621-SP0
Python 3.11.6
OpenSSL 3.0.11 19 Sep 2023
urllib3 2.0.7

### Steps to Reproduce

by using below request object, it occured. (with urllib3 1.26.x is fine)

from urllib3.util.retry import Retry
import requests
from requests.adapters import HTTPAdapter
def getRequestObject(retries : int = 2, session=None, backoff_factor=0.8):
	with warnings.catch_warnings():
		warnings.filterwarnings('error')
		try:
			urllib3.Retry(method_whitelist={})
		except (DeprecationWarning, TypeError):  # TypeError covers for future removal
			RETRY_METHODS_PARM = 'allowed_methods'
		else:
			RETRY_METHODS_PARM = 'method_whitelist'

	RETRY_KWARGS = dict(
		total=retries,
		connect=retries,
		read=retries,
		redirect=10,
		backoff_factor=backoff_factor
	)
	RETRY_KWARGS[RETRY_METHODS_PARM] = {'POST'}
	retry = urllib3.Retry(**RETRY_KWARGS)
	adapter = HTTPAdapter(max_retries=retry)

	session = session or requests.Session()
	session.mount('http://', adapter)
	session.mount('https://', adapter)
	return session
getRequestObject().get('https://any url')

### Expected Behavior

No exception

### Actual Behavior

it spit out below exception error from any of https urls.
"Max retries exceeded with url: xxxxxxxxxxxxxxxxxxxxxxxxxx (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_ILLEGAL_PARAMETER] sslv3 alert illegal parameter (_ssl.c:1006)')))"

**Comment by sethmlarson** [comment]
Unfortunately it's very likely that there's an issue either with your OpenSSL configuration, the peer, certificate, or something like that and not with urllib3 in particular. In order to prove that it is indeed an issue with urllib3, please create a TLS connection to the host and port with `ssl.create_default_context().wrap_socket(socket.create_connection(("<your-host-here>", 443)))` Sorry we can't be of more help, going to close this due to its likelihood of not being a defect in urllib3. Will reopen if you report back otherwise.

**Comment by Mitchell-kw-Lee** [comment]
When do below two lines, 
   sock = socket.create_connection((r"apis.data.go.kr", 443))
   ssl_context = ssl.create_default_context().wrap_socket(sock)"
the exception says "check_hostname requires server_hostname"
You try and debug with above origin code in the first thread with below.

objectRequest = getRequestObject('GET')
objectRequest.get('https://apis.data.go.kr/1160100/service/GetStocDiviInfoService/getDiviInfo', verify=False)
