### ISSUE TITLE
Support `Content-Encoding: x-gzip`

### ISSUE THREAD

**Issue by SpecLad** [urllib3/urllib3#3174]
### Context

I'm using an API that returns a gzipped response, but the reported `Content-Encoding` is `x-gzip` rather than `gzip`, so urllib3 fails to decompress it.

According to [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html#section-8.4.1.3):

>  A recipient SHOULD consider "x-gzip" to be equivalent to "gzip".

Therefore, I would expect e.g. `Response.read(decode_content=True)` to automatically decompress such responses.

Unfortunately, I can't find a public server that would produce such responses, so I can't provide a simple reproducer.

### Alternatives

I can set `decode_content=False` and gunzip the content manually.

### Duplicate

> Has the feature been requested before?

Not that I could find.

### Contribution

> Would you be willing to submit a PR?

Probably not.

**Comment by sigmavirus24** [comment]
https://github.com/urllib3/urllib3/blob/7d0648b53cf4159e7f3ebb8353cb642942ec93e6/src/urllib3/response.py#L207-L220 could be trivially updated to say, after we get past the MultiDecoder return do a `if mode.startswith("x-"):\n\t\tmode = mode[2:]` and then we don't need to worry about `x-gzip` or `x-compress`. And if any other encodings are eXperimental first, we can handle those backwards compatibly as well.

**Comment by SpecLad** [comment]
FWIW, I don't think it's a good idea to blindly assume that `x-foo` is the same as `foo`, since there is no guarantee that will be the case. Plus, the only registered `x-` encodings are `x-gzip` and `x-compress` (and urllib3 doesn't even support `compress`).

**Comment by sethmlarson** [comment]
@jeremycline has submitted a PR for this issue.

**Comment by skydiver1980** [comment]
Let's do what we have to do to get this done
