### ISSUE TITLE
Migrate run_server_in_thread and run_server_and_proxy_in_thread to Hypercorn

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#3197]
The first blocker to add HTTP/2 support to urllib3 is to have a test server that supports HTTP/2. Since https://github.com/tornadoweb/tornado/issues/1438, we're migrating to Hypercorn. This issue is about migrating all uses of `run_tornado_loop_in_thread` in test/conftest.py.

- [x] #3198 
- [ ] #3222

**Comment by sethmlarson** [comment]
From our discussion it seems like proxies might be much harder than a regular server. Let's split the proxy issue off?
