### ISSUE TITLE
Handle OpenSSL 3.2.0 new error message for unexpected unencrypted records

### ISSUE THREAD

**Issue by ecerulm** [urllib3/urllib3#3268]
### Subject

I was expecting to all tests working on "main" branch but there are 3 failing test cases

* TestProxyManager::test_https_proxymanager_connected_to_http_proxy[http]
* TestProxyManager::test_https_proxymanager_connected_to_http_proxy[https]
* TestSSL::test_ssl_failure_midway_through_conn 

```
nox -s test-3.12 
...
FAILED test/with_dummyserver/test_socketlevel.py::TestProxyManager::test_https_proxymanager_connected_to_http_proxy[http] - assert 'Your proxy appears to only use HTTP and not HTTPS' in "('Unable to connect to proxy', SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1000)')))"
FAILED test/with_dummyserver/test_socketlevel.py::TestProxyManager::test_https_proxymanager_connected_to_http_proxy[https] - assert 'Your proxy appears to only use HTTP and not HTTPS' in "('Unable to connect to proxy', SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1000)')))"
FAILED test/with_dummyserver/test_socketlevel.py::TestSSL::test_ssl_failure_midway_through_conn - AssertionError: Regex pattern did not match.
```

### Environment

```
OS macOS-14.2.1-x86_64-i386-64bit
Python 3.12.1
OpenSSL 3.2.0 23 Nov 2023
urllib3 2.1.0
```
### Steps to Reproduce

```
nox -s test-3.12 
```

### Expected Behavior

The test should work, or they should be skipped, or if it's because they are not supported on macOS, then may it should be conditionally skipped. 

### Actual Behavior

3 test fails

**Comment by ecerulm** [comment]
Just to be clear if I skipped those test manually with `-k` then it will pass.

``` 
nox -R -s test-3.12 -- -k 'not (test_https_proxymanager_connected_to_http_proxy or test_ssl_failure_midway_through_conn)'

...
==================================================================== 1750 passed, 311 skipped, 4 deselected, 58 warnings in 320.33s (0:05:20) =====================================================================
nox > Session test-3.12 was successful.
```

**Comment by sethmlarson** [comment]
@ecerulm Thanks for reporting this, it looks like OpenSSL 3.2.0 may have changed the error message that gets raised for these cases. I believe extending our regex to catch this case should be all that's needed.

**Comment by ecerulm** [comment]
I've been testing more 


For the 2 test cases below  the issue seems to be timing
```
test/with_dummyserver/test_socketlevel.py::TestProxyManager::test_https_proxymanager_connected_to_http_proxy[http]
test/with_dummyserver/test_socketlevel.py::TestProxyManager::test_https_proxymanager_connected_to_http_proxy[https]```

If at https://github.com/urllib3/urllib3/blob/2ac4efacfef5182aaef3e26a4f1e066ab228dfdd/test/with_dummyserver/test_socketlevel.py#L1252 I add a wait statement then it works all the time. 

```
        self._start_server(http_socket_handler)
        import time
        time.sleep(1)
```

it seems that the server is not ready that quick.

**Comment by ecerulm** [comment]
> @ecerulm Thanks for reporting this, it looks like OpenSSL 3.2.0 may have changed the error message that gets raised for these cases. I believe extending our regex to catch this case should be all that's needed.

I added PR #3271 to recognize the SSLError  "record layer failure" and map it to  "Your proxy appears to only use HTTP and not HTTPS..."
