### ISSUE TITLE
Provide a Test/Test-Mechanism for #3292

### ISSUE THREAD

**Issue by abebeos** [urllib3/urllib3#3293]
(re #2799, #3292)

> @illia-v , as for a test, me blacking out a bit. It seems this needs special constructs within the test-system (possibly already available).

Some kind of mock-object must ensure that the first `_raw_read` does not return enough bytes, thus the loop is entered.

_Originally posted by @abebeos in https://github.com/urllib3/urllib3/issues/3292#issuecomment-1902059283_

https://github.com/urllib3/urllib3/blob/8754be950dcf58739ad9b16ff1b46e2c096d1346/src/urllib3/response.py#L916-L953

**Comment by sigmavirus24** [comment]
@abebeos this project does not open separate issues as a means of excusing a lack of testing for an open pull request. If you feel there's a gap that needs to be addressed, please address it as part of the existing pull request. If you can't find a way to write tests for the changes you're making, we can coach you on that if necessary.

**Comment by abebeos** [comment]
Follow-up: https://github.com/abebeos/urllib3/issues/7
