### ISSUE TITLE
Ensure HTTP/2 isn't offered for tunnel CONNECT requests

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#3298]
We don't intend to support HTTP/2 for establishing a proxy tunnel, HTTP/1.1 works just fine for this purpose.

**Comment by Nightrider0098** [comment]
Hey i could see that there is a Error thrown when using Proxy config or proxy flag in http2. 
<img width="980" alt="image" src="https://github.com/urllib3/urllib3/assets/39752890/22160c8f-a87d-46bf-b0d1-51d4e0e33c28">

Is there any other thing that needs to be done?

**Comment by Nightrider0098** [comment]
Hey have raise a pr. Do we need any other flags also? 
https://github.com/urllib3/urllib3/pull/3321
