### ISSUE TITLE
Add support for sending a request body with HTTP/2

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#3302]
* Requests that don't have a body should set `end_stream=True` on the Headers event.
* There should never be an empty `Data` event, some HTTP/2 implementations don't handle this properly.
* Must respect window of server. Maybe this is handled automatically?

**Comment by Nightrider0098** [comment]
Hey was working on the issue. Tried to add a checks and while loop when handling body. 
https://github.com/urllib3/urllib3/pull/3322

Is it the correct way to handle the body, or i need to do something different.

**Comment by tcdent** [comment]
Opened a pull request for this: https://github.com/urllib3/urllib3/pull/3421

**Comment by sethmlarson** [comment]
Closed in https://github.com/urllib3/urllib3/pull/3421
