### ISSUE TITLE
Move length_remaining into BaseHTTPResponse

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#3315]
Now that `HTTPResponse` and `HTTP2Response` both have a `length_remaining` attribute, it should be made part of `BaseHTTPResponse`. This will also remove one mypy ignore comment: https://github.com/urllib3/urllib3/pull/3311#pullrequestreview-1841977649.

I'm happy to provide more details if needed.

**Comment by programmer-ke** [comment]
Hey @pquentin, see if the attached PR fixes this.
