### ISSUE TITLE
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

### ISSUE THREAD

**Issue by rishav667** [urllib3/urllib3#3353]
can anyone help me with the below error
Error occurred ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
I am using requests==2.28.2 version and while logging into tableau using rest api the error is coming.
As I am first creating the session and then doing the post request.
The issue is coming only in prod environment

**Comment by sigmavirus24** [comment]
Duplicate of https://github.com/psf/requests/issues/6645
