### ISSUE TITLE
imprecise types on `urllib3.Retry.new` / `urllib3.Retry.increment`

### ISSUE THREAD

**Issue by asottile-sentry** [urllib3/urllib3#3363]
### Subject

when attempting to subclass `urllib3.Retry` -- one would want to implement `def increment(...) -> Self:` as both `increment` and `new` [preserve the type](https://github.com/urllib3/urllib3/blob/733f638a2faa02b4ff8a9f3b5668949d39396b8b/src/urllib3/util/retry.py#L264) but label the return value as `Retry` (essentially breaking subclassing types): https://github.com/urllib3/urllib3/blob/733f638a2faa02b4ff8a9f3b5668949d39396b8b/src/urllib3/util/retry.py#L243

if the codebase were python 3.11+ I would use `from typing import Self` -- it appears elsewhere in the codebase one-off `SelfT` `TypeVar`s are created -- that pattern could be followed here

alternatively the `TYPE_CHECKING` trick could be used and is understood by the current major type checkers:

```
if TYPE_CHECKING:
    from typing_extensions import Self
```

### Environment

N/A -- latest primary branch source, mypy 1.9

### Steps to Reproduce

```python
from typing import Any, Self
import urllib3
class MyRetry(urllib3.Retry):
    def increment(self, *a: Any, **k: Any) -> Self:  # type error on this line!
        return super().increment(*a, **k)
```

```console
$ mypy t.py
t.py:5: error: Incompatible return value type (got "Retry", expected "Self")  [return-value]
Found 1 error in 1 file (checked 1 source file)
```

### Expected Behavior

no errors

### Actual Behavior

shown above

**Comment by illia-v** [comment]
Thanks for reporting this!

> if the codebase were python 3.11+ I would use `from typing import Self` -- it appears elsewhere in the codebase one-off `SelfT` `TypeVar`s are created -- that pattern could be followed here
> 
> alternatively the `TYPE_CHECKING` trick could be used and is understood by the current major type checkers:
> 
> ```
> if TYPE_CHECKING:
>     from typing_extensions import Self
> ```

`Self` from `typing_extensions` looks cleaner, it's already been used in the codebase too
https://github.com/urllib3/urllib3/blob/733f638a2faa02b4ff8a9f3b5668949d39396b8b/src/urllib3/_collections.py#L13
https://github.com/urllib3/urllib3/blob/733f638a2faa02b4ff8a9f3b5668949d39396b8b/src/urllib3/_collections.py#L396
