### ISSUE TITLE
"unable to get local issuer certificate", even though cURL works with the same website

### ISSUE THREAD

**Issue by nawordar** [urllib3/urllib3#3370]
### Subject

I am trying to build and test my Python application in CI. It uses Poetry for dependency management and its `pyproject.toml` contains references to other repositories on our internal GitLab instance. As Poetry uses urllib3 and I was able to reproduce the problem using urllib3 alone, I am reporting the problem here. 

We are using a custom certificate for websites hosted on intranet. I installed the CA certificate provided by administrator in the container used for testing:

```dockerfile
COPY certs /usr/local/share/ca-certificates/
RUN update-ca-certificates
```

Inside the container on my local machine, cURL is able to access GitLab, but urllib3 is not:

<details><summary>urllib3 error</summary>

```
root@02636afb4ed6:/# curl https://gitlab.company.com
<html><body>You are being <a href="https://gitlab.company.com/users/sign_in">redirected</a>.</body></html>
root@02636afb4ed6:/# echo $?
0
root@02636afb4ed6:/# python3 -c "import urllib3; http = urllib3.PoolManager(); http.request('GET', 'https://gitlab.company.com')"
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 405, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1061, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1108, in _create
    self.do_handshake()
  File "/usr/lib/python3.11/ssl.py", line 1379, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 828, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 828, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 828, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 800, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gitlab.company.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
```

</details>

To make sure that the problem is not caused by urllib3 not using system certificates, I passed the path explicitly: `python3 -c "import urllib3; http = urllib3.PoolManager(ca_certs='/etc/ssl/certs/ca-certificates.crt'); http.request('GET', 'https://gitlab.company.com')"`. This did not change anything.

I also tried downloading certificate chains from the browser (Firefox found two), concatenating them and installing in the system, but that didn't help either.

### Environment

Container based on the `docker.io/ubuntu:23.10` image.

```
OS Linux-6.1.82-1-MANJARO-x86_64-with-glibc2.38
Python 3.11.6
OpenSSL 3.0.10 1 Aug 2023
urllib3 1.26.16
```

### Steps to Reproduce

Unfortunately, the problem concerns website on the intranet with a custom certificate and I can't think of a way to reproduce it outside that environment. Anyway, here is the Dockerfile I'm using:

<details><summary>Dockerfile</summary>
<p>

```dockerfile
FROM docker.io/ubuntu:23.10

# Make pip and requests use system certificates
ENV PIP_CERT=/etc/ssl/certs/ca-certificates.crt
ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update                                \
 && apt-get install --no-install-recommends --yes \
        ca-certificates                           \
        git                                       \
        openssh-client                            \
        pipx                                      \
        python3-poetry                            \
        twine                                     \
 && rm -rf /var/lib/apt/lists/*                   \
  ;

# Install certificates
COPY certs /usr/local/share/ca-certificates/
RUN update-ca-certificates
```

</p>
</details> 

### Expected Behavior

Running `python3 -c "import urllib3; http = urllib3.PoolManager(); http.request('GET', 'https://gitlab.company.com')"` does not raise an error.

### Actual Behavior

Running `python3 -c "import urllib3; http = urllib3.PoolManager(); http.request('GET', 'https://gitlab.company.com')"` raises an error.

**Comment by sigmavirus24** [comment]
This sounds like your internal GitLab instance is mis-configured and/or the certificate chain you've been provided are not complete. Without knowing how your company is managing its internal PKI system, let me give you some details:

There is typically a Root of the chain of trust. This, if your company is following CA/B forum standards can be valid for 20-25 years.

There is typically also at least one other chain between the Root and an issued certificate, i.e., the Issuer. This is typically valid for ~5-10 years.

The Issuer is what signs and provides the certificate for a service. The service (GitLab in your case) should be returning in the TLS Handshake:

* Its certificate
* The certificate for the Issuer
* The certificate for the Root

If it only provides its certificate, then urllib3 cannot verify that if the Issuer is not in your set of trusted certificates.

You can see what your server provides by using `openssl s_client -connect gitlab.company.com:443` and seeing what Certs are returned. Likewise, `cURL` will show you certificate information with `-vv` (or maybe `-vvv` I can't remember which) and show you what it does for TLS verification. Also, please include your curl command when you say that it works since it's possible you're specifying a flag that in fact makes it work but does not verify TLS certificate chains of trust.

**Comment by nawordar** [comment]
I finally managed to resolve the issue. In fact, I didn't have the whole certificate chain installed in the container. The weirdest thing is that cURL worked. The output just shows this during certificate verification:
```
# curl -vvv https://gitlab.company.com
...
* Server certificate:
*  subject: CN=*.company.com
*  start date: Oct 25 13:07:21 2023 GMT
*  expire date: Oct 24 13:07:20 2024 GMT
*  subjectAltName: host "gitlab.company.com" matched cert's "*.company.com"
*  issuer: C=PL; O=cyber_Folks S.A.; CN=cyber_Folks
*  SSL certificate verify ok.
...
```
It looks like cURL doesn't verify the whole chain.

So you were right that the problem was not with urllib3, but I reported it as a bug, since cURL worked. Anyway, thank you for your help. I'm still learning about certificates.

**Comment by sigmavirus24** [comment]
Curl may look up and retrieve the intermediates which is what browsers do but openssl does not do this and Python is using openssl so it does not do it. Furthermore, it is widely frowned upon as a bad practice even if browsers have no good way of undoing the harm they have done. Please file a bug with your gitlab instance managers to do the right thing here. They should be returning the full chain
