### ISSUE TITLE
All Retry backoff_factor to optionally start applying from first retry

### ISSUE THREAD

**Issue by Berbe** [urllib3/urllib3#3375]
### Context
Managing HTTP retries with `urllib3`'s `Retry`, I read [from the docs](https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html#urllib3.util.Retry) the `backoff_factor` parameter applies from the second retry onwards.
This is confirmed though [some 2016 issue](https://github.com/urllib3/urllib3/issues/847).

While default behaviour seems based on someone habits & experience, it would be nice to give the user a little more control over the backoff strategy.

### Alternatives
No other way found, except manually implementing a retry strategy.

### Duplicate
No issue found

### Contribution

**Would you be willing to submit a PR?**
Yes
However, tests might be lacking, and I would be glad to get some contributing writing them.

**Comment by Berbe** [comment]
I made an attempt on a test.

**Comment by sethmlarson** [comment]
Thanks for opening this. Our retry backoff model has been in place for some time and I'm not super keen on adding yet another parameter for retries, especially because this has only been requested now and in 2016. I hesitate to suggest we change the default though, it's been working the same way since 2014 at least.

**Comment by sigmavirus24** [comment]
I would suggest stamina as that package is generic and works with many HTTP client libraries

**Comment by sethmlarson** [comment]
Going to close this one in favor of the suggestions above.

**Comment by soxofaan** [comment]
The stamina proposal is interesting, but this drags in additional dependencies, which feels like overkill to circumvent just this if:
https://github.com/urllib3/urllib3/blob/c5595202baaf77259b6404d455442d68ea33dbaa/src/urllib3/util/retry.py#L312-L313

I understand the decision to not further complicate the Retry API, bit is there some wiggle room here?

For example: would it be an option to keep the existing API and behavior, but just refactor out this block to a new method:
https://github.com/urllib3/urllib3/blob/c5595202baaf77259b6404d455442d68ea33dbaa/src/urllib3/util/retry.py#L312-L315

Then one just has to subclass `Retry` and override that method to get a sleep before the first retry.
And maybe even better, it also allows implementing some different backoff policy, without urllib3 having to provide and document a whole new API surface.
