### ISSUE TITLE
Dependency management issue

### ISSUE THREAD

**Issue by sambhavnoobcoder** [urllib3/urllib3#3390]
### Subject

I tried installing urllib3 on a Ubuntu system . on first install it gave the error asking a version of idna<4 and idna>=2.5 . however on installing idna ==2.5 , it asked me a version of idna >=2.8 , hence making a redundant install step  
### Environment

Ubuntu 22.04 LTS 

### Steps to Reproduce

pip install urllib3
### Expected Behavior

requires idna >=2.8

What should happen.

requires idna >=2.8

### Actual Behavior
requires idna <4 ,>=2.5
What happens instead.
You may attach logs, packet captures, etc.

**Comment by sigmavirus24** [comment]
Please provide actual commands and real output. Real pip wouldn't tell you to install 2.5 and then 2.8. Likely what you saw was a conflict with your system packages or with some other dependency you have. In that case you didn't read the message closely and didn't understand what it was telling you (that it couldn't resolve the conflict). In that case, there's no big in this project

**Comment by sethmlarson** [comment]
Closing this due to lack of response.
