### ISSUE TITLE
publish.yml uses two different versions of actions/download-artifact

### ISSUE THREAD

**Issue by nedbat** [urllib3/urllib3#3418]
### Subject

In https://github.com/urllib3/urllib3/blob/main/.github/workflows/publish.yml, there are two jobs, one for pypi and one for testpypi.  They pin different versions of the download-artifact action:

https://github.com/urllib3/urllib3/blob/main/.github/workflows/publish.yml#L77
```yaml
      uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
```

https://github.com/urllib3/urllib3/blob/main/.github/workflows/publish.yml#L102
```yaml
      uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
```

Is there a reason for them to be different?  BTW: what do you use to pin to hashes with the version in the comments?

**Comment by sethmlarson** [comment]
@nedbat  Thanks for bringing this to our attention! I've used [Frizbee](https://github.com/stacklok/frizbee) for locking a bunch of tagged Github Actions, the content is preserved by Dependabot if it's there.
