### ISSUE TITLE
pyproject.toml specifies an illegal value in the "dynamic" field

### ISSUE THREAD

**Issue by dralley** [urllib3/urllib3#3420]
### Subject

pyproject.toml specifies "version" in the "dynamic" field

https://github.com/urllib3/urllib3/blob/main/pyproject.toml#L39

"version" is an illegal value for this field as per the metadata specification

https://packaging.python.org/en/latest/specifications/core-metadata/#dynamic-multiple-use

I'm unsure if there was a particular intention behind specifying this, but anyway when I inspect the metadata of the built packages and that provided by PyPI, the dynamic field is not set in those places, possibly because of sanitization.

**Comment by sigmavirus24** [comment]
@dralley a very quick look shows this to be an artifact of a prior build-system: [flit](https://flit.pypa.io/en/latest/pyproject_toml.html#new-style-metadata) whose docs specifically instruct users to place this there.

I do not believe either hatch or hatch-vcs rely on this behaviour though, so I think it should have been fixed when we migrated to those systems recently. cc @pquentin

**Comment by pquentin** [comment]
Hello, the version is dynamic because we read it from git. And it was dynamic before that when we read it from the `src/urllib3/_version.py` file. It is allowed as mentioned here: https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-project-metadata-the-project-table

And documented in Hatch docs here: https://hatch.pypa.io/1.10/config/metadata/#version

**Comment by dralley** [comment]
Well it seems like the wording of the metadata format docs needs to be adjusted then.  Trying to close the gap between what those docs say and this line 

>A string containing the name of another core metadata field. The field names Name, Version, and Metadata-Version may not be specified in this field.

Is awfully difficult.

**Comment by pquentin** [comment]
This specification does not apply to pyproject.toml but to the distributions uploaded to PyPI.
