### ISSUE TITLE
Cannot pass host parameter to PoolManager

### ISSUE THREAD

**Issue by mbUSC** [urllib3/urllib3#3422]
https://urllib3.readthedocs.io/en/stable/reference/urllib3.poolmanager.html

Since `host` is not a keyword parameter, it is ignored when passed into the `PoolManager` constructor as `**connection_pool_kw`

**Comment by sethmlarson** [comment]
That's because `host` is not something you should configure at the "PoolManager"-level, instead `host` is determined by the absolute URL you pass with `.request()`.
