### ISSUE TITLE
v2.0.5 is tagged strangely

### ISSUE THREAD

**Issue by wimglenn** [urllib3/urllib3#3423]
very minor - tripped up some scripting

```
2.0.0
2.0.0a1
2.0.0a2
2.0.0a3
2.0.0a4
2.0.1
2.0.2
2.0.3
2.0.4
v2.0.5   <------------
2.0.6
2.0.7
2.1.0
2.2.0
2.2.1
2.2.2
```

You might want to re-push this tag as `2.0.5` ?

**Comment by sethmlarson** [comment]
Yeah, that is a known issue unfortunately. I've pushed a tag with the correct naming: https://github.com/urllib3/urllib3/releases/tag/2.0.5
