### ISSUE TITLE
why this happens ??

### ISSUE THREAD

**Issue by S0u1Gh0st** [urllib3/urllib3#3426]
I was writing a couple of scripts..
The strange thing is that when I try to run a file in the log I get an error in another file
first one named urllib3.py

import urllib3 as url3
import urllib.request as req

rs = req("GET","https://httpbin.org/")

and the error say .. the module urllib3 dont have 'request'

i try the second script named sopita.py

import requests
from bs4 import BeautifulSoup 

URL = "https://duckduckgo.com/"
page = requests.get(URL)

print(page.text)

# the error
(pynv) [layka@matrix net]$ python sopita.py
Traceback (most recent call last):
  File "/home/layka/py/net/sopita.py", line 1, in <module>
    import requests
  File "/home/layka/py/pynv/lib/python3.12/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/layka/py/net/urllib3.py", line 4, in <module>
    rs = urllib3.request("GET","http://192.168.1.1")
         ^^^^^^^
NameError: name 'urllib3' is not defined

**Comment by sethmlarson** [comment]
Thanks for opening this issue. Unfortunately, your report is unlikely to be a defect in Python and instead a result of either your script or environment. I recommend checking to make sure you don't have any files named `urllib3`, that you have urllib3 2.0+ installed (so you can use `urllib3.request("GET", "https://...")`, and that your script doesn't have other issues.

If you're looking for general Python help, you can check out the [Python Discord](https://www.pythondiscord.com/) for folks that can help you further.
