### ISSUE TITLE
Automatically detecting non-relative imports

### ISSUE THREAD

**Issue by kevinburke** [urllib3/urllib3#345]
Lately there was an issue with a non-relative import breaking pip's vendoring of urllib3. I was wondering if we can add an automated check for a non-relative import that would break vendoring.

I tried adding this to tox.ini

```
egrep -R "^(\s+)from urllib3|^(\s+)import urllib3" urllib3
```

However this matches a false positive in pyopenssl.py, sadly.

Wondering if there's a best practice here or something we can do.

**Comment by jayvdb** [comment]
fwiw, this will be achieved by https://github.com/shazow/urllib3/pull/398
