### ISSUE TITLE
optimization request: _encode_invalid_chars is slow

### ISSUE THREAD

**Issue by holmanb** [urllib3/urllib3#3454]
### Context

While benchmarking cloud-init's unit tests, I notice that the largest amount of time is spent, surprisingly, in urllib3's `url.py::_encode_invalid_chars()`.
```
   Ordered by: internal time
   List reduced from 10107 to 3032 due to restriction <0.3>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   236638    5.866    0.000    9.313    0.000 url.py:227(_encode_invalid_chars)
```

### Duplicate

Has the feature been requested before?

I searched and didn't see any requests to optimize this function.

### Contribution

Would you be willing to submit a PR?

I put together a prototype of an idea that passes the unittests and cuts over half of a second off urllib3's unittests for me. It complicates the function a bit, but I'll put up a PR and we can discuss if it is a desirable addition.

_(Help can be provided if you need assistance submitting a PR)_

**Comment by pquentin** [comment]
I'd like to understand cloud-init's use case a bit more. How did you end up with 236k calls to this function? Is this over a long period of time?

**Comment by sethmlarson** [comment]
Closing due to lack of response.
