### ISSUE TITLE
What is a dnf/yum user to do?

### ISSUE THREAD

**Issue by jasonperrone** [urllib3/urllib3#3487]
I'm on RHEL 8.10. I am getting constantly dinged by my cyber security group for this library. It's telling me that there is a security vulnerability and that I need to upgrade to 1.26.19. (I'm currently on 1.24.2). But this is installed from the Red Hat yum repo and it seems to be stuck at 1.24.2. There's never a further update available. So I said to myself, ok let's uninstall it from the repo and install it with pip. But, if I attempt to dnf remove python3-urllib3, it wants to delete like 50 other dependencies, so I am too afraid to remove it. 

Honestly don't know what to do.

**Comment by sethmlarson** [comment]
Sorry you're in this predicament. We aren't in control of how Red Hat packages our software or which security fixes are patched in to their distribution, please open an issue with them. Please note that they may selectively patch issues even if they don't increase the version number to 1.26.19, for example, you'll have to see if the vulnerabilities you're being "dinged" for are already patched or not in their distribution.

**Comment by jasonperrone** [comment]
Thanks, I will do that!
