### ISSUE TITLE
Unable to use tls-in-tls for server side

### ISSUE THREAD

**Issue by jnewbigin** [urllib3/urllib3#3533]
I am implementing a simple https proxy with man-in-the-middle capability. For this, I require tls-in-tls and was excited to find that `urllib3` implemented that feature.

However, at https://github.com/urllib3/urllib3/blob/905549d64a948abd4b6962edecb8dd5569166275/src/urllib3/util/ssltransport.py#L65 you can see that
`SSLTransport` makes a call to `ssl_context.wrap_bio` but does not supply a value for `server_side`. That then takes the default value of `False` <https://docs.python.org/3/library/ssl.html#ssl.SSLContext.wrap_bio>

For my proxy, I require to set `server_side=True`.

I have successfully used the `SSLTransport` class by creating a subclass and overriding `__init__`  to change the call to `wrap_bio` (see below). This means I have now duplicated the rest of the `__init__` function and don't make a call to the superclass which is not ideal.

By exposing the `server_side` flag in the constructor for `SSLTransport` it would serve my use case well an retain full compatibility with existing usages.

If you are supportive of this, I can prepare a PR

```
class SSLTransportServer(SSLTransport):
    def __init__(
            self,
            socket: socket.socket,
            ssl_context: ssl.SSLContext,
            server_hostname: str | None = None,
            suppress_ragged_eofs: bool = True,
            server_side: bool = False,
    ) -> None:
        """
        Create an SSLTransport around socket using the provided ssl_context.
        suitable for server side of the TLS connection
        """
        self.incoming = ssl.MemoryBIO()
        self.outgoing = ssl.MemoryBIO()

        self.suppress_ragged_eofs = suppress_ragged_eofs
        self.socket = socket

        self.sslobj = ssl_context.wrap_bio(
            self.incoming, self.outgoing, server_hostname=server_hostname, server_side=server_side
        )

        # Perform initial handshake.
        self._ssl_io_loop(self.sslobj.do_handshake)
```

**Comment by pquentin** [comment]
Hello, and thank you for opening this issue! I understand that only a small change is needed to make SSLTransport useful for servers. However, this class is not part of urllib3's public API, so we will not make changes to accommodate other uses. Our goal is to be able to modify this file without having to consider server needs. This is not just a theoretical concern; in the past, we've received complaints from users after we altered internal helper functions.

However, you are welcome to copy this file for use in your project, provided you include the original license. Thank you!
