### ISSUE TITLE
Vendor `backports.ssl` package

### ISSUE THREAD

**Issue by alekstorm** [urllib3/urllib3#370]
(Continuing the conversation from [#367](https://github.com/shazow/urllib3/issues/367#issuecomment-39660734))

I admit I'm at a bit of a loss as to how to do this - `backports.ssl` is designed to be a drop-in replacement for the standard `ssl` module, but since it depends on pyOpenSSL, we can't automatically switch to it unless the latter is installed as well. Does that mean pyOpenSSL should be vendored in as well, or specified in the `extras_requires` parameter to `setuptools.setup()`? Should we be automatically switching at all (with explanatory logging statements), or allow the user to configure which `ssl` implementation is used, or both? Should `backports.ssl` even be vendored, since it can be monkey-patched in by the user a la gevent with `backports.ssl.monkey.patch()`?

Note also that since OS X ships with an ancient OpenSSL by default, which Tornado relies on, the urllib3 test suite hangs on each of the methods in `test_https.TestHTTPS_TLSv1` unless `backports.ssl.monkey.patch()` is called or the user recompiles their Python against a newer (probably Homebrew-installed) OpenSSL.

Guidance here would be much appreciated; I'm prepared to make all necessary changes to `urllib3` and `backports.ssl` to get them to play nicely together, but I need to know your (@shazow's) vision for the interop first.
##

**Comment by sethmlarson** [comment]
I don't think this is necessary any more.
