### ISSUE TITLE
HTTPResponse.read() returns empty string when response has `Connection: close`

### ISSUE THREAD

**Issue by alekstorm** [urllib3/urllib3#373]
Compare:

```
import urllib3
http = urllib3.PoolManager()
res = http.request('GET', 'https://signin.infusionsoft.com/login')
print res.read()
```

(Prints `''`)

```
import httplib
conn = httplib.HTTPSConnection('signin.infusionsoft.com')
conn.request('GET', '/login')
res = conn.getresponse()
print res.read()
```

(Prints a large HTML entity body)

**Comment by duongnam99** [comment]
it's took me 2 hour's to relized this problem :(( from 5am to 7am :((

**Comment by pquentin** [comment]
@duongnam99 Sorry, but this is how our API works: using `read()` or `stream()` only makes sense if you use `preload_content=False`. See https://urllib3.readthedocs.io/en/latest/advanced-usage.html#streaming-and-io for more details.
