### ISSUE TITLE
allow http requests through https proxy

### ISSUE THREAD

**Issue by bninja** [urllib3/urllib3#476]
this has been brought up a few times for `requests`:
- https://github.com/kennethreitz/requests/issues/1622
- https://github.com/kennethreitz/requests/issues/1903

and elsewhere:
- http://wiki.squid-cache.org/Features/HTTPS#Direct_SSL.2BAC8-TLS_connection
- http://dev.chromium.org/developers/design-documents/secure-web-proxy

case for me is: send http req --ssl--> https proxy (manipulates and fwds) --> origin. but `ProxyManager` tunnels these reqs unnecessarily (?).

would like to disable tunneling for https proxies so behavior is same as for http proxies just over ssl'd cxn. leaves open  proxying https reqs through https proxy (this doesnt appear to work now, but dont specifically need it).
##

**Comment by phuslu** [comment]
Hi @bninja @Lukasa 

I tried fix requests/urllib3 https-proxy by https://github.com/shazow/urllib3/pull/1121

Alough it's a very draftly patch, but it really make requests/urllib3 works with https-proxy now 😄 
Would you please have a look https://github.com/shazow/urllib3/pull/1121 ?

**Comment by sethmlarson** [comment]
Support for this has landed in `master` in https://github.com/urllib3/urllib3/pull/1679
