### ISSUE TITLE
wrap_socket does not accept server_hostname in 2.7.x (breaks with gevent)

### ISSUE THREAD

**Issue by sharoonthomas** [urllib3/urllib3#482]
The recent backport of SNI related features into 2.7 series has resulted in urllib looking at python 2.7.8+ as python 3.2+ and ssl_.py calls wrap_socket with the server_hostname as argument. While this works well when not monkey patched with gevent, I am reporting the bug here since one of the features of this library is gevent compat.
##

**Comment by ssbarnea** [comment]
3 months later and we still have this bug open even if we do have a patch. I suppose it would make sense to remove Python 2.7 compatibility in this case.

**Comment by Lukasa** [comment]
@ssbarnea Such is the nature of open source. It's an orphaned patch which needs some love.

**Comment by ssbarnea** [comment]
@Lukasa I solved the problem locally by removing the grequests dependency and reusing the support from inside requests.

**Comment by shazow** [comment]
@ssbarnea I'm not sure what kind of response you're expecting. None of us are being paid to work on urllib3; I invite you to fix this: http://urllib3.readthedocs.org/en/latest/#sponsorship

**Comment by sharoonthomas** [comment]
Sorry everyone, haven't had the time to fix the test case. Will try to do it sometime next week (if no one else does it by then)

Sent from my iPhone

**Comment by shazow** [comment]
@sharoonthomas Somebody added a $15 bounty on this, you should grab it if you can finish it soon. :)

**Comment by sharoonthomas** [comment]
@shazow I am keeping a watch on this patch, but a fully working patch on gevent for this cannot be sent until gevent/gevent#477 is fixed. To be specific:

* SSLSocket implementation in gevent does not accept server_hostname (though python 2.7.9 does).
* ssl. sslwrap was removed by python 2.7.9 (this one is easier to get around).

For anyone who might pick off from here the code is on my fork (https://github.com/sharoonthomas/urllib3/compare/issue-482)

**Comment by shazow** [comment]
@sharoonthomas Ah thanks for the updates, makes sense. Thanks for keeping an eye on this!

**Comment by shazow** [comment]
@sprin Thanks for bumping up the bounty to $115. :)

Looks like the referenced gevent issue is making progress. If we're in a super-hurry, we may use a polyfill patch from the gevent thread or somesuch.

**Comment by sprin** [comment]
Patching gevent appears to be the preferred solution. I think a patch to gevent should be awarded the bounty, but it made sense to add to the bounty started here.

I have not been able to use any of the proposed polyfills with success when Py 2.7.9, gevent, and requests are used together.

**Comment by shazow** [comment]
Agree that incentives given for the gevent contributors might be better suited in this scenario. :) Maybe we should poke the gevent thread and offer up for one of them to come claim the bounty once they close their bug.

**Comment by sharoonthomas** [comment]
@shazow +1

**Comment by Lukasa** [comment]
:cake: :sparkles:

**Comment by zeevt** [comment]
if you patch gevent like this: https://github.com/zeevt/gevent/commit/beafef169b43e5a19e42e69c115ac278c6abdce4 it works and passes my tests (sends SNI etc.)

**Comment by sigmavirus24** [comment]
Except that we don't carry patches for gevent @zeevt

**Comment by shazow** [comment]
Is this fixed in the latest gevent? Can anyone confirm?

**Comment by transfluxus** [comment]
This error popped up a while ago in my application? Is it something easily fixable? upgrading urllib or something?

**Comment by Lukasa** [comment]
@transfluxus My understanding is that this is a gevent bug. Try upgrading gevent.

**Comment by sethmlarson** [comment]
Since there hasn't been any movement or additional reports here going to assume this is resolved.
