### ISSUE TITLE
Pipelining?

### ISSUE THREAD

**Issue by jtolio** [urllib3/urllib3#52]
I know this is super lame to file an issue instead of emailing a mailing list or something for a feature question, but I can't find a urllib3 mailing list anywhere.

Anyway, I am trying to find any kind of support for HTTP pipelining in an existing library in Python before attempting something more drastic. Specifically, I am trying to pipeline a series of PUTs (yeah, they're idempotent), like so:

PUT
PUT
PUT
get response
get response
get response

Ideally, I'd love for this to be handled for me in some kind of threadsafe way, but I'm willing to do it myself. urllib3 seems really close! Threadsafe, connection pooling, the works! I even saw some other website that offhandedly speculated that urllib3 might even do pipelining. But I hardly think that's possible, as you have to call release_connection manually after reading the body of a response.

Anyway, do you know anything about this? It's sort of surprising to me how undersupported this HTTP feature seems to be. If urllib3 doesn't support it, any wise thoughts on what I might have to do instead?

-JT

**Comment by cattleyavns** [comment]
@hannosch: You can use pipeline function from this code, use that function with httplib:
```
"""
Using the builtin http client, demonstrate different strategies for multiple requests:
- serial requests with one connection (the baseline)
- pipelining requests with one connection
- conncurrent requests with multiple connections

When reusing connections, each response must be fully read before using the next response.
Generator expressions are returned so requests are sent immediately, and the timing is fair.
"""

from __future__ import print_function
try:
    from http import client
except ImportError:
    import httplib as client


def sequential(host, *requests):
    "Send requests (method, path[, body[, headers]]) and generate responses serially."
    conn = client.HTTPConnection(host)
    return (conn.request(*request) or conn.getresponse() for request in requests)


def pipeline(host, *requests):
    "Pipeline requests (method, path[, body[, headers]]) and generate responses."
    conn = client.HTTPConnection(host)
    responses = []
    for request in requests:
        conn.request(*request)
        responses.append(conn.response_class(conn.sock, method=conn._method))
        conn._HTTPConnection__state = 'Idle'
    return (response.begin() or response for response in responses)


def concurrent(host, *requests):
    "Send requests (method, path[, body[, headers]]) in parallel and generate responses."
    conns = []
    for request in requests:
        conns.append(client.HTTPConnection(host))
        conns[-1].request(*request)
    return (conn.getresponse() for conn in conns)


if __name__ == '__main__':
    import time
    requests = [('GET', '/delay/1')] * 3
    for func in (sequential, pipeline, concurrent):
        print(func.__name__)
        responses = func('httpbin.org', *requests)
        start = time.time()
        for response in responses:
            assert response.status == client.OK and response.read()
            print(time.time() - start)
```

**Comment by macpacheco** [comment]
I was able to make it work with the following hack:
Before sending a pipelined request:
    conn._HTTPConnection__state = httplib._CS_IDLE
Before getresponse:
    conn._HTTPConnection__state = httplib._CS_REQ_SENT
where conn is the httplib connection object.
In my case the requests are identical except for one query variable.
I sent 74 requests in a row. Only then did the getresponse/read for all requests.
