### ISSUE TITLE
Content-length header not set on PUT/POST with empty body

### ISSUE THREAD

**Issue by jimr** [urllib3/urllib3#555]
Lots of discussion over at Requests: kennethreitz/requests/issues/223 including a PR to work around the issue: kennethreitz/requests/pull/957

Basically, nginx is returning 411 responses when using urllib3 to make PUT or POST requests with an empty body because the content-length header is only set when the body isn't empty.

We're encountering this issue with the elasticsearch-py library, which is relying on urllib3 to set this header appropriately (see elasticsearch/elasticsearch-py@20aa35d791bbcfca555ef059ea1c619019a93ff7)

I've had a poke around the code but can't find the appropriate place to apply a fix for this.
##

**Comment by jimr** [comment]
OK, looks like this is actually an issue with `httplib` in Python that has since been resolved: http://bugs.python.org/issue14721

Our issue seems to be that we're running Python 2.7.3 which doesn't include the fix.

**Comment by shazow** [comment]
@jimr Thanks for investigating, good to know! :)

**Comment by jimr** [comment]
So as it turns out it's not quite fixed in `httplib` (see my bug report & patch here: http://bugs.python.org/issue23539; basically) so you might want to consider protecting `urllib3` users from this by emulating that logic rather than assuming it'll do the right thing. For most people, a `urllib3` upgrade is going to be a simpler task than a Python upgrade.

**Comment by shazow** [comment]
Re-opened in case we want to do something more about this. :)

**Comment by sigmavirus24** [comment]
Requests solved this years ago, hehe. I'll be happy to send a fix to urllib3. Just nag me about it, I'm sure I'll forget.

**Comment by shazow** [comment]
@sigmavirus24 +1

**Comment by jimr** [comment]
Adding something like this in `connectionpool.HTTPConnectionPool.urlopen` should do it:

```
set_default_content_length = ( 
    (body is None and method.upper() in ['PATCH', 'POST', 'PUT']) or
    body == ''
)   
if set_default_content_length:
    headers.setdefault('Content-Length', 0)

# Make the request on the httplib connection object.
httplib_response = self._make_request(conn, method, url,
                                      timeout=timeout_obj,
                                      body=body, headers=headers)
```

That would be consistent with the `httplib` fix.

**Comment by shazow** [comment]
Might be better to put it in `request.py`, which already does things like that anyways.

@jimr Interested in doing a PR? :)

**Comment by jimr** [comment]
Aye, could do. OK if I include something like HTTPretty to simplify mocking?

**Comment by shazow** [comment]
@jimr Umm you could try but I'm not sure it would actually be simpler. :) Annoyingly, our request generating is not quite as decoupled as it should be.

**Comment by jimr** [comment]
Aye, I noticed that :) I actually have the patch + tests all working except for some reason the mocked `HEAD` requests aren't working as expected. I'll see about moving the logic into `request.py` as suggested & once all the tests pass I'll open a PR.

**Comment by shazow** [comment]
@jimr You're welcome to open a PR before it's fully ready, happy to give an extra pair of eyes as you go. :)

**Comment by jimr** [comment]
Cool, thanks. BTW do you mean `utils/request.py`?

**Comment by shazow** [comment]
I mean it's similar to the whitelist here https://github.com/shazow/urllib3/blob/master/urllib3/request.py#L41.

Specifically, the default header'ing should probably go into `request_encode_body`.

**Comment by jimr** [comment]
Gotcha, thanks for the pointer.

**Comment by shazow** [comment]
Np. :) In regards to testing, it'd probably be enough to just test RequestMethods directly (or write a little mock class which inherits from it). Although, it'd be nice to also get one end-to-end test in test_socketlevel.py or somesuch.

**Comment by eduzen** [comment]
Hi, this is my first contribution to urllib3. I'm a little bit lost. I read the suggestions in the thread and the suggestion to update ``request.py``. But I'm not sure if this is the right approach. I'm open to suggestions and obviously how to test it.

Thanks!

**Comment by jimr** [comment]
This shouldn't be an issue any longer - my patch to fix the upstream issue in `httplib` was merged years ago, and should be in recent releases of Python 2.7 and 3.5+.

**Comment by jimr** [comment]
See https://bugs.python.org/issue23539 for the resolution.

**Comment by sethmlarson** [comment]
Thanks for looping back @jimr!
