### ISSUE TITLE
Default timeout

### ISSUE THREAD

**Issue by JulienPalard** [urllib3/urllib3#655]
o/

In [util.Timeout](https://github.com/kennethreitz/requests/blob/8b5e457b756b2ab4c02473f7a42c2e0201ecc7e9/requests/packages/urllib3/util/timeout.py#L19), urllib3 use the socket global default timeout, but not the "user set" default timeout, probably modified by `socket.setdefaulttimeout(10)`, so ignoring any `socket.setdefaulttimeout`. Why ?

I think it would be cool to be able to set a "setdefaulttimeout" and have it impact `urllib3`, so also impacting `requests`.

In another hand, one should not know that `urllib3` or `request` use `socket` under the hood, and doing a `socket.setdefaulttimeout` to configure the default timeout of `urllib3` or `requests`  tie them, I mean, if you change the underlying used module, the timeout will still be applied, but to the wrong module, so probably being ignored. Also this is surprising to set a setting on a module A to impact the behavior of module B.

So we have pros and cons here, but totally ignoring socket.setdefaulttimeout may not be the better solution, conversation opened :)
##

**Comment by Lukasa** [comment]
Agree, I think setting `socket.setdefaulttimeout` should affect urllib3. The only way in which that's a problem is that, if you rely on it, non-sockety platforms (like GAE) won't work. However, that's a problem for downstream library authors.

Generally, we should encourage people to use urllib3's timeout infrastructure, but if `socket` *is* being used we should respect settings in that module.

**Comment by JulienPalard** [comment]
Seems a good compromise, I agree:

 - modules should encourage using their own methods to set timeout to be implementation independent
 - When using socket, if a defaulttimeout is set, respect it
 - Obviously, setting the timeout from the module API have precedence over default timeout at a socket level

**Comment by shazow** [comment]
Agreed, don't think there is any reason why we're not using `socket.getdefaulttimeout()`. +1 to using this as the default.

In fact, we have `connection.py:HTTPSConnection.__init__(..., timeout=socket._GLOBAL_DEFAULT_TIMEOUT)` which makes no sense to me at all. That should not be there.

@JulienPalard Would you like to do a PR with these changes?

**Comment by JulienPalard** [comment]
I'd like to do so :-) However the `make test` fail, I can still do my modifications and check it fails the same way, but it may hide something:

```
$ make test
nosetests
SSS..........F.........................................................S..S..............S.............SSS.....S....S.................................................................................................................................................................
======================================================================
FAIL: ECONNREFUSED error should raise a connection error, with retries
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/julien/urllib3/test/with_dummyserver/test_connectionpool.py", line 279, in test_connection_error_retries
    self.assertEqual(e.reason.args[1].errno, errno.ECONNREFUSED)
AssertionError: 101 != 111
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
urllib3.util.retry: DEBUG: Incremented Retry for (url='/'): Retry(total=9, connect=3, read=None, redirect=None)
urllib3.connectionpool: WARNING: Retrying (Retry(total=9, connect=3, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(101, 'Network is unreachable'))': /
urllib3.connectionpool: INFO: Starting new HTTP connection (2): localhost
urllib3.util.retry: DEBUG: Incremented Retry for (url='/'): Retry(total=8, connect=3, read=None, redirect=None)
urllib3.connectionpool: WARNING: Retrying (Retry(total=8, connect=3, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(101, 'Network is unreachable'))': /
urllib3.connectionpool: INFO: Starting new HTTP connection (3): localhost
urllib3.util.retry: DEBUG: Incremented Retry for (url='/'): Retry(total=7, connect=3, read=None, redirect=None)
urllib3.connectionpool: WARNING: Retrying (Retry(total=7, connect=3, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(101, 'Network is unreachable'))': /
urllib3.connectionpool: INFO: Starting new HTTP connection (4): localhost
urllib3.util.retry: DEBUG: Incremented Retry for (url='/'): Retry(total=6, connect=3, read=None, redirect=None)
urllib3.connectionpool: WARNING: Retrying (Retry(total=6, connect=3, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(101, 'Network is unreachable'))': /
urllib3.connectionpool: INFO: Starting new HTTP connection (5): localhost
urllib3.util.retry: DEBUG: Incremented Retry for (url='/'): Retry(total=5, connect=3, read=None, redirect=None)
urllib3.connectionpool: WARNING: Retrying (Retry(total=5, connect=3, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(101, 'Network is unreachable'))': /
urllib3.connectionpool: INFO: Starting new HTTP connection (6): localhost
urllib3.util.retry: DEBUG: Incremented Retry for (url='/'): Retry(total=4, connect=3, read=None, redirect=None)
urllib3.connectionpool: WARNING: Retrying (Retry(total=4, connect=3, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(101, 'Network is unreachable'))': /
urllib3.connectionpool: INFO: Starting new HTTP connection (7): localhost
urllib3.util.retry: DEBUG: Incremented Retry for (url='/'): Retry(total=3, connect=3, read=None, redirect=None)
urllib3.connectionpool: WARNING: Retrying (Retry(total=3, connect=3, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(101, 'Network is unreachable'))': /
urllib3.connectionpool: INFO: Starting new HTTP connection (8): localhost
urllib3.util.retry: DEBUG: Incremented Retry for (url='/'): Retry(total=2, connect=3, read=None, redirect=None)
urllib3.connectionpool: WARNING: Retrying (Retry(total=2, connect=3, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(101, 'Network is unreachable'))': /
urllib3.connectionpool: INFO: Starting new HTTP connection (9): localhost
urllib3.util.retry: DEBUG: Incremented Retry for (url='/'): Retry(total=1, connect=3, read=None, redirect=None)
urllib3.connectionpool: WARNING: Retrying (Retry(total=1, connect=3, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(101, 'Network is unreachable'))': /
urllib3.connectionpool: INFO: Starting new HTTP connection (10): localhost
urllib3.util.retry: DEBUG: Incremented Retry for (url='/'): Retry(total=0, connect=3, read=None, redirect=None)
urllib3.connectionpool: WARNING: Retrying (Retry(total=0, connect=3, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(101, 'Network is unreachable'))': /
urllib3.connectionpool: INFO: Starting new HTTP connection (11): localhost
--------------------- >> end captured logging << ---------------------

Name                      Stmts   Miss  Cover   Missing
-------------------------------------------------------
urllib3                      17      0   100%   
urllib3._collections        149      0   100%   
urllib3.connection           83      0   100%   
urllib3.connectionpool      226      0   100%   
urllib3.exceptions           57      0   100%   
urllib3.fields               62      0   100%   
urllib3.filepost             32      0   100%   
urllib3.poolmanager         101      1    99%   183
urllib3.request              29      0   100%   
urllib3.response            212      0   100%   
urllib3.util                  0      0   100%   
urllib3.util.connection      27      0   100%   
urllib3.util.request         20      0   100%   
urllib3.util.response        17      0   100%   
urllib3.util.retry           76      0   100%   
urllib3.util.ssl_            55      0   100%   
urllib3.util.timeout         48      0   100%   
urllib3.util.url             91      0   100%   
-------------------------------------------------------
TOTAL                      1302      1    99%   
No handlers could be found for logger "nose.plugins.cover"
make: *** [test] Error 1
```

What do you think ?

**Comment by Lukasa** [comment]
ENETUNREACH? What a weird error code to see here. Why would localhost be considered unreachable?

**Comment by shazow** [comment]
Strange indeed, especially since all the other tests pass. What version of Python and on what platform are you running? Could you try rebooting and running the tests again?

**Comment by JulienPalard** [comment]
Here is my python version and OS version:

```
$ python --version
Python 2.7.3
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.8 (wheezy)
Release:        7.8
Codename:       wheezy
```

Rebooting ? Naupe, no way. You better explain the test that is failing, so I understand why and fix something. I'm a dev, not a user.

**Comment by JulienPalard** [comment]
OK got it, `localhost` resolved to `::1`, but ipv6 is disabled in my sysctl `net.ipv6.conf.all.disable_ipv6=1`.

So strange nobody noticed.

So my make test runs like:

```
$ make test
nosetests
SSS....................................................................S..S..............S.............SSS.....S....S.................................................................................................................................................................
Name                      Stmts   Miss  Cover   Missing
-------------------------------------------------------
urllib3                      17      0   100%   
urllib3._collections        149      0   100%   
urllib3.connection           83      0   100%   
urllib3.connectionpool      226      0   100%   
urllib3.exceptions           57      0   100%   
urllib3.fields               62      0   100%   
urllib3.filepost             32      0   100%   
urllib3.poolmanager         101      1    99%   183
urllib3.request              29      0   100%   
urllib3.response            212      0   100%   
urllib3.util                  0      0   100%   
urllib3.util.connection      27      0   100%   
urllib3.util.request         20      0   100%   
urllib3.util.response        17      0   100%   
urllib3.util.retry           76      0   100%   
urllib3.util.ssl_            55      0   100%   
urllib3.util.timeout         48      0   100%   
urllib3.util.url             91      0   100%   
-------------------------------------------------------
TOTAL                      1302      1    99%   
No handlers could be found for logger "nose.plugins.cover"
make: *** [test] Error 1
```

Is it OK ?

**Comment by Lukasa** [comment]
urllib3 requires 100% code coverage, so you're going to need a test that will hit line 183 in poolmanager.py.

**Comment by JulienPalard** [comment]
I did not yet modified the code, that's just a fresh `git pull`. Howver I can try to test this line, but that's another PR.

**Comment by shazow** [comment]
> Rebooting ? Naupe, no way. You better explain the test that is failing, so I understand why and fix something. I'm a dev, not a user.

Had I known why it was failing, I would have explained it. I'm sorry if my methods for debugging are offensive to you as a dev—I don't know what the state of your machine might be and how it may interact with our test suite.

Good work figuring out the ipv6 thing. No clue why L101 of PoolManager is not being exercised on your environment, please let us know when you've figured it out or how we can help.

**Comment by JulienPalard** [comment]
@shazow Sry for being a bit rude/direct on this ! (Spent 25 days trying to explain to elasticsearch that I'm a dev and they have to trust my diagnostics, they closed my bugs twice before listening to me, conclusion: I was right, so I'm still a bit nervous on the subject... sorry !)

Crawling the code to search how to modify it cleanly I'm starting to understand you used `None` to represent an infinite timeout, I'm not a huge find of this, for me `None` mean "Don't know" (like NULL in SQL). However I'm not going to propose to change this, as this is documented and exposed via the `Timeout` object.

And everything seems to work:
This gives me a timeout (Running `netcat -l -p 9876` aside):
```
import socket
socket.setdefaulttimeout(2)

import urllib3
http = urllib3.PoolManager(retries=0)
http.request('GET', 'http://localhost:9876/')
```

But in [requests/adapters.py:323](https://github.com/kennethreitz/requests/blob/master/requests/adapters.py#L323) they have a `def send(self, request, stream=False, timeout=None, ...`

So, not giving a timeout gives us a `None` here, so, from an `urllib3` point of view, an explicitly set infinite timeout. I think the fix may probably be to set `timeout=TimeoutSauce.DEFAULT_TIMEOUT` here. So my PR will goes to `requests`, if you think I'm right here.

**Comment by shazow** [comment]
> Crawling the code to search how to modify it cleanly I'm starting to understand you used `None` to represent an infinite timeout, I'm not a huge find of this, for me `None` mean "Don't know" (like NULL in SQL). However I'm not going to propose to change this, as this is documented and exposed via the `Timeout` object.

I think that's more an artifact of [`socket.settimeout`](https://docs.python.org/2/library/socket.html#socket.socket.settimeout)'s behaviour. We generally treat `None` as you described, and `False` to outright disable something (e.g. `retries=False` disables retries and raises the original exception). Though we're probably passing the given value down the API stack until it hits `socket` which does what you described. :/

@Lukasa can speak more to requests' side of things, but what you said sounds about right.

**Comment by Lukasa** [comment]
I believe that requests' current handling of timeouts is wrong, but fixing it requires a change in 3.0.0. I think we have an issue somewhere for that, but right now I can't find it. I think the PR in urllib3 is right, urllib3 needs the function. I also think requests needs a separate PR that falls back to the urllib3 default timeout.

**Comment by sigmavirus24** [comment]
>  I also think requests needs a separate PR that falls back to the urllib3 default timeout.

Sent to the `proposed/3.0.0` branch, not to master, in case someone's watching who wants to do this.

**Comment by JulienPalard** [comment]
Patching `requests/adapters.py:323` to get `timeout=TimeoutSauce.DEFAULT_TIMEOUT` instead of `None` seems enough for me to fix the whole problem, am I wrong ?

**Comment by Lukasa** [comment]
I don't think that'll allow people to change the socket library timeout midway through execution, will it?

**Comment by JulienPalard** [comment]
That's hard to define what really is "midway through execution", in one sense, `socket` neither allow it:
```
sock = socket.socket(af, socktype, proto)
socket.setdefaulttimeout(2)
sock.connect(sa)
# Will timeout (mdk.fr port 9876 if one want to test it)
```

In urllib3 connections seems created in `util/connection.py:74`:
```
sock = socket.socket(af, socktype, proto)

# If provided, set socket level options before connecting.
# This is the only addition urllib3 makes to this function.
_set_socket_options(sock, socket_options)

if timeout is not socket._GLOBAL_DEFAULT_TIMEOUT:
    sock.settimeout(timeout)

```

So, as long as the socket is reused, nobody can change the timeout using setdefaulttimeout, as socket does not support it, and its looks normal.

Next, as long as I reviewed `socket._GLOBAL_DEFAULT_TIMEOUT` or its identical counterpart in `timeout.py` `DEFAULT_TIMEOUT` are used from one end to another, and if they arrive to `util/connection.py:74` which is the case, the new timeout will be used, checked using:

```
import requests
try:
    socket.setdefaulttimeout(2)
    print(requests.get('http://mdk.fr:9876/'))
except Exception as e:
    print(e)

socket.setdefaulttimeout(5)
print(requests.get('http://mdk.fr:9876/'))
```

I count 2s to get the first timeout and 5s to get the other.

But while reviewing from one end to another, I had to change my first patch to move the `s/None/TimeoutSauce.DEFAULT_TIMEOUT` one level up, and here is my new patch:

```
--- a/requests/sessions.py
+++ b/requests/sessions.py
@@ -36,6 +36,8 @@ from .status_codes import codes
 # formerly defined here, reexposed here for backward compatibility
 from .models import REDIRECT_STATI
 
+from .packages.urllib3.util import Timeout as TimeoutSauce
+
 REDIRECT_CACHE_SIZE = 1000
 
 
@@ -390,7 +392,7 @@ class Session(SessionRedirectMixin):
         cookies=None,
         files=None,
         auth=None,
-        timeout=None,
+        timeout=TimeoutSauce.DEFAULT_TIMEOUT,
         allow_redirects=True,
         proxies=None,
         hooks=None,
```

I'm not sure it's necessary to update every `timeout=None`, but it's probably a good idea, that make more sense, and probably fix other usages via other methods or more direct calls to underlying classes.

Any though on this ?

**Comment by Lukasa** [comment]
Why does the patch move up? We really don't want to import urllib3 into the `Session` class, so we need to keep it in the `HTTPAdapter`.

**Comment by JulienPalard** [comment]
Patch moved up because `Session` is gilty to set timeout to `None`, `Adapters.send` already receive an explicit `None` as a timeout.

If you don't want to import urllib3 into Session, we may `import socket`, as `socket._GLOBAL_DEFAULT_TIMEOUT` is identical to `DEFAULT_TIMEOUT` urllib3's `timeout.py`.

But you probably don't want socket imported either, and it make sense (to not depend on it here).

 - In socket, `None` mean `∞`, and `_GLOBAL_DEFAULT_TIMEOUT` means "Not set, use the default".
 - In urllib3, `None` mean `∞`, and `DEFAULT_TIMEOUT` means "Not set, use the default", and is just the same object than the socket `_GLOBAL_DEFAULT_TIMEOUT`
 - In requests, `None` mean "Not set, use the default" but is wrongfully passed as-is to urllib3, changing its meaning, and there is no `∞`, yet using an explicit `None` or giving nothing (resulting to a default `None`) will wrongfully mean `∞`.

If I'm right here, a proper fix may be to be explicit in `requests` on how to represent infinite timeout and default timeout, choose a notation, identical or not from the urllib3 / socket one, and map it correctly when talking to urllib3.

We may choose `None` as "Not set, use the default" (For my point of view, the real meaning), and something else for `∞`, maybe `-1` but that's not verbose, too magic, and almost meaningless. Maybe `0`, same problems. Maybe an explicit sentinel like `requests.infinite` ? Or why not simply `float("inf")` ? Natural and explicit.

In another hand we may choose the same mapping as urllib3 or socket, so we need a sentinel to represent the default timeout, either a new one, or reusing their already shared one, but in this last case, it forces us to import either urllib3 or socket.

It's probably possible to neither import urllib3 nor socket, we have to tell apart "timeout not given" and "timeout given", to bind clearly "timeout not given" to "default timeout", exactly like does the socket module:

```
def create_connection(address, timeout=_GLOBAL_DEFAULT_TIMEOUT,
```

So, first things first, let's define how `requests` represents "default timeout" and "infinite timeout".

**Comment by Lukasa** [comment]
I think the sensible thing to do is to have requests define its own internal sentinel object for 'default timeout', and then have the adapter convert it into a urllib3 default timeout.

**Comment by JulienPalard** [comment]
This seems OK, if we convert just when calling urllib3 is does not force requests to import urllib3, cause where we're calling urllib3 it's already imported.

Do we keep the same semantics of None means infinite, and sentinel means default ? I'm not a big fan of it, only advantage, it binds with urllib3 and sockets more directly, giving more readable code.

In the other end, None clearly does not mean infinite, it clearly mean "unknown", and "unknown" clearly binds to the default, float("inf") clearly mean infinite, so I think there's an open discussion here.

**Comment by sethmlarson** [comment]
We've dropped GAE so that's no issue any more. Currently we do resolve the default timeout via `socket.getdefaulttimeout()` for read/connect separately so I think that covers this issue? If there's something else needed from this issue we can open a new one.
