### ISSUE TITLE
Any opinion on a Fedora unbundling question?

### ISSUE THREAD

**Issue by ralphbean** [urllib3/urllib3#702]
An [issue was raised](https://bugzilla.redhat.com/show_bug.cgi?id=1231381) in the Fedora bugtracker about handling `ssl_match_hostname` unbundling on Fedora releases that carry Python 2.7.9.  Here's the rundown:
- Currently, we replace the bundled `ssl_match_hostname` shim with a symlink to the system copy of `ssl_match_hostname` (to unbundle).
- In the ticket, Carl points out correctly that we don't need that extra lib/dep on Fedora releases that carry Python 2.7.9, so he wants to remove it.
- In doing so, he's suggesting that we reintroduce some of those import patches that we used to carry.
- Instead, we could replace the bundled `ssl_match_hostname` module with a symlink to the stdlib `ssl` module on Python 2.7.9 systems, and keep the old symlink on older Fedora releases.

How does that sound?  Do you have any opinion on how we do this?  Any different ideas?  Cheers!
##

**Comment by shazow** [comment]
/cc @sigmavirus24 

Hmm I'm trying to think of how we can restructure the module/imports such that the packages dir (or at least the contents) can be safely deleted and things will Just Work with a sufficiently new Python. Ideally I'd prefer to avoid wrapping all of our in-module `import .packages...` statements with try/except import, though. Maybe alias-wrap all the imports in urllib3/packages/__init__.py.

Any other ideas?

**Comment by sigmavirus24** [comment]
> Or maybe better yet, alias-wrap such that it uses the system-default version first before using the vendored backports.

Unless we do detailed version checking, won't this break things? I need time to wrap my head around this but I'm looking into it.

**Comment by shazow** [comment]
From my quick look, they're just stdlib backports which hopefully won't be breaking often. But yea, that could be painful.

**Comment by Lukasa** [comment]
I think it's not too difficult an idea to have a module structure that allows you to define backports but only use them conditionally. Basically an extension of the `compat` module idea, but with submodules because something something namespacing.

**Comment by sigmavirus24** [comment]
So a compat module is what I like best with explicit checks around Python version so we're not importing the wrong thing in the wrong place. I'm not sure it should be in `packages/__init__.py` though. That seems to overload the purpose of that (handle compat and other things).

Perhaps a `packages.compat`? I doubt @ralphbean would remove that since the compat module itself isn't vendored code.

**Comment by carlgeorge** [comment]
Hey guys, I raised the originally issue @ralphbean was referring to.  What is the drawback of just using try/except blocks around the imports?  I'm sure you have your reasons, but I'm not grasping the problem.  Please help me understand.

    try:
        from ssl import CertificateError
    except ImportError:
        from backports.ssl_match_hostname import CertificateError

**Comment by Lukasa** [comment]
@carlgeorge Nothing is inherently problematic with it, we're just trying to work out how to structure it so that we can make it easy for both ralph and us. =)

**Comment by carlgeorge** [comment]
From a package maintainer standpoint, the obvious goal is to unbundle libraries and use the system copies.  I think the ideal setup is to safely import from the standard library or system site packages if the bundled library is manually deleted (such as in an RPM spec file).  If this approach sounds sane, I can work up a pull request to make the changes.

**Comment by ralphbean** [comment]
Hey everyone, thanks for taking this seriously.  @carlgeorge, some patches have been submitted in the past that do what you're describing, but they were rejected.  From certain points of view, they clutter the urllib3/requests source code and make it less readable.  (OTOH, it's more explicit?)

While the longer-term question of how to structure the urllib3/requests compat modules seems to still be up in the air, I'm going to go ahead and pursue my proposal for the Fedora package of conditionally symlinking in the stdlib ssl module, depending on whether or not Python 2.7.9 or greater is present (or not).

**Comment by shazow** [comment]
Right, while it's not inherently a problem, it's much more preferable to manage import rewriting in one place rather than in every single file where it's touched. :)

**Comment by KyleWpppd** [comment]
Thank you for your responses and feedback.

One way I've seen this done is the way Google's projects do it, by having a "[google_imports.py](https://github.com/GoogleCloudPlatform/datastore-ndb-python/blob/master/ndb/google_imports.py)" file, and anything that could be imported from multiple places seems to do done that way.

Would that be an acceptable solution for urllib3?

**Comment by Lukasa** [comment]
Maybe? Right now this is not a major issue for urllib3, as it doesn't do `isinstance` checks or anything like that on vendored modules, so import rewriting should be basically transparent. So I suspect that this boils down to us carrying code to support downstream patches, which seems unnecessary.

**Comment by sigmavirus24** [comment]
So just to add some information about why `try/except` blocks aren't acceptable, this project used to do similar things for stdlib modules that were *renamed*. In that case, when others installed libraries like python-future or the myriad of other poorly considered and poorly implemented solutions, we were broken and it took hours to determine the cause. So if we accept anything, we really do want *explicit version checks*. Yes, that's gross, but it's also the safest option when people are relying on bad third-party code that knowingly (yes, the authors are aware and some just don't care) break other third-party modules. The best way for us to be safe is to be extra paranoid, especially given the libraries and tools that rely on urllib3 (directly or indirectly).

**Comment by sethmlarson** [comment]
We've now eliminated `urllib3.packages` and therefore no unbundling should happen in 2.0 and beyond. For 1.26.x OS packagers should continue to do what they've been doing.
