### ISSUE TITLE
.read should only return empty (false) when there is nothing left to read (EOS)

### ISSUE THREAD

**Issue by gilesbrown** [urllib3/urllib3#709]
I have some code that does a partial read of a "raw" response in requests to look for "magic bytes".  Digging into the urllib3 code I find that the size you pass in is used as the pre-decode amount which means that the decompressor doesn't have enough bytes to give you anything.  This confused my code into thinking it had read all of the response, which it hadn't.

Here is a simple example:

In [1]: import urllib3
In [2]: http = urllib3.PoolManager()
In [3]: resp = http.request('GET', 'http://httpbin.org/gzip', preload_content=False)
In [4]: resp.read(8)
Out[4]: b''

I would argue that the amount passed into .read (8 in this case) should be the amount _after_ decoding.

[EDIT]
I originally did not include the `preload_content=False`.  This is necessary.  Without it the content is (correctly) loaded into `.data`.
##

**Comment by Lukasa** [comment]
I have mixed feelings about that. To do it requires that we cache buffers internally, which is kind of a nightmare, and leads to some really in deterministic behaviour (for example, read might not actually make a socket call).

What exactly are you doing if you don't find the magic bytes?

**Comment by shazow** [comment]
I understand why this isn't always intuitive but most of the use-cases I can think of, you're being careful about what you read from the _server_.

It's not hard to create a client-side buffer, right? Lots of helpers here https://docs.python.org/2/library/io.html, and our response already acts as a file-like object so hopefully a recipe should be pretty simple?

Although if we were to redesign the response object someday, perhaps we could use better composition to allow both kinds of semantics. :/

**Comment by gilesbrown** [comment]
@Lukasa my use case is in my web data extraction (aka scraping) library https://github.com/eBay/wextracto.   The library has quite few places where it acts as a kind of tee, reading a little bit and passing stuff on for downstream processing.  In this case I am creating a temporary file to hold the response content (https://github.com/eBay/wextracto/blob/master/wex/response.py#L102).  What I was trying to do was to grab just the magic bytes on the way through so that I can efficiently decide if the content requires decoding.  The reason this is helpful is because sometimes you get a combination of content-encoding: gzip + content-type: application/x-gzip and with that combination the content may or may not be double gzipped.  The easiest way to tell efficiently is to look for the magic bytes.

@shazow Yes I am confident I can cook up an alternative.  Worst case I can just do all the content decoding in Wextracto.  I raised this issue because I think the current behaviour goes against well established practice for file-like objects of only returning false-ness when there is nothing more to read.

https://docs.python.org/2/tutorial/inputoutput.html#methods-of-file-objects

For example the `gzip` module:
    $ curl -s http://httpbin.org/gzip > example
    $ python -c "import gzip; print(gzip.open('example').read(8))"
    {
        "gzi
    
You can of course tell me that you don't intend this object to be file-like or that it's too hard to do now.  If it's the latter then I would probably suggest that you detect this situation and issue a warning.  I don't think that would be too hard to do. Right?
  

Use case aside the thi

**Comment by shazow** [comment]
> file-like objects of only returning false-ness when there is nothing more to read.

That's a good point.

**Comment by sigmavirus24** [comment]
Yeah, I'm frankly torn on this issue as well. For one thing, I think changing this now is going to be surprising behaviour for some people. I wonder if having this "recipe" in `urllib3.contrib` would be a good compromise so that users that know they need it can use it (like @gilesbrown).

**Comment by shazow** [comment]
Honestly the basic recipe of this will break because we return "" sometimes when we shouldn't for file-like objects. This is tricky. Is it reasonable to assume a minimum read amount?

**Comment by sigmavirus24** [comment]
For the basic recipe? If we know it's compressed, do we know if reading any less than `N` bytes will cause us to return `b''`? If so we can just always read `N` and then keep reading after that to ensure we return `x` bytes to the user.

**Comment by gilesbrown** [comment]
Just an FYI in case it's helpful to you folks I'm just in the process of proving this commit:

    https://github.com/gilessbrown/wextracto/commit/90910a6da020fe5f69df0dc2d5a288974f8ed62f

Which includes this:

    https://github.com/gilessbrown/wextracto/blob/master/wex/http_decoder.py

Which may or may not be helpful to you.

**Comment by shazow** [comment]
@gilesbrown Very nice code, thank you for sharing that. Will be a handy reference if we rewrite that portion.

**Comment by gilesbrown** [comment]
Now with tests and 100% coverage and fixed bug!

https://github.com/gilessbrown/wextracto/commit/9e4fa910bbf8e9b41708391fedd04b16b562e832

**Comment by gilesbrown** [comment]
I meant to offer this at the time, but domestic life was a little frantic.  Would you like me to create a pull request based on this code?

**Comment by shazow** [comment]
@gilesbrown What are you proposing for the PR? Changing the read size to be post-inflation?

It's a backwards-incompatible change but I guess if people really really wanted to be careful about reads from the server then they could just not use the automagic decoding. :/ @sigmavirus24 @Lukasa thoughts?

**Comment by sigmavirus24** [comment]
I'm 100% against any backwards-incompatible changes. Like I suggested, this could be something in a `util` module or `contrib` module and then moved into urllib3 if a 2.0 is ever planned (if the users find it to be something that's desirable).

**Comment by gilesbrown** [comment]
Well I am going to note that I consider the current behaviour is a bug.  This behaviour can silently fail on people in an unexpected way (as it did with me).

But I'll leave it open to you folks to decide.  FWIW I'm not particularly interested in writing a PULL request for a non-mainstream piece of functionality.  In that case I'll just settle with leaving the code in Wextracto.  Sorry if that sounds belligerent but you now life is too short right? :)

**Comment by shazow** [comment]
@sigmavirus24 How come? We litter minor backwards incompatible changes on a regular basis. :)

And yea I agree that returning "" feels very much like a bug.

**Comment by shazow** [comment]
@gilesbrown That's totally cool and appreciated. Thanks for being patient with us. :)

**Comment by gilesbrown** [comment]
Out of curiosity I was poking around with `requests` to check if there was any evidence of this.  I didn't find any really.  It seems like `.iter_content()` is the only place where `decode_content` comes into play for partial reads.

The `if` here: https://github.com/shazow/urllib3/blob/8e082ccc7f56f8c32c4babd98294dfd41db9aa97/urllib3/response.py#L318
does ensure that the request generates a non-empty chunk but it does also allow the possibility of an infinite loop:
```
import requests
get = requests.get('http://httpbin.org/gzip', stream=True)
gen = get.iter_content(0)
next(gen)
```

but I guess you could argue that if you pass a zero amount you can expect odd behaviour?

**Comment by sigmavirus24** [comment]
@shazow I'm not convinced this is "minor" in terms of backwards incompatibility though. Others have been far less disruptive.

re requests: I'm not certain we shouldn't just bail early if you pass 0, but that's an entirely separate bug.

**Comment by shazow** [comment]
I'd call it minor. I classify minor as things that I suspect maybe a few dozen people are even aware of. :P

**Comment by gilesbrown** [comment]
@sigmavirus24 I can see why you would want to think of that request behaviour as an entirely separate bug but it is a consequence of `.read(1)` being allowed to return an empty string.  If the convention was followed then the line I referenced in urllib3/response.py would follow the traditional:

```
while whatever:
    data = self.read(amt=amt, decode_content=decode_content)
    if not data:
        break
    yield data
````

and you would not have an infinite loop.

If you really want to think of it as two bugs then that is your business, but the root cause is the same.  Having `amt` as the *pre*-decode amount rather than the *post*-decode amount.

**Comment by Lukasa** [comment]
If we want to satisfy all use cases, we're in a really tricky place. The space of options is and whether they're currently supported is:

|                                   | Decompress | Don't Decompress |
|---------------------------------------|:-----------:|:-----------------:|
| **Bytes read from the wire**          |  ✓          |  ✓                |
| **Bytes received in the application** | ✗           |  ✓                | 

Put another way, if you are about the number of bytes you read *from the wire*, you can control that perfectly with urllib3 today, regardless of `decode_content`. If you care about the number of bytes your application receives, you can only control that if you set `decode_content` to `False` and handle the decoding yourself.

I have no objection to supporting that final box, but I think we should consider really carefully whether we want to do it by adding a cross mark in an already supported box. The proposal in this issue (to change the semantic of `read`) would do that, *unless* it was accompanied by either another parameter or a new function that preserves the current logic.

I am +1 on supporting *all* of the above. I am -1 on supporting a different configuration of the above (i.e. moving the cross to another box). I am +0.1 on doing nothing (because the status quo has some value). I am open to relegating the current 'default' logic to a backup method (`raw_read` or some such thing), and moving @gilesbrown's suggestion to the `read` method, though it will break a surprising amount of code.

**Comment by gilesbrown** [comment]
To be as clear as possible I do not actually care about how many bytes are read from the wire or received in the application.  What I care about is that the `.read()` method should only return `''` under one of two conditions.
    * I pass in an `0` read size
    * there is nothing left to be read
This is the age old behaviour for python file-like objects and by doing something different you have a bug which leads to incorrect behaviour that can fail silently. 
So I have re-named the issue to reflect this.

**Comment by Lukasa** [comment]
@gilesbrown So, in that case should we just move the check from `stream()` into `read()`?

**Comment by gilesbrown** [comment]
@Lukasa which check?

**Comment by Lukasa** [comment]
The one that checks whether the length of the decoded body is 0, and if it is spins around again.

**Comment by gilesbrown** [comment]
I'm not sure I understand what you're getting at?  Yes I think that if the what you get back from the decompressor is empty then you need to feed it some more until you have nothing left to feed it or you get enough back.  Yes that should happen in the `.read()` implementation.  Does that answer your question?

**Comment by gilesbrown** [comment]
To be clear the bug is:

```
(urllib3)LM-sjn-00874409:~ gsbrown$ cat example.py
import sys
import shutil
import urllib3


def copy_to_stdout(size):
    http = urllib3.PoolManager()
    readable = http.request('GET', 'http://httpbin.org/gzip',
                            preload_content=False)
    shutil.copyfileobj(readable, sys.stdout, size)


if __name__ == '__main__':
    copy_to_stdout(int(sys.argv[1]))
(urllib3)LM-sjn-00874409:~ gsbrown$ python example.py 51 | wc -c
       0
(urllib3)LM-sjn-00874409:~ gsbrown$ python example.py 52 | wc -c
     156
```

This is breaks the interface here:
    https://docs.python.org/2/library/io.html#io.RawIOBase.read

Which goes against the claimed support here:
    https://urllib3.readthedocs.org/en/latest/#usage

If you want to tell me this is a bug but you don't want to fix because of backward compatibility then I will shrug and move on, but I should not have framed this in a way that could be interpreted as a feature request (e.g. support post-compression size to read) because primarily it is a bug.

**Comment by gilesbrown** [comment]
P.S. If you look in the code of `shutil.copyfileobj` you will see code that matches the pattern of how I am suggesting `.stream()` should look.

**Comment by Lukasa** [comment]
Actually, `read` violates that contract more severely as I show here:

```python
>>> import urllib3
>>> p = urllib3.PoolManager()
>>> r = p.urlopen('GET', 'http://http2bin.org/gzip', preload_content=False)
>>> len(r.read(15))
0
>>> len(r.read(15))
0
>>> len(r.read(15))
0
>>> len(r.read(15))
11
>>> len(r.read(15))
25
```

This is why I asked the questions above: in addition to returning lengths of 0, we may return *more* bytes than *amt*. That is a bug, by the same logic. And treating it as a bug means we need to discuss all of what I mentioned in my comment, sadly. =(

**Comment by gilesbrown** [comment]
@Lukasa ok cool.  I was getting a little cross because I inferred from your talk of use cases that you did not consider this to be a bug.  On the understanding that the discussion is "how does the potential breakage in existing code balance with the existing breakage in existing code?" then I'm fine with that.  As I said previously "it is a bug but it would break too much to fix it" is a reasonable position, but if that is your position I would suggest some mitigation like a warning if you read with a non-zero size read and `decode_content=True` and you get some bytes back from the raw fp and the decompressor gives you nothing.

**Comment by Lukasa** [comment]
@gilesbrown No problem.

Yeah, I totally agree. This is definitely a bug: I think if we're going to call a method `read` then it should do what `read` does or very clearly document that it won't do that. However, getting `read` to do exactly what it should is somewhat painful, requiring an internal buffer and some clever length checking. You've identified one piece of low-hanging fruit (don't return `0`), but I think if we believe this is worth changing we should re-architect to DTRT altogether by ticking all those boxes.

**Comment by gilesbrown** [comment]
Well for the record I'm now pretty confident that the http_decoder code I posted here:
    https://github.com/gilessbrown/wextracto/blob/master/wex/http_decoder.py
works and is does the buffering just fine.

I think supporting the use case for "read exactly n bytes from the raw stream and then give me back whatever you get from the decompressor which may be empty" looks like it would simply be a case of not looping here:

    https://github.com/gilessbrown/wextracto/blob/master/wex/http_decoder.py#L39

I really don't think the code changes are that tricky.  Understanding whether there is anybody who cares about the differences in behaviour between specifiying a pre or post decode size is a harder job.

I did a search of github looking for Python code with "preload_content" and found quite lots of copies of repackaged urllib3.

Here was my query:
    https://github.com/search?utf8=%E2%9C%93&q=preload_content+NOT+param+NOT+TestResponse+language%3APython&type=Code&ref=searchresults

I found at least one example of `copyfileobj`:
    https://github.com/Py64/beaver/blob/68dc490355acc8ed177d3ffb77fffa483e3a6674/examples/getpkg-package/usr/bin/getpkg.py

but the chunk size here is going to ensure that the decompression issue doesn't come into play.

Another example doing its own loop:
    https://github.com/rafelivgi/IronChrome/blob/07f059dadb7da659d37303432b13a02bdc1411af/Dev%20Components/selfupdate/selfupdate.py#L63

A fun one where it gets passed to ElementTree:
    https://github.com/UserGraund/testik/blob/f1a6cffeb09192cbfab4f184b99d5f19ac70e835/parcer/views.py#L54

I could not find a single example where the code was doing a length comparison other than with 0.

I found not explicit examples of small reads (other than those in my own code).  The ElementTree example listed above is a *potential* small read depending on how that code behaves.

My impression is that given the small amount of evidence it is actually more likely that there is code out there that is not working, but people have not realized than that there is code that I haven't found that actually depends on a the specific number of bytes read from the wire, but obviously I can't prove that :)

**Comment by justinvanwinkle** [comment]
Regardless of before or after decoding, blocking socket-like interfaces should not return an empty string except when the stream is complete.  This is how every single other interface works and violating that will lead to tons and tons of bugs.

**Comment by shazow** [comment]
I agree with @justinvanwinkle, and IMO the only sensible way around this is to break the compatibility promise of amt representing socket read and change it to representing amount decoded.
