### ISSUE TITLE
smarter context handling?

### ISSUE THREAD

**Issue by matejcik** [urllib3/urllib3#712]
related to #472 

urllib3 _could_ for example use `create_default_context` in `create_urllib3_context` if it is available

also i'd move certificate path logic into `create_urllib3_context` (why is it separate, anyway?)

i'd also propose to auto-call context.set_default_verify_paths() if available and cert_reqs is other than CERT_NONE

i can send a PR with all or some of this if you want it; just wanted to ask in advance if this is something desirable
##

**Comment by Lukasa** [comment]
@matejcik I think that this starts getting complex fast. Having urllib3 make these kinds of decisions automatically makes me a bit sad, *especially* if we don't support passing custom SSLContext objects (which we currently do not). I'd want to hold off on all of this until we have support for that.

**Comment by matejcik** [comment]
i might split this into sub-issues then, but maybe let me first explain myself better :)

i see several issues with context handling as it is.
first and foremost, by not using `create_default_context`, urrlib3 is making decisions differently from Python's ssl module. that can lead to confusion and subtle problems, IMHO.

second, related to this, there is no way to `set_default_verify_paths()` with urllib3. i consider that a problem and will submit an issue/PR for it in any case, but i thought that it could fold into this one. namely because it's somewhat unclear how to accomplish it without significantly changing the whole context handling

related, ISTM `set_default_verify_paths` step is superfluous if you don't actually have your own cert store (at which point you probably can tell if it's not being used, and use it explicitly), and that there is no way doing it automatically would break anything. i'll be trying to get this behavior into python ssl as well.
but yes, this step is a little more magic than the rest and i can understand you not wanting this.

then there is the support for custom ssl contexts... am i reading it right in that it's only a question of adding an additional parameter to `set_cert()`, similarly to what the `ca_cert_dir` parameter did? or better, a new `set_context()` method that can sidestep `set_cert` ?

at which point it would make sense to expose `create_urllib3_context` more and fold all `set_cert()` parameters into it?

**Comment by Lukasa** [comment]
@matejcik I understand your issues. =) You may find it helpful to read #507 and kennethreitz/requests#2118 for the top-level overview of what we're planning here.
