### ISSUE TITLE
Set TCP_QUICKACK when available

### ISSUE THREAD

**Issue by shazow** [urllib3/urllib3#746]
(I think only available on Linux?)

John Nagle said so: https://news.ycombinator.com/item?id=10608356

> That still irks me. The real problem is not tinygram prevention. It's ACK delays, and that stupid fixed timer. They both went into TCP around the same time, but independently. I did tinygram prevention (the Nagle algorithm) and Berkeley did delayed ACKs, both in the early 1980s. The combination of the two is awful. Unfortunately by the time I found about delayed ACKs, I had changed jobs, was out of networking, and doing a product for Autodesk on non-networked PCs.
> Delayed ACKs are a win only in certain circumstances - mostly character echo for Telnet. (When Berkeley installed delayed ACKs, they were doing a lot of Telnet from terminal concentrators in student terminal rooms to host VAX machines doing the work. For that particular situation, it made sense.) The delayed ACK timer is scaled to expected human response time. A delayed ACK is a bet that the other end will reply to what you just sent almost immediately. Except for some RPC protocols, this is unlikely. So the ACK delay mechanism loses the bet, over and over, delaying the ACK, waiting for a packet on which the ACK can be piggybacked, not getting it, and then sending the ACK, delayed. There's nothing in TCP to automatically turn this off. However, Linux (and I think Windows) now have a TCP_QUICKACK socket option. Turn that on unless you have a very unusual application.
> Turning on TCP_NODELAY has similar effects, but can make throughput worse for small writes. If you write a loop which sends just a few bytes (worst case, one byte) to a socket with "write()", and the Nagle algorithm is disabled with TCP_NODELAY, each write becomes one IP packet. This increases traffic by a factor of 40, with IP and TCP headers for each payload. Tinygram prevention won't let you send a second packet if you have one in flight, unless you have enough data to fill the maximum sized packet. It accumulates bytes for one round trip time, then sends everything in the queue. That's almost always what you want. If you have TCP_NODELAY set, you need to be much more aware of buffering and flushing issues.
> None of this matters for bulk one-way transfers, which is most HTTP today. (I've never looked at the impact of this on the SSL handshake, where it might matter.)
> Short version: set TCP_QUICKACK. If you find a case where that makes things worse, let me know.
> John Nagle
##

**Comment by Lukasa** [comment]
We should do both.

The thing that John Nagle doesn't adequately explain is that TCP_NODELAY is a *send*-side option, and TCP_QUICKACK is a *receive*-side option. That means the thing that TCP_NODELAY fixes for us is not fixed by TCP_QUICKACK: we'd need the server to set TCP_QUICKACK for us to safely turn off TCP_NODELAY.

In the case of urllib3, TCP_NODELAY is not a particular risk: we don't have a socket write profile that sends lots of tinygrams (one of the few things httplib got right). Amusingly, requests has an edge case where it gets this wrong (uploading chunk-encoded bodies), but that's fixable using TCP_CORK (and I may well do that at some point).

We should set TCP_QUICKACK *if we can*, because it's clearly a net social good. But we should keep TCP_NODELAY as well. =)

**Comment by shazow** [comment]
Yarp, totally makes sense, I forgot we're building a client here rather than a server lolol.

**Comment by wangyoucao577** [comment]
Does windows really have the "TCP_QUICKACK" option? I think only Linux has this option. Both Windows and Linux have the TCP_NODELAY option.

**Comment by haikuginger** [comment]
> Does windows really have the "TCP_QUICKACK" option? I think only Linux has this option.

Hence why we want to set it _when available_. 🙂

**Comment by wangyoucao577** [comment]
Understand,  thanks. But this library is a send-side one, isn't it? The TCP_QUICKACK option should be setted at the receive-side.  How can you set it?

**Comment by haikuginger** [comment]
If my understanding is correct (and if it's not, @sigmavirus24 will likely correct me quite quickly), while urllib3 is a sending-side library for _HTTP_, the HTTP protocol requires that both clients and servers be both TCP senders and TCP receivers in turn.

**Comment by sigmavirus24** [comment]
@haikuginger reading some of the conversation between @Lukasa and Andrey, QuickAck *is* a server side option. That said, Cory seems to think it's a [good idea regardless](https://github.com/shazow/urllib3/issues/746#issuecomment-158737634).

That said, it'd be nice if the man page for tcp documented it as such.

**Comment by wangyoucao577** [comment]
It make sense, I can understand. I saw you have set the TCP_NODELAY option in codes, but you haven't set the TCP_QUICKACK option, have you?

**Comment by Lukasa** [comment]
Correct. This is because TCP_QUICKACK weirdly turns itself on-and-off at odd times, and no-one has sat down to look at the code hard enough to work out how we use it correctly.

**Comment by nh2** [comment]
http://stackoverflow.com/questions/1615447/disable-tcp-delayed-acks

> You could `setsockopt(sockfd, IPPROTO_TCP, TCP_QUICKACK, (int[]){1}, sizeof(int))` after every `recv` you perform.  It appears that `TCP_QUICKACK` is only reset when there is data being sent or received; if you're not sending any data, then it will only get reset when you receive data, in which case you can simply set it again.

**Comment by sethmlarson** [comment]
After reading https://github.com/python-trio/trio/issues/1792#issuecomment-723389327 I think we'll stick with NODELAY only instead of setting QUICKACK. Seems to be the best choice for a general-case library like urllib3.

**Comment by crrodriguez** [comment]
For all the readers that come from googling this behaviour, the linux kernel has a per route quickack option now. Using systemd-networkd you can either enable quick acks for routes recieved via DHCP or static ones. I hope this helps most people here.
