### ISSUE TITLE
Add support for HTTP Alternative Services

### ISSUE THREAD

**Issue by Lukasa** [urllib3/urllib3#836]
HTTP Alternative Services are outlined in [RFC 7838](https://www.rfc-editor.org/rfc/rfc7838.txt). From the text:

> HTTP conflates the identification of resources with their location.  In other words, "http://" and "https://" URIs are used to both name and find things to interact with.
> 
> In some cases, it is desirable to separate identification and location in HTTP; keeping the same identifier for a resource, but interacting with it at a different location on the network.
> 
> For example:
> - An origin server might wish to redirect a client to a different server when it is under load, or it has found a server in a location that is more local to the client.
> - An origin server might wish to offer access to its resources using a new protocol, such as HTTP/2, or one using improved security, such as Transport Layer Security (TLS).
> - An origin server might wish to segment its clients into groups of capabilities, such as those supporting Server Name Indication (SNI), for operational purposes.
> 
> This specification defines a new concept in HTTP, "Alternative Services", that allows an origin server to nominate additional means of interacting with it on the network.

The main interest I have in this specification is that it's likely to be the building block for HTTP Opportunistic Encryption, which I'd very much like urllib3 to support.

In the short term I don't expect anyone to pick this work up: it's not an enormously high priority for me right now, certainly. However, I want an issue to track it, as this will allow anyone who wants this feature to put a bounty on it to get the work done.

Flagging this as "someday".
##

**Comment by shazow** [comment]
+1, thanks for tracking this!

**Comment by mrmcmuffinz** [comment]
Hi, 

Just wondering when we can some hopes on http/2 support?

Thanks,

-Abe.

**Comment by Lukasa** [comment]
@mrmcmuffinz The answer is very much "someday". HTTP/2 in synchronous code is a freaking nightmare, so adding HTTP/2 really relies on being able to obtain some useful asynchrony, either by hiding threads in the background (difficult in Python) or by opting in to a concurrency model.

So, definitely not before v2 lands: see #1068.
