### ISSUE TITLE
Streamline use of OS-native certificates for HTTPS validation

### ISSUE THREAD

**Issue by davidfstr** [urllib3/urllib3#842]
In considering the documentation at:
- https://urllib3.readthedocs.org/en/latest/security.html#using-your-system-s-root-certificates

It is easy to use the Mozilla-provided certifications for HTTPS validation. However these certificates may vary from the OS-native certificates. In such a case, urllib3 might fail to fetch a URL that a native browser app would succeed in fetching. This behavior is confusing to the user.

I propose adding an easy-to-use function to urllib3 that attempts to find the OS-native certificates automatically, so they can then be used for HTTPS validation. Something to automate the platform-specific certificate search alluded to from the StackOverflow post linked from the documentation link above.

Is this something that you (the maintainers) would be interested in supporting?
##

**Comment by shazow** [comment]
Hiya. I'd be happy to review such a PR. :)

FWIW, in approximate order of priority, we'd like to support: Linux (debian/ubuntu, redhat/fedora/centos, opensuse, freebsd, arch/gentoo), OS X, Win 10/8/7.

Related PR: #802

**Comment by Lukasa** [comment]
So to be clear, before you dive down this rabbit-hole @davidfstr, you should know that there are two PRs in the works that expose the functionality you're likely to want.

The first is #835, which will let you pass an `SSLContext` object that has had `load_default_certs` called on it. That works for Linux.

The second is #802, which will fill in the gaps for OS X and Windows (which are much harder).

I believe that adding a new API on top of those is probably unnecessary.

**Comment by shazow** [comment]
Indeed, any help in getting those other two PRs merged in would be a great help also (more feedback/review, collaboration on the PR, etc).

**Comment by sigmavirus24** [comment]
> The first is #835, which will let you pass an SSLContext object that has had load_default_certs called on it. That works for Linux.

Correction: most Linux. I'm pretty sure it's broken on debian, no?

**Comment by Lukasa** [comment]
I believe it works fine for Debian.

**Comment by davidfstr** [comment]
Okay I'll see about giving the PRs and eyeball - at least at the API level.

None of my users so far have complained about a mismatch between native certificate  stores and certifi, so the confusion problem I mentioned earlier is currently just an academic concern to me.

But at some point there will definitely be a mismatch and it will be useful if there's already a quick fix available.

**Comment by sethmlarson** [comment]
I believe this issue should be closed already. `SSLContext.load_default_certs()` is good at finding system cert bundles now.
