### ISSUE TITLE
Consider replacing urlparse with something that can handle the WHATWG's 'generous' definition of a URL.

### ISSUE THREAD

**Issue by Lukasa** [urllib3/urllib3#859]
For basically its entire lifetime, urllib3 has used urlparse and friends from the standard library to handle the task of working with URLs.

However, it has recently been pointed out that the WHATWG maintains a URL specification that its proponents claim is merely a codification of common browser practice. That URL specification contains a parsing section that is _dramatically_ more generous than urlparse and friends are: for example, it allows the scheme to be separated from the authority portion of the URL by a colon followed by _at least_ two slashes (allowing for the possibility of having an unbounded amount of slashes: @bagder's testing has found that Firefox will handle a string like `'http:' + ('/' * 8000) + 'example.com'` without complaint).

Given this remarkably expansive definition of the allowed format of a URL, and given that this apparently _really does happen_ on the web, and given also that the position of the WHATWG is that this generosity of parsing is a net good, we should at least consider adopting that parser.

It may be sensible to for us to write a standalone library (as part of the hyper project, perhaps) that is then vendored into urllib3/requests as appropriate. Regardless, we should discuss whether we want to do this or whether we think we should be less lenient.
##

**Comment by Lukasa** [comment]
Some relevant issues are whatwg/url#118, whatwg/url#119, and curl/curl#791.

**Comment by haikuginger** [comment]
I'm somewhat -1 on this. In the context of a browser, I think being a bit lax makes sense, but urllib3 isn't a browser: it's a library that can and should expect validated input. I think that to make a change, we should have clear backing from the community of urllib3 users that this is something that would have real and immediate use that trumps the possible ambiguity that might be introduced, as well as the loss of the existing work on making stdlib modules conform to standard-track RFCs.

That said, I do think we can revisit error messaging around possibly-invalid/noncompliant URLs.

**Comment by Lukasa** [comment]
> it's a library that can and should expect validated input.

That's not entirely true. In particular, urllib3 receives unvalidated input from servers which may redirect it. That's the situation I'm worried about here.

**Comment by haikuginger** [comment]
> That's the situation I'm worried about here.

Understood. But it's not like the WHATWG standards make previously-invalid URLs valid; it's just saying "it's OK to parse these invalid URLs if you can." WIthout a clear demand from our user base (is this actually an issue that needs to be solved?) or shift in the open-source library community (will our users expect us to handle URLs that we don't currently?), I'm not sure we should.

**Comment by Lukasa** [comment]
@haikuginger Quite reasonably. However, it depends entirely on your definition of 'valid'. The WHATWG specification codifies the "standard behaviour" of web browsers, which means that a server operator has a reasonable belief that returning `Location: http://////////////////////////example.com/` in a redirect should be handled by a user-agent. We can decide not to do that, but I want to make sure that we do that in full knowledge that this expectation exists.

**Comment by haikuginger** [comment]
>We can decide not to do that, but I want to make sure that we do that in full knowledge that this expectation exists.

Absolutely! I've said my piece; I'll defer to the maintainers now.

**Comment by shazow** [comment]
Are you opposed to modifying our internal `parse_url` to handle these cases?

**Comment by Lukasa** [comment]
Me? No.

**Comment by shazow** [comment]
I'd vote for that, then. :)

**Comment by jaddison** [comment]
I found this issue because I ran into a triple http slash when handling redirects with `requests`. 
 Apologies for the noise, but I thought I'd add in a `requests`-specific way to address this issue - for the sake of others who might run into this issue:

```
re_slash = re.compile(r'^(https?://)/*(.+)$')

def hook(r, *args, **kwargs):
  s = r.headers.get('Location', '')
  m = re_slash.match(s)
  if m:
      r.headers['Location'] = ''.join(m.groups())
      return r

r = requests.get(url_to_retrieve, hooks={'response': hook})
```
