### ISSUE TITLE
SessionManager: Provide default instance?

### ISSUE THREAD

**Issue by shazow** [urllib3/urllib3#868]
This is more thinking ahead and depends on #849 but something I want to discuss:

Would be nice if users could do:

``` python
from urllib3 import http # or maybe `session` or `default` or something?

r= http.request('GET', whatever)
```

Two questions:
1. Is it _safe_ to provide a default instance (or magic property) of SessionManager for people to use?
   Need to consider single-threaded, multi-threaded, and possibly multi-process (this actually might be _more_ safe in a multi-process environment than our current approach where people might accidentally re-use a late-instantiated pool).
2. What should it be named?
   I like using `http` in all of the examples like `http = PoolManager()`, `http = ConnectionPool()` etc., so `http` feels natural to me as a default instance you make http requests through, but I'm open to other ideas.
   Originally, we used to use `pool = PoolManager()` but I think `http` is more friendly in practice.
##

**Comment by haikuginger** [comment]
Hmm. I really like the concept, but I'm not positive on how to implement it- specifically, would it actually be possible to have the import return an instance of `SessionManager`?

Requests gets around this and provides `requests.get()` et al by initializing a Session for every request that gets made - here, I feel that would kind of defeat the purpose of `SessionManager`. If we went that way, I think it makes more sense to just bind it to a new `ConnectionPool`.

**Comment by shazow** [comment]
@haikuginger In `__init__.py`

```python
http = SessionManager()
```

Alternatively it could be a magic `@property` which provides it on-access.

**Comment by haikuginger** [comment]
Yup, there it is. Sometimes it just slips by me.

I'm 👍, with a little bit of trepidation around the possible results of information leakage - this basically means that every import of urllib3 in a given Python process will have the same SessionManager. Which isn't necessarily a bad thing, but is worth thinking about, especially if we want to add extensibility to `SessionContext` later on.

**Comment by shazow** [comment]
> this basically means that every import of urllib3 in a given Python process will have the same SessionManager.

Yes, that's a good point, but I think that's okay as long as the SessionManager's instantiated configuration is immutable (so we can assume they're interchangeable).

**Comment by shazow** [comment]
Lately I've been thinking providing a module-global function that wraps our `RequestMethods.request(...)` method, something like:

```python
# __init__.py
default_session = SessionManager() 

def request(method, url, fields=None, headers=None, **kw):
    return default_session.request(method, url, fields=fields, headers=headers, **kw)
```

Then we can do stuff like

```python
from urllib3 import request

r = request('GET', 'https://www.google.com/')
```

And still get all the benefits out of the box. Thoughts?

**Comment by haikuginger** [comment]
I like it! One (completely nonfunctional) thought - maybe have it in the docs as

```python
import urllib3

r = urllib3.request('GET', 'https://www.google.com/')
```

It'd behave exactly the same way, and people could obviously still do things the `from-import` way, but it might help create an unconscious association that the state of that particular `SessionManager` is embedded in urllib3 as a package, rather than in any particular import of it - does that make sense at all?

I definitely do like exposing that static method more than I do exposing a default session with no abstraction; this way, we can even specifically mark the default session as private (`_default_session`) so that people aren't tempted to fiddle with it.

**Comment by haikuginger** [comment]
@shazow, do you want this in the `SessionManager` branch prior to the 1.17 release?

**Comment by shazow** [comment]
Nah it can be added later (but if you're interested in prototyping, I'm happy to see it in a PR meanwhile!)

**Comment by sethmlarson** [comment]
Going to close this as `SessionManager` isn't being developed currently.
