### ISSUE TITLE
SessionManager: Ability to disable cookies

### ISSUE THREAD

**Issue by shazow** [urllib3/urllib3#888]
SessionManager is going to include a bunch of autoconfigured functionality, will be useful to be able to disable portions of it when creating a fresh instance.

(Unless we feel that SessionManager is the wrong place for the autoconfigured functionality, then we need yet another layer.)

To be clear, these disabling/enabling should happen during instantiation, not after. Perhaps another fun opportunity to use `False` as a semantic value. :P

Also another open question: Maybe this should live in SessionContext?
##

**Comment by haikuginger** [comment]
This is at least partially handled by recent commits on #849; I'm envisioning a more complete "semantic wrapper" being available on another level.

**Comment by sethmlarson** [comment]
Since SessionManager isn't currently being developed I'm going to close this issue.
