### ISSUE TITLE
SSPI support for proxy authentication

### ISSUE THREAD

**Issue by benjimin** [urllib3/urllib3#945]
I've created a demo of SSPI NTLM authenticated HTTP proxy support ([link](https://github.com/benjimin/pywebcorp)). Would it be possible to incorporate functionality like this into urllib3? If so, where might be the best place?

The idea is that in windows domains the proxy may require authentication using the same credentials as for the user to log on to their workstation. SSPI is the interface which allows application software to utilise the operating system log-on credentials (e.g. for NTLM authentication). This tends to be more secure and convenient than prompting the user for a password (like basic authentication), and is used automatically by applications like chrome and firefox.
##

**Comment by Lukasa** [comment]
Thanks for the question @benjimin!

urllib3 basically does not include support for HTTP authentication mechanisms. We have moderate support for Basic Auth in the form of the `make_headers` function, but even that isn't used by default: you have to opt-in to using it.

Generally speaking, then, the way to handle this is to simply make urllib3 calls directly. In particular, you can create an appropriate configured `ConnectionPool` and `PoolManager`, whereby these two methods intercept and control the `urlopen` method in such a way as to appropriately handle the authentication.
