### ISSUE TITLE
Malformed header causes IndexError during header parsing

### ISSUE THREAD

**Issue by konklone** [urllib3/urllib3#950]
This response (note the space and quotes around `Content-type`):

```
$ curl --head https://consumersentinel.gov
HTTP/1.0 200 OK
 "Content-type": text/html
pragma: no-cache
retry-after: 600
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Server: BigIP
Connection: Keep-Alive
Content-Length: 2835
```

Causes this error in `urllib3`:

```
  File "/home/eric/.pyenv/versions/2.7.11/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 590, in urlopen
    **response_kw)
  File "/home/eric/.pyenv/versions/2.7.11/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 373, in from_httplib
    headers = HTTPHeaderDict.from_httplib(headers)
  File "/home/eric/.pyenv/versions/2.7.11/lib/python2.7/site-packages/requests/packages/urllib3/_collections.py", line 317, in from_httplib
    key, value = headers[-1]
IndexError: list index out of range
```

I'm using `urllib3` via `requests`, but it doesn't look like that's causing the issue.
##

**Comment by haikuginger** [comment]
@konklone, can you confirm for me that this happens in Python 2 and not in Python 3? I think there might be a difference in the way httplib is parsing the headers between them.

**Comment by haikuginger** [comment]
Actually, not a difference in the parsing - found the issue, and will have a PR shortly.

**Comment by konklone** [comment]
Awesome! Let me know if I can provide any additional details.

**Comment by Lukasa** [comment]
*What* the hell is that monstrous header? Whomever is operating that web server needs a very stern telling off, because that output isn't even close to acceptable.

Regardless, good debugging folks!

**Comment by konklone** [comment]
Well, they have an HSTS preload policy in place, so I'm inclined to cut them some slack. ;)

**Comment by Lukasa** [comment]
Juuuuuuuuust barely. ;)

**Comment by aiosin** [comment]
anyone still encountering this issue can use python3 to circumvent this error  
 https://stackoverflow.com/questions/45905775/

**Comment by squarelover** [comment]
What if you can't use Python3?

**Comment by sethmlarson** [comment]
Maybe we should pick up that PR and try to get this implemented again.
