### ISSUE TITLE
urllib3 does not urlencode redirect targets on redirect.

### ISSUE THREAD

**Issue by eladbitton** [urllib3/urllib3#952]
I am crawling pages and I'm getting `UnicodeEncodeError`. 

The problematic url is : http://www.efind.co.il/detailed/52133.html
I've isolated my code to this:
`url = "http://www.efind.co.il/detailed/52133.html"
manager = PoolManager()
response = manager.request('GET', url)`

This url is redirecting to this url: articles.efind.co.il/info/דגי-נוי-בבריכה-מאמר
which is not 'ascii'.

Because this is auto redirect i can't do anything about it. I am quoting the first url and giving it to the urllib, I don't have control over the redirected urls.

Anything i can do?
##

**Comment by nateprewitt** [comment]
If you call request with `redirect=False`, it should halt the request before performing the next request to articles.efind.co.il/info/דגי-נוי-בבריכה-מאמר. You can probably handle the encoding of the `Location` header before calling request on the new URL.

**Comment by eladbitton** [comment]
This is optional, but i think urllib should handle the redirects properly by itself.

**Comment by nateprewitt** [comment]
I don't want to give incorrect information, so I'd wait for @Lukasa, @sigmavirus24 or @shazow to confirm this. 

To my understanding, unicode in URI/IRIs is supposed to be converted to UTF-8 and then % encoded before being sent across the wire. So the server emitting raw unicode in the Location header is a violation of [RFC3987](https://www.ietf.org/rfc/rfc3987.txt) and a compliance problem with the server, not urllib3.

**Comment by sigmavirus24** [comment]
@nateprewitt this has nothing to do with 3987 and everything to do with the encoding that Python expects a header to use. I suspect (although @eladbitton didn't say this explicitly) that @eladbitton is using Python 3 which tries to coerce everything to `latin-1`.

@eladbitton could you share your *full* traceback and version information (of Python and urllib3).

That said, RFC 3987 *does describe* how to convert that particular URL, but most servers will send lots of junk in headers and expect clients to handle it.

**Comment by eladbitton** [comment]
```
Traceback (most recent call last):
  File "/home/elad/Installed Applications/eclipse/plugins/org.python.pydev_5.1.2.201606231256/pysrc/pydevd.py", line 1530, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/elad/Installed Applications/eclipse/plugins/org.python.pydev_5.1.2.201606231256/pysrc/pydevd.py", line 937, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/elad/Installed Applications/eclipse/plugins/org.python.pydev_5.1.2.201606231256/pysrc/_pydev_imps/_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/elad/workspace/Crawler/crawler/test.py", line 18, in <module>
    response = manager.request('GET', url)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/request.py", line 69, in request
    **urlopen_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/request.py", line 90, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/poolmanager.py", line 276, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/poolmanager.py", line 248, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 363, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1141, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.5/http/client.py", line 983, in putrequest
    self._output(request.encode('ascii'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 10-15: ordinal not in range(128)
```

I am using python3.5 and urllib3-1.16. Urllib3 can't encode the redirected url to 'ascii' because it isn't 'ascii'.

**Comment by Lukasa** [comment]
So this looks potentially like it's a bit of a urllib3 bug. It's passing the redirect URL straight back to httplib, but it needs to be urlencoded first, which is apparently not something urllib3 has ever done.

So yes, this is a bug.

**Comment by sigmavirus24** [comment]
Aha, so what's actually happening is that the standard library is perfectly happy with the URL until the last line in the traceback.

So in the traceback the `url` is the path `/info/דגי-נוי-בבריכה-מאמר`. I think we should either migrate to `rfc3986` which will normalize the path for us:

```py
>>> import rfc3986
>>> rfc3986.uri_reference('http://articles.efind.co.il/info/דגי-נוי-בבריכה-מאמר').unsplit()
u'http://articles.efind.co.il/info/%d7%93%d7%92%d7%99-%d7%a0%d7%95%d7%99-%d7%91%d7%91%d7%a8%d7%99%d7%9b%d7%94-%d7%9e%d7%90%d7%9e%d7%a8'
```

Alternatively, we can update our `Url` class to do this for us.

**Comment by nateprewitt** [comment]
I'd be happy to assist with this if it would be helpful. Right now, it looks like the `Url` class (more specifically the `parse_url` method) is only used in the `PoolManager` but not the underlying `HTTPConnectionPool`. Implementing the change in `Url` would require `HTTPConnectionPool.urlopen` to be updated to either call `parse_url` or instantiate the class in some other fashion.

**Comment by Lukasa** [comment]
I am totally up for urllib3 using rfc3986.
